### PR TITLE
Removes wrong color assignment

### PR DESCRIPTION
**Pull request by javierarce**
Removes a color assignment I inadvertently added.

screen shot 2015-09-24 at 10 49 17
screen shot 2015-09-24 at 10 49 21

### CODE REVIEW

**Comment by javierarce** [comment]
@xavijam: please review it.

**Comment by xavijam** [comment]
:+1: :dancer:

**Comment by javierarce** [comment]
However there's a difference between those two dropdowns. The first one (`.SettingsDropdown-itemLink`) has `text-decoration: underline` and the last one (`BreadcrumbsDropdown-optionsItem`) doesn't.

**Comment by xavijam** [comment]
weird, @josecruz what do you think about it?

**Comment by javierarce** [comment]
I'm going to merge this, but please let's take a decision on the underline.

**Pull request merged**
