### PR TITLE
New create dialog fixes

### LINKED ISSUE #3099: Show "Unknown size" instead of 0 in the gdrive file list
screen shot 2015-04-09 at 12 21 25

### LINKED ISSUE #3109: Redesign ArcGIS panel

### LINKED ISSUE #3114: Avatar broken if not set on dashboard
image

The dashboard [uses the avatar_url](https://github.com/CartoDB/cartodb/blob/master/app/views/admin/shared/_new_private_header.erb#L40) property on the user model, but it might be nil or an empty string. Probably we should use [`user.avatar`](https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L717-L719) instead which falls back on a default avatar if the user don't have one.

Probably should also apply in [user permissions presenter](https://github.com/CartoDB/cartodb/blob/master/app/models/permission/permission_user_presenter.rb#L16) as well as the [user decorator](https://github.com/CartoDB/cartodb/blob/master/app/models/user/user_decorator.rb#L63) too, which are used for the dashboard API.

cc @javisantana for spotting it

### LINKED ISSUE #3118: Improve error message in Gdrive and Dropbox
When failing, be sure we mention the need of deactivating the pop-up blocker.
"We are sorry, can’t connect to your Google Drive account." -> "We are sorry, can’t connect to your Google Drive account. Just in case it helps, be sure you have the pop-up blocker deactivated for this website"

### PR DESCRIPTION
**Pull request by xavijam**
## Several fixes

- [x] Improve error message in source service import options (fixes #3118).
- [x] Show "Unknown size" instead of 0 in the gdrive file list (fixes #3099).
- [x] Fix instagram panel problems (add fallback, fix last item hover,...).
- [x] When there is only one item selecting a source service import option, go directly to selected state.
- [x] Redesign ArcGIS panel (fixes #3109).
- [x] Fix problem with Twitter slider, when user has reached all credits.

#### Bonus
- [x] Avatar broken if not set on dashboard (fixes #3114).
- [x] Add new user notification for checking user public profile.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2943/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2946/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2950/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2954/))

**Comment by xavijam** [comment]
@kartones what do you think about "avatar" change in user decorator?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2957/))

**Comment by Kartones** [comment]
nice! didn't knew about the helper that grabs the default if not present, so go ahead!

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
@kartones, changed infowindow in instagram decorator.
By default: 
screen shot 2015-04-13 at 16 21 06

**Comment by xavijam** [comment]
Without created time field :P

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2958/))

**Comment by Kartones** [comment]
:D much better

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2967/))

**Pull request merged**
