### PR TITLE
Fine tune design

### PR DESCRIPTION
**Pull request by nobuti**
This PR implements #11063

This should be easy to test, just read the issue and check all issues are fixed in every browser your machine has.

### CODE REVIEW

**Comment by nobuti** [comment]
pinging @piensaenpixel for CR about styles.

**Comment by xavijam** [comment]
I've checked that:

- Fill input is bigger than rest.

screen shot 2017-02-01 at 12 54 52

- Icons are not aligned in the center of the box.

screen shot 2017-02-01 at 12 39 15

Reviewing that myself.

**Comment by xavijam** [comment]
About first thing, it turns out that select field is smaller than the rest, fixed in https://github.com/CartoDB/cartodb/pull/11417/commits/6fe04636aea89ee39137ffd402d9a3c8ac99e8cd.
And further to the second point, the problem is due to the SVG, not about the position of the  itself (as @nobuti pointed offile), so 👍 .

**Comment by xavijam** [comment]
Tested in Chrome, Safari and Firefox, :+1:

**Pull request merged**
