### PR TITLE
Disable import from external services when not configured

### PR DESCRIPTION
**Pull request by javitonino**
Disables import services (dropbox/gdrive & co) when they are not configure (e.g: offline). As a bonus, it disables the tab navigation when not needed, and hides it completely when no service is configured (only data file available).

screenshot_20160526_145507

screenshot_20160526_145536

### CODE REVIEW

**Comment by javitonino** [comment]
Please CR @xavijam. I may have been overeager hiding the navigation & tabs. It can be easily reverted if needed, as it changes the design a bit.

**Comment by javitonino** [comment]
Hold that review! Making some changes...

**Comment by javitonino** [comment]
Now with more new editor compatibility. All ready for CR @xavijam

**Comment by xavijam** [comment]
Looks good to me :)

**Pull request merged**
