### PR TITLE
Change default map bounds to whole world

### LINKED ISSUE #4635: Change default map bounds to whole world instead of null island

### PR DESCRIPTION
**Pull request by Kartones**
Closes #4635

### CODE REVIEW

**Comment by Kartones** [comment]
@javisantana CR please

**Comment by javisantana** [comment]
:es: cc @viddo this fix the problem with bbox so we can keep the frontend fix

**Comment by viddo** [comment]
:shipit:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5316/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5335/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5336/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5337/))

**Pull request merged**
