### PR TITLE
Show affected maps on delete items dialog

### LINKED ISSUE #1752: Make new dialog to scroll content if overflows inner height
At the moment the dialog has a `position: fixed` and thus scrolls the body behind the dialog instead.

### PR DESCRIPTION
**Pull request by viddo**
Solves #1687
Solves #1752

screen shot 2015-01-14 at 11 02 34

Some notes related to this PR:
- the medusa maps are not done yet, so the actual preview need to be added later.
- based on offline discussion earlier, I propose to postpone the last task listed on the issue (_provide a horizontal scroll buttons on sides to show prev/next_). this would take more time and is really nice-to-have. see above for how it looks without that (I think it's OK for now).

Also refactored some common things:
- inlines CSS animations since they are not truly reusable
- use default behaviour for base_dialog, i.e. not clean on hide, wasn't used previously either
- spec helpers to check a `this.view.el.innerHTML` => `this.innerHTML()`
- truncate too long texts using CSS instead of JS code, simpler and easier to manage
- fixed #1752 (make dialog content scrollable instead of body) while at it

### CODE REVIEW

**Comment by viddo** [comment]
@xavijam @saleiva please review (see comments in PR desc)

**Comment by saleiva** [comment]
Awesome. +1 on keeping the horizontal scroll buttons for later, please add a ticket to the backlog so we don't forget.

**Comment by viddo** [comment]
great, done, TBD in #1780

**Comment by viddo** [comment]
@javisantana for heads up, there is a small change on Visualization model, but I imagine it should not be any trouble for the Odyssey integration?

**Comment by javisantana** [comment]
@viddo no idea, probably yes, we will see

**Comment by javisantana** [comment]
I mean, that change is pretty "big" so I'd say not to merge this without a smoke test pass

**Comment by viddo** [comment]
The only changed code on existing dashboard is in the [table item view](https://github.com/CartoDB/cartodb/pull/1748/files#diff-19), which is very local. I didn't refactor any other code that uses the table metadata class directly for the very reason to avoid a big change and thus introducing new bugs. What makes you consider this a big change? Or were you referring to something else I overlooked?

**Comment by javisantana** [comment]
you are right, sorry, I though it would be used in more places :/

**Comment by viddo** [comment]
Alright! Anyway, we're testing on staging nevertheless so will verify that case not breaking at least.

**Comment by viddo** [comment]
noticed some minor kinks while review on staging, fixed in the last commits

**Pull request merged**
