### PR TITLE
Enables/disables type and content guessing with the same toggler in the create dialog

### LINKED ISSUE #3456: Add option to disable geocoding guessing in the UI
cc @saleiva 

It should be deactivated with the check for guessing types.

SB/5222685

### PR DESCRIPTION
**Pull request by xavijam**
In short, current type guessing button will enable/disable type and content guessing at the same time.

screen shot 2015-05-05 at 13 05 24

Fixes #3456.
REVIEWER: @viddo.

cc @iriberri and @saleiva (text looks good?)

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3459/))

**Comment by viddo** [comment]
Looks good! :+1:

**Comment by iriberri** [comment]
:+1:

**Comment by xavijam** [comment]
:dancer:

**Pull request merged**
