### PR TITLE
[Dashboard Removal] Editor Dashboard

### PR DESCRIPTION
**Pull request by jesusbotella**
This PR removes Editor dashboard page contained within `cartodb` folder from the repository.

This migrated dashboard page is within `lib/assets/javascripts/cartodb/dashboard`. The entry point for the page is [`entry.js`](https://github.com/CartoDB/cartodb/blob/41a8d0b03b5b19b080865a39e4dc884805282c82/lib/assets/javascripts/cartodb/dashboard/entry.js) and [`index.js`](https://github.com/CartoDB/cartodb/blob/41a8d0b03b5b19b080865a39e4dc884805282c82/lib/assets/javascripts/cartodb/dashboard/index.js) for the static one.

This page is the non-migrated one and wasn't even used for Editor users because as the dashboard is static, the server returns the same index.html and we load the newer assets for all users.

The main dashboard was bundled with Browserify and it was removed when the migrated dashboard was put in place, but the dashboard deps are still being compiled through JS concatenation:
https://github.com/CartoDB/cartodb/blob/41a8d0b03b5b19b080865a39e4dc884805282c82/lib/build/files/js_files.js#L2-L48

https://github.com/CartoDB/product/issues/289

### CODE REVIEW

**Comment by jesusbotella** [comment]
This PR is ready to review 🎉 

I don't know if @VictorVelarde or @rjimenezda can give it a look, so that we make sure I didn't forget anything.

However, apart from the code review, the most important thing is to pass a thorough acceptance so that we check that everything works without issues.

**Comment by rjimenezda** [comment]
As long as it builds, I think we're fine. It should fail at the build stage.

But sure we should check nothing's broken

**Comment by jesusbotella** [comment]
That's what I thought too, but just in case 😂

**Comment by VictorVelarde** [comment]
For me it's fine, as long as the acceptance is run (Check that Editor, Public Dashboard, and Public User feed working without issues).

**Comment by Jesus89** [comment]
:wave: I have manually tested the Public dashboard and user feed (/me, /maps, /datasets). I have not found any issue, there.

In the Editor I saw the message `cartodb/dashboard/views/video_player not found` required in `table_editor_view.js`. I fixed this issue, moving the template to `cartodb/old_common/views/video_player`. The model is in `cartodb/old_common` too. However, I think we could remove this in the future if it is not used.

Apart from that, I have not found any other issues, so I think we could merge this one... :boom:

**Pull request merged**
