### PR TITLE
Fixes maps an datasets URLs in the user feed page

### PR DESCRIPTION
**Pull request by javierarce**
This PR fixes the malformed URLs for maps and datasets that appear in the user feed. Prepending the `base_url` part adds the `/u/username` part that was missing in the links from organization users.

### CODE REVIEW

**Comment by javierarce** [comment]
Can you have a look, @xavijam?

**Comment by javierarce** [comment]
Can you have a look, @viddo?

**Comment by viddo** [comment]
With this approach the first part of the URL would always be based on a configuration setting (current user, right?), AFAIK subdomains and first part of path (/u/…) may differ depending on the vis _owner_. Does this actually work as expected for all URLs? 

Is there a reason for not using `vis.viewUrl().public()` instead, which handles this? `vis.viewUrl(currentUser).public()` might be even better since it takes the current user access into account too.

**Comment by javierarce** [comment]
In this case the `base_url` variable refers to the vis owner, and all the maps and datasets showed in the feed belongs to him/her.

The reason we aren't using `vis.viewUrl` is because in this case the `vis` elements of the collection is just the default backbone model obtained querying the `/api/v1/viz` endpoint.

**Comment by viddo** [comment]
Aha, thx for clarifying! In that case :+1: 
cc @xavijam let's keep this (:point_up:) in mind for the future, I'm not very fond of having logic duplicated but fixing it would require quite a change I think.

**Pull request merged**
