### PR TITLE
2068 tables get registered twice sometimes

### PR DESCRIPTION
**Pull request by juanignaciosl**
This is a fix for #2068. @javisantana @Kartones please CR this. Since it's only invoked from one controller I've moved the code from `Api::ApplicationController` to the controller, making the check for request parameters unnecessary. Now ghost table linking will only be triggered when a user requests dashboard _page_.

### CODE REVIEW

**Comment by Kartones** [comment]
+1

**Comment by javisantana** [comment]
I tried to do that but didn't managed to do haha, so thanks

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1562/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1566/))

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1573/))

**Pull request merged**
