### PR TITLE
Changed line opacity and width of default polygon stroke

### LINKED ISSUE #3372: Reduce default opacity of poligon-stroke to 0.5 was about reducing the line-width
I'd put the opacity to line-opacity to 1.
Sorry mate!

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #3372.

This one if for you @saleiva!

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3279/))

**Comment by alonsogarciapablo** [comment]
@saleiva, is this what you are expecting? Thanks!

**Comment by saleiva** [comment]
+1!

**Comment by saleiva** [comment]
:bump!

**Pull request merged**
