### PR TITLE
Fixes static maps for password protected visualizations

### PR DESCRIPTION
**Pull request by javierarce**
This PR just updates cartodb.js to enable static maps for password protected maps.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2779/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2785/))

**Comment by javierarce** [comment]
@xavijam: can you have a look, please?

**Comment by xavijam** [comment]
Ok, only cartodb.js update? So far so good :+1:

**Comment by javierarce** [comment]
Yep, just that. Thanks!

**Pull request merged**
