### PR TITLE
Avoids reloading the map previews on click

### PR DESCRIPTION
**Pull request by javierarce**
This branch adds code to:

- Avoid reloading the map previews on click.
- Adds trigger events to the mappreview class.

@xavijam: can you review it, please? The previews will be reloaded if the image couldn't load, but we can change it if you think is better.

### CODE REVIEW

**Comment by xavijam** [comment]
From my point of view, we should try to not render again the whole item and only change the necessary parts when needed. And not add more attributes to the model because it is a visualization model, not a standard view. What do you think @viddo ?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1615/))

**Comment by javierarce** [comment]
We can use a simple flag if you think is better.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1618/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1638/))

**Comment by javierarce** [comment]
Updated code with the changes mentioned in my last comment.

**Comment by viddo** [comment]
:+1:

**Comment by javierarce** [comment]
retest this please

**Comment by xavijam** [comment]
:dancer:

**Comment by javierarce** [comment]
Sorry, I merged this accidentally and there's one test failing. I've fixed it here: https://github.com/CartoDB/cartodb/issues/2279

**Pull request merged**
