### PR TITLE
Avoid the_geom column collision fixes #2108

### LINKED ISSUE #2108: Error importing Shapefile converted from GDAL+ogr
`````
Sequel::DatabaseError: PG::Error: ERROR:  function st_force_2d(character varying) does not exist
LINE 2:           SELECT public.GeometryType(ST_Force_2D(the_geom))
HINT:  No function matches the given name and argument types. 
You might need to add explicit type casts.
`````

Import ID: `8b43dfb1-ce6d-4b5d-90d9-b62abebcd546`

`````
What we are doing is taking parcel data from many counties in Colorado 
and merging them all into EPSG:4326 and normalizing the columns and 
data.  This is all being done in ogr GDAL in 2 steps.  First normalizing 
the columns and projects into a series of shp files.  After that we run 
a ogr merge to make one master file. 
`````

Source file can be found at SB/4391807, as well as further info about it's creation from ogr2ogr.
**They were able to upload the Shapefile without reprojecting.**

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones @rafatower CR this, please. You have more info in #2108 (you can even reproduce the error if you want with `*_rpj.zip` files. I've added a comment with what's happening. I think this is the right fix if we should override `the_geom` when there's a geometry column.

What to test: importing, and check guessing (ip, countries, latlong and geom columns) work and the_geom gets populated as usual.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1688/))

**Comment by Kartones** [comment]
uhmmm there's something I don't understand. If I'm correct georeferencing shouldn't override existing geometries, no?

I mean, if I already have geoms, it should only try to fill the gaps (null geoms), not touch those already referenced, because if I have for whatever reason changed the geometries my changes would get "automatically lost".

Same happens with data that already has a geometry upon import. Would your change override imported geometry with georeferenced one?

**Comment by juanignaciosl** [comment]
This is the importer geofererencer, so I think it's only used at import time.

I don't know if I'm right (that's why I requested a deeper CR), I'll explain my point. If you see [importer georeferencer](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/georeferencer.rb#L41) you can see it chains several attempts of creations of the_geom, and in most of them the first thing the method does is returning if it shouldn't do it ([see](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/georeferencer.rb#L76)), [2](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/georeferencer.rb#L88)...). Since `create_the_geom_from_geometry_column` does not, and we're using a geometry column (so we are fairly confident it's good data) I guessed we should better override it.

In my case, a previous `the_geom` existed, but it was just text. The actual problem comes later: since CartoDB expects `the_geom` to be geospatial data, many things won't work as expected. I'm not sure whether we should always override it but we should certainly do if it's not geospatial data, don't you think?

**Comment by Kartones** [comment]
The flow is right now:
a) import data into a table
b) georeference (not touching geom if present)
c) cartodbfy table (which checks geom and if invalid, renames to invalid_the_geom IIRC)

Also, in the importer the policy is to never delete user data. If cartodbfication detects invalid geometries, invalid cartodb_ids, etc. it simply renames the column and creates an empty geom (or proper sequential autoincrement cartodb_id).

That's why I see this change as not fully right/good... even if data is bad.

**Comment by rafatower** [comment]
My understanding is that at the end of the import process a well known geometry column must exist, even if empty (all nulls).

What I think we should do is renaming `the_geom` IF it is not of a geometry type and give up "georeferencing":
```
if column_exists_in?(table_name, :the_geom)
  column = Column.new(db, table_name, :the_geom, schema, job)
  if supported_types.include(column.geometry_type) then
    # normal flow
  else
    # the half-imported table has something in the_geom that does not look like a geometry type for us
    # rename to the_geom_backup or something
   return false # and return
  end
end
```

**Comment by juanignaciosl** [comment]
I agree @rafatower , what do you think, @Kartones ?

**Comment by Kartones** [comment]
But then we're repeating the code that cartodbfy method does :(  (in a "dumber" version)

Anyway, if is an improvement over what we have now and is quick to code, go ahead with @rafatower  approach and we'll handle duplicated logic in the future

**Comment by rafatower** [comment]
We can avoid duplicate code by giving up if the_geom does not contain a
valid type (no renaming, letting the cartodb extension do it stuff). That
should be easy to test.

On Tue, Feb 17, 2015 at 5:32 PM, Kartones <notifications@github.com> wrote:

> But then we're repeating the code that cartodbfy method does :( (in a
> "dumber" version)
>
> Anyway, if is an improvement over what we have now and is quick to code,
> go ahead with @rafatower <https://github.com/rafatower> approach and
> we'll handle duplicated logic in the future
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/2285#issuecomment-74698423>.
>



-- 
Rafa

**Comment by juanignaciosl** [comment]
I don't think we're duplicating code, but I certainly feel this needed a deeper explanation, so take a look at [my last comment](https://github.com/CartoDB/cartodb/issues/2108#issuecomment-74703124) and move discussion there. Thank you both for this deep CR indeed :-)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1703/))

**Comment by juanignaciosl** [comment]
I hit a deadlock: you can't know _in advance_ whether `the_geom` is valid or not, so I'm doing another approach to this problem (another problem statement indeed): instead of "the_geom data is not valid" we can approach that "`the_geom` is not the column which has the geolocated data". Georeferencer is not as orthogonal as his method naming says: it doesn't always geoference `the_geom`, since methods like `create_the_geom_from_geometry_column` don't always _create the geom_ but _a georeferenced column_ if it finds another.

So what I'm doing now is avoiding the original error by checking the actual column, so in the final import there'll be an empty `the_geom` (since the original one is not valid), a `invalid_the_geom` (same reason),  and a `wkb_geometry` that has been successfully geometrified.

I'm not sure if this is better for the user, but it's certainly more coherent with current CartoDB behaviour (and removes every hint of code or logic duplication @Kartones was worried about). What do you think?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1704/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1710/))

**Comment by Kartones** [comment]
mm looks fine to me, ask @javisantana  just in case but I see it ok.

**Comment by juanignaciosl** [comment]
I'll wait for @javisantana opinion then.

**Comment by javisantana** [comment]
You went too much into details here, I think we should go to your original question:

> I think this is the right fix if we should override the_geom when there's a geometry column.

I think, in case the file has our special columns (cartodb_id, the_geom, updated_at, created_at) those columns should be kept and checked for correct type and fail if the type is not good.

So in case of attached csv (with wrong the_geom but good wkb_geometry) should fail with a "the_geom contains no valid geometry". 

It has a reason, as much magic we have more will take to move that code where the place it belongs (cartodb-postgres extension)

This is actually a problem of file format definition and lack of documentation about that in the importer

**Comment by javisantana** [comment]
I filed a ticket to update documentation (and actually define it properly) https://github.com/CartoDB/cartodb/issues/2329

**Comment by juanignaciosl** [comment]
I only have a concern here: if we fail import because of detecting invalid guessed type for `the_geom` it feels to me like we're changing CartoDB behavior when it finds invalid data, because right now the import will work and extension would move that data to `invalid_the_geom`. If it's ok to you I'll change the code to fail instead of avoiding it.

**Comment by javisantana** [comment]
my concern here is the undefined behavior. If I have a file with wrong the_geom and right wkb_geometry but we finally import the file, what is inside the_geom ?

Whatever you define is ok for me, keep in mind:

- this is public api and should be documented (see #2329) and maintained
- it should be as simple as possible. That logic we do on rails will be moved to cartodb-extension

**Comment by juanignaciosl** [comment]
I think CartoDB should try the best effort possible for user on importing, so in case of wrong the_geom and right wkb_geometry the_geom should contain the geometrified wkb_geometry.

I think a simple, consistent way to express this should be:
* If there's an existing `the_geom` with invalid geometry it will be moved to `invalid_the_geom`.
* If there's an existing geometry column with valid geometry it will be moved to `the_geom`.

@Kartones do you agree with this, after all the discussion?

**Comment by Kartones** [comment]
Fine by me.

Just make sure to test that upon export and reimport, or importing common data we don't end with any "extra" geometry field, because @iriberri told me last friday she's seeing it lately in some scenarios (she can provide better details).

**Comment by javisantana** [comment]
agree on what you decide if we document it properly :) https://github.com/CartoDB/cartodb/issues/2329

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1841/))

**Comment by juanignaciosl** [comment]
I've added NOMERGE to avoid temptations, since this needs to go through QA.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2129/))

**Pull request merged**
