### PR TITLE
Keep vis and permission model synced

### PR DESCRIPTION
**Pull request by viddo**
Revert #3571 for the create-empty-map, reintroducing the bind that kept vis <-> permission in sync that was removed in https://github.com/CartoDB/cartodb/commit/0f6748a4e6899b1afe5a8fee7bbee7d2b4d1f367, so now synced/consistent both ways.

### CODE REVIEW

**Comment by viddo** [comment]
@xavijam found 2 other cases and realized where the culprit was in the first place

**Comment by javisantana** [comment]
:(

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3563/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3565/))

**Pull request merged**
