### PR TITLE
Change analyses copies

### PR DESCRIPTION
**Pull request by rjimenezda**
This is the same PR as #13413, it's just pointing to a rebased branch, there were a lot of conflicts because of the core & builder renames.

It looks apparently fine, pasting the content of the previous PR

## Related to #13384
This PR updates the copies of the analyses modal, the analyses nodes list and analyses forms.

## Screenshots
Add analysis modal:

screen shot 2018-01-17 at 10 09 50

## Acceptance
Use [this document](https://docs.google.com/spreadsheets/d/1evEdrFyJEefx2-NOHU2_kDcNkKNM0_dbvJ-l9BAg2Go/edit#gid=0) and check every copy in Builder has the correct text.

### CODE REVIEW

**Comment by rjimenezda** [comment]
This PR also closes https://github.com/CartoDB/cartodb/issues/13403

**Comment by arianaescobar** [comment]
I just found something here, @rjimenezda 

In dropdowns, we should use the analysis' [shortnames](https://docs.google.com/spreadsheets/d/1evEdrFyJEefx2-NOHU2_kDcNkKNM0_dbvJ-l9BAg2Go/edit#gid=0&range=E:E). Right now, the full name is being displayed instead:

screen shot 2018-03-06 at 11 44 16

**Comment by rjimenezda** [comment]
Good catch. I always forget that analyses show up there as well. I'll give it a look tomorrow

**Comment by arianaescobar** [comment]
Guides are updated (pending merge) and the announcement blog post is mostly ready. Should we run a proper acceptance of this PR to make sure everything is ok? 

@rjimenezda @hannahblue @alonsogarciapablo

**Comment by ivanmalagon** [comment]
I've done an acceptance but feel free to take a second look on it. I'll send you the credentials on private.

**Comment by arianaescobar** [comment]
I found some stuff... sorry guys 😥

### In the Add Columns from Second Dataset analysis

- [ ] The workflow node should have `S` from `Second` in uppercase

screen shot 2018-03-14 at 13 11 00

### In the Create Centroids of Geometries analysis

- [ ] The workflow node should say: `Create Centroids of Geometries`

screen shot 2018-03-14 at 13 08 28

- [ ] `Categorize by` is now just `Categorize`

### In the Find Nearest analysis

- [ ] The Step 1 title should be `Select your points`

screen shot 2018-03-14 at 13 16 43

### Dropdowns

- [ ] Please review that on dropdowns we use the [analysis short name](https://docs.google.com/spreadsheets/d/1evEdrFyJEefx2-NOHU2_kDcNkKNM0_dbvJ-l9BAg2Go/edit#gid=0&range=E:E) instead of the long one. Here, in a dropdown within the analysis options UI, it should only be `Create Lines`.

screen shot 2018-03-14 at 13 20 09

While in another dropdown, in the Add Widgets modal, it's correct:

screen shot 2018-03-14 at 13 21 59

That's how we'll avoid this:

screen shot 2018-03-14 at 13 32 27

- [ ] Although, in the case of `Add columns` above, that's the correct short name. We should make it so that the short name never breaks into two lines. 

- [ ] In the dropdowns inside the Add Widgets modal, we're missing the `Source` after the node. 

screen shot 2018-03-14 at 13 22 15

Like we do have in the rest of the tool:

screen shot 2018-03-14 at 13 24 15
screen shot 2018-03-14 at 13 24 27
screen shot 2018-03-14 at 13 24 52

### Headers

- [ ] The analysis nodes in the headers should be using the analysis short name instead of the long one to avoid this:

screen shot 2018-03-14 at 13 41 20

### Others

- [ ] Please check that [the correct Analysis name](https://docs.google.com/spreadsheets/d/1evEdrFyJEefx2-NOHU2_kDcNkKNM0_dbvJ-l9BAg2Go/edit#gid=0&range=D:D) (the long one) is displayed in both titles or descriptions of all the analyses splash screens. The following ones, for example, are incorrect.

- The name of the analysis in this description should have the proper uppercase letters
screen shot 2018-03-14 at 13 28 30

- It should say `Second` instead of `2nd`
screen shot 2018-03-14 at 13 31 27

- The correct name is `Create Travel or Distance Buffers`
screen shot 2018-03-14 at 13 36 15

- [ ] I couldn't review the copy changes in **Enrich from Data Observatory** because it isn't available on that staging account. Could we enable it to test it?

**Comment by arianaescobar** [comment]
Aweeeeesome ✨
Everything looks great :) 

I don't want to be too picky but there are still some naming incongruencies on the splash screens. For example: 

`layer` instead of `Layer` in the description
screen shot 2018-03-15 at 14 28 48

`travel`, `distance`, and `buffer` should be capitalized 
screen shot 2018-03-15 at 14 29 14

Can you point me to the file/s where I can check these texts without having to perform the actual analysis on Builder? 🙏🏼

@ivanmalagon are we also changing the guides URLs? If so, these are the new ones https://docs.google.com/spreadsheets/d/19cIViUR-wlTAin02pwHdTq9J-MTi5yAw7IiSJvvDSRg/edit

**Comment by rjimenezda** [comment]
@arianaescobar Basically here:

https://github.com/CartoDB/cartodb/blob/analysis-copies-rebase/lib/assets/javascripts/locale/en.json

The overlay texts are all under `"analyses-onboarding"`

**Comment by arianaescobar** [comment]
✨ OMG THAT FILE IS MY MECCA ✨ 
STRAIGHT TO BOOKMARKS

**Comment by alonsogarciapablo** [comment]
Thanks for the thorough acceptance @arianaescobar!

**Comment by arianaescobar** [comment]
@rjimenezda I did some copy corrections here. Ready to copy&paste (&review!).

```
    "sampling": {
      "title": "Subsample Percent of Rows",
      "description": "A sample of your original table was randomly selected to give approximately a percentage of the rows from your base dataset."
    },
    "merge": {
      "title": "Add Columns from Second Dataset",
      "description": "This analysis performed a columnar JOIN in order to get columns from two different tables."
    },
    "intersection": {
      "title": "Select Points in Polygons",
      "description": "This analysis performs a spatial intersection, returning only the rows from the target layer which intersect with geometries in the base layer.",
      "source-cartodb-id": "This number represents the cartodb_id of the base geometry."
    },
    "area-of-influence": {
      "title": "Create Travel or Distance Buffers",
      "description": "Create Travel or Distance Buffers creates polygons according to the parameters set by the user.",
      "the-geom": "This column was updated to show the travel or distance buffers requested."
    },
    "aggregate-intersection": {
      "title": "Intersect and Aggregate",
      "description": "This operation performs a spatial intersection and aggregates the geometry values from the target layer that intersect with the geometry of the base layer.",
      "count-vals-density": "This column is added if COUNT was chosen as the aggregation operation.",
      "extra-column": "This column is added if {operation_type} is chosen with column {column_name}."
    },
    "filter": {
      "title": "Filter by Column Value",
      "description": "Filter by Column Value allows you to quickly narrow down the total data you display on a map or input into an analysis node."
    },
    "filter-by-node-column": {
      "title": "Link Second Layer",
      "description": "Link Second Layer allows you to filter the data in your layer by propagating the filters in the target layer. Now if you filter on widgets added to the first node, the results in the second node would be also filtered."
    },
    "spatial-markov-trend": {
      "title": "Predict Trends and Volatility",
      "trend": "The normalized trend for each geometry.",
      "trend_up": "The probability that a geometry's value will move to a higher class.",
      "trend_down": "The probability that a geometry's value will move to a lower class.",
      "volatility": "A measure of the potential for a geometry to possess values in other classes.",
      "description": "Trends and volatility are calculated based on the time series data input. Trends calculated from inputs with a longer history are more precise. Inputs for the time column should equally spaced (e.g., all one week/month/year apart)."
    },
    "moran": {
      "title": "Detect Outliers and Clusters",
      "description": "Detect Outliers and Clusters finds areas in your data where clusters of high values or low values exist, as well as areas which are dissimilar from their neighbors.",
      "quads": "Classification of the geometry from the analysis.",
      "significance": "The statistical significance of the geometry's classification of one of four quadrant types.",
      "moran": "The local statistic calculated from the Moran's I analysis for each geometry/value in the dataset.",
      "vals": "Value used in analysis. If a denominator is entered, this is the 'standardized' rate (centered on mean, normalized by standard deviation)."
    },
    "kmeans": {
      "title": "Calculate Clusters of Points",
      "cluster-no": "A numeric identifier for each cluster in your dataset. Values start at 1 and go up to the %{clusters} clusters you requested (or max rows if less).",
      "description": "Point clustering uses k-means to calculate a predefined number of clusters from your data."
    },
    "data-observatory-measure": {
      "title": "Enrich from Data Observatory",
      "custom-column": "This column contains the data requested from the Data Observatory.",
      "description": "The Data Observatory enrichment is the result of the geometry location and the measure requested."
    },
    "data-observatory-multiple-measures": {
      "title": "Enrich from the Data Observatory",
      "custom-columns": "These columns contain the data requested from the Data Observatory.",
      "description": "The Data Observatory enrichment is the result of the geometry location and the measures requested."
    },
    "connect-with-lines": {
      "title": "Create Lines from Points",
      "description": "Create Lines from Points using a single point, column values, or a second layer.",
      "the-geom": "This column was updated to be lines according to the method chosen.",
      "line-sequential": "This analysis creates a line by connecting all points in the dataset in a specified order.",
      "line-source-to-target": "Link a source point to a target point based on a shared attribute.",
      "line-to-single-point": "Connect the coordinate from latitude and longitude columns to the point geometry (`the_geom`) in your dataset."
    },
    "group-points": {
      "title": "Create Polygons from Points",
      "the-geom": "This column was updated to polygons encompassing the base points.",
      "category": "This will be the category over which the polygons were calculated.",
      "description": "Group points into polygons to create new polygons."
    },
    "georeference": {
      "title": "Geocode",
      "the-geom": "This column, which stores the geographic information in your dataset, has been updated to reflect the boundaries or locations from the inputs specified.",
      "description": "Geocoding data is a service that uses information from many sources to get the geographical information associated with latitude/longitude columns, city names, postal codes, administrative boundaries, IP addresses, or street addresses."
    },
    "centroid": {
      "title": "Create Centroids of Geometries",
      "description": "Centroids are calculated from all, groups, or singular geometries. Using the optional parameters of Categorize, Weight, and Operation, you can change how they are calculated and what information the result will contain.",
      "the-geom": "Point geometries representing the centroid(s) of your base layer.",
      "aggregated-value": "Stores the aggregate value for each centroid.",
      "non-aggregated-value": "Contains the count of features considered for each centroid.",
      "category": "Stores the category value for each centroid from the base layer."
    },
    "closest": {
      "title": "Find Nearest"
      "description": "Select points from second dataset nearest to the geometries in current layer.",
      "source_cdb_id": "This column has been created with the related points id from the base layer.",
      "the-geom": "This column has been updated with the target table geometries.",
    }
```

**Pull request merged**
