### PR TITLE
Fixes overlap in the analysis onboarding

### LINKED ISSUE #10512: Modal showing analysis results overlaps side panel
On my laptop (1280 x 800) this what happened after adding a new AOI analysis:

screen shot 2016-11-02 at 18 38 27

cc: @javierarce @piensaenpixel

### PR DESCRIPTION
**Pull request by javierarce**
Fixes #10512

screen shot 2016-11-04 at 13 02 59

This PR sets the `.is-editing` class to the onboarding pane if the editor is being used. Previously, that class was only set after the onboarding appeared.

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam

**Comment by xavijam** [comment]
Let me add @nobuti to this thread because he knows more than me about editor model.

**Comment by xavijam** [comment]
About code there is no discussion, it is perfect.

**Comment by nobuti** [comment]
🇸🇭

**Pull request merged**
