### PR TITLE
2586 changing a table from public to private delete visualizations that still have permission

### LINKED ISSUE #2586: Changing a table from public to private delete visualizations that still have permission
1. User A creates a private table and gives read permission to user B.
2. User B creates a visualization based on A.
3. User A switches table to public.
4. User A switches table to private without revoking user B permission.
5. User B visualization has been deleted in spite of having permission.

Making the table private should check for existing permissions.

cc @iriberri

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #2586. Since ACL is not removed when a visualization is made private, explicit permission must be revoked manually, just like when user grant it, but this is consistent with existing UI and we avoid deleting existing visualizations unnoticed. I've tested the full flow (create private table, share, create map with user b, make it public -keeps working-, make it private again -keeps working-, revoke permission -is destroyed-), looks good to me. @Kartones, @javisantana , CR or comments about anything I should've tested?

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5214/))

**Comment by Kartones** [comment]
The datasets used in the map were private right? so the named map was used. If yes, then I think is fine...

maybe just try doing some query from A to some table shared from B after playing with permissions, although they should work as no grants/revokes are performed.

:+1:

**Comment by juanignaciosl** [comment]
Yep, it was private, then shared, then public, then private, then revoked permissions and worked as expected.

I've also done some querying scenarios:
1. Query from new B map to private shared A table --> works, ok.
2. Revoked permissions --> B map is deleted, ok.
3. Retry 1 --> permission denied, ok.
4. Made table public and retry 1 --> permission denied, ok (no explicit grant).
5. Granted read again and retry 1 --> works, ok.
6. Made table private --> B map is still working, ok,
7. Granted write --> still working, ok.
8. Revoked permission (including map deletion warning) --> B map is deleted, ok.

@Kartones, final :+1:?

**Comment by Kartones** [comment]
I think is a go, yes!

**Comment by juanignaciosl** [comment]
Thanks!

**Pull request merged**
