### PR TITLE
Transform create map/dataset button into link

### PR DESCRIPTION
**Pull request by javierarce**
Original issue: #4739 

screen shot 2015-07-29 at 13 09 03
screen shot 2015-07-29 at 13 09 17

cc @josecruz

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5464/))

**Comment by josecruz** [comment]
Looks good to me! :+1:

**Comment by xavijam** [comment]
Hey guys, we decided to have this element as a button, why did we change it?
cc @piensaenpixel @saleiva

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5625/))

**Pull request merged**
