### PR TITLE
infowindows: close buttons

### PR DESCRIPTION
**Pull request by matallo**
close https://github.com/CartoDB/cartodb/issues/7737

CR @alonsogarciapablo /cc @piensaenpixel

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
Thanks! 👍 

Can we bump the internal dependencies and the version in package.json so that editor starts using the version of CartoDB.js that enables this? Thx

**Comment by matallo** [comment]
damn, I always forget it ><

**Comment by matallo** [comment]
done ✨

**Comment by alonsogarciapablo** [comment]
🚢

**Pull request merged**
