### PR TITLE
Provide layer cartocss in viz-json v3

### PR DESCRIPTION
**Pull request by xavijam**
Related tickets: https://github.com/CartoDB/support/issues/858 and https://github.com/CartoDB/support/issues/859

### THE PROBLEM
We are not providing the CartoCSS within the layers information in the vizJSON v3. Turns out, when map instantiation is completed, CARTO.js takes the CartoCSS info from it and add it to the CARTO.js layer model. Bad thing? It comes "converted", not with turbo-carto, and it makes fail the auto-style.

Adding an example, because it is easier:

- Create a map, imagine you have a layer of points, and you apply this type of CartoCSS (via UI or manually).
```css
#layer {
  marker-fill: ramp([category], (#ff3300, #00ffff, #ffff00, #ff00ff,#66ff33), ("Partiers", "Intra-borough residents", "Working class", "Visitors with Expensive Taste", "Orthodox Jewish"), "=");
  marker-fill-opacity: .5;
  marker-allow-overlap: true;
  marker-line-width: 0;
  marker-line-color: #ffffff;
  marker-line-opacity: 1;
}
```
- Publish it.
- Go to the public embed url and open the browser developer tools.
- Print `vizJSON` object in the console and check that layer doens't contain the CartoCSS.
screen shot 2017-07-20 at 12 23 55

- But, if you check the instantiation response (remember, ```/api/v1/map/named/tpl_xxxx…/jsonp?config=xxxx```), layer info will contain the converted CartoCSS.
screen shot 2017-07-20 at 12 25 51

CARTO.js will take (you, CARTO.js, smart :) ) that CartoCSS from the instantiation response and will add it in the layer-model.
```css
#layer {
  [ category = "Partiers" ] {
    marker-fill: #ff3300;
  }
  
  [ category = "Intra-borough residents" ] {
    marker-fill: #00ffff;
  }
  
  [ category = "Working class" ] {
    marker-fill: #ffff00;
  }
  
  [ category = "Visitors with Expensive Taste" ] {
    marker-fill: #ff00ff;
  }
  
  [ category = "Orthodox Jewish" ] {
    marker-fill: #66ff33;
  }
  marker-fill-opacity: .5;
  marker-allow-overlap: true;
  marker-line-width: 0;
  marker-line-color: #ffffff;
  marker-line-opacity: 1;
}
```
- Bad thing is when you want to apply the auto-style, it will look into the "current" CartoCSS the main "marker-fill" attribute and it will not find it, because rest of marker-fill are located within conditionals, and we get rid of them in the process of autostyle. So, the CartoCSS of the autostyle ends up to be:

```css
#layer {
  [ category = "Partiers" ] {
  }
  
  [ category = "Intra-borough residents" ] {
  }
  
  [ category = "Working class" ] {
  }
  
  [ category = "Visitors with Expensive Taste" ] {
  }
  
  [ category = "Orthodox Jewish" ] {
  }
  marker-fill-opacity: .5;
  marker-allow-overlap: true;
  marker-line-width: 0;
  marker-line-color: #ffffff;
  marker-line-opacity: 1;
}
```

- And that's why you can find the map with this look:
screen shot 2017-07-20 at 12 36 01

### THE SOLUTION
Provide the CartoCSS of the CARTO layers in the vizJSON v3.

### QUESTIONS ASKED?
I've been wondering with @matallo and @javisantana about why it was NOT included from the beginning. @javisantana said we didn't want to include it in order to not expose any info about the style, but it doesn't make sense because it appears in the instantiation response, so it is likely there is no problem. In any case, @juanignaciosl, it would be great if you can check it/confirm it.

### HOW MANY MAPS ARE AFFECTED BY THIS PROBLEM?
All **public** maps having a ramp applied in the original CartoCSS, and if the user wants to apply the auto-style.

### DOES IT ONLY AFFECT PUBLIC MAPS?
Yes, because private Builder provides the original CartoCSS from the beginning and CARTO.js initializes layers with that value.

@nobuti @saleiva @noguerol @kevin-reilly for awareness.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Santana Is Right™. As this is a Builder map, layers are presented as "named map layers" by [VizJSON3NamedMapLayerPresenter#data_for_carto_layer](https://github.com/CartoDB/cartodb/blob/831fcd9392913503afce4952611e8de1c89266ec/app/controllers/carto/api/vizjson3_presenter.rb#L246), which doesn't output the style. I must admit that I don't know why, but _this is a feature_. Nevertheless, I don't know the motivation for that. If you think that we should do it, we will.

@xavijam , Let's add cartocss to vizjson for named map layers, then?

**Comment by xavijam** [comment]
Yeah, I feel we should add them. Fixing the tests right now mate 💋

**Comment by juanignaciosl** [comment]
@xavijam sorry, I didn't see that you had already done it. 👍  to the change and the test. Please apply for the next backend position :-)

**Comment by xavijam** [comment]
> @xavijam sorry, I didn't see that you had already done it. 👍 to the change and the test. Please apply for the next backend position :-)

I've heard there is no space left now :joy:.

**Comment by xavijam** [comment]
Testing it in ded02.

**Pull request merged**
