### PR TITLE
Add loading+error state for privacy dialog

### LINKED ISSUE #2338: Changing map privacy to password protected requires at least two clicks on "save settings"
The first time you click on "save settings" after setting a password no requests are done.

image

### LINKED ISSUE #2340: Add loading state (and error if needed) when a dataset/map is changing its privacy

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2340 

The previous approach, of using the tab pane, was not very suitable for this use-case which became painfully clear when trying to accommodate the new saving and error states. So, instead I've replaced it with the same approach as done in the other dialogs, i.e. a view model to encapsulate the view logic.

privacy-loading

Also:
- It will display a generic error message if the save fails for whatever reason
- Fixes #2338 the bug that required two clicks to trigger events
- Bonus:
  - Permissions will only be persisted if they are actually changed
  - Fixed typo in sub title, now it states _Although we believe in the power of open data, you can also protect your ~~tables~~ **dataset**._ (or _map_), depending on viewing a dataset or map.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1885/))

**Comment by viddo** [comment]
ping @xavijam @saleiva code review etc. (see description for rationale and scope)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1886/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1887/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1888/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1889/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1891/))

**Comment by xavijam** [comment]
Check tests :), apart from that, go ahead :+1:.

**Comment by viddo** [comment]
Backend tests, fix on the way here --> #2486

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1896/))

**Pull request merged**
