### PR TITLE
Show deprecation warning for DO enrichment analysis [ch126412]

### PR DESCRIPTION
**Pull request by neokore**
Related to https://app.clubhouse.io/cartoteam/story/126412/add-deprecation-message-in-do-analysis

### CODE REVIEW

**Comment by neokore** [comment]
Acceptance: https://ryeguas1.carto-staging.com/
But staging dedicated has problems to enable DO Catalog, we are working on it, but you can bypass it via JS.

**Comment by neokore** [comment]
Please confirm deprecation date, deprecation warning date and the "more info" link. /cc @VictorVelarde @borja-munoz

**Comment by borja-munoz** [comment]
These details must be confirmed by @xavipereztr and/or @martejpad

**Comment by VictorVelarde** [comment]
LGTM. Details on dates were set in the original card:
- official deprecation date: 2021-03-15
- warning date: the deployment date, asap (currently set on today, 2021-02-09)

**Comment by VictorVelarde** [comment]
So I'm gonna fix assets and make a deployment asap

**Review by VictorVelarde — APPROVED** [review]
🚀

**Pull request merged**
