### PR TITLE
Import animation

### PR DESCRIPTION
**Pull request by javierarce**
Adds import animation to the onboard screen. See #3001.

### CODE REVIEW

**Comment by javierarce** [comment]
@xavijam: can you review this, please?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3059/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3061/))

**Comment by javierarce** [comment]
@xavijam: can you review this, please?

**Comment by xavijam** [comment]
Haven't you finally added a C option? (

**Comment by javierarce** [comment]
No, @saleiva told me not to add it for the moment.

**Comment by xavijam** [comment]
:(, ok. Code is ok.

**Comment by javierarce** [comment]
Thanks.

**Pull request merged**
