### PR TITLE
Add index to eumapi

### LINKED ISSUE #7148: List users at the Enterprise User Management API
Even it's not hard to get that information from the postgres catalog views, it'd be nice to have implemented retrieving the list of users of the organization to complete the typical CRUD operations.

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #7148 

I had to use v2, since there is already a `'(/user/:user_domain)(/u/:user_domain)/api/v1/organization/:id/users'`

that conflicts with RESTfull list. I couldn't refactor that one since it accepts a complex paged query.

All other routes are updated and backwards compatible with v1, so shouldn't be a major drama.

Please review, @juanignaciosl .

### CODE REVIEW

**Comment by juanignaciosl** [comment]
I wouldn't duplicate every route, I'd only add the new one, but I guess that is a matter of taste (maybe it should've been v2 from the very beginning). How come the previous endpoint is not enough to solve #7148?

**Comment by gfiorav** [comment]
About the `v2` on all routes: it's to simplify the usage, if you use `v1` for the other routes it's also ok. I thought it was the best solution overall.

Regarding the previous endpoint: it's meant to be paginated and accepts some other params to do so. Not to RESTy. If you think that was better then lets consider just documenting that endpoint.

**Comment by juanignaciosl** [comment]
I have no strong opinion on any of the comments, so up to you. 👍

**Comment by gfiorav** [comment]
Thanks @juanignaciosl !

Hey @csobier , we need to update the docs for EUMAPI!

Main changes are that were it said `v1` it's now `v2` and that we need to add a new section (like update a user, show a user, etc.) for showing all users (called index) that would be a `GET` to `.../organization/:name/users`

**Pull request merged**
