### PR TITLE
Static pages bug fixes and Feature Flag removal

### PR DESCRIPTION
**Pull request by jesusbotella**
This PR applies the final touches to static pages deploy:

- Fixes a bug inside the Profile page that broke Billing link on the Profile page sidebar.
- Removes the feature flag check on Profile and Account pages, to always render the static version of Profile and Account pages, so that we don't serve different assets depending on the CARTO flavour that the user uses (Hosted or Open Source).
- Generates only `profile` and `dashboard` static pages: the ones that we need to serve.

### Acceptance

- [ ] Rails fallback. No NGINX (Local, open source development).
- [ ] Staging

### CODE REVIEW

**Comment by ivanmalagon** [comment]
**Rails fallback**

Tested with a user that has no migration FF:
- Production mode with `grunt build`: pages get built and served. They work OK.
- Development mode with `npm run dashboard`: pages get build and served. They work OK.

**NGINX serving**
Waiting for redeployment to pass acceptance on staging.

**Comment by ivanmalagon** [comment]
**NGINX part on staging**

- Both pages are served to a user with no FF.
- Forms and links are working.

**Comment by alrocar** [comment]
Acceptance 🍏 

I didn't realize before but should we fix the failing tests or is it something transient?

**Comment by jesusbotella** [comment]
Yes, I think we should fix the tests, gonna look a it right now 😂

**Comment by jesusbotella** [comment]
retest this please

**Pull request merged**
