### PR TITLE
Add some warnings about updating extensions

### PR DESCRIPTION
**Pull request by rafatower**

### CODE REVIEW

**Review by ilbambino — APPROVED** [review]
👍

**Comment by rafatower** [comment]
Of course this PR does not actually touch code and shouldn't affect tests.

This is the only one reported as broken after running the retries (in `serial_tests_logs`):
```
Failures:

  1) DataImport updates synch_job state after failed data import
     Failure/Error: Carto::Synchronization.find(sync_job.id).state.should eq Carto::Synchronization::STATE_FAILURE
       
       expected: "failure"
            got: "queued"
       
       (compared using ==)
     # ./spec/models/data_import_spec.rb:421:in `block (2 levels) in <top (required)>'

Finished in 5 minutes 6.18 seconds
90 examples, 1 failure

Failed examples:

rspec ./spec/models/data_import_spec.rb:409 # DataImport updates synch_job state after failed data import
```

looks a lot like a race condition (checking before finishing)

**Comment by rafatower** [comment]
I can reproduce the failure locally:
```
carto@5b36b3bc0cfa:/cartodb$ RAILS_ENV=test bundle exec rspec ./spec/models/data_import_spec.rb:409
  updates synch_job state after failed data import (FAILED - 1)

Failures:

  1) DataImport updates synch_job state after failed data import
     Failure/Error: Carto::Synchronization.find(sync_job.id).state.should eq Carto::Synchronization::STATE_FAILURE
       
       expected: "failure"
            got: "queued"
       
       (compared using ==)
     # ./spec/models/data_import_spec.rb:421:in `block (2 levels) in <top (required)>'

Finished in 1 minute 3.41 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/models/data_import_spec.rb:409 # DataImport updates synch_job state after failed data import
```

**Comment by rafatower** [comment]
This was the problem with the regression test:

https://github.com/CartoDB/cartodb/blob/9540b7e04f88bb26dbf244c56d343dd443b047cf/spec/models/data_import_spec.rb#L415

```
carto@5b36b3bc0cfa:/cartodb$ curl --connect-timeout 10 http://mydatasource.cartodb.wadus.com/foo.csv
curl: (28) Connection timed out after 10000 milliseconds
```

**Comment by rafatower** [comment]
We're gonna have to wait to lauch the CI again:
```
2021-06-08T10:13:55.7693620Z ERROR:  Could not find a valid gem 'bundler' (= 1.17.3), here is why:
2021-06-08T10:13:55.7695369Z           Unable to download data from https://rubygems.org/ - bad response Service Unavailable 503 (https://api.rubygems.org/specs.4.8.gz)
```

**Pull request merged**
