### PR TITLE
6860 analysis payload consistency check

### LINKED ISSUE #6860: Analysis payload consistency check

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #6860.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
@javitonino CR this, please.

**Comment by javitonino** [comment]
`params_from_request` and `json_post` seem to do mostly the same. Can you rewrite one in terms of the other?

**Comment by juanignaciosl** [comment]
@javitonino take a second look, please.

**Comment by javitonino** [comment]
Better, thanks! LGTM :+1:
P.S: Love that commit message :stuck_out_tongue_closed_eyes:

**Comment by juanignaciosl** [comment]
outch :sweat_smile:

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
@javitonino sorry, do a second CR, please. A merge with master has been a little painful.

**Comment by javitonino** [comment]
Quite the merge. Everything looks ok, ship it!

**Pull request merged**
