### PR TITLE
Using organization to_poro method instead of direct object dump

### PR DESCRIPTION
**Pull request by Kartones**
@javisantana  CR please

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2008/))

**Comment by javisantana** [comment]
@viddo added that change so he should know if this works

**Comment by viddo** [comment]
By looking at the code it should work fine, but to be certain we would have to verify by visiting a new public page with a logged in organization user.

**Comment by javisantana** [comment]
@viddo could you take care of that testing?

**Comment by viddo** [comment]
sure!

**Comment by viddo** [comment]
Found another bug while at it, fixed and verified :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2012/))

**Pull request merged**
