### PR TITLE
Fix password button state

### LINKED ISSUE #4613: When clicking on password protected and then clicking on the unavailable button it returns an error
When clicking on password protected and then clicking on the unavailable button it returns an error:
privacy

### PR DESCRIPTION
**Pull request by viddo**
Fixes #4613 

@javierarce can you code review please? Changed the previously changes, so render on model change, except for password which is handled by the event specific callbacks (password change, input key up), and update UI based on current model state to avoid the inconsistent states.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5222/))

**Comment by javierarce** [comment]
:+1:

But will it still be possible to click in the disabled button? Shouldn't we stop the event?

**Comment by viddo** [comment]
No need to, there was already a [check to abort if option model indicates that can't save](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/change_privacy/change_privacy_view.js#L30-L32), the problem was that the UI didn't reflect the correct UI state (disabled) and the model having a default password when it should have been empty, that's what I fixed in the PR

**Comment by javierarce** [comment]
Oh, ok. Thanks for the explanation!

**Pull request merged**
