### PR TITLE
Implement lock datasets dialog

### PR DESCRIPTION
**Pull request by viddo**
solves #1744 

I feel the copy could be improved, have a look at the screenshots:
screen shot 2015-01-15 at 18 40 22
screen shot 2015-01-15 at 18 40 00

Also refactored delete items dialog to simplify the code, with the batch process convenient function.

### CODE REVIEW

**Comment by viddo** [comment]
ping @xavijam @saleiva @carlostallon please review :)

**Comment by saleiva** [comment]
Unlock action should be green (the button and the icon :P)
Can we also add a line break after "...list."?

**Comment by viddo** [comment]
Aha, yeah both ideas sounds good to me, I'll fix them

**Comment by xavijam** [comment]
Do we have any unlock icon? It would be great if it changes when user tries to unlock the map/dataset. And I would make the text block narrower.

**Comment by xavijam** [comment]
Using branch ```1744-lock-datasets-dialog``` for fixing https://github.com/CartoDB/cartodb/issues/1817

**Comment by xavijam** [comment]
I've checked that the dialog is not hidden until "save" is done, and sometimes it takes time. Shouldn't we close the window without waiting the response? I feel it is a simple call and it shouldn't fail. Or add the loader after user decide to lock/unlock...

**Comment by viddo** [comment]
Line break'd:
screen shot 2015-01-16 at 10 07 02

Unlock icon + indicated as a positive action:
screen shot 2015-01-16 at 11 10 51

**Comment by xavijam** [comment]
:+1:

**Comment by viddo** [comment]
@xavijam re: the delay on lock/unlock => updated view, that's a problem for all changes that are done async. I would suggest that we try to implement and apply a consistent pattern to not have to re-implementing this behaviour on every use-case. @saleiva [proposed a intermediate-loading-kind-of-screen](https://github.com/CartoDB/cartodb/issues/1633#issuecomment-68736291) which I think is a good solution for current use-cases. 

BUT that said, since we disabled the batch operations and I considered this "nice-to-have". I propose to create an issue to track these cases and put it on the backlog for now, and start working on it when we know we have time and can meet the Feb deadline.

**Comment by xavijam** [comment]
ok

**Comment by viddo** [comment]
[done](#1825), put it on the last milestone before deadline

**Comment by xavijam** [comment]
Let me finish my task, check it, wait for green ball and go, agree?

**Comment by xavijam** [comment]
BTW viddo, lock_datasets_view is a bit confused, because you can lock maps and datasets.

**Comment by viddo** [comment]
AFAIK, one can only lock datasets, right? If it's necessary I could throw an error if trying to open the view if given items are not datasets, but even so I think the "Lock selected items..."-link should be displayed when viewing maps in the first place, so should not reach that state.

**Comment by saleiva** [comment]
Nope, Maps can be also locked (pretty useful when you put a map in production in a blogpost for example)

**Comment by xavijam** [comment]
Not together, so:
- Lock/unlock datasets.
- Lock/unlock maps.

**Comment by viddo** [comment]
Oh, my bad.. should just be a concern for the copy in the template, easily fixed

**Comment by viddo** [comment]
@xavijam forgot to [run the tests](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1151/console)?

**Comment by xavijam** [comment]
Yes :(


On 16 Jan 2015 at 12:51:52, Nicklas Gummesson (notifications@github.com) wrote:

@xavijam forgot to run the tests?

**Comment by viddo** [comment]
Fixed last issues, will be able to lock/unlock maps as well, and with proper copy:
screen shot 2015-01-16 at 14 37 16

@xavijam please review last commits :**

**Comment by xavijam** [comment]
retest this please

**Comment by xavijam** [comment]
:+1

**Pull request merged**
