### PR TITLE
Fix disconnect from external sources for org users (gdrive, box and dropbox)

### PR DESCRIPTION
**Pull request by VictorVelarde**
### Acceptance
The issue affects organization users, when dealing with **gdrive, dropbox and box**

A deployment to staging has been done with these users:
- *gdrive*
- *my-connect-org-1* at my-connect-org

The acceptance should include a test with both of them, for these 3 services.

The test consists in:
1. Go to _Account settings_
2. Click on _Account_
3. _Connect to external data sources_ > select a service
4. _Connect_ (**)
5. **Disconnect** --> EXPECTED result: the disconnection is successful

Tests:
- [x] **gdrive** user --> at https://gdrive.carto-staging.com/account
- [x] **my-connect-org-1** user --> https://my-connect-org.carto-staging.com/u/my-connect-org-1/account

---

(**) **IMPORTANT**: some warnings on security will appear at step 4. Be sure to allow popups AND unverified app

### CODE REVIEW

**Comment by jesusbotella** [comment]
What was the original error? I suppose it was complaining when building the request URL, right?

**Comment by VictorVelarde** [comment]
Hi @jesusbotella The wrong URL, causing a 404, was something like this: 
https://deliverydotcom.carto.com/u/delivery/undefined/api/v1/imports/service/gdrive/invalidate_token

The offending 'undefined' was being built at https://github.com/CartoDB/cartodb/blob/a2d5edb1aa64844c968d731b6015345c4821da60/lib/assets/javascripts/dashboard/data/backbone/sync-options.js#L25

**Comment by VictorVelarde** [comment]
Hi @jesusbotella if your fine with it, we'll move to Acceptance

**Comment by VictorVelarde** [comment]
All right, I also made my acceptance, without warnings, so I'll merge and deploy.

We can reopen the original issue if anything happens later on.

**Pull request merged**
