### PR TITLE
4229 check name duplication against central user database to avoid user creation failure

### LINKED ISSUE #4229: Check name duplication against central user database to avoid user creation failure
If you signup at organization signup page with google button with the gmail mail that shares username with a user not local (existing in Central) it should have a fallback like as it where local.

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #4229. @Kartones CR this, please.

### CODE REVIEW

**Comment by Kartones** [comment]
:+1:

**Comment by juanignaciosl** [comment]
@Kartones , @ethervoid , could you CR this, please? I had to change a couple of things, first because of tests, and then I thought a better design that I had to undo :sweat_smile: . Also, there's a test configuration change I want you all to agree.

**Comment by Kartones** [comment]
:+1: I haven't yet done any central-related tests so if is ok to remove the central config... fine by me

**Comment by juanignaciosl** [comment]
Ok, merging, since test passes, it works in staging and @ethervoid is on vacation today :-) Thanks!

**Pull request merged**
