### PR TITLE
Analyses views folder

### LINKED ISSUE #7444: Create a folder for analyses views within layer-content-views
:)

### PR DESCRIPTION
**Pull request by nobuti**
This PR closes #7444.

cc @xavijam @viddo

### CODE REVIEW

**Comment by viddo** [comment]
👍

**Comment by viddo** [comment]
Merge? Would need this to continue working on the analysis, to avoid conflicts :)

**Comment by nobuti** [comment]
Sorry @viddo for the delay, I didn't have cristal clear about the person responsable to make the merge.

**Comment by viddo** [comment]
No worries :) 
Generally, the person who creates the PR is responsible for merging (after review etc.)

**Pull request merged**
