### PR TITLE
WIP: Working SAML auth in VM against a test endpoint

### PR DESCRIPTION
**Pull request by CloudNiner**
This PR allows SAML authentication in Carto. Configured via a new `saml_authentication` property in app_config.yml. Generally, if configured, SAML authentication takes precedence over other methods.

These are the basics required for a specific client and works with their SAML authentication scheme. Additional TODOs are noted below, some of which are not necessary for the client, but should be strongly considered now that this feature is moving out of a Carto fork.

Instructions to setup a development environment to test this were provided to @javisantana via the #cartodb-azavea slack channel.

Additional TODOs:
 - Autocreate users if the user doesn't exist yet in
   cartodb on login. Should be quite straightforward to do
   this in the same way as for http_header_authentication.
 - Come up with a way to test this code in isolation
 - Clean up a bit so that SAML is more compatible with
   other auth providers
 - Come up with a more extensible way to convert the SAML
   name_id to a username/subdomain
 - Handle subdomainless urls
 - Implement SAML logout. This was not part of the original feature
   request for us. But should be relatively straightforward:
   https://github.com/onelogin/ruby-saml#single-log-out

### CODE REVIEW

**Comment by juanignaciosl** [comment]
I'll be working on the testing and merge here: CartoDB/cartodb/pull/11047 .

**Comment by juanignaciosl** [comment]
Hi, @CloudNiner . I'm testing this and I have a first question. Disclaimer: I haven't used SAML before, so it will probably be easy or dumb :_).

I'm testing this with Salesforce SAML. After setting everything until authentication response worked, authentication fails because `name_id` is empty. [Code](https://github.com/CartoDB/cartodb/pull/11047/files#diff-d5241d488259f32ecbe2f636133e5ddaR190):

```ruby
=> 190:     return nil unless saml_response.attributes['name_id'].present?
```

Salesforce returns these attributes:

```ruby
@attributes={"userId"=>["0050Y000000NjP5"], "username"=>["juanignaciosl@carto.com"], "email"=>["juanignaciosl@carto.com"], "is_portal_user"=>["false"]}
```

You said that "Come up with a more extensible way to convert the SAML
name_id to a username/subdomain". Does that mean that you chose `name_id` because it fits your environment? Would a "name_attribute" configuration parameter that defaults to `name_id` but that can be set to `username` in my case makes sense to you?

Thanks!

**Comment by CloudNiner** [comment]
No problem, happy to help. Definitely not dumb questions!

We just expect that some field in the SAML response identifies a unique ID for a user. Adding a configuration parameter for that field to the saml_authentication section in app_config.yml makes sense, as you suggested. We just used `name_id` because it was the field our SAML endpoint was using. 

The comment regarding "Come up with a more extensible way to convert the SAML
name_id to a username/subdomain" was more focused around this bit, which transforms the email in name_id to a Carto username [(link)](https://github.com/CartoDB/cartodb/pull/10991/files#diff-d5241d488259f32ecbe2f636133e5ddaR192):
```ruby
=> 192:    subdomain = CartoDB.email_to_subdomain(saml_response.attributes['name_id'])
```
Our email_to_subdomain method was a bit more specific than the one here, I just tried to make it as generic as possible, but I'm sure I missed some cases. If the unique ID that the SAML endpoint returns isn't an email, you could just use that for the username instead of munging the email. This might be something else that can be sensibly configured in app_config.yml.

**Comment by juanignaciosl** [comment]
@CloudNiner thanks! I'll probably add the `name_id` configuration to the first merge, and approach the transformation and other TODOs afterwards.

**Pull request merged**
