### PR TITLE
Don't automatically open the share modal after the vis is created

### PR DESCRIPTION
**Pull request by javierarce**
What it says on the tin.

Original ticket: https://github.com/CartoDB/cartodb/issues/3973

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4323/))

**Comment by javierarce** [comment]
@viddo: can you have a look, please?

**Comment by viddo** [comment]
:ok_woman: :ok_hand:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4331/))

**Comment by xavijam** [comment]
Have you tried this change? I feel this is provoking a JS error (https://github.com/CartoDB/cartodb/issues/4067).

Uncaught Error: success callback is required

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4359/))

**Pull request merged**
