### PR TITLE
Test - adding an empty file to trigger build

### PR DESCRIPTION
**Pull request by rporres**
Testing https://github.com/CartoDB/cartodb-onpremise/issues/555 against a branch containing a trivial change

### CODE REVIEW

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by rporres** [comment]
Works fine. Closing the PR without merging.

**Comment by rporres** [comment]
reopening to check PR hooks

**Comment by rporres** [comment]
It was not reopened as branch is deleted

**Pull request closed without merging**
