### PR TITLE
Fix for https mixed content when requesting cached embed

### PR DESCRIPTION
**Pull request by rafatower**
Kind of urgent fix

@javisantana or @Kartones please review

### CODE REVIEW

**Comment by rafatower** [comment]
Kartones reviewed it on my desk and says ok

**Comment by javisantana** [comment]
looks ok

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3858/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3859/))

**Pull request merged**
