### PR TITLE
Open analysis modal from edit-analysis-workflow

### LINKED ISSUE #6951: Check and connect all "add analysis" buttons available under analysis form views
screen shot 2016-03-22 at 15 02 38
screen shot 2016-03-22 at 15 02 51

### PR DESCRIPTION
**Pull request by viddo**
Opens analysis from the editing analysis

Resolves #6951

@xavijam can you review?

### CODE REVIEW

**Comment by xavijam** [comment]
Easy and straight-forward :clap:.
Also, I feel it fixes #6951, doesn't it?

**Comment by viddo** [comment]
Missed that one, fixed in the last commit.

"Easy and straight-forward", IMHO should be easier, I still think passing dependencies several layers still smell, but I'll address that separately.

**Comment by xavijam** [comment]
From what we have, it is easy. About if it could be easier, yes. But as you have said, let's tackle it in a separate issue.

**Comment by viddo** [comment]
Frontend tests passing, merging

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
