### PR TITLE
backend support for size on all visualization types

### PR DESCRIPTION
**Pull request by Kartones**
Backend part solution for #3701

### CODE REVIEW

**Comment by Kartones** [comment]
@juanignaciosl micro-CR please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3774/))

**Comment by juanignaciosl** [comment]
:+1: , although a test -covering both old and new endpoints, probably- would've been nice.

**Comment by Kartones** [comment]
There are some tests about the query builder but they mock sizes.
Here I'd have to also mock the table object *... and really doing a table.size or 0 check didn't looked like an interesting spec... I'd prefer to do meaningful unit tests only.

* else this gets deep into querying the DB, and table sizes are tricky to check, building the specs of the query builder I hit various PG issues because size are estimations and not recalculated instantly, so far from easy to test in detail from here.

**Pull request merged**
