### PR TITLE
3458 detect gnip server errors

### LINKED ISSUE #3458: Twitter imports should return a meaningful error message when gnip is down
See import with id `30fd3832-a12b-43f0-8daa-cf77f395da6e`

gnip was down and returning 503 errors at the time of the import.

Branch: `3458-detect-gnip-server-errors`

### PR DESCRIPTION
**Pull request by Kartones**
Closes #3458

### CODE REVIEW

**Comment by Kartones** [comment]
@rafatower CR please :) Easy one!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4450/))

**Comment by rafatower** [comment]
:+1:

buuut... you add a new error code and need to modify 5 files. Just take a look at this: https://github.com/CartoDB/cartodb/blob/master/services/table-geocoder/lib/exceptions.rb

With that code, there's 1-on-1 relation between exception and error code, you can write things like:
```ruby
# from exception to error code
GmeGeocoderTimeoutError.additional_info.error_code
GmeGeocoderTimeoutError.additional_info.title

# from error code to additional info
Carto::GeocoderErrors.additional_info(1000).title
Carto::GeocoderErrors.additional_info(1000).what_about
```

**Comment by Kartones** [comment]
Oh, I like your way, indeed!

I had to change a lot of files, yes, but the dammed importer needs a rewrite of the exceptions hierarchy in general, to clean the error mapping and all this stuff. Note taken and next time I'll implement your system at the importer.

**Pull request merged**
