### PR TITLE
#6187 Presenter cache for user presenter

### LINKED ISSUE #6187: Get rid of redundant dashboard queries
While we where investigating CartoDB/cartodb-management#4338 we saw that dashboard repeats (x1) user database size and (x3) user visualization total counts per each visualization. Eliminating those 8 queries would reduce the number of queries by 50%, reducing the need of hitting the user database (`cartodb.CDB_UserDataSize`).

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #6187 and should improve dashboard performance.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
@rafatower, @ethervoid  CR this, please.

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by juanignaciosl** [comment]
Ping @ethervoid, @rafatower

**Comment by ethervoid** [comment]
:+1:

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
