### PR TITLE
Several public map fixes

### LINKED ISSUE #3419: Embed author link points to faulty URL
screen shot 2015-04-29 at 15 08 23
_from article here: http://pejl.svt.se/stora-skillnader-i-ambulanssjukvarden/_

Expected result: The maps page of that user
Actual result: Redirected to either login page (if not logged in) or my own public page (if logged in).

I guess it's because the URL points to `username.cartodb.com/` when it probably should be `username.cartodb.com/maps` nowadays (due to the recent URL changes)

### LINKED ISSUE #3420: Map author link on map page points to wrong URL
screen shot 2015-04-29 at 15 10 08
https://team.cartodb.com/u/saleiva/viz/95b85b34-ead3-11e4-9292-0e9d821ea90d/public_map

Expected: Take me to the profile of that user (https://team.cartodb.com/u/saleiva/)
Actual: Takes me to my own profile page (logged in, I guess due to redirect, URL points to https://saleiva.cartodb.com/)

### PR DESCRIPTION
**Pull request by xavijam**
- [x] Styles were broken when owner name was so long.
- [x] Map description styles changed (normal weight, lighter color).
- [x] Related tables weren't rendered in some cases.
- [x] Map owner link was wrong (fixes #3420).
- [x] Square logo, being in mobile, resized.
- [x] Embed map owner link fixed (fixes #3419).

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3359/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3363/))

**Comment by Kartones** [comment]
This fixes part of #3408

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3375/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3376/))

**Pull request merged**
