### PR TITLE
fixes using !bbox! in sql view

### PR DESCRIPTION
**Pull request by javisantana**

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3498/))

**Comment by javisantana** [comment]
cc @viddo 
cc @Kartones because of the refactor

**Comment by Kartones** [comment]
mm you forgot to make the change also at https://github.com/CartoDB/cartodb/blob/master/app/models/layer.rb (the old model). Take into account that until everything is migrated, changes need duplicating code

**Comment by Kartones** [comment]
for the rest ok, but check that please

**Comment by viddo** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3513/))

**Comment by javisantana** [comment]
cc @Kartones

**Comment by Kartones** [comment]
good to go!

**Comment by saleiva** [comment]
bump!

**Comment by viddo** [comment]
:+1:

**Comment by saleiva** [comment]
bump!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4117/))

**Comment by javisantana** [comment]
restest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4129/))

**Comment by saleiva** [comment]
bump!

**Comment by xavijam** [comment]
What about this?

**Pull request closed without merging**
