### PR TITLE
fix spaces

### PR DESCRIPTION
**Pull request by piensaenpixel**
@nobuti 👓 

image

Close https://github.com/CartoDB/cartodb/issues/9224

### CODE REVIEW

**Comment by nobuti** [comment]
👍  not sure if we should add a helper for this in the same manner as `u-tSpace--m` and so on.

**Comment by piensaenpixel** [comment]
we need remove the margin, not change it :( and the component is common for all the builder, isn't it?

**Comment by piensaenpixel** [comment]
@nobuti green light? :D

**Comment by nobuti** [comment]
@piensaenpixel first thing in the morning, I promise 😞

**Comment by nobuti** [comment]
🇪🇸

**Pull request merged**
