### PR TITLE
[DO] Token endpoint

### PR DESCRIPTION
**Pull request by gonzaloriestra**
Related to CartoDB/cartodb#15077

### CODE REVIEW

**Comment by alrocar** [comment]
If I'm not wrong we added this [issue](https://github.com/CartoDB/cartodb-central/issues/2556) to avoid having to call central for the token.

Right now, I think we can try with the current approach in this PR. It will add a little bit more of latency but since the whole process is batch and it happens once every hour I think it's fine.

**Comment by gonzaloriestra** [comment]
@alrocar I thought we changed the approach when we decided to use the short-lived access tokens, but I guess we could sync the key anyway and request the token directly from cartodb. Anyway, yes, we can improve it in the next iteration.

**Comment by alrocar** [comment]
@gonzaloriestra sure, no problem. Let's move forward!

**Comment by oleurud** [comment]
## Acceptance [wip]
- [x] fails without api_key
- [x] fails with random apikey
- [x] works getting token with master
- [x] works getting token with regular api key
- [x] fails getting token with regular api key without do permissions
- [x] works getting token with oauth api key
- [x] fails getting token with oauth api key without do permissions
- [ ] can do queries to BQ with the token

**Pull request merged**
