### PR TITLE
913 faster excel imports

### PR DESCRIPTION
**Pull request by rafatower**
@juanignaciosl can you please review?

### CODE REVIEW

**Comment by juanignaciosl** [comment]
:+1:

**Comment by rafatower** [comment]
The failure is due to the missing pip package: `sh: 1: in2csv: not found` though it is listed in `python_requirements.txt`

**Comment by rafatower** [comment]
please retest

**Comment by rafatower** [comment]
retest please

**Comment by rafatower** [comment]
test please

**Comment by rafatower** [comment]
please test

**Comment by rafatower** [comment]
retest this, please

**Comment by recena** [comment]
retest this, please

**Comment by rafatower** [comment]
retest this, please

**Comment by recena** [comment]
@rafatower It seems everything it is working fine.

**Pull request merged**
