### PR TITLE
Add affected users feedback before revoking access

### LINKED ISSUE #1963: Show feedback of affected users/visualizations before revoking access
In the privacy dialog a owner of a dataset can revoke access:
screen shot 2015-01-27 at 17 56 31

Before saving (or previously) the user should be warned if there are related visualizations that will not work as expected if the access is revoked, see #1962 for proposed solution

### PR DESCRIPTION
**Pull request by viddo**
Fixes #1963 

Basically, get related visualizations and compare their owners against the users list and show affected state accordingly:

affected

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1313/))

**Comment by viddo** [comment]
@xavijam review plz

**Comment by xavijam** [comment]
:dancer:

**Comment by xavijam** [comment]
&& :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1315/))

**Pull request merged**
