### PR TITLE
Adds merge analysis

### LINKED ISSUE #8279: Implement merge analysis form

### LINKED ISSUE #8478: Remove "FILTER" kind of tag from the filter card on the Add Analysis modal
screen shot 2016-07-04 at 21 20 23

### PR DESCRIPTION
**Pull request by javierarce**
animation

Closes #8279 
Closes #8478

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam || @javisantana

**Comment by xavijam** [comment]
Merge without fear, better to test it in production :)

**Comment by xavijam** [comment]
:es

**Comment by saleiva** [comment]
DALE AL MERGE!

**Comment by javierarce** [comment]
Merging the merge

**Pull request merged**
