### PR TITLE
Cdb 1685 multiuser quota is not well calculated in multiuser dashboard

### PR DESCRIPTION
**Pull request by Xatpy**
Ref ticket [#1685](https://github.com/CartoDB/cartodb/issues/1685)  : **multiuser quota is not well calculated in multiuser dashboard**

the percent has been multiplied by 100.

Example preview:
screen shot 2015-03-11 at 14 24 26

FYI: @viddo @xavijam  . Also, I checked that this bug is only happening with *old* organizations dashboard, so it's ok in the new 👌.
screen shot 2015-03-11 at 14 26 58

### CODE REVIEW

**Comment by xavijam** [comment]
xatpy, in the new dashboard image, 130% appears ... just saying.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2228/))

**Comment by Xatpy** [comment]
@xavijam do you mean that appears 130% (in the new) instead of 129.96% (in the old)? 
So, I don't know the designs about it (I mean the number of percentage that should be displayed), so I just do it like it was.

**Comment by xavijam** [comment]
All clear ;)

**Comment by Xatpy** [comment]
Please, @javisantana , could you check it?

**Comment by javisantana** [comment]
:es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2235/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2240/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2241/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2242/))

**Pull request merged**
