### PR TITLE
Codemirror autocomplete

### PR DESCRIPTION
**Pull request by nobuti**
This PR adds autocomplete to the sql editor in the builder.

autocomplete

TODO:
- [x] Add some tests to the builder part.
- [x] Apply changes to the dataset view.
- [x] Adjust the keywords with more accurate list of sql keywords and postgis functions.
- [x] Add autocomplete to the rest of editors with the proper keywords.

CR @xavijam

### CODE REVIEW

**Comment by piensaenpixel** [comment]
image

image


@nobuti all yours :)

**Comment by xavijam** [comment]
You are making me cry :_), cc @CartoDB/solutions

**Comment by makella** [comment]
@nobuti here are some common CartoCSS properties by geometry/feature type. 

We do have a full list of everything that is supported [here](https://carto.com/docs/carto-engine/cartocss/properties/) but I pulled out the ones that I think people will use most. Let me know if you have any questions.

I didn't include raster styling properties... should I?

### Map
`buffer-size:`

### Points
```
marker-fill:
marker-width:
marker-fill-opacity:
marker-opacity:
marker-line-color:
marker-line-width:
marker-line-opacity:
marker-comp-op:
marker-allow-overlap:
marker-file:
marker-type:
marker-height:
marker-width:
marker-transform:
marker-placement:
marker-ignore-placement:
marker-spacing:
marker-avoid-edges:
point-file:
point-opacity:
point-comp-op:
point-allow-overlap:
point-placement:
point-ignore-placement:
point-transform:
```
### Lines
```
line-color:
line-width:
line-opacity:
line-comp-op:
line-pattern-file:
line-join:
line-cap:
line-dasharray:
line-dash-offset:
line-offset:
line-simplify:
line-simplify-algorithm:
line-smooth:
line-clip:
```
### Polygons
```
polygon-fill:
polygon-opacity:
polygon-comp-op:
polygon-pattern-file:
polygon-pattern-alignment:
polygon-pattern-opacity:
polygon-smooth:
polygon-simplify:
polygon-simplify-algorithm:
polygon-gamma:
polygon-gamma-method:
polygon-geometry-transform:
polygon-clip:
```
### Building
```
building-fill:
building-fill-opacity:
building-height:
```
### Text
```
text-name:
text-face-name:
text-size:
text-fill:
text-opacity:
text-comp-op:
text-halo-radius:
text-halo-fill:
text-halo-rasterizer:
text-allow-overlap:
text-transform:
text-placement:
text-placement-type:
text-dx:
text-dy:
text-wrap-width:
text-wrap-before:
text-character-spacing:
text-line-spacing:
text-min-distance:
text-avoid-edges:
text-orientation:
text-vertical-alignment:
```
### Shield
```
shield-name:
shield-face-name:
shield-size:
shield-file:
shield-fill:
shield-opacity:
shield-text-opacity:
shield-allow-overlap:
shield-placements:
shield-placement-type:
shield-dy:
shield-dx:
shield-text-dx:
shield-text-dy:
shield-min-distance:
shield-avoid-edges:
```


### Other
```
image-filter:
comp-op:
opacity:
```

**Comment by nobuti** [comment]
Applied to cartocss and dataset editors as well. Ready for another pass.

**Comment by piensaenpixel** [comment]
\o/

**Comment by AbelVM** [comment]
:clap:

**Comment by nobuti** [comment]
🚀

**Comment by jsanz** [comment]
\o/

--
Jorge Sanz
CARTO - Predict through location

**Comment by makella** [comment]
@nobuti I made a mistake here!

I accidentally wrote `image-filter` and it should be `image-filters`!

sorry

**Pull request merged**
