### PR TITLE
Update the groupLayer definition when the query_wrapper of any layer changes too

### LINKED ISSUE #2673: Changing the method of a Density visualization doesn't refresh the visualization
uaa___cartodb

**Steps to reproduce:**

1. Create a simple table and add one or more points to it.
2. In the Map View, select "Density" in the visualization wizard.
3. By default, "Hexagons" will be selected as the Method and you should see an hexagon where you used to see a Marker.
4. Change the method to "Rectangles".

**Current behavior:**

1. Map is not refreshed, and hexagons are not "replaced" by rectangles.
2. If you change the value of any other field (e.g: color), the map will be refreshed and you will see rectangles.

**Expected behavior:**

1. When Method changes, the map is refreshed and you can see rectangles instead of hexagons. This is the behavior for other fields (e.g: color, polygon stroke, etc.)

There are no JS errors in the console.

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #2673 (and hopefully doesn't break anything else) :grinning:

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
@javisantana. Can you please CR? Thx!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2238/))

**Comment by javisantana** [comment]
sounds good :es:

**Comment by javisantana** [comment]
don't forget to:

- update NEWS
- bump frontend versin

ask help to someone to do that

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2257/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2258/))

**Pull request merged**
