### PR TITLE
Fixing async js test

### PR DESCRIPTION
**Pull request by xavijam**
cc @viddo

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4402/))

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4404/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4406/))

**Comment by viddo** [comment]
@xavijam this seems to do the trick :+1:

**Comment by xavijam** [comment]
merging?

**Comment by viddo** [comment]
:racehorse:

**Pull request merged**
