### PR TITLE
Broader session logout fixes #4860

### LINKED ISSUE #4860: Destroy all sessions on logout

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #4860 . @Kartones , CR this, please.

### CODE REVIEW

**Comment by Kartones** [comment]
:+1:

**Comment by juanignaciosl** [comment]
@matallo CR this as well, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5554/))

**Comment by matallo** [comment]
:+1:

**Pull request merged**
