### PR TITLE
2695 provide original file name in the import api

### LINKED ISSUE #2695: Provide original file name (if it exists), in the import API
If the import api could provide that, we would avoid the problem below.

screen shot 2015-03-10 at 15 52 53

cc @javisantana  @saleiva

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #2695. @Kartones CR this, please.

@xavijam: if this gets @Kartones :es: , import api will display a new `display_name` field. Example:
```
{"id":"16135ab1-33cc-48bc-b733-77f4141ff2fc","user_id":"c043713d-1655-4b9d-b909-f0193021150e","table_id":"df15b092-081d-403c-83c4-5b173b4482c5","data_type":"url","table_name":"county_usa","state":"complete","error_code":null,"queue_id":"16135ab1-33cc-48bc-b733-77f4141ff2fc","tables_created_count":1,"synchronization_id":null,"type_guessing":true,"quoted_fields_guessing":true,"content_guessing":true,"create_visualization":true,"visualization_id":"a3696fe0-2b9a-11e5-a295-04014675d001","user_defined_limits":"{\"twitter_credits_limit\":0}","get_error_text":null,"display_name":"county_usa.zip","success":true,"any_table_raster":false,"derived_visualization_id":"a3696fe0-2b9a-11e5-a295-04014675d001"}
```

I've tried to always return something. If I can't parse a filename I will return the id. But prepare frontend to display the id if `display_name`is empty or nil, please.

### CODE REVIEW

**Comment by Kartones** [comment]
Like it! :+1:

**Comment by xavijam** [comment]
Marvelous. Pass me the ticket when you finish it please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5032/))

**Comment by saleiva** [comment]
LOVE IT

**Comment by juanignaciosl** [comment]
@xavijam all yours! :dancer:

**Comment by xavijam** [comment]
Please, merge it into master and I'll take care of the frontend part in other ticket. :dancer:

**Pull request merged**
