### PR TITLE
3943 reduce redis commands

### LINKED ISSUE #3943: Can we reduce redis commands [from the editor]?
In development environment with SQL API, Maps API and Rails app running (resque was stopped) I started `redis-cli monitor` and tracked the number of commands.

I got:
```
cut -d ' ' -f 4 | sort | uniq -c | sort -nr
780 "ZSCORE"
  26 "get"
  10 "del"
   6 "select"
   6 "info"
   4 "unwatch"
   4 "hmget"
   4 "hget"
   2 "HMSET"
   1 "hset"
```

ZSCORE commands are requesting things like `"ZSCORE" "user:development:mapviews_es:stat_tag:3d5ce24a-c907-11e4-b2fc-6476ba93d4f6" "20150507"`. Do we need that somewhere in the editor for the map?

### PR DESCRIPTION
**Pull request by juanignaciosl**
This PR closes #3943 by reducing Redis usage in three ways:
- Public map visualization adapter don’t request visualization stats (daily map views).
- Public map page don’t request user stats (api calls).
- ApiCalls now uses one ZSCAN per month instead of 30 ZRANGE for mapviews. The "per month" is because Redis gem doesn't support multiple MATCH arguments, I'll try to push a PR that accepts an array of matches, but it's not important for the moment.

Some data on the impact on my development environment (only two maps):

Dashboard: ~190 requests to ~18. Mostly because of replacing 180 zscore with 12 zscan.
Editor map view: ~690 to ~90. Mostly because of replacing 600 zscore with 32 zscan. Probably still too many.
Public dashboard: ~120 to ~10. Same.

@rochoa , @rafatower  could you CR this, please?

I still have to test this in staging, any hint on the impact of this, other that dashboard mapview charts?

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4711/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4712/))

**Comment by rafatower** [comment]
:+1: you'll probably have to speak with clinker about the version of redis-server package...

**Comment by juanignaciosl** [comment]
Yep, in progress (that's why tests are failing).

**Comment by rochoa** [comment]
LGTM :+1:

**Comment by juanignaciosl** [comment]
Ok, I'll deploy when Clinker passes tests.

**Comment by javisantana** [comment]
do we know why opening a visualization launch more commands than the dashboard?

**Comment by juanignaciosl** [comment]
Yes, although dashboard requests mapviews from many visualizations, editor requests other information, especially geometry types and user database information. We can continue improving this later if needed, because many requests are duplicated some might be cached.

**Comment by javisantana** [comment]
got it, those are not only stats related. Yep, will improve that

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4824/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4825/))

**Pull request merged**
