### PR TITLE
Fixes torque related errors

### PR DESCRIPTION
**Pull request by javierarce**
This PR fixes a couple of things:

- `Uncaught TypeError: Cannot read property 'last' of undefined`.
- Accessing a method that doesn't exist: `applyWizard`

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3251/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3253/))

**Comment by javierarce** [comment]
@xavijam or @javisantana: can you review this, please? I'm assuming that replacing `this.options.layer.collection` with `this.options.map.layers` is ok, but I'm unsure.

**Comment by javisantana** [comment]
@javierarce yes, it's the same 

:es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3283/))

**Pull request merged**
