### PR TITLE
Removes fake clone this button

### PR DESCRIPTION
**Pull request by javierarce**
Removes the clone this button from the blue header that is not doing anything at this moment:

1. If the user is not logged in, the button redirects her to the login page and then nothing will happen.
2. If the user is logged in, we replace the option with a dropdown.

screen shot 2015-03-03 at 11 01 29
screen shot 2015-03-03 at 11 01 00

#2 and [this condition](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/public/views/public_header.jst.ejs#L8) tells me that we removed that option on purpose… is that so?

In that case, I'll remove that [this code](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/public/public_header.js#L62) 

@CartoDB/frontend / @xavijam: can you review it, please?

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2025/))

**Comment by viddo** [comment]
Code wise it looks legit, but not familiar with the "clone" functionality to really say anything about that.

**Comment by xavijam** [comment]
No more clone game, ok :+1:.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2076/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2077/))

**Comment by iriberri** [comment]
Oh :( I want this feature

**Pull request merged**
