### PR TITLE
Browserify editor3

### PR DESCRIPTION
**Pull request by rochoa**
Deprecates factor-bundle, uses browserify's external/require internals to use several bundles.

Contrary to previous solution it works with linked modules.

cc @alonsogarciapablo @viddo @xavijam

### CODE REVIEW

**Comment by viddo** [comment]
Does this have the same output (bundles/results) as factor-bundle yielded?

> Contrary to previous solution it works with linked modules.

(For future reference) what does _"works with linked modules"_ really mean?

What goes for the changes look legit so 👍

**Comment by alonsogarciapablo** [comment]
I'm giving this a try, but it looks 👍

**Comment by rochoa** [comment]
@viddo If you were doing:

```
npm link cartodb.js
npm link cartodb-deep-insights.js
```

It was not generating the same bundles, missing some dependencies in common bundle, as when you were just `npm install`ing them.

Some refs:
 - https://github.com/substack/factor-bundle/issues/66
 - https://github.com/nodejs/node/issues/3402

**Comment by alonsogarciapablo** [comment]
Working 👍

**Pull request merged**
