### PR TITLE
Save collapse state in layer definition model.

### PR DESCRIPTION
**Pull request by nobuti**
This PR implements #11927.

### CODE REVIEW

**Comment by nobuti** [comment]
The test for the collapse functionality was already there. What additional
test do you suggest?

**Comment by matallo** [comment]
following @ivanmalagon approach I'd add a new spec for every new method, in this case `toggleCollapse` even if we need to rewrite/rearrange the existing specs to match

happy to discuss and approve, though, I don't have a very strong opinion on this specially if we had this already covered, maybe is just a matter of styleguide

**Comment by nobuti** [comment]
💋

**Comment by javierarce** [comment]
Accepted: 💚

**Comment by matallo** [comment]
merged, bumping assets in `master` for deploy

**Comment by matallo** [comment]
aaand deployed 🚀

**Pull request merged**
