### PR TITLE
Update googlemaps api version to v3.32

### PR DESCRIPTION
**Pull request by VictorVelarde**
## Related to https://github.com/CartoDB/cartodb/issues/13902

A simple update of the gmaps version, from current 3.30 to 3.32 (which has been already used in carto.js)

## Acceptance
*gmaps* user at staging

- Create a map
- Use GMaps as the basemap
- Check the version being used with dev tools.
- **Expected**: there should be a tag with `<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.32"></script>`

Important: as the user doesn't have a valid gmaps api key, the gmaps will NOT BE RENDERED (and there will be javacript errors regarding to invalid key), but the script tag will be there. So this is a little "leap of faith"

### CODE REVIEW

**Comment by VictorVelarde** [comment]
retest this please

**Comment by VictorVelarde** [comment]
Hi @ramiroaznar This is ready for acceptance. See STA 🔝

**Comment by ramiroaznar** [comment]
image

LGTM, right?

**Comment by VictorVelarde** [comment]
Yes, that's the expected error because of a "made-up" api-key

**Pull request merged**
