### PR TITLE
Add more info to the sync errors

### PR DESCRIPTION
**Pull request by ethervoid**
We need more info to trace some synchronizations problems.

Please @juanignaciosl check this out

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Since it's a debug trace for a method having all the parameters is often useful, I'd also have logged `result`, but that's not a big deal :+1:

**Comment by rafatower** [comment]
I'd add the sync id there

**Comment by rafatower** [comment]
never mind: as soon as it passes the tests go ahead.

**Comment by ethervoid** [comment]
Retest this please

**Comment by rafatower** [comment]
retest this, please

**Pull request merged**
