### PR TITLE
Export gpkg files on builder

### PR DESCRIPTION
**Pull request by rjimenezda**
Fix CartoDB/support#1220

This PR allows users to download GPKG files on CARTO. On Builder, the private dataset view and the public dataset view.

For the import: https://github.com/CartoDB/cartodb/pull/14153

### CODE REVIEW

**Comment by rjimenezda** [comment]
@ramiroaznar staging user: exportum-patronus

**Comment by rjimenezda** [comment]
To accept this: Create a dataset with geometry, create a map with it. Make the dataset public.

Try to export GPKG from:
- Private dataset view
- Public dataset view (open same url as the private one without a session)
- Builder

GPKG should be an option in all cases.

**Comment by ramiroaznar** [comment]
image
:boom: 
image
:boom:

**Comment by ramiroaznar** [comment]
LGTM!

**Pull request merged**
