### PR TITLE
Update Sequel-Rails

### PR DESCRIPTION
**Pull request by javitonino**
#12136

Update the adapter from Sequel to Rails. 😱 It's "just" a gem update, and a million search+replace changes. Comprehensive list:
- `Gemfile` and `Gemfile.lock` [Gem changelog](https://github.com/TalentBox/sequel-rails/blob/master/History.md). This is a massive update, but their changelog is nice. Some highlights:
  - Rename `Rails::Sequel` module as `SequelRails` (0.4.0)
  - Ensure we've dropped any opened connection before trying to drop database (0.4.0). We do this manually, maybe we can skip it. But not in this PR.
  - 0.9.15 will be the last version to support Rails 3 (which is important to us) and ruby < 2.2 (which we don't care about)
- [Disabled the railtie loading](https://github.com/CartoDB/cartodb/pull/12118/files#diff-b1fe55db50c712fef0673345e5b9c0d9R6)
- [Monkey patch the gem](https://github.com/CartoDB/cartodb/pull/12118/files#diff-f066c8f7ae36e28fabc717f9259df4e9R5) to make it compatible with Vizzuality's fork
- [Load default configuration](https://github.com/CartoDB/cartodb/pull/12118/files#diff-d66d1793183b750b07272d4ca99755a9R2). See the bottom of [this section of the docs](https://github.com/TalentBox/sequel-rails#using-sequel-rails)

**Acceptance**
- [x] Migrate the database from scratch (`make prepare-test-db`)
- [x] Test database operations, specially user db, including
  - [x] User management
  - [x] Group management
  - [x] Permission management
  - [x] Dataset management
  - [x] Editing data inside a dataset

### CODE REVIEW

**Comment by juanignaciosl** [comment]
[Deploying this fails: `#22840 Sequel::Error: Extension schema_dumper does not have specific support handling individual databases
Sequel::Error: Extension schema_dumper does not have specific support handling individual databases`](https://rollbar.com/vizzuality/CartoDB/items/22840/occurrences/24971202373/).

**Comment by javitonino** [comment]
Ha, CI didn't catch this because this only happens when a migration results in an action. It does not trigger if the DB is up to date. Good catch!

**Comment by javitonino** [comment]
Fun times diving into Sequel internals. Here's the story.
- We are on Sequel 3.42
- Sequel 3.47 changed the Sequel plugins API, so a DB object is passed to the plugin in initialization (to determine if it is compatible with that DB driver). Sequel 3.48 (last 3.xx) deprecates the old one. Sequel 4.0 removes it altogether.
- Sequel-Rails 0.4.4 moves from the old plugin API to the new one. This is not very well reflected in the Gemfile requirements.
- We need Sequel-Rails 0.9.0 at a minimum for Rails 4 support

So, two options here:
- Update Sequel to 3.47. We cannot directly go to Sequel 4 due to some deprecated stuff. We could use 3.48 but we get lots of ugly deprecation warnings. [Changelog](https://github.com/jeremyevans/sequel/blob/master/CHANGELOG#L1951) (looong)
- Remove the `schema_dumper` extension (AFAIK, we don't really use it). Hope no other extension breaks (it doesn't seem like it, but...).

I'm pushing a change with Sequel 3.47 to see what CI says.

**Comment by javitonino** [comment]
And of course, Sequel 3.46.0 changes slightly the behaviour of association caching, and we are expert on using edge cases for that :(

@juanignaciosl What are your thoughts on disabled DB schema dumping? AFAIK, we are not using it for anything, it is not used for db creation, and not even committed to the repo. I checked in `sequel-rails` code and this is the only extension being used, so just disabling this one should be enough.

**Comment by juanignaciosl** [comment]
Schema dumping is usually only used for test purposes, and AFAIK we don't use it at all, as you said. I'd disable it and check.

**Comment by javitonino** [comment]
Ok, this runs migration correctly now, let's test it!

**Comment by juanignaciosl** [comment]
No issue detected in acceptance 🎉

**Pull request merged**
