### PR TITLE
Numeric inputs improvements

### LINKED ISSUE #7500: [STYLE] Numeric inputs ranges improvements
- FILL: Should be min: 1px, max: 40px, step: 0.5px 
- STROKE: Should be min: 0px, max: 10px, step: 0.5px
- FONT-SIZE: Should be min: 6px, max: 24px, step: 1px
- FONT OFFSET: Should be min: -15px, max: 15px, step: 1px
- TORQUE DURATION: min: 0, max: 60, step: 1
- STEPS: min: 1, max: 1024, step: 4
- RESOLUTION: min: 1, max: 16, step: 1
- TRAILS: min: 0, max: 10, step: 1

### PR DESCRIPTION
**Pull request by MariaCheca**
Closes #7500 

Note that `animated-steps` component `min` value has been changed to 0 instead of 1, as the 4 by 4 steps would result in 1025 as the max number, which would be one number ahead the `max` value assigned (1024).

CR @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
Have you changed lib/sql submodule? ;)

**Comment by xavijam** [comment]
@javierarce, could you check changes over fill component?

**Comment by MariaCheca** [comment]
I just reverted the changes in lib/sql :)

**Comment by javierarce** [comment]
@xavijam: sure, I'll have a look

**Comment by javierarce** [comment]
👍

**Comment by xavijam** [comment]
You forgot to bump package version, but in any case, merging!.

**Comment by MariaCheca** [comment]
✨

**Pull request merged**
