### PR TITLE
2867 liked datasets count is incorrect

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones could you CR this fix for #2867, please?

@xavijam if you want to test and merge this in a branch you're currently working at, like you did with previous fixes, please let me know. Otherwise I'll merge it into master.

### CODE REVIEW

**Comment by xavijam** [comment]
Go to master when it is done please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2509/))

**Comment by Kartones** [comment]
:+1:  So the listing was missing shared ones, right?

**Comment by juanignaciosl** [comment]
Yep. Count was right (although, "link" permission was also missing), but listing was missing shared ones, that's why @saleiva saw less visualizations than the counted ones (it was missing private shared with him).

I still have to make test pass, stay tuned.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2519/))

**Pull request merged**
