### PR TITLE
Fix visuals in privacy share permissions view

### LINKED ISSUE #2363: Fixes on Share with your colleagues modal
There is an horizontal scrollbar that is not being used.
The grey button shouldn't have white bkg.
"Share with your XX colleages" should be something like "Select your colleagues you want to give access in the list below"

screen shot 2015-02-19 at 17 01 55

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2363 

- Moved back button to header
- Removed subheader
- Updated affected views due to class name changes

privacy-visual-changes

### CODE REVIEW

**Comment by viddo** [comment]
@saleiva @xavijam review, please

**Comment by viddo** [comment]
by request, @javierarce can you review this too?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1906/))

**Comment by saleiva** [comment]
:+1:

**Comment by javierarce** [comment]
:eyes: Looks fine to me :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1909/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1914/))

**Pull request merged**
