### PR TITLE
Updated submodule cartodb.js.

### PR DESCRIPTION
**Pull request by nobuti**
This PR update cartodb.js submodule, in order to hotfix #8674.

cc @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
We used to commit the generated `cartodb.uncompressed.js` file, don't we need it anymore?

**Comment by nobuti** [comment]
flag?

**Comment by xavijam** [comment]
-> :es:

**Comment by nobuti** [comment]
:cartojal:

**Pull request merged**
