### PR TITLE
Fix CSV import errors for empty files

### PR DESCRIPTION
**Pull request by jgoizueta**
This addresses #960

cc @rafatower @iriberri do you think this would be the right spec?

### CODE REVIEW

**Comment by iriberri** [comment]
Check `all_empty_lines.csv`, it's just a single empty line at the moment.

**Comment by jgoizueta** [comment]
@iriberri has noticed we have an specific 'Malformed CSV' error message (2003).
So we can use it instead of 1002 (Unsupported/Unrecognized file type)

**Comment by jgoizueta** [comment]
The problem with having malformed CSVs to fail (currently malformed lines are ignored, then the import fails only for an empty result, i.e. all lines are malformed or empty) is that some users may prefer a file with an odd malformed line to import.

The alternative, discussed in #6178 would be to import them as now, ignoring malformed lines and then show the user a message about 'some malformed lines were ignored'.

It would be simpler for us to just return the malformed CSV error.

**Comment by iriberri** [comment]
> The alternative, discussed in #6178 would be to import them as now, ignoring malformed lines and then show the user a message about 'some malformed lines were ignored'.

I guess that the problem here is that at the end you would need to show those lines to the user (or the line number of the first incidence, at least), or the warning could become annoying for the user. Not sure what your thoughts are, but just to contribute a bit. :-)

On the other hand I also think that if something is malformed we should just raise an error for it. Perhaps a combination of "import error" + "malformed entry at line 92" would be nice, but afaik we don't have any "customized" error input at the moment so this would be a new thing.

**Comment by jgoizueta** [comment]
I also think we should raise an error, with or without the additional information about affected lines.

But I've also remembered why it's not easy to fix this: we may or may not normalize not normalize the csv before sending it to ogr2ogr based on the detected encoding and separator. If the file goes through the CSV normalizer it's easy to detect the 
(non-blank) malformed lines, but otherwise...

**Comment by rafatower** [comment]
I'm confused: I just see changes in test files.

For the sake of the discussion: this is trying to deal with malformed CSV files, defined as "CSV file with empty lines". To avoid confusion with some malformed line geometry. Am I right?

I think it's better not to mix end of line delimiters with empty lines. One of the delimiters is not supported by `ogr2ogr` so something to be documented as part of the CSV requirements cc/ @iriberri:

http://www.gdal.org/drv_csv.html
> At least two fields per line must be present. Lines may be terminated by a DOS (CR/LF) or Unix (LF) style line terminators

**Comment by jgoizueta** [comment]
@rafatower: yes, I've committed only tests so far, expecting to define the spec before implementing it.

And we're trying to discern the malformed CSV cases (no relation to line geometries) from the empty file case which are now treated identically. And invalid end of lines are  a case of malformed CSV (as treated but the CSV Ruby lib, at least).

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by rafatower** [comment]
closing it, to be reopened some day?

**Pull request closed without merging**
