### PR TITLE
2603 fix caching geometry types

### PR DESCRIPTION
**Pull request by rafatower**
This fix makes the geometry types caching work as it should

There's a difference with respect to the original fix, in case of miss it queries the db and sets the redis key timeout to:
- 5 minutes if there are not geometries
- 24h if there are geometries

@javisantana I count on Table#geometry_types not being used for the editor
@Kartones  and @juanignaciosl please review

### CODE REVIEW

**Comment by rafatower** [comment]
retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2966/))

**Comment by Kartones** [comment]
:+1: I'd just move the cache times to constants so is faster to just enter and change them, but is a matter of personal taste, no scientific law :smile:

**Comment by javisantana** [comment]
@rafatower you can be sure it's not used in the frontend

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2970/))

**Pull request merged**
