### PR TITLE
Change Mailchimp import to use campaigns

### LINKED ISSUE #2849: Change Mailchimp import to use campaigns
[Branch](https://github.com/CartoDB/cartodb/tree/issue-2849)

### 1st round
- [x] Show users who have opened a campaign
- [x] anonimize data returned (emails)
- [x] Replace old code that used lists

### 2nd round
- [x] Remove campaigns who have tracking disabled
- [x] Change flow to:
  - retrieve campaign list
  - retrieve then subscriber activity
  - set `opened` field of campaign data with subscriber activity data
  - anonymize emails and other personal data (except ip)

### 3rd round
- [x] Try to apply some CartoCSS to color differently `opened=true` emails

cc @saleiva

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #2849

### CODE REVIEW

**Comment by Kartones** [comment]
@rafatower CR please

@matallo @saleiva All logic is here. I'm only pending checking if is easy to add automatically the cartocss to differentiate the opened items.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2470/))

**Comment by rafatower** [comment]
Ok by me, from my ignorance about the mailchimp api client

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2477/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2480/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2482/))

**Comment by saleiva** [comment]
Hey @Kartones why the sync options are always deactivated?

**Comment by saleiva** [comment]
Hey @Kartones take a look at the code. I couldn't try it on local, but the styling should be better now.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2486/))

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2489/))

**Pull request merged**
