### PR TITLE
Update install.rst

### PR DESCRIPTION
**Pull request by JohnQUnknown**
Added an instruction to create the database prior to migration since this failed otherwise.

### CODE REVIEW

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by javitonino** [comment]
This replaces: https://github.com/CartoDB/cartodb/pull/7506
cc @juanignaciosl

**Comment by javitonino** [comment]
Merging, thanks @JohnQUnknown for the patch!

**Pull request merged**
