### PR TITLE
Stopping click event within filters view

### LINKED ISSUE #3646: Clicking on the white bar (filters), shouldn't unselect the selected items from the maps/datasets lists
Sometimes you fail clicking on an option and then you have to select again everything you had.

### PR DESCRIPTION
**Pull request by xavijam**
filters-view-click

REVIEW: @viddo
cc @saleiva 
Fixes #3646

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3978/))

**Comment by viddo** [comment]
OK!

Btw, as seen in screen shot 2015-05-29 at 09 48 32, why not make the links expand the full height of the sub-header container to give more surface area to click? I feel that some of this "miss clicks" might be due to that too.

**Comment by xavijam** [comment]
agree vikingo! :). Take a look at my last commit.

**Comment by xavijam** [comment]
restest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3985/))

**Comment by viddo** [comment]
:+1:

**Pull request merged**
