### PR TITLE
Refactor and add warnings for connectors max number of rows

### PR DESCRIPTION
**Pull request by ethervoid**

### CODE REVIEW

**Comment by ethervoid** [comment]
Tested and working.

Screenshot of the warning message to be reviewed by @brittanymicek or @csobier :)

captura de pantalla 2016-09-29 13 53 34

**Comment by csobier** [comment]
Suggested edit:
"Maximum limit reached
You have reached the maximum limit of 90000 rows. Some of your data may not be imported from the database connector."

**Comment by brittanymicek** [comment]
+1 to @csobier with just one additional edit:
Maximum limit reached
You have reached the maximum limit of 90,000 rows. Some of your data may not be imported from the database connector.

**Comment by ethervoid** [comment]
I want to make a point about the intentionality of the message. When we reach this point we're pretty sure that the user has reached the limit of rows but we don't know for sure, hence the `possibly` part of the message

**Comment by csobier** [comment]
Hmm, okay, how about:
"You may have reached the maximum limit
For a database connector import, the number of rows allowed is 90,000. Some of your data may not be imported."

**Comment by ethervoid** [comment]
Looks good for me, changing!

**Pull request merged**
