### PR TITLE
Improve password expiration flow

### PR DESCRIPTION
**Pull request by gonzaloriestra**
Closes https://github.com/CartoDB/cartodb/issues/14502

### CODE REVIEW

**Comment by alrocar** [comment]
Acceptance 🔴 

I've found a couple of issues.

I deployed on a staging server and set in `app_config.yml`:

```
session_domain:      'DOMAIN_OF_STAGING_SERVER'
subdomainless_urls:  true
...
cartodb_com_hosted: true
```

and commented the `cartodb_central_api` section.

- I created an organization with password expiration in org settings set to 1 day. 
- I log in as org admin.
- From the Rails console, I set the `last_password_change_date` for the org admin to a couple of days. to simulate the password expiration scenario.
- I click on `Avatar > Your account` link
- I am redirected to the login screen, but no error is shown (it should show the `your session has expired... blabla` error)
screen shot 2019-01-07 at 13 28 39

- I login and I'm redirected to the password change screen.
- I change the password and I'm redirected to the `/me` JSON response:

screen shot 2019-01-07 at 13 29 04

Other redirections (not AJAX requests) seem to work properly.

Second issue (may be unrelated to this one) is about password change. It does not seem to work properly. I change the password, but next time I force the password to expire, I have to login with the previous password I had, so I suspect it's not being updated? 

I may have been doing something wrong, so please could you double check this is actually happening?

**Comment by gonzaloriestra** [comment]
@alrocar the problem is that we cannot use subdomainless in staging, as @javitonino pointed out. That should be tested locally or with an onpremises virtual machine.

Regarding the password not changing, I couldn't reproduce it, could you check it again?

**Comment by javitonino** [comment]
Well, it's not impossible, but it's a mess of configuration changes (more than only Rails) :D

**Comment by alrocar** [comment]
oh I see, then I'm testing locally. Thanks

**Comment by alrocar** [comment]
Tested locally and acceptance 🍏

**Pull request merged**
