### PR TITLE
Fetch org users from dataset view.

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes https://github.com/CartoDB/cartodb-management/issues/4560

cc @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
Why not fetch them when there are required?
I've just checked that in the builder page, we are requesting those users at the beginning and I feel it is a unnecessary request at that point, only used in the share dialog.

**Comment by nobuti** [comment]
Not exactly, we are showing how many people the visualisation is shared with in the header.

**Comment by xavijam** [comment]
Hum... ok. We could provide the total number or organization users there are in an object, exposed in the html, what do you thing @javitonino @gfiorav ?

**Comment by javitonino** [comment]
Should be easy to add, we can provide a list with all the users and groups in the org in every request. Or we can include only the objects the visualization is shared with, and load the full list in the share dialog (we can do paging then for visualizations with lots of users).

**Comment by xavijam** [comment]
I feel we only need the number of users, with that we will avoid that first request, right @nobuti?

**Comment by xavijam** [comment]
In any case, let's merge this one and open a new ticket about the other thing.

**Comment by nobuti** [comment]
@xavijam yep, only `total_user_entries` excluding the current user by default.

**Pull request merged**
