### PR TITLE
Add dependent visualizations to visualizations method in GET

### PR DESCRIPTION
**Pull request by jesusbotella**
This PR adds dependent visualizations properties (`dependent_visualizations` and `dependent visualizations_count`) to datasets returned when requesting data via GET method.

This comes from a carto-python PR that adds a check when removing datasets with dependent_visualizations (https://github.com/CartoDB/carto-python/pull/107).

### CODE REVIEW

**Comment by gonzaloriestra** [comment]
:heavy_check_mark: Acceptance OK

**Comment by alrocar** [comment]
retest this please

**Comment by alrocar** [comment]
retest this please

**Comment by alrocar** [comment]
Just one known issue in one test. Deploying 🚀

**Pull request merged**
