### PR TITLE
Layer updates don't get reflected on named maps

### LINKED ISSUE #4167: Layer updates don't get reflected on named maps

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #4167

### CODE REVIEW

**Comment by Kartones** [comment]
@javisantana CR please. My bad here, but far away when I built the named maps code, as it was incorrectly relying on vis cache invalidation for performing appropiate named map updates (instead of as now calling a descriptive method that explicitly updates the NM).

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4506/))

**Comment by Kartones** [comment]
Switching to @rafatower as CR'er

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
