### PR TITLE
Disable analysis steps

### PR DESCRIPTION
**Pull request by rjimenezda**
Related issue #13311 

This PR does two things:

- It makes it so some analysis steps get greyed out while some data needs to be input on previous ones
- It merges some steps together where it makes sense (area of influence, clusters, outliers)

Acceptance:

- [ ] Check merged analyses
- [ ] Check disabled steps work on several analysis (join column, aggregate intersection, find nearest)

### CODE REVIEW

**Comment by rjimenezda** [comment]
@CartoDB/design deployed on ded13

**Comment by rjimenezda** [comment]
Sorry, geocoding is missing this enhancement. Working on it. Though it might be problematic.

**Comment by arianaescobar** [comment]
We believe in you, Román 🙌🏼

**Comment by rjimenezda** [comment]
Other Analyses have an empty select initially, it's just how geocoding is designed, there has to be some specific geocoding selected for it to work 😞

**Comment by rjimenezda** [comment]
I added the same behavior to DO, which works in a similar way to Geocoding, but allows for an empty Select

**Comment by rjimenezda** [comment]
@matallo check the new approach, I like it better.

I've added a dummy field to the Georeference-placeholder analysis, it won't be checked against camshaft.

We also have to force a validation error on the georeference-placeholder model, so it can't be saved.

So now we have selected georeference-placeholder, which displays as an empty string. It doesn't show on the list, so you can't re-select it, and as soon as you select something else, the second step is disabled.

**Comment by rjimenezda** [comment]
@CartoDB/design deployed for acceptance on rui, roman-rui has data-observatory enabled so you can check that analysis as well.

Thanks!

**Comment by rjimenezda** [comment]
@urbanphes 

1 - I can try, I did it for a few others but didn't notice that one.

2, 3, 4 - All of that is happening on production already. I can try to fix, but particularly the show the errors on each change I thought was intended.

**Comment by arianaescobar** [comment]
@urbanphes Those last two things have already been reported on separate issues: 

- Required tooltips: https://github.com/CartoDB/cartodb/issues/11656
- Focus state: https://github.com/CartoDB/cartodb/issues/13403

**Comment by rjimenezda** [comment]
Let me evaluate how hard it is to not show the tooltips, so we can decide wether to tackle it on this PR or on another one

**Comment by rjimenezda** [comment]
filter

Looking into the tooltips

**Comment by rjimenezda** [comment]
Check it now @urbanphes 

I'm investigating the tooltips & it's not as simple as I expected I think

**Comment by rjimenezda** [comment]
@CartoDB/design please check it out, still on roman-rui.

**Comment by urbanphes** [comment]
Hey @rjimenezda the number 1 is solved (Filter by column value)

**Pull request merged**
