### PR TITLE
Update zindex

### PR DESCRIPTION
**Pull request by IagoLast**
https://github.com/CartoDB/cartodb/issues/13304
---

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
Thanks @IagoLast! I assigned @jesusbotella as the reviewer cause he's surely more aware of the possible implications of this change.

**Comment by alonsogarciapablo** [comment]
🚀

**Comment by IagoLast** [comment]
fixed in https://github.com/CartoDB/cartodb/commit/f841c76ea482849f0615e7ad0277e19900b848f0

**Comment by alonsogarciapablo** [comment]
Thanks @IagoLast and @jesusbotella! 👏 👏 👏

**Pull request merged**
