### PR TITLE
Updated the README

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes some issues that I encountered while setting up CartoDB locally.

@javisantana and I talked about moving the `Install Varnish` section to the `Optional installation` section, to simplify things, but I'm not sure if Varnish is required by other components (e.g: `Windshaft`).

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2162/))

**Comment by javisantana** [comment]
varnish is totally optional so let's move it

**Comment by alonsogarciapablo** [comment]
Moved!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2169/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2170/))

**Comment by javisantana** [comment]
:es:

this does not need deploy

**Pull request merged**
