### PR TITLE
New upselling flows...

### LINKED ISSUE #2630: Review all upselling flows
- ~~when raising an error on import because you don't have enough quota~~ => (#2630)
- [x] when being close to the limits
- [x] when trying to change the privacy of a table (privacy levels and collaboration)
- [x] when being exposed to a 'paid' feature (like sync tables)
- ~~when trying to connect data from a paid datasource (Twitter/ArcGIS/...)~~=> (#2910)

Anything more?

### PR DESCRIPTION
**Pull request by xavijam**
screen shot 2015-03-25 at 17 27 26

screen shot 2015-03-25 at 17 58 09

screen shot 2015-03-25 at 19 01 52

- [x] when being close to the limits in settings pages.
- [x] when trying to change the privacy of a table (privacy levels and collaboration)
- [x] when being exposed to a 'paid' feature (like sync tables)

Fixes #2630

cc @saleiva @viddo

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2550/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2553/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2555/))

**Comment by xavijam** [comment]
Ready to be reviewed, mainly changes in templates and styles for adding new upgrade block.
Also I had to merge [pull 2897](https://github.com/CartoDB/cartodb/pull/2897) because styles were there and it didn't make any sense to create a new one.

**Comment by saleiva** [comment]
:es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2557/))

**Pull request merged**
