### PR TITLE
New editor change lock modal

### PR DESCRIPTION
**Pull request by viddo**
lock

Implements the new change-lock modal for the editor.

There are more changes than there really are, since I moved the view and related files from `dashboard` to the `common` dir. 

Noteworthy changes:
- The model was changed to be an actual model instead of a collection to avoid duplicating manual state-change logic, this made it a little simpler
- The view has a default template for the "standard" texts and states (used on dashboard), but added the option to provide separate template, which I used for the use-case where an already locked item is opened in editor for which the modal is displayed directly indicating that the user must unlock it to continue (cancel and return to dashboard), since the template was diverging so much.

### CODE REVIEW

**Comment by viddo** [comment]
@javierarce please review :)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3618/))

**Comment by saleiva** [comment]
Making that text shorter would be killer @javierarce

**Comment by javierarce** [comment]
We could say something like:

> Locking this map will hide it from the dashboard. Reveal it using the header menu or the bottom link.

**Comment by saleiva** [comment]
Love that :)

**Comment by viddo** [comment]
Fixed in https://github.com/CartoDB/cartodb/commit/db5c184104057bde056e44cee500ecbc1aed8948 have a look there. Deploying on ded04 too if you want to have a "real" look

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3622/))

**Comment by javierarce** [comment]
:+1: Looks good to me!

**Pull request merged**
