### PR TITLE
Bump Webpack version

### PR DESCRIPTION
**Pull request by matallo**
Webpack 3.0.0 was officially released several days ago [1]. It improves speed significantly.

I've been working locally (and deploying to staging) with no further hassle rather than fixing `source-map-support` version to `0.4.3`.

[1] https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

### CODE REVIEW

**Comment by xavijam** [comment]
Nice @CartoDB/frontend !

**Comment by rjimenezda** [comment]
I can't find any problems on staging, it's on ded03 in case anyone wants to poke at it.

👍

**Comment by xavijam** [comment]
If you don't find any major problem, go ahead man!

**Comment by rjimenezda** [comment]
We can move it to deploy, but maybe not deploy it today?

**Comment by xavijam** [comment]
> We can move it to deploy, but maybe not deploy it today?

Yep, let's do it on Monday.

**Pull request merged**
