### PR TITLE
Unify scrollbars

### PR DESCRIPTION
**Pull request by Jesus89**
Related to: #12184 

## Changes
- Refactor scrollbars: carousel, custom-list, editor, modals
- Use wheel to scroll carousel and widgets (horizontal)
- Fix bottom shadow in "Add analysis" modal
- https://github.com/CartoDB/deep-insights.js/pull/600
- https://github.com/CartoDB/cartodb.js/pull/1784
- https://github.com/CartoDB/CartoAssets/pull/171

### Carousel
s-carousel-2

### Dropdown
s-dropdown

### Popup
s-popup-2

### Legends
s-legends

### List (layers, widgets)
s-list

### Modals (add widget, add analysis, select marker image)
s-add-widget
s-add-analysis
s-select-marker-image

### Widgets (horizontal)
s-widgets-h

### Widgets (vertical)
s-widgets-v

### CODE REVIEW

**Comment by josecruz** [comment]
They're looking awesome @Jesus89!!!

One last minute change. Can we also replicate the "growing" effect on hover for the Carousel scrollbars?

cc @piensaenpixel @urbanphes

**Comment by Jesus89** [comment]
Growing how? What about dark colors?

**Comment by Jesus89** [comment]
Deployed in ded10.

**Comment by josecruz** [comment]
Thanks @Jesus89!!

@urbanphes tested it and its looking perfect so :bandera:

Lovely job 💃 !

**Comment by xavijam** [comment]
So finally we are getting rid of the super nice popup scroll :( @piensaenpixel @josecruz.

**Comment by xavijam** [comment]
So, apart from nobody answered me last comment, I feel we missed the image popup. 
screen shot 2017-10-03 at 06 36 43

**Comment by piensaenpixel** [comment]
Sorry @xavijam, yes we needed to consolidate all the scrollbars :(

**Comment by Jesus89** [comment]
@xavijam I implemented the changes (I swear :stuck_out_tongue:) I have checked that in production all popups and legends are with the old style. Let me check it...

**Comment by Jesus89** [comment]
Oh nice. Production points to custom branches: https://github.com/CartoDB/cartodb/blob/master/package.json#L27-L29

**Comment by Jesus89** [comment]
Now cartodb.js and deep-insights.js point to the right branches in production: #12896 :grinning:

**Pull request merged**
