### PR TITLE
Using last cartoassets changes

### PR DESCRIPTION
**Pull request by xavijam**
Related ticket: https://github.com/CartoDB/cartodb/issues/8081.
But, in fact, it is a task from https://github.com/CartoDB/cartodb/milestone/139 milestone.

Basically making use of the new changes added in CartoAssets https://github.com/CartoDB/CartoAssets/pull/162.
But, before merging this, we need to merge those changes in CartoAssets, then in CARTO.js, after that in Deep-insights, and finally here. 💃 

cc @CartoDB/frontend

### CODE REVIEW

**Comment by xavijam** [comment]
No need to change NEWs, I feel.

**Comment by xavijam** [comment]
Deploying it in ded04 servers.

**Comment by xavijam** [comment]
Tested it in ded04 server and looks ok, from private builder to public embed, but could anyone ( @CartoDB/frontend ) take a look please? 💋

**Comment by nobuti** [comment]
It works smoothly, I couldn't find any flaws. Also, some savings in the final bundle:

- 5kb en editor3css y 2 kb en deep_insights.css, uncompressed.
- gzips remain in almost the same value, totally understandable.

But the main goal of this ticket was not the final weight, so kudos :)

**Comment by xavijam** [comment]
So... starting the party with CartoAssets ---> CARTO.js ---> Deep-Insights.js ---> Builder

**Comment by xavijam** [comment]
Again, deployed in ded04, just in case someone wants to check it (again). If nobody complains about it, we will deploy it tomorrow morning 💃 .

**Pull request merged**
