### PR TITLE
[ch120967] Include connections and synchronizations in user migrations

### PR DESCRIPTION
**Pull request by Shylpx**
### Resources

- [Clubhouse story](https://app.clubhouse.io/cartoteam/story/120967/include-connections-in-user-migrations)

### Context

- Information not being migrated:
  - DB connections.
  - All parameters for Oauth connections.
  - Relationship between synchronization and connections.

### Changes

- [x] Migrate information about DB connections
  - [x] Add tests
- [x] Add missing parameters to Oauth connections
  - [x] Add tests
- [x] Link synchronizations with connections
  - [x] Add tests

### CODE REVIEW

**Comment by thedae** [comment]
@Shylpx sorry for the delay, I didn't realize this PR was in my list :(

I want to review it, but please check the failing CI and make sure you're synchronized with master

**Review by thedae — APPROVED** [review]
:+1:

**Review by jgoizueta — APPROVED** [review]
LGTM

If I understand correctly, synchronizations are exported/imported via the canonical visualizations, which should exist for all sync tables, right?

Hey, nice detail having `create_db_connection` handle new records :)

**Comment by Shylpx** [comment]
> If I understand correctly, synchronizations are exported/imported via the canonical visualizations, which should exist for all sync tables, right?

@jgoizueta Thanks! Yes, the synchronizations are being exported via visualizations. So, I just updated the `service_item_id`, to use the new connection ID after the migration.

**Pull request merged**
