### PR TITLE
Deletes table prior to invalidating cache

### LINKED ISSUE #5516: Deleting dataset does not invalidate varnish cache
Same steps as in #5515:

- create a new empty dataset from dashboard
- add a new column
- rename a column
- delete the dataset
- create a new empty dataset again

Actual result:
GET requests to the SQL API returns old column fields (e.g. one of the renames from previous steps). 

Expected result:
GET requests should return correct data of the new dataset (e.g. the column fields).

For what it's worth, it could be because the new dataset will have the previously-deleted-dataset ("_untitled_table_") which is probably cached in varnish.

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #5516

Keep an eye on this @javisantana 

I haven't found reasons to believe further reordering is necessary (for example when adding or removing a column). Do you think otherwise?

### CODE REVIEW

**Comment by gfiorav** [comment]
Could you do a quick CR @juanignaciosl ? Thanks!

**Comment by juanignaciosl** [comment]
Uhm. Could you explain why does this fixes the problem? I'm not doubting your change, I just mean I miss that information: if I see the old code I see deletion and cache invalidation, it looks like it would've worked unless table deletion raised an error. Maybe you could add a comment in the code, since code is correct and clear but _intention_ of the action order is not obvious. I'll do the CR afterwards :-)

**Comment by gfiorav** [comment]
My fault! Lack of info :smile: 

Previously, the fact that the cache was invalidated *prior* to the table itself being deleted meant that a small window was open in between those operations where if an SQL request came in, it would cause the cache to be revalidated. Consequently, the next time the user would try to create a table with the same name, errors would occur.

This doesn't fix the problem (it has to be solved maybe in the extension) but it helps mitigate it.

**Comment by juanignaciosl** [comment]
LGTM, although this kind of reordering can expose other problems (not sure about `remove_table_from_stats` best placement, for example). Keep an eye on new related errors ;-)

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
