### PR TITLE
DO UI captions

### PR DESCRIPTION
**Pull request by javitonino**
Fixes https://github.com/CartoDB/bigmetadata/issues/207
Fixes https://github.com/CartoDB/bigmetadata/issues/210

It looks like this (@noguerol):
screenshot_20170801_165237

### CODE REVIEW

**Comment by noguerol** [comment]
👌

**Comment by arianaescobar** [comment]
@noguerol asked me to review this in case we were missing anything and I found two things missing (which weren't on the original ticket but also needs to be changed!):

1. `Select a area` to `Select region` and inside the dropdown, `Search by area` to `Search by region`. We gotta keep things consistent! :) 

screen shot 2017-08-03 at 14 25 59

2. Lastly, ampersands (&) are not being rendered correctly on the dropdown. Althought to keep it consistent we should either always use `and` or always use `&`. I would go with `and`.

screen shot 2017-08-03 at 14 40 07

**Comment by javitonino** [comment]
I'll add this, when there are no measures available:
screenshot_20170803_171207

I'm trying to make the requested changes, although they are a bit trickier than expected, as the texts you want to change are autogenerated. Also, regarding the tag naming (& vs and), it is a bit more convoluted, since it implies regenerating the entire DO dump https://github.com/CartoDB/bigmetadata/issues/231. It's something we will keep in mind for the future, but it's not something that can be changed instantly.

**Comment by arianaescobar** [comment]
Regarding that one you added, can we not show the "Filters" link when there are no available ones?

**Comment by javitonino** [comment]
Fixed the strings:
screenshot_20170803_173455

Hiding the "filters" element implies adding more logic, and it is an edge case. I only noticed this because I am testing in my local machine that has very little data loaded into the observatory. I think this is something that very few people will see so, IMHO, as long as the message is not clearly incorrect, we should not invest more work.

Yeah, I'm lazy 👉👈 (and also a backender writing javascript, my soul is slowly burning for this :P)

**Comment by arianaescobar** [comment]
haha fine... yeah, I was confused with that state of not having any filter, there should always be at least SOMETHING, right?

**Comment by xavijam** [comment]
So, we gave a 👍 thanks to @rjimenezda. Should we review anything else?

**Comment by javitonino** [comment]
Yes, please 🙏 Lots of changes since the last review.

**Comment by javitonino** [comment]
Deployed in ded01 for acceptance, thanks to @rubenmoya 💌

**Pull request merged**
