### PR TITLE
Fix reconfigure dataservices test

### PR DESCRIPTION
**Pull request by javitonino**
Whenever we update dataservices client in cartodb, we get failures in this test. The reason is that the test relies in the new dataservices client version to be installed in the CI machine but our CI machinery does not deploy that extension explicitly.

Furthermore the test only cares about the configuration of the extension, and not the extension itself. The test was failing because a failure in installation resulted in no configuration being done.

This PR just stubs the extension installation itself, so we only do the configuration part. This way, cartodb tests go back to being independent of dataservices extensions.

Could you please take a look at this @ethervoid?

### CODE REVIEW

**Comment by ethervoid** [comment]
Did you test this in production?

**Comment by javitonino** [comment]
Not yet. It should not affect anything, since it's running the same code in the same order (it's just a difference of what is part of which method).

But yes, we'll need to do acceptance (after CR) regarding user creation and DS configuration.

**Comment by amartinj** [comment]
Acceptance failed: https://rollbar.com/carto/CartoDB/items/36416/occurrences/47064044135/

**Comment by javitonino** [comment]
Ha, acceptance failed due to a parallel deployment of cartodb extension. let's discuss in a moment how to workaround it.

**Comment by juanignaciosl** [comment]
Acceptance :+1:

**Pull request merged**
