### PR TITLE
7423 exporting a private map shared with me fails

### PR DESCRIPTION
**Pull request by gfiorav**
This is the safest solution: We don't show download buttons for public pages involving private maps.

We might want to deploy this for Monday in case we don't come up with a better solution.

Review and make any changes you see fit, @juanignaciosl 

I won't be available until Friday afternoon 🌴 

cc/ @xavijam

### CODE REVIEW

**Comment by gfiorav** [comment]
Have a look please, @juanignaciosl

**Comment by juanignaciosl** [comment]
LGTM

**Comment by juanignaciosl** [comment]
It doesn't work from the UI, it returns a 403 error.

**Comment by juanignaciosl** [comment]
🙊  it _does_ work, I'm not sure about what happened, sorry 👍

**Comment by gfiorav** [comment]
😀 np! Deploying!

**Pull request merged**
