### PR TITLE
Show "New dataset" button when there are datasets in initial state

### PR DESCRIPTION
**Pull request by elenatorro**
Related issue [Support#2209](https://github.com/CartoDB/support/issues/2209)

### CODE REVIEW

**Comment by elenatorro** [comment]
retest this please

**Comment by elenatorro** [comment]
I tested it on staging with a test user:

1. I've uploaded the first dataset to the user's account directly from a notebook using cartoframes

Screenshot 2019-11-05 at 18 28 46

2. Then, I've entered the data page, and the button is shown:

Screenshot 2019-11-05 at 18 29 33

**Comment by elenatorro** [comment]
If this is going to change in the short term, I wouldn't change here and I'd include it as you suggest as part of the iteration, cause in this case is not an RT-like issue, what do you think?

**Comment by csubira** [comment]
Ok, no problem! I just add it in a card to the _Kuvizs in dashboard_ kanban https://github.com/orgs/CartoDB/projects/99#card-28832827 so we can tackle it when the new initial/empty state design proposal is ready. Go ahead and 🚀 !

**Pull request merged**
