### PR TITLE
Removes 'to_i' casts and forces 'geocoding_quota' not to be nil with validations

### PR DESCRIPTION
**Pull request by gfiorav**
Before this fix, if the user had no geocoding quota left causing the attribute 'geocoding_quota' to load as 'nil', a 'No method '-' defined' error was raised (even though the geocoding was successful).

This issue is described in ticket [4846](https://github.com/CartoDB/cartodb/issues/4846). 

A test to verify that `nil` geocoding quota is casted to '0' has also been added for the future.

### CODE REVIEW

**Comment by gfiorav** [comment]
cc @Kartones

**Comment by Kartones** [comment]
+1 but have you searched why the user had a `nil` instead of `0`? I'm worried that @juanignaciosl said it should be always 0, so maybe the vagrant user is not being properly created or something similar.

**Comment by gfiorav** [comment]
I had no idea that it should load to 0.

Looking at the organization user treatment:
```
def remaining_geocoding_quota
    if organization.present?
      remaining = organization.geocoding_quota.to_i - organization.get_geocoding_calls
    else
      remaining = geocoding_quota.to_i - get_geocoding_calls
    end
    (remaining > 0 ? remaining : 0)
  end```

It seemed like `nil`was expected.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5543/))

**Comment by juanignaciosl** [comment]
I think I haven't said "it should always be 0" but "it should not be nil [at that point]". @gfiorav @Kartones at that point, for non organization users, it _should_ have a value. Organization users are the only users that haven't got geocoding quota right now, since it's accounted for the organization, although that could change if we allow org owners to set custom quotas for users.

I don't like the cast, since data errors my be overlooked with this. First of all, have you checked why that user had no `geocoding_quota`? Was it an organization user?

**Comment by juanignaciosl** [comment]
[Development rake task `setup`](https://github.com/CartoDB/cartodb/blob/master/lib/tasks/setup.rake#L21) is wrong: it creates a non-org user without geocoding quota. So...
1.- I wouldn't add the cast.
2.- I'd fix the data and the task.
3.- I _might_ add a validation check for users making it mandatory for users without org, although this must be tested, it's just a quick thought.

**Comment by gfiorav** [comment]
Ok! Interesting... then maybe we should remove the cast from organizations and add proper validation and tests?

**Comment by gfiorav** [comment]
New commit removes al `to_i` casts and adds validations to ensure `geocoding_quota` is never `nil`. This **breaks** user creation scripts, but that is the idea: they should be redone properly.

cc @juanignaciosl

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5551/))

**Comment by juanignaciosl** [comment]
As said through Slack, this must be extensively tested through the application, and scripts must be fixed before pushing new changes. I'd also ask for a test at user_spec that checks a normal user cannot be created without geocoding_quota.

**Comment by Kartones** [comment]
- Organization geocoding wasn't to be touched, so please leave it as it is
- Normal geocoding quota is the one that gave problems, but as @juanignaciosl said, better to fix then the scripts if those are the source
- You have fixed no scripts, so this cannot be pushed (apart from the bug of touching the org. geocoding), if the issue is at `\scripts\create_dev_user`, go and edit that script from this branch. If is the setup rake [Nacho mentioned above](https://github.com/CartoDB/cartodb/pull/4848#issuecomment-127275190) go edit it.

What matters is doing things right, not doing a quick patch that hides the issue without fixing it. If takes more time, then so be it but let's improve current situation. And along the way try to learn how things work and it'll be worth even more.

**Comment by gfiorav** [comment]
cc @Kartones 

In the spirit of doing things right, we should never cast `geocoding_quota` from `nil` to `0`. 'geocoding_quota' should never be nil neither in organization or normal users. This value should be defaulted to `0` in the db upon creation.

Hacking the rake tasks is just letting the problem persist. I think we should have a conversation @juanignaciosl, @javisantana, you and me about changing the 'user' table to default `geocoding_quota` to '0'

**Comment by Kartones** [comment]
Yes, it should be 0 and not nil, but the code is supposed to also *always* set it to some value, either 0 or > 0, so of course the final step would be to set a DEFAULT 0 on the DB, but we also need to see where we're not setting up the user quota and fix it.

One thing is having a default value as a fallback, another is having a setup script not working properly. It's not excluding, but if we just cast or set a default value we're not fixing the setup error.

**Comment by gfiorav** [comment]
Setting a default value in the DB *will* fix the error as you will never see `nil`- `number` in 
```ruby
remaining = geocoding_quota - get_geocoding_calls
```
no? The only time you can have that is if there has been an error, and in that case it's very useful to have an error rise. If we cast the error (`nil` to `0`) we will not know something is wrong.

Maybe I'm wrong, but this is why I think adding a `default to 0` in the DB is a better fix than manually adding `user.geocoding_quota = 0` in every script, moreover if having a 'nil' value in 'geocoding_quota' is never ok.

**Comment by Kartones** [comment]
Again, this are two issues:
a) We have a setup scenario **where we are NOT setting the user geocoding quota**
b) We are not setting default quota to a number so if a) happens b) makes code break

b) is a result of a). If instead of a casting issue we had an assert of "fail if user has no geocoding quota setup" it would still be an issue and b) wouldn't be a valid solution.

In fact the more I think about it the more I'd rather make the whole thing crash due to the nil because that way we know there is a flow at our code where we're not setting up the quota /cc @juanignaciosl 

So please, let's fix the setup scripts and then we talk about default values or not. Or else go talk with @javisantana and @juanignaciosl and if they say otherwise I'd accept their argument, we're going in circles with this discussion and for me adding a default value without fixing setup scripts is not acceptable.

**Comment by gfiorav** [comment]
Yes! That is precisely my point! :)

Let's do it!

Fixing the setup scripts now...

**Comment by Kartones** [comment]
ok, then sorry I misunderstood you... Thanks!

**Comment by gfiorav** [comment]
Script fixed; running checks

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5558/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5600/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5603/))

**Comment by gfiorav** [comment]
Ready for review @Kartones @juanignaciosl

**Comment by Kartones** [comment]
looks fine, just try creating a new user throught the box, other through Central, and other using an organization owner (they can create org users too) at staging, but code looks :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5613/))

**Comment by gfiorav** [comment]
retest this,please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5636/))

**Comment by gfiorav** [comment]
retest this,please

**Comment by gfiorav** [comment]
retest this,please

**Comment by gfiorav** [comment]
retest this,please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5649/))

**Comment by gfiorav** [comment]
retest this,please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5655/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5653/))

**Pull request merged**
