### PR TITLE
Slow imports improvement: Better Query Batcher

### LINKED ISSUE #3835: Analyze slow imports
## Tasks

- [x] Create sequence and use it instead of boolean field to improve query planning
- [x] Replace all old QueryBatcher calls by new system
- [x] Rename `CartodbIdQueryBatcher` to `IdBasedQueryBatcher`
- [x] Build tests for the new code
- [x] Research Mailchimp datasource improvements

## Data samples:

(1)
- https://data.cityofchicago.org/Community-Economic-Development/Business-Licenses-Current-Active/uupf-x98q

- https://data.cityofchicago.org/Health-Human-Services/Food-Inspections/4ijn-s7e5
121MB exported as CSV

(2)
- https://data.cityofchicago.org/Service-Requests/311-Service-Requests-Vacant-and-Abandoned-Building/7nii-7srd
- https://data.cityofchicago.org/Transportation/Average-Daily-Traffic-Counts/pfsx-4n4m

(3)
- https://data.cityofchicago.org/Service-Requests/311-Service-Requests-Vacant-and-Abandoned-Building/7nii-7srd
- https://data.cityofchicago.org/Public-Safety/Crimes-2014/qnmj-8ku6

(4)
- Mailchimp

<del>Branch: `3835-new-query-batcher`</del>
Branch for mailchimp improvements: `optimize-mailchimp-connector`

### PR DESCRIPTION
**Pull request by Kartones**
See #3835  for more details

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4008/))

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4009/))

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4010/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4011/))

**Comment by recena** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4015/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4021/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4022/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4023/))

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4028/))

**Pull request merged**
