### PR TITLE
Adding 'Edit in CartoDB' link to new public map

### PR DESCRIPTION
**Pull request by xavijam**
Basically checking if logged user and map owner are the same.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3379/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3380/))

**Comment by xavijam** [comment]
Please @javierarce, could you take care of and release this thing tomorrow? thanks :).

**Comment by javierarce** [comment]
Sure :)

**Pull request merged**
