### PR TITLE
Fixes inability to apply buffer-size style

### PR DESCRIPTION
**Pull request by fdansv**
This leaves aside Map symboliser rules so that the code can be sent to the server.

@javisantana, @iriberri

### CODE REVIEW

**Comment by iriberri** [comment]
:heart:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2357/))

**Comment by javisantana** [comment]
add a test please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2394/))

**Pull request merged**
