### PR TITLE
Privacy modal improvements

### PR DESCRIPTION
**Pull request by javierarce**
This PR updates the privacy modal putting the password field inside of the card.

password

I've removed the code that emptied the password when the card was selected. Currently the input field is shown all the time and it would look weird that checking and unchecked the password card would clear it.

Original ticket: https://github.com/CartoDB/cartodb/issues/3753

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4321/))

**Comment by javierarce** [comment]
@viddo: can you have a look, please?

**Comment by javierarce** [comment]
bump

**Comment by viddo** [comment]
Cool, I like this inlined password field better :+1:

**Pull request merged**
