### PR TITLE
Updating trade-areas analysis with new attributes, isolines and dissolved

### LINKED ISSUE #7292: Update trade areas analysis with last updates
https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.6.0/reference.json

cc @viddo @rochoa @dgaubert

### PR DESCRIPTION
**Pull request by xavijam**
Fixes #7292.

screen shot 2016-05-04 at 14 42 14

CR: @viddo 
cc @dgaubert @rochoa @saleiva 

Until we don't have Maps API released we can't merge it.

### CODE REVIEW

**Comment by xavijam** [comment]
By the way, we have limited isolines from 1 to 30, no idea if it is a good decision or not, who could give us a better explanation/choice @saleiva ?

**Comment by viddo** [comment]
Looks legit 👍

**Comment by xavijam** [comment]
retest this please

**Comment by xavijam** [comment]
_Failing on-premise frontend tests due to a lack of internet network._

**Pull request merged**
