### PR TITLE
Disable HTML mode when having NONE as popup

### PR DESCRIPTION
**Pull request by matallo**
close https://github.com/CartoDB/cartodb/issues/8647

### CODE REVIEW

**Comment by matallo** [comment]
waiting for disabled style for toggle to be reviewed in cartoassets (I'll bump version then), working already

CR @piensaenpixel /cc @saleiva

**Comment by xavijam** [comment]
ping!

**Comment by xavijam** [comment]
I'd add a test checking the behaviour BTW.

**Comment by matallo** [comment]
roger!

**Comment by matallo** [comment]
test added, review @xavijam?

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
