### PR TITLE
[Metrics] 6290 Adds "Liked map" event

### PR DESCRIPTION
**Pull request by jmartinter**
Adds:
 - lauches a new Segment.com event 'Liked map' each time a user likes or removes like in a map

Modifies:
 - replaces hash creation style in EventTracker class (from 'key' => value to key: value)

cc'ed @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
@guido could you take a look please?

**Comment by jmartinter** [comment]
cc'ed @gfiorav

**Comment by xavijam** [comment]
Ouch, thanks @jmartinter, I mixed up with other user.

**Comment by gfiorav** [comment]
I'll fix those Hound complaints for you, @jmartinter :P

**Comment by gfiorav** [comment]
@jmartinter all good: :+1:

**Comment by jmartinter** [comment]
I take note for next PR. Thanks!

**Comment by xavijam** [comment]
After a successfully PR merged, please delete the branch @jmartinter :)

**Pull request merged**
