### PR TITLE
Hiding signup link from header if it isn't SaaS

### PR DESCRIPTION
**Pull request by Xatpy**
Ref. [ticket #2191](https://github.com/CartoDB/cartodb/issues/2191) : **"create an account" should be removed from open-source edition **

Assuming that:
SaaS ==> account_host: ‘cartodb.com’ in app_config.yml

I had to add account_host var to javascript from Cartodb.config[:account_host]
Tests modification adding account_host to db.config.

- account_host:       'localhost.lan:3000'
screen shot 2015-03-03 at 18 06 00

- account_host:       'cartodb.com'
screen shot 2015-03-03 at 18 11 52

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2054/))

**Comment by Xatpy** [comment]
Please, @javisantana @CartoDB/frontend , could you check it? thanks!

**Comment by viddo** [comment]
This change probably requires that you update the [new public header](https://github.com/CartoDB/cartodb/blob/master/app/views/admin/shared/_new_public_header.erb) too

**Comment by Xatpy** [comment]
Oh, you're right @viddo. I'll do it. thanks!

**Comment by javisantana** [comment]
:es:

**Comment by Xatpy** [comment]
- account_host: 'cartodb.com'
screen shot 2015-03-04 at 19 17 09

- account_host: 'localhost.lan:3000'
screen shot 2015-03-04 at 19 12 13

cc @viddo

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2089/))

**Comment by viddo** [comment]
:+1:

**Comment by Xatpy** [comment]
Closing this PR because it continues in [this 'general' one #2646](https://github.com/CartoDB/cartodb/pull/2646)

**Pull request closed without merging**
