### PR TITLE
Don't offer new DO UI unless user has DO credits

### PR DESCRIPTION
**Pull request by xavijam**
Related ticket: https://github.com/CartoDB/cartodb/issues/12648

Basically that ^^^.

## Acceptance criteria
Taking into account DO credits and the DO feature flag `data-observatory-multiple-measures`, those are the possible cases:

| DO Credits | Feature flag | New Do analysis UI |
|------------|--------------|--------------------|
| ✓          | ✓            | ✓                  |
| ✓          | ✗            | ✗                  |
| ✗          | ✓            | ✗                  |
| ✗          | ✗            | ✗                  |

✓ - credits or feature flag applied, new DO working
✗ - no credits, or no feature flag applied, no new DO working

cc @juanignaciosl @noguerol @kevin-reilly @nobuti

### CODE REVIEW

**Comment by rubenmoya** [comment]
🇪🇸

**Comment by xavijam** [comment]
Being deployed in Ruis.

**Comment by nobuti** [comment]
If the user doesn't have the feature flag, the old DO analysis UI is shown, and it checks the quota explicitly. The same happens for no quota assignment. Is that correct? Other than that, it works as expected.

**Comment by xavijam** [comment]
After talking with @juanignaciosl, seems like what you mentioned (offline) @nobuti is true. We need to check if the user has more than 0 quota or if the user has 0 quota but soft-limit enabled. So back to development.

**Comment by xavijam** [comment]
\o/ 🎉

**Pull request merged**
