### PR TITLE
Hides the like label in certain cases

### PR DESCRIPTION
**Pull request by javierarce**

### CODE REVIEW

**Comment by xavijam** [comment]
In case you want a second opinion :+1: :es: :coffee: :cactus:

**Comment by javierarce** [comment]
@saleiva, @piensaenpixel: I maintained the 20px separation between the heart and the icons. Is that too much or is it ok?

screen shot 2015-09-22 at 17 14 53
screen shot 2015-09-22 at 11 43 33
screen shot 2015-09-22 at 11 43 58
screen shot 2015-09-22 at 11 44 10

**Comment by saleiva** [comment]
spacing is so weird, what about moving the "like block" to the end of the list?

**Comment by javierarce** [comment]
Ok, yeah, I'll do that.

**Comment by javierarce** [comment]
## User feed
screen shot 2015-09-23 at 14 50 30

#### maps
screen shot 2015-09-23 at 15 29 44

#### datasets 

screen shot 2015-09-23 at 15 29 50

## Explore
screen shot 2015-09-23 at 15 44 46

#### mobile / small screens
screen shot 2015-09-23 at 15 44 58

**Comment by javierarce** [comment]
@xavijam I added several extra fixes:

- I moved the like buttons to the right side.
- Fixed some links in the explore page (so they maintain the same protocol and not use http by default)
- Fixed the margin of the loader in the explore page

**Comment by xavijam** [comment]
staging server?

**Comment by javierarce** [comment]
Same as usual.

**Comment by xavijam** [comment]
Safari: 

screen shot 2015-09-23 at 17 13 49

**Comment by xavijam** [comment]
Same happening in Firefox...

**Comment by javierarce** [comment]
Thanks, I'll check that. The rest is ok?

-- 
Javier Arce

**Comment by xavijam** [comment]
Yeah, i only miss the fix for clock icon and the text, i suppose it will be solved in other ticket?

**Comment by javierarce** [comment]
Yes. Ok, I fixed the the like initialization that was preventing hiding the likes.

**Comment by javierarce** [comment]
Ok, I'm going to deploy this @xavijam

**Comment by xavijam** [comment]
Ok, about the icon separator?

**Comment by javierarce** [comment]
Yes, this fixes the position of the like (to the right side) and the hiding of the 'likes' label.

**Comment by xavijam** [comment]
No, about this:
screen shot 2015-09-24 at 16 20 46

**Comment by javierarce** [comment]
I'm doing another PR for that.

**Pull request merged**
