### PR TITLE
Frontend cleaning

### PR DESCRIPTION
**Pull request by xavijam**
### Concerns

- Common submodule now called ```old_common``` (changes in .gitsubmodule !!! ).
- Error and static html pages don't require external js, css or images anymore, new style included.
- Removed unnecessary assets, starting with CSS, images and sprites.
- Renamed js old common folder to ```old_common```. And ```new_common``` is now the new ```common```.
- Removed unnecesary and old JS and JST files.
- Replaced common, new_common, new_dashboard, new_organization, etc etc ... things.
- S3 upload improved.

@CartoDB/frontend

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3545/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3547/))

**Comment by recena** [comment]
retest this please

**Comment by recena** [comment]
retest this please

**Comment by xavijam** [comment]
Now test are failing due to any of my faults, sorry!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3567/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3569/))

**Comment by recena** [comment]
@xavijam Nice work!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3571/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3573/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3574/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3575/))

**Pull request merged**
