### PR TITLE
replace 404 with new design

### PR DESCRIPTION
**Pull request by matallo**
this comes directly from http://cartodb.com/404, as in copy&paste, we need to automate this somehow

this is WIP, waiting for @carlostallon changes

/cc @azamorano @xavijam

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1596/))

**Comment by xavijam** [comment]
@matallo, don't forget we need to review this please.

**Comment by javisantana** [comment]
don't forget to update NEWS

**Comment by matallo** [comment]
thanks for the reminder @javisantana

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1604/))

**Comment by azamorano** [comment]
Tests failed with [syntax error](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1604/console ) @matallo could you please review before merging?
Apart from that, shouldn't we do the same refactor for the rest of the static pages included in public?

**Comment by javisantana** [comment]
@matallo check this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1739/))

**Comment by matallo** [comment]
Retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1749/))

**Comment by matallo** [comment]
screen shot 2015-02-19 at 11 44 02

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1763/))

**Comment by matallo** [comment]
Retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1773/))

**Comment by matallo** [comment]
:sparkles:

**Pull request merged**
