### PR TITLE
Fixes redirection to vis when creating a vis from two tables

### PR DESCRIPTION
**Pull request by javierarce**
cc @CartoDB/frontend

### CODE REVIEW

**Comment by xavijam** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1486/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1488/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1489/))

**Pull request merged**
