### PR TITLE
Fixes the showing of map previews in the delete items dialog

### PR DESCRIPTION
**Pull request by javierarce**
We attempt to load the previews after the rendering of the dialog has been finished. This PR fixes the problem and adds new spec.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2095/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2097/))

**Comment by javierarce** [comment]
@CartoDB/frontend / @viddo: can you review this PR, please?

**Comment by viddo** [comment]
:+1: but this does not solve the 2nd rendering on the maps list as you found, right?

**Comment by javierarce** [comment]
No, just the 1st problem. We can work in another ticket/PR for that.

**Comment by viddo** [comment]
Then OK for me :)

**Comment by javierarce** [comment]
:bow:

**Pull request merged**
