### PR TITLE
using a different url for visualizations based on feature flag, fixed #3...

### PR DESCRIPTION
**Pull request by javisantana**
...083

### CODE REVIEW

**Comment by javisantana** [comment]
cc @rafatower

**Comment by rafatower** [comment]
:+1: gonna start from that branch and update all affected tests

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2912/))

**Comment by javisantana** [comment]
merged in another branch

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3062/))

**Pull request closed without merging**
