### PR TITLE
Add unique constraint to viz.permission_id (1:1 relation)

### PR DESCRIPTION
**Pull request by javitonino**
This is a great opportunity to add this constraint. Visualization <-> Permission relation is actually 1:1. Already checked the databases, there is no case with duplicates `permission_id`'s (yay!) so I think this is safe to do without a cleaning script.

Part of #7013

### CODE REVIEW

**Comment by javitonino** [comment]
test

**Comment by javitonino** [comment]
a

**Comment by javitonino** [comment]
retest this please

**Comment by javitonino** [comment]
Can you CR? @juanignaciosl

**Comment by juanignaciosl** [comment]
:sparkles:

**Pull request merged**
