### PR TITLE
Sending widgets to tiler closes #6448

### LINKED ISSUE #6448: Send widgets to tiler
Send widgets to tiler for named maps.

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #6448.

cc @javisantana

### CODE REVIEW

**Comment by juanignaciosl** [comment]
@gfiorav CR this, please.

**Comment by juanignaciosl** [comment]
@xavijam , added `layer_id`:

screen shot 2016-02-19 at 13 12 27

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
@xavijam , last commit should fix the "named map not updated on widget change" issue #6616 (and varnish caching indeed). Please let me know if you have any issue.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by xavijam** [comment]
In the frontend part, only pending this PR -> https://github.com/CartoDB/cartodb.js/pull/1130

**Comment by juanignaciosl** [comment]
@gfiorav CR the backend code of this PR, please.

**Comment by gfiorav** [comment]
It looks :+1: to me

**Pull request merged**
