### PR TITLE
Deleting a password protected visualization from the dashboard fails

### LINKED ISSUE #2418: Deleting a password protected visualization from the dashboard fails
#### Steps to reproduce it

1. Create a visualization
2. Set its privacy to private with password
3. Go to the dashboard and delete it

#### Expected result

The vis should disappear.

#### Actual result

The vis is not removed from the dashboard and the backend returns the following error:

```
named_maps_api: "Communication error with tiler API. HTTP Code: PUT:400 http://10.0.1.254:80/tiles/template/tpl_40ee2056_b929_11e4_b6f4_0e9d821ea90d?api_key=[redacted personal api key]  {"error":"Error: Missing or empty layers array from layergroup config"}"
```

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #2418

### CODE REVIEW

**Comment by Kartones** [comment]
@rafatower CR please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1833/))

**Comment by rafatower** [comment]
ok with it but a test would be nice

**Comment by Kartones** [comment]
Ok, added a task for the test (sadly is not as quick as I'd like), I'll write it whenever I can this sprint

**Pull request merged**
