### PR TITLE
staging public pages are not indexed anymore

### LINKED ISSUE #4906: staging public pages are being indexed
https://www.google.es/search?q=cartodb-staging.com&oq=cartodb-staging.com&aqs=chrome..69i58j69i60l3j69i57.2974j0j4&sourceid=chrome&es_sm=91&ie=UTF-8

### PR DESCRIPTION
**Pull request by matallo**
- [x] Public pages
- [x] Login
- [x] Signup
- [ ] Error pages (404, 500, HTML5, ...)

close #4906

CR @xavijam

### CODE REVIEW

**Comment by matallo** [comment]
added the rest of layouts (better safe than sorry) and the env :sweat_smile: 
 @xavijam

**Comment by xavijam** [comment]
Looks ok :+1:

**Comment by matallo** [comment]
I'm takling the error pages independently (as they need to be changed)

btw, @CartoDB/systems shouldn't we approach this with a robots.txt better? These will work anyway as we can use the `ENV` in the layout views

**Comment by viddo** [comment]
Considering _we_ (cartodb) don't want to index staging servers, why not add this at the nginx level instead of enforcing it here, inline in the code? Something like https://gist.github.com/sergejmueller/0e508f3a4d92fd7ec110 using the x-robots-tag Bonus: this way we don't have to remember adding it to new layout files.

**Comment by xavijam** [comment]
Uff... totally agree @viddo, @luisbosque could you take care of it?

**Pull request closed without merging**
