### PR TITLE
Migrates old color ramps and old quantification methods 

### LINKED ISSUE #7902: Choropleth styles migration is not working anymore
## STR
- Create a map of points.
- Go to the editor and apply the choropleth wizard.
- Go to the new builder, and check style panel.
- Screenshot below:

screen shot 2016-06-17 at 10 19 38

The problem basically is that we set the range with the `wizards-properties` value, that only represents the color, we should "convert" it in the fill component @javierarce.
screen shot 2016-06-17 at 10 13 32

### PR DESCRIPTION
**Pull request by javierarce**
Closes #7902

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam and/or/xor @javisantana

**Comment by xavijam** [comment]
Looks good man! yay! thanks.

**Comment by xavijam** [comment]
Ready then?

**Comment by javierarce** [comment]
Yes, I just thought I could simplify it a bit before merging.

**Pull request merged**
