### PR TITLE
Onpremises style issues IE

### PR DESCRIPTION
**Pull request by elenatorro**
Related issues:

* https://github.com/CartoDB/onpremises/issues/504
* https://github.com/CartoDB/onpremises/issues/511
* https://github.com/CartoDB/onpremises/issues/484
* https://github.com/CartoDB/onpremises/issues/501
* https://github.com/CartoDB/onpremises/issues/507

## Acceptance

User: `onpremises-style` 

`#504`
* Go to edit a map's legend and switch to html view
* [x] Check code comments are placed correctly

`#511`
* Create a formula widget and edit it
* [x] Checkboxes are placed correctly in IE11
* [x] Checkboxes are placed correctly in Chrome
* [x] Checkboxes are placed correctly in Safari
* [x] Checkboxes are placed correctly in Firefox

`#484`
* Go to edit map and click on "Download map"
* [x] Glitch must not be visible in Firefox
* [x] Glitch must not be visible in IE11

`#501`

* Go to dashboard -> datasets 
* Click on New Dataset
* "Let CARTO automatically guess data types and content on import" checkbox icon must be visible in blue.
  * [ ] in IE11
  * [ ] in Chrome
  * [ ] in Firefox
  * [ ] in Chrome

`#507`

* Log in with an organization user
* Go to dashboard / datasets
* Click on a dataset and then click on "Change privacy..."
* Click on "Share it with your colleagues"
* [x] Modal footer must be ok in IE11
* [x] Modal footer must be ok in Firefox
* [x] Modal footer must be ok in Chrome
* [x] Modal footer must be ok in Safari

### CODE REVIEW

**Comment by jesusbotella** [comment]
I have tested all the use cases mentioned above and all work as expected except the one of the edit form in IE11. The check icon is still cut in the bottom :(

ie11

The comments in the legend are placed correctly, but they are only shown in the Cloropleth legend, I suppose it is correct the way it is.

**Comment by ivanmalagon** [comment]
Spotted several issues

#### Share datasets

In Chrome it's now broken compared to production.

image

Production: no grey bar, content centered.

image

In the PR branch: grey bar, content aligned to the top.

#### Connect pages

Spotted in Chrome.

image

Production: grey background extends wholly to the bottom.

image

 In this PR branch: backgrounds doesn't extend.

**Comment by ivanmalagon** [comment]
Another thing spotted (not introduced by this PR, it's happening on production also)

In IE, once you click on a custom legends you can't click back to none. It's like the page doesn't react to any click.

**Comment by ivanmalagon** [comment]
✅ All green everything

Found two issues not introduced in this PR. Opening an issue for them.

**Comment by elenatorro** [comment]
Deployed 🚀

**Pull request merged**
