### PR TITLE
500 obtaining layer infowindow data of some vis

### LINKED ISSUE #3091: 500 obtaining layer infowindow data of some vis
```
TypeError: can't convert nil into String
File "app/models/layer.rb", line 69 in to_json
File "app/controllers/api/json/layers_controller.rb", line 22 in show
File "app/controllers/application_controller.rb", line 50 in wrap_in_profiler
````

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #3091

### CODE REVIEW

**Comment by Kartones** [comment]
@rafatower CR please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2959/))

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2964/))

**Comment by rafatower** [comment]
Looks good to me though you have something weird thing in the tests (they look unrelated)

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2969/))

**Pull request merged**
