### PR TITLE
Check for csv named as xls or xlsx and try to parse it correctly

### LINKED ISSUE #4271: importer doesn't work via url but it does downloading and dragging the file
**str**

- go to dashboard
- click "New map"
- choose "connect"
- paste http://londondatastore-upload.s3.amazonaws.com/dataset/recorded-crime-summary-data-london-borough-level/boro.csv

**expected behaviour**

- import file

**actual behaviour**

- error: Unknown (99999)

it works if you download and drag the file to the dashboard

### PR DESCRIPTION
**Pull request by ethervoid**
**This PR fixes #4271**

**Context**

We receive a file `file.csv` but the request comes with a `Content-Type: application/vnd.ms-excel`. When the user try to import it fails.

**Error**

The problem is that try to use `in2csv` but believing that is a `xls` file. `in2csv` gives an error when try to convert it to `csv` because the file doesn't have the BOF header.

**Solution**

Get the mime-type of the file and if that type is `text/plain` we assume that is a `csv` file and try to convert using `-f csv` flag

Please @CartoDB/backend take a look to it. Thank you :)

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4855/))

**Comment by rafatower** [comment]
I'm ok with the patch but probably the detection about content type should be done before reaching Excel2Csv. I don't remember, where's that decision taken?

**Comment by Kartones** [comment]
I am ok with making the importer smarter but, do we want to handle this user screw ups?

I mean, if you provide a valid extension (CSV) but content doesn't maches, maybe we should just tell the user a simple "wrong format", which is the truth. Don't know, is the same as with encoding issues, we've taken the approach of "if is not UTF-8 is your issue, not ours".

Another point: Also, if we do this, then why not check all allowed types have correct content? We should generalize this check/solution (no matter we fix or return error) instead of only covering this xls to csv scenario no?

/cc @iriberri @javisantana

**Comment by ethervoid** [comment]
The first approach was to do in the downloader but there we should decided what has priority the Content-type header or the mime-type of the file. I've put it in the Excel2csv to reduce the possible cases to excel files or text/plain files that we assume are CSV.

In case there are more cases or this appear in other points of the importer we can improve the solution to a higher level, for example the downloader.

What do you think?

**Comment by Kartones** [comment]
Also, please add a test, create an xls file from Openoffice with 2/3 rows, rename and add it to the fixtures (test "samples") etc.

**Comment by ethervoid** [comment]
The first approach I've tried to do is to check in the downloader but there we have to decided what we prioritize the mime-type of the file over the content-type header or vice versa.

I think this fix is useful because the user is not going to know why are we giving him that error when he's trying to import a csv. The solution passes to know how our downloader works.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4974/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4992/))

**Comment by ethervoid** [comment]
@Kartones pls CR this PR to finally merge it in master

**Comment by rafatower** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4993/))

**Pull request merged**
