### PR TITLE
Fix bubble wizard legend not being updated on column change

### PR DESCRIPTION
**Pull request by viddo**
Solves #2594 

There are two issues:

1. Changed the default lock state to be off, so the values are updated as expected. If set manually to locked they will _not_ be updated even if changing column later on (AFAIK this is the desired behavior of this lock state).
1. Even if I fixed 1, when changing to bubble wizard from another it did not always update the legend if some other props happened to be the same.

While at it also did some cleanup on the formatting to adhere to the informal standard.

bubble-legends

Bonus: Fixed this test case that caused the annoying JS error output (not failing test though) on stdout:
```bash
..........>> TypeError: 'undefined' is not an object (evaluating 'tbl.offsetWidth') at
>> vendor/assets/javascripts/datepicker.js:458
>> vendor/assets/javascripts/datepicker.js:770
>> vendor/assets/javascripts/cartodb.uncompressed.js:25
>> vendor/assets/javascripts/cartodb.uncompressed.js:25
>> vendor/assets/javascripts/datepicker.js:776
>> lib/assets/javascripts/cartodb/common/import/custom_datepicker.js:135
>> lib/assets/javascripts/cartodb/common/import/custom_datepicker.js:63
....
```

### CODE REVIEW

**Comment by viddo** [comment]
I guess you @javierarce is the best candidate to review this since you did the original code related to the lock state.

cc @saleiva

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2291/))

**Comment by saleiva** [comment]
:raised_hands:

**Comment by javierarce** [comment]
Perfect :flags:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2293/))

**Pull request merged**
