### PR TITLE
Allows to remove overlays pressing the backspace key

### PR DESCRIPTION
**Pull request by javierarce**
Some users (ok, just @andrewxhill :P) have complained that sometimes they hit the backspace key to remove an overlay, but instead they get sent to the previous page. 

This fix intends to solve that issue and avoid our users to become lonely and confused.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2180/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2186/))

**Comment by javierarce** [comment]
@CartoDB/frontend: can you review this, please?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2187/))

**Comment by xavijam** [comment]
Question: Is there any possibility to close the overlay without calling hide method?

**Comment by viddo** [comment]
@xavijam `._close` like in the changeset?

**Comment by viddo** [comment]
Isn't this a wanted behaviour for all modals in that case? From what I can see this is only fixed on some particular modals?

**Comment by viddo** [comment]
..apart from that I think the change is fine.

**Comment by xavijam** [comment]
I was asking :(. If document bind is removed, for me :+1:

**Comment by javierarce** [comment]
@viddo: the Image overlay inherits from the Text overlay and the Title overlay is really a Text overlay but with different settings. So I just had to apply the change to Text and Annotation overlays.

@xavijam: yes, the `keydown` binding is removed when the element is destroyed.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2193/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2259/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2260/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2277/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2278/))

**Pull request merged**
