### PR TITLE
Trying to stop this madness

### PR DESCRIPTION
**Pull request by xavijam**
cc @CartoDB/frontend

### CODE REVIEW

**Comment by xavijam** [comment]
So, in that case, we are pointing to the wrong submodule commit in master...

screen shot 2017-07-12 at 16 40 51

https://github.com/CartoDB/cartodb.js/tree/a316f4c786ae84597f7931cdaeea4540e914d7d4

**Comment by alonsogarciapablo** [comment]
Yes, that's the problem @xavijam.

**Comment by xavijam** [comment]
:+1:, let me fix it then 💋 .

**Comment by xavijam** [comment]
I feel it looks better know :)

**Comment by xavijam** [comment]
merging!

**Pull request merged**
