### PR TITLE
more excluded rows

### PR DESCRIPTION
**Pull request by saleiva**
@javierarce PR please!

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5068/))

**Comment by javierarce** [comment]
:+1: but just a minor thing (although useful if we keep adding columns): Could you put the ```minlat```, ```maxlat```, etc. near ```lat```, ```lon```, ```long```, ```latitude```, etc? Same thing wit the columns that have anything to do with ```x``` and ```y```.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5070/))

**Comment by saleiva** [comment]
Hey @javierarce take a look!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5128/))

**Comment by javierarce** [comment]
ok, let me merge with master

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5129/))

**Pull request merged**
