### PR TITLE
Centroide enabler form

### PR DESCRIPTION
**Pull request by nobuti**
This PR applies the enabler form component into the centroid model.

centroid

cc @xavijam

### CODE REVIEW

**Comment by nobuti** [comment]
Please @javierarce could you take a look too please?

**Comment by xavijam** [comment]
Let's check that the places where the "Operator" component is being used are not affected by any of these changes.

**Comment by nobuti** [comment]
@xavijam Already checked, the component in the intersection analysis is working as expected. But I'll double check.

**Comment by xavijam** [comment]
Check in style, aggregation options.

**Comment by nobuti** [comment]
Checked 👍

**Comment by javierarce** [comment]
👍  Nice!

**Pull request merged**
