### PR TITLE
Add source maps for minified files

### LINKED ISSUE #1109: be able to serve uncompressed javascript resources with a url flag
in production all the javascript files are compressed and it's impossible to debug.

we should be able to add ?debug=true to the url so the assets are served without ofuscation

### PR DESCRIPTION
**Pull request by viddo**
This adds support for source-maps for staging/production, fixes #1109 
Finally only needed to add one new task so was mostly a matter of moving things around a little bit to create the sourcemaps properly.

Noteworthy changes: 
- `uglify` supports concat'ing by itself so using that to get proper sourcemaps based on original source files rather than the concat'ed files
- Updated uglify-related dependencies, to support sourcemaps flags
- Added [`exorcise`](https://github.com/thlorenz/exorcist) task, to extract inlined sourcemaps from browserify modules
- https://github.com/CartoDB/cartodb/blob/master/lib/build/tasks/s3.js#L20
- In terms of build time there should not be any (noticable) difference, the new "exorcise" task only takes like ~120ms, but there's some new `.map` files so upload S3 might take a little longer (didn't need to update [`S3.js` task btw since it already contained a wildcard to upload sourcemaps](https://github.com/CartoDB/cartodb/blob/master/lib/build/tasks/s3.js#L20).

Added a new grunt task `sourcemaps` to generate sourcemaps in `tmp/sourcemaps/javascripts`, w/o having to overwrite existing dev files in `public/assets`, from there just drag it to the logged trackjs trace:
trackjs

Another thing to take into account when debugggin in staging/production, taken from [minifyify FAQ](https://github.com/ben-ng/minifyify#faq):
> * Why does the sourcemap cause my debugger to behave erratically?

> Some of the optimizations UglifyJS performs will result in sourcemaps that appear to broken. For example, when UglifyJS uses the comma operator to shorten statements on different lines, a single debugger "step" in minified code may execute multiple lines of the original source.

> Another common example of erratic behavior is when code like this is compressed:

 > ```
>  var myThing = myFunc('a')
>    , cantGetHere = myFunc('b');
>  ```

> If you set a breakpoint on the second line, your debugger might not pause execution there. I've found that setting the breakpoint on the first line and stepping onto the second line is more reliable.

### CODE REVIEW

**Comment by viddo** [comment]
@xavijam @javisantana please review. :) deployed on rui0x if you want to have a look

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3591/))

**Comment by viddo** [comment]
cc @CartoDB/frontend FYI

**Comment by xavijam** [comment]
:us:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3605/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3606/))

**Pull request merged**
