### PR TITLE
Checking if files array is not empty when file input changes, within create dialog

### LINKED ISSUE #3379: Create import view throws uncaught error on canceling selected a file (2nd time)
STR:
- Open a create-dataset/map or add-layer dialog
- Click "Connect dataset" tab (if view is not already displayed)
- Click "Select a file" and select a valid file
- Cick "<--" button to revert selection
- Click select again, but cancel (esc) this time

Expected result: 
- No change

Actual result:
- A JS error is thrown: _Uncaught Error: TrackJS Caught: Cannot read property 'substr' of undefined_

Seems to be because the upload model is not reset properly on the cancel, error thrown because [file name is not available in the upload model's _validate method](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_common/background_importer/upload_model.js#L94)

### PR DESCRIPTION
**Pull request by xavijam**
Basically, when a file didn't select (unselected in this case, because before this action, user selected a file) any item, it failed because we didn't check if files Array was empty or not. 

Fixes #3379

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3520/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3610/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3615/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3620/))

**Comment by saleiva** [comment]
buuu

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3654/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3656/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3660/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3661/))

**Comment by xavijam** [comment]
@javierarce could you have a look? Bug fixed + missing tests in the import-data process.

**Comment by javierarce** [comment]
:+1: :dancers:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3680/))

**Pull request merged**
