### PR TITLE
Revert removing public_map_deps files

### PR DESCRIPTION
**Pull request by elenatorro**
Related issue https://github.com/CartoDB/support/issues/2048

Context
===

This issue has been solved by adding the `public_map_deps` that was removed when cleaning the dashboard dependencies. I haven't seen any other missing dependencies in these files.

Screenshot 2019-05-13 at 11 29 30

Acceptance
===

* Login: https://2048publiceditor.carto-staging.com (`2048publiceditor`)
* Create map
* Publish map
* Access to published map public link
* Open the console and check it's requesting the required files and rendering properly

### CODE REVIEW

**Comment by oriolbx** [comment]
@elenatorro I'm still getting the error when I open the public_map: https://2048publicmap.carto-staging.com/viz/c5659cbf-d178-465c-928f-28ed09554689/public_map

Screenshot 2019-05-13 at 12 07 25


However, it doesn't happen when I open the embed map: https://2048publicmap.carto-staging.com/viz/c5659cbf-d178-465c-928f-28ed09554689/embed_map

**Comment by elenatorro** [comment]
I see! it seems it's still not working when the user is not logged in. Checking that!

**Comment by jesusbotella** [comment]
I don't know why it works in one page and not in the other one. It shouldn't work in either of those.

The 403 error comes from S3 and that's because you didn't changed editor assets version, thus the new (or old :joy:) file is not generated because editor assets are not being generated.

**Comment by elenatorro** [comment]
Yes! I had the first thought when looking at the screenshot, it's now deployed again 👍

**Pull request merged**
