### PR TITLE
fix #12508

### LINKED ISSUE #12508: set_org_config in connectors_api task does not work
### Context

Trying to enable a connector for an organization.

### Steps to Reproduce

```
cd /opt/carto/builder/embedded/cartodb
RAILS_ENV=production RAILS_CONFIG_BASE_PATH=/data/production/config/builder bundle exec rake cartodb:connectors:set_org_config[bigquery,organization,true,1000000]
```

### Current Result

```
** Invoke cartodb:connectors:set_org_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute cartodb:connectors:set_org_config
rake aborted!
undefined local variable or method `user' for main:Object
/opt/carto/builder/embedded/cartodb-bq-connector/lib/tasks/connectors_api.rake:54:in `with_provider_org_config'
/opt/carto/builder/embedded/cartodb-bq-connector/lib/tasks/connectors_api.rake:155:in `block (3 levels) in <top (required)>'
```

### Additional info

I'm providing a PR for this (in a few minutes)

### PR DESCRIPTION
**Pull request by alrocar**
There was a minor bug in the `set_org_admin` task in the `connectors_api.rake` file.

### CODE REVIEW

**Comment by xavijam** [comment]
@CartoDB/builder-backend ^^^

**Comment by xavijam** [comment]
@alrocar, please, ping whatever you consider in the PRs, if not nobody will be aware.

**Comment by juanignaciosl** [comment]
Moved to CR at our kanban, we can take care of this from now on if you want, @alrocar . Thank you, @xavijam !

**Comment by javitonino** [comment]
Merged & deployed

**Comment by alrocar** [comment]
Thanks guys!

**Pull request merged**
