### PR TITLE
Fix signup with multiple active invitations

### PR DESCRIPTION
**Pull request by gonzaloriestra**
Closes https://github.com/CartoDB/cartodb/issues/12995

### CODE REVIEW

**Comment by alrocar** [comment]
@gonzaloriestra look like CI didn't run, could you take a look, please?

**Comment by gonzaloriestra** [comment]
It ran successfully with the first commit. As the second one only changed the news file, it was skipped. So everything is fine :heavy_check_mark:

**Comment by alrocar** [comment]
Assigning @amiedes for acceptance and deployment.

It might sound familiar to you 👅

**Comment by amiedes** [comment]
Acceptance OK, waiting for CI to deploy.

**Pull request merged**
