### PR TITLE
Fix analysis quota view leak

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes a leak related to the quota analysis view. In some scenarios, we found the analysis-control-view is not properly removed when the parent view was removed. This could cause an inconsistent state of this view when the analysis finishes or fails. Basically, it gets stuck in the fetching state.

### Context

In analyses-view.js we have [a bind](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-view.js#L129) for when the analysis form collection is reset or an analysis is removed. When an analysis is done, [the source changes](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/layer-content-analyses-view.js#L123), so we [reset the analysis form collection](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/layer-content-analyses-view.js#L203) with the new data. This follows [a complete render of the parent view](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-view.js#L132-L153). But the thread in the actual view is not finished, so when it get back to [this point](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/layer-content-analyses-view.js#L204) the former view is rendered again, this time in memory because it was removed from the DOM when the parent view was re-rendered, but still listening and rendering subviews.

### CODE REVIEW

**Comment by nobuti** [comment]
As far as I know, no news needed.

**Comment by xavijam** [comment]
Tested in staging and working like a charm

**Comment by xavijam** [comment]
When green, I'll merge it 💃 . Good catch man!

**Comment by xavijam** [comment]
Frontend passing, merging 💃 .

**Pull request merged**
