### PR TITLE
Allow selecting numeric columns in the source_column select view

### LINKED ISSUE #9647: Source column in the line-to-source analysis should let selecting numeric columns
From: https://github.com/CartoDB/camshaft/issues/185

### PR DESCRIPTION
**Pull request by javierarce**
This PR:

- Fixes the `line-to-source` analysis to allow selecting numeric columns in the source column.
- Fixes the title of the `target` param from`Target column` to `Target` 

Closes #9647

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @dgaubert

**Comment by javierarce** [comment]
CR: @nobuti

**Comment by nobuti** [comment]
👍

**Comment by dgaubert** [comment]
late, but: 👍

**Pull request merged**
