### PR TITLE
Use transaction with timeout instead of DB direct connection in lat/long table geocoding

### PR DESCRIPTION
**Pull request by iriberri**
From what is being discussed at: https://github.com/CartoDB/cartodb/issues/7047

cc @rafatower

### CODE REVIEW

**Comment by rafatower** [comment]
That call should never be made synchronously from the editor, this will be a workaround for it. I was positive there was already an issue for editor to change it. But I seem unable to find it.

**Comment by iriberri** [comment]
I don't remember an issue like that either, but if you haven't created yet I can go for it.

**Comment by iriberri** [comment]
This just passed CI so I'm deploying asap.

**Comment by rafatower** [comment]
:+1:

**Comment by iriberri** [comment]
retest this please

**Pull request merged**
