### PR TITLE
Fix for annotation save issue

### PR DESCRIPTION
**Pull request by javierarce**
This PR fixes an issue with annotations text not being saved.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2936/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2937/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2947/))

**Comment by javierarce** [comment]
@xavijam || @viddo: can you review this, please?

**Comment by viddo** [comment]
LGTM :+1:

**Pull request merged**
