### PR TITLE
Fill: hide value

### PR DESCRIPTION
**Pull request by matallo**
make fill components options not required when hide value, as explained in https://github.com/CartoDB/cartodb/pull/7722#issuecomment-224697176

CR @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
:+1:, test is worthy @javierarce?

**Comment by javierarce** [comment]
I can take care of the spec in another ticket if you are in a rush.

**Comment by xavijam** [comment]
@javierarce: fine by me, because right now some fill components are not working in the styles.
@matallo, could you check linting problems 🙏 ?

**Comment by matallo** [comment]
not lint but npm erroring, launched again anyway 😞

**Comment by matallo** [comment]
💚

**Comment by xavijam** [comment]
Green light, green life.

**Pull request merged**
