### PR TITLE
Capture 4XX error exceptions

### PR DESCRIPTION
**Pull request by javierarce**
- Adds a try catch block to capture the exceptions caused by the image request.

### CODE REVIEW

**Comment by javisantana** [comment]
what exception is throwing? I'm curious about this because a 400 should be captured by onerror. Maybe is because is cached?

**Comment by javierarce** [comment]
403. And the problem is that they block other requests.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1637/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1680/))

**Comment by javisantana** [comment]
:es: please, update news if needed and merge

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1692/))

**Pull request merged**
