### PR TITLE
updated extension to 0.8.2

### PR DESCRIPTION
**Pull request by javisantana**

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5409/))

**Comment by javisantana** [comment]
retest this please

**Comment by javisantana** [comment]
restest this please

**Comment by javisantana** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5427/))

**Pull request merged**
