### PR TITLE
Make users_controller works with new account and profile page

### LINKED ISSUE #2545: Make users_controller works with new account and profile page
In branch user-account please

- [x] Split organization and standard user controllers.
- [x] Send errors when account update fails
- [x] Make it work for standard and organization users
- [x] Send flash notifications when needed
- [ ] Add Google+ auth.

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #2545

### CODE REVIEW

**Comment by Kartones** [comment]
Was just a test commit from home to see if SSH etc. works from home :P

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2034/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2036/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2037/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2039/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2041/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2053/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2055/))

**Pull request merged**
