### PR TITLE
Adding metric for checking node management

### PR DESCRIPTION
**Pull request by xavijam**
Related ticket: https://github.com/CartoDB/cartodb-management/issues/4986

cc @CartoDB/frontend @CartoDB/builder-backend

### CODE REVIEW

**Comment by javitonino** [comment]
I think this will need backend changes, because Guido was a troll and we validate that events exist, right?

**Comment by xavijam** [comment]
I remembered something like that and that's what I wanted your opinion 💃  💋  ❤️

**Comment by juanignaciosl** [comment]
Added to our TODO column, stay tuned.

**Comment by xavijam** [comment]
Great thanks mates!

**Comment by xavijam** [comment]
Just taken into account with FullStory ^^^ 💃 .

**Pull request merged**
