### PR TITLE
Don't stop event propagation when action dialogs are opened

### LINKED ISSUE #2939: Breadcrumbs dialog overlaps "Delete" and "Lock" dialog
**Steps to reproduce:**

- Click on the Breadcrumbs menu.
- Select a map or dataset (whatever you're viewing).
- Click "Lock map" or "Delete map", or "Lock dataset" or "Delete dataset"

**Current behavior:**

- A dialog is open and the breadcrumbs menu overlaps it.

**Expected behavior:**

- Breadcrumbs menu should be hidden when the user selects a map or dataset..

captura de pantalla 2015-03-27 a las 15 56 15

### PR DESCRIPTION
**Pull request by xavijam**
Basically, it could be fixed just preventing map_item and dataset_item click events. But it causes problems with our ```cdb.god``` (:pray:), which if it notices that an event arrives, it fires a ```closeDialogs``` event ([code](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_dashboard/main_view.js#L131)). And finally, that provokes unselect all current selected items ([code](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_dashboard/filters_view.js#L109)).
So, right now, I've found the solution committed easy and painless, what do you think?

cc @viddo @alonsogarciapablo 

It fixes #2939.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2777/))

**Comment by viddo** [comment]
I do not really understand your description.. do I interpret this change correctly that the event should propagate and thus trigger the `closeDialog` event?

**Comment by xavijam** [comment]
In short, we have to prevent and stop dataset and map clicks, if not closeDialogs event will unselect items each time.

**Comment by viddo** [comment]
OK :+1:

**Comment by alonsogarciapablo** [comment]
I'm QAing it in staging.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2788/))

**Comment by alonsogarciapablo** [comment]
I tried locally. I verified it fixes #2939. :+1:

**Pull request merged**
