### PR TITLE
Show labels in the custom choropleth legend

### LINKED ISSUE #11015: Labels not rendered in Pixel aggregated legends
### Context
Custom labels are not rendered in Pixel aggregated legends.

screen shot 2016-12-12 at 15 27 42

 

### Steps to Reproduce

1. Aggregate a layer by Pixel.
2. Edit the legend.
3. Check LEFT LABEL and write something. The label is not written in the legend.
4. Check RIGHT LABEL and write something. The label is not written in the legend.
 

### Additional info
#SMOKE_MG31

cc @luisbosque @xavijam

### PR DESCRIPTION
**Pull request by javierarce**
Closes #11015 

### How to test this

1. Create a map.
2. Select aggregation by pixel.
3. Add a legend.
4. Change the left and right labels.

The labels should appear in the legend.

This fix depends on https://github.com/CartoDB/cartodb.js/pull/1534. Please, make sure you update your javascript dependencies before testing this fix.

legend

### CODE REVIEW

**Comment by javierarce** [comment]
Oh, I didn't know that, but I inadvertently used @nobuti solution to fix the custom choropleth :)

**Comment by javitonino** [comment]
Uhm, this doesn't work correctly in staging for me. The left and right labels do not appear in the legend at all. You can test with user jtorres09u

**Comment by javierarce** [comment]
Have you checked that cartodb.js is updated, right?

**Comment by nobuti** [comment]
Changes in cartodb.js are already shipped. Waiting green and 🚀

**Pull request merged**
