### PR TITLE
Hiding "common data" link if it isn't SaaS

### PR DESCRIPTION
**Pull request by Xatpy**
Ticket [Ref.1958](https://github.com/CartoDB/cartodb/issues/1958) : **common data" link not working in open-source edition, not sure if it
should be disabled**

Assuming that:
SaaS ==> account_host: ‘cartodb.com’ in app_config.yml

Preview:
screen shot 2015-02-26 at 16 44 38

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1973/))

**Comment by lbosque** [comment]
Ey @Xatpy @santisaez @azamorano do you think account_host is the best attribute to check for this?

Since this is related with common data credentials, in my opinion, the best thing to do is checking these attrs exist and are not empty:
common_data:
username: ''
host: ''
api_key: ''

Don't you think?

**Comment by javisantana** [comment]
@Xatpy I'd check what @lbosque proposes, checking common data instead of accout_host

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2080/))

**Comment by Xatpy** [comment]
@javisantana @lbosque I've just changed it. Please, could you check it? Also, should I have to test in staging?(I tested only in local)

**Comment by javisantana** [comment]
too many checks in there, I'd do a helper like "common_data_enabled". Talk with some backend developer

**Comment by Xatpy** [comment]
@javisantana , I talked with @Kartones , and he told about using [this](https://github.com/CartoDB/cartodb/blob/master/app/models/common_data.rb#L86-L88)
Do you think that would be correct (although it isn't using 'host') ?

**Comment by Kartones** [comment]
Disclamer: Out of my ignorance of Common Data. But that method looks as a good candidate.

**Comment by javisantana** [comment]
yes, you need to expose it, not sure how :D

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2088/))

**Comment by Xatpy** [comment]
Retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2092/))

**Comment by Xatpy** [comment]
Closing this PR because it continues in [this 'general' one #2646](https://github.com/CartoDB/cartodb/pull/2646)

**Pull request closed without merging**
