### PR TITLE
Updating deep-insights dependency

### PR DESCRIPTION
**Pull request by xavijam**
In order to release this fix -> https://github.com/CartoDB/deep-insights.js/pull/496
cc @javierarce

### CODE REVIEW

**Comment by xavijam** [comment]
hey @donflopez, there are torque changes, all good?

**Comment by xavijam** [comment]
It is in ded02.

**Comment by donflopez** [comment]
🇪🇸  go!!

**Comment by xavijam** [comment]
Already merged with https://github.com/CartoDB/cartodb/pull/10763#issuecomment-262454298, right @nobuti?

**Comment by xavijam** [comment]
_Checked, yes_

**Comment by nobuti** [comment]
Late but yes.

**Pull request closed without merging**
