### PR TITLE
Removed debug output

### PR DESCRIPTION
**Pull request by juanignaciosl**
@zenitraM could you check this, please? You did it many months ago and I guess it's just debug trace. Thanks!

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1296/))

**Comment by javisantana** [comment]
:es:

**Comment by zenitraM** [comment]
Huh, the email just arrived, sorry I didn't see it before. :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1510/))

**Pull request merged**
