### PR TITLE
10875 increase spec coverage

### PR DESCRIPTION
**Pull request by ivanmalagon**
Implements #10875 

Added missing tests for several objects related to icon markers.

### CODE REVIEW

**Comment by javitonino** [comment]
Does not look like there should be any acceptance for this (it seems there are only tests). Can you confirm @ivanmalagon? Or in case we need acceptance, suggest something to try?

**Comment by ivanmalagon** [comment]
I would just select one marker icon in fill styling from the modal. So instead choosing one from the preview list, pick one from the icons modal. I inserted one check that shouldn't break anything (indeed, it does the contrary).

Being paranoic here but a test doesn't hurt anybody.

**Comment by xavijam** [comment]
Let me accept it :D

**Comment by xavijam** [comment]
Checked in local, working like a charm. Not need to be test it in staging because it is super tiny thing.

**Pull request merged**
