### PR TITLE
Add analysis by dragging a layer on top of another one

### LINKED ISSUE #6924: Integrate analysis creation through drag & drop
- [ ] create a `point-in-polygon` analysis whenever a layer is dragged onto another one.

### PR DESCRIPTION
**Pull request by javierarce**
Closes #6924 

Thsi PR allows adding a `point-in-polygon` analysis by dragging and dropping a layer onto another layer.

analysis_drag_drop

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @viddo 
CC: @xavijam

**Comment by javierarce** [comment]
I need to add a new spec, I'll ping you when I'm done.

**Comment by javierarce** [comment]
Ok, you can review it.

**Comment by viddo** [comment]
:+1:

**Comment by javierarce** [comment]
I'm merging this branch since the frontend tests passed.

**Comment by javierarce** [comment]
Merging this branch, since frontend checks are :green_heart: .

**Pull request merged**
