### PR TITLE
Update dependencies.

### LINKED ISSUE #12571: After selecting pixel style, if you add a time-series widget it adds it like an animated one
In this case we should not "force" to add the widget like an animated one, it should be static.

## Steps to reproduce.
- Create a map with a dataset of points.
- Apply the pixel style over that layer.
- Add a time-series widget

### Current result
- It adds an animated time-series widget.

### Expected result
- It should not add an animated time-series widget.

In case we want a heatmap animated, we have the animated style, with the possibility to animated with heatmap.

*This issue is not related with the aggregations changes.

cc @ivanmalagon

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #12571.

~~This introduces hasAnimationStyle in the layerDefMode in order to create a static timeseries widget for a torque layer. We need some mechanism to choose the widget type for a torque layer, because heatmap (pixel) or animated styles create torque layers.~~ There is already a mechanism, so we use it in DI. This PR get rid of recovering timeseries widgets when not animated, and adds the missing `_invalidateSize` handler.

This relays on https://github.com/CartoDB/deep-insights.js/pull/573.

In order to test it, check if you can reproduce the STR described in the issue's description.

### CODE REVIEW

**Comment by rubenmoya** [comment]
I've found an issue while doing the acceptance:

Steps to reproduce:
- Create a map with a dataset of points
- Apply the pixel style over that layer
- Add a time-series widget
- Apply the animation style over that layer

Current result:
There are two time series, the first one we created is overridden with the one created by the animation style, and it also adds a new one, both of them have the same configuration.

Expected result:
There is only one time series object.

I thought it had nothing to do with this changes (since there is another issue related to this), but it's not happening in production when following the same steps.

**Comment by nobuti** [comment]
Yes, it has to do with some changes I made to clean some old code. My bad.

**Comment by nobuti** [comment]
In an unexpected turn of events, I reverted the `hasAnimationStyle` stuff. I realized that we already had an `animated` attribute in the widget domain. That is what we are using in DI. I've updated the description to explain the changes made in this PR.

**Comment by nobuti** [comment]
Ready for another round.

**Comment by nobuti** [comment]
Indeed, I thought the same.

**Comment by rubenmoya** [comment]
Working as expected, 🚢 it

**Comment by rubenmoya** [comment]
retest this please

**Comment by rubenmoya** [comment]
retest this please

**Pull request merged**
