### PR TITLE
Adds downloaded Ivanovo.zip to importer spec fixtures and changes url to local

### LINKED ISSUE #2469: Remove url path and move the file to local for running properly mapinfo_spec
Here -> https://github.com/CartoDB/cartodb/blame/master/services/importer/spec/acceptance/mapinfo_spec.rb

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #2469

CR @Kartones please! Just two lines :)

### CODE REVIEW

**Comment by Kartones** [comment]
Ok, but what does the file include inside?

**Comment by gfiorav** [comment]
@Kartones the same thing the remote file did. The remote file was hosted in: http://dl.dropboxusercontent.com/u/931536/Ivanovo.zip

**Comment by Kartones** [comment]
Ok, I guess then this list of russian stores is ok :stuck_out_tongue_closed_eyes: 

:+1:

**Comment by gfiorav** [comment]
Haha, one can only guess :laughing:

**Pull request merged**
