### PR TITLE
Dataset upload limit reached modal style fixed

### LINKED ISSUE #9845: Found modals no migrated
### STR
1. Create a zip with 12 csv files (don't add big ones).
2. Import it in CARTO.
3. After a while, a warning message will appear with a SHOW button.
4. Click show button.
5. Modal appears showing any message, but styles are not correct.

cc @ethervoid @piensaenpixel @MariaCheca 

screen shot 2016-09-22 at 11 34 32
screen shot 2016-09-22 at 11 34 25

### PR DESCRIPTION
**Pull request by MariaCheca**
Fixes #9845

screen shot 2016-09-22 at 15 34 44
screen shot 2016-09-22 at 15 49 31

CR @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
And `partial_import_details` file ?

**Comment by MariaCheca** [comment]
Oops! On my way.

**Comment by MariaCheca** [comment]
@xavijam now it's complete! Sorry for forgetting that one.

**Comment by xavijam** [comment]
Great! thanks @MariaCheca, please @ethervoid, we should keep the same design for the new warning modal. If you need help @MariaCheca is your woman.

**Pull request merged**
