### PR TITLE
Add protocol replacer in npm script

### PR DESCRIPTION
**Pull request by ivanmalagon**
This PR forces shrinkwrap to use `https` protocol for packages coming from the npm registry. This will diminish unneeded `npm-shrinkwrap.json` diffs.

It does it through a `sed` command to `update-internal-deps` script that replaces `http://registry.npmjs.org` to `https://registry.npmjs.org` in `resolved:` properties. GitHub URLs keep untouched.

### CODE REVIEW

**Comment by ivanmalagon** [comment]
Good catch.

Going back to development to find an alternative.

**Comment by rochoa** [comment]
What about using an [`.npmrc`](https://docs.npmjs.com/files/npmrc) file to set the registry? I'm not fully sure if that would solve this specific problem, but worthy to try.

**Comment by nobuti** [comment]
Why not a simple node js file?

**Comment by ivanmalagon** [comment]
No need for NEWS.md. This is an internal job.

**Comment by rubenmoya** [comment]
Working as expected :)

**Pull request merged**
