### PR TITLE
Fix cartocss code for categories.

### LINKED ISSUE #10223: Category legend shows values always
It looks like its not being filtered. After using a widget it should show only the categories with data, right?

#SMOKE_MG29

cc/ @nobuti

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #10223.

CR @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
cc @rochoa

**Comment by xavijam** [comment]
And cc @javierarce, just in case he can see any possible error.

**Comment by nobuti** [comment]
https://github.com/CartoDB/cartodb/pull/10237/commits/d1bc1ba644c714018ede9e81dbe66f833e69298c fixes legends for torque categories. Could you take another look @xavijam?

**Comment by javierarce** [comment]
LGTM

**Pull request merged**
