### PR TITLE
Handle non existing vizs with 404 closes #3200

### LINKED ISSUE #3200: Move test suite describe 'non existent visualization'

### PR DESCRIPTION
**Pull request by juanignaciosl**
@rafatower CR this, please.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3026/))

**Comment by rafatower** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3036/))

**Comment by juanignaciosl** [comment]
@rafatower take another look, please, because I've suffered a merge and found a bug.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3050/))

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
