### PR TITLE
Geocoder batch download using http client

### PR DESCRIPTION
**Pull request by rafatower**
What's in there:
- Upgrade typhoeus, mostly for testability (hope not to find major issues)
- Use our http client instead of open3 wget
- Basic error handling (there was none) when downloading results
- Tests

@Kartones and/or @juanignaciosl can you please review? (one of you guys should be enough)

My intent is to release this early in the morning just in case there's any problem with typhoeus.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4815/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4816/))

**Comment by ethervoid** [comment]
Ok for me :)

**Comment by Kartones** [comment]
:+1:  was quick to check

**Pull request merged**
