### PR TITLE
Fix create from scratch

### PR DESCRIPTION
**Pull request by viddo**
This is the quickfix to solve the reported issue w/ creating empty map not working:
- Call correct callback on error in loading view ... https://github.com/CartoDB/cartodb/commit/e4dc5efa020930745e396d1dc56a49f4f5be4df7
- Make sure the vis has the appropriate permission owner … https://github.com/CartoDB/cartodb/commit/7085e7f020d631f807bf6f4b74e5a4d0a6fb387a

Found another issue with the creating empty dataset also failing when reached table quota (not handling the error properly).

The proper fixes for this is more complicated, I'll create separate issues and reference the fix here to explain the situation more in detail.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3557/))

**Comment by viddo** [comment]
retest this please

**Comment by viddo** [comment]
please review @xavijam since you know the create dialog.
clinker fails due to the submodule issue, which got triggered by the version change

**Comment by xavijam** [comment]
go go go!

**Pull request merged**
