### PR TITLE
Join analysis UI revamp

### PR DESCRIPTION
**Pull request by nobuti**
This PR implements #10850.

merge

### CODE REVIEW

**Comment by xavijam** [comment]
I found something in the acceptance, the label of the right-source is not being rendered.

screen shot 2017-05-25 at 14 57 43

**Comment by xavijam** [comment]
Hey @saleiva, what would you do it in this case (using different nodes from same layer)?

screen shot 2017-05-25 at 15 09 02

Would you like something like that?

option 1
screen shot 2017-05-25 at 15 12 26
---
option 2
screen shot 2017-05-25 at 15 14 02

**Comment by saleiva** [comment]
2nd!

**Comment by xavijam** [comment]
_Oido cocina, gracias_

**Pull request merged**
