### PR TITLE
Reset oid in metadata after successful sync fixes #3717

### LINKED ISSUE #3717: Layers disappear when unsyncing a table
S/B: 5269251

Steps to reproduce:
- create a sync table
- after the initial import, force a sync (this changes the OID)
- create a map with a layer using that table
- unsync the table

Expected: everything ok

Actual: the layer using that table disappears.

The problem is that every sync changes the table OID because it actually replaces the old table with a new one under the hood.

The ghost tables are kind of protected against that but when the table loses its condition of "synced tabled" the discrepancy between metadata's OID and the actual table's OID is detected and a delete followed by a register triggered from ghost tables code.

### PR DESCRIPTION
**Pull request by rafatower**
@Kartones  @javisantana please review

Tested locally, if everything's fine will deploy tomorrow morning.

### CODE REVIEW

**Comment by Kartones** [comment]
:+1:  good catch!

**Comment by javisantana** [comment]
you rocks :*

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3792/))

**Comment by rafatower** [comment]
Thanks, buddies! :smile:

**Pull request merged**
