### PR TITLE
Allow tcp_keepalive option in Redis settings

### PR DESCRIPTION
**Pull request by zenitraM**
This involves:
- Bumping Redis and Resque
- Allowing to passing tcp_keepalive option on Redis conf

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1657/))

**Comment by javisantana** [comment]
is this production safe?

**Comment by zenitraM** [comment]
@javisantana I'm testing it. By default it only exposes the tcp_keepalive to be able to enable it on the config, and it is false by default, so it won't change anything on behavior.

The only problems that could arise (that I can think of) come from upgrading resque/redis gem versions.

**Comment by javisantana** [comment]
nice, let merge/deploy it tomorrow morning

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1699/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1728/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1731/))

**Comment by zenitraM** [comment]
hey, quick review please? :angel: @kartones @rafatower

**Comment by Kartones** [comment]
+1

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
