### PR TITLE
Fixed hidden pagination in add dataset listing for IE and Firefox

### LINKED ISSUE #9104: Windows 8 Add Dataset layers error: No Pagination Shown
## Context
A user is unable to add an additional dataset layer to a map visualization if the dataset is not listed on the first page of results from the "add a new layer" screen. The pagination UI does not appear in order to select a dataset not listed on the first page of results.

## STR
Using a Windows 8 machine and either Internet Explorer 11 or Firefox, login to a CARTO account. 

Create a multilayer map visualization. Select to add a second layer: 
screen shot 2016-07-25 at 14 47 37

From the "add a new layer" screen that opens, select to add a new layer from stored datasets, scroll to the bottom of results in order to select a dataset that is on page 2 of the dataset list screen. No pagination UI will show and you will be unable to select a dataset if not on the first page of results:
screen shot 2016-07-25 at 14 29 45

## Expected Result
Currently, a pagination UI interface is shown when the dataset does not appear on the first page of results when using CARTO on the latest Mac OS, Chrome browser:
screen shot 2016-07-22 at 15 29 42

## Current Result
No pagination UI is shown if accessing CARTO account from a Windows 8 machine.

### PR DESCRIPTION
**Pull request by MariaCheca**
Fixes #9104

- Chrome:
screen shot 2016-08-09 at 15 39 54
_Bad news: Chrome shows a bit more margin on the bottom._

- Microsoft Edge (_Microsoft recomended browser_):
screen shot 2016-08-09 at 15 40 34 2

- IE 11:
screen shot 2016-08-09 at 17 18 17 2

- Firefox
screen shot 2016-08-09 at 15 40 52 2

 CR @piensaenpixel cc @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
Which IE is that @MariaCheca ?
Also, firefox under Chrome has been affected?

**Comment by MariaCheca** [comment]
@xavijam IE 11,  and Firefox in OSX was affected too but now it's solved :)

**Comment by xavijam** [comment]
Ok, @piensaenpixel, could you take a look please? it is kind of urgent 💋

**Comment by piensaenpixel** [comment]
go @MariaCheca

**Comment by MariaCheca** [comment]
✨

**Pull request merged**
