### PR TITLE
add favicon, close #3898

### LINKED ISSUE #3898: favicon's not showing up on the sessions page

### PR DESCRIPTION
**Pull request by matallo**
CR @fdansv

(I added an unintended commit on the other PR and closed it, forget about that)

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4071/))

**Comment by fdansv** [comment]
:ship: :it:

**Comment by matallo** [comment]
updated @xavijam

**Comment by xavijam** [comment]
God bless you

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4080/))

**Pull request merged**
