### PR TITLE
13970 disappearing shared map

### PR DESCRIPTION
**Pull request by amartinj**
Closes https://github.com/CartoDB/cartodb/issues/13970

Acceptance:
Aside from checking that this works, check the query and its execution plan.

### CODE REVIEW

**Comment by javitonino** [comment]
:red_circle: tests, some seem like they might be related to this change.

**Comment by juanignaciosl** [comment]
@javitonino for acceptance, I shared 16 datasets. Now I see the 16 datasets... but without paging. Is that expected?

**Comment by javitonino** [comment]
Uhm, no, it shouldn't. Frontend should request with `?per_page=9` and backend should respect that.

**Comment by juanignaciosl** [comment]
@javitonino arg, sorry; at shared section the per_page is 20, I had assumed that it was equal (15). Testing, stay tuned.

**Comment by juanignaciosl** [comment]
:+1:

**Pull request merged**
