### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pablete**
An apt-get update is needed before installing varnish.

Updated postgis references to point to 2.1.7

Update POSTGIS_SQL_PATH

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3338/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3339/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3340/))

**Comment by javisantana** [comment]
thanks @pablete

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3341/))

**Pull request merged**
