### PR TITLE
basemaps: prepare mapbox

### PR DESCRIPTION
**Pull request by matallo**
re: https://github.com/CartoDB/support/issues/1265

this is the kickstart of the changes to the Mapbox basemap modal, where the access token field is removed and just the **Integration URL** is used.

Ideally there's further work to be done, but at this point we're using the integration URL provided. As it is not a straight-forward process, and the url is accessible after several steps menus this should be documented and linked from the modal itself, as in the Assets modal.

screen shot 2018-02-19 at 16 40 23
screen shot 2018-02-19 at 16 41 44

Paging design to join the discussion, the modal is currently working but needs the changes explained above.

/cc @alonsogarciapablo @piensaenpixel

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
:+1:

**Comment by alonsogarciapablo** [comment]
@piensaenpixel perhaps it's worth pointing users to https://www.mapbox.com/help/carto/?

**Comment by piensaenpixel** [comment]
+1 @alonsogarciapablo I open a ticket for it.
Thanks

**Comment by Jesus89** [comment]
One week with no updates.

This is a **hotfix**. I consider we should release this ASAP. What should I do with it?

@alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
Yep, we should get this out of the way.

@piensaenpixel what's the status of https://github.com/CartoDB/design/issues/1239? If that's going to take a while, we can always explain with some text but as @Jesus89 says, we should fix this. Thanks 💋

**Comment by alonsogarciapablo** [comment]
@Jesus89 I talked to @piensaenpixel about this. They will be working on a design to display some help text but let's first release the fix as you mentioned first. We will improve once the design is ready.

**Pull request merged**
