### PR TITLE
Adds delete_column dialog

### PR DESCRIPTION
**Pull request by javierarce**
This PR adds the new delete column dialog:

screen shot 2015-06-16 at 12 53 23

Original ticket: https://github.com/CartoDB/cartodb/issues/4020#event-331856987

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4356/))

**Comment by javierarce** [comment]
@viddo: can you check this PR, please?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4362/))

**Comment by viddo** [comment]
:+1:

**Comment by javierarce** [comment]
Thanks!

**Pull request merged**
