### PR TITLE
Fix user permissions when organization should take preference

### PR DESCRIPTION
**Pull request by matallo**
re: https://github.com/CartoDB/support/issues/808

Perdurable issue that has been around at least since Builder was launched.

When migrating the permission model it took into account the old schema where organization was retrieved from user groups collection. This worked in Editor and Builder, however when retrieving the organization from the user model it only worked in Editor, but not in Builder.

Also, uncommented the specs regarding this. During this task I rephrased a bit the suite where for example didn't make any sense to retrieve the groups from the organization (confirmed with @javitonino) but is only checked for the user.

**acceptance**

- try all the permission combination for user, group, and organization; prevalence order should be organization > group with more permission > group with fewer permission > user
- try both in Editor, and Builder

I'd feel more confident running a smokes through this (this has been brought up several times during smokes testing).

### CODE REVIEW

**Comment by xavijam** [comment]
What is the related ticket @matallo ?

**Comment by matallo** [comment]
updated description :)

**Comment by rjimenezda** [comment]
There seems to be something broken when:

a) Accessing the dataset view
b) Trying to add the shared dataset to a map

```
Uncaught TypeError: e.isNew is not a function
    at R.i._ownAclItem (permission-model.js:218)
    at R.i._organizationAclItem (permission-model.js:232)
    at R.i.<anonymous> (permission-model.js:192)
    at R.i._findMostPrivilegedAclItem (permission-model.js:256)
    at R.i.findRepresentableAclItem (permission-model.js:191)
    at R.i.hasWriteAccess (permission-model.js:101)
    at R.i.render (dataset-item-view.js:48)
    at R.i._addItem (datasets-list-view.js:47)
    at underscore.js:73
```

**Comment by rjimenezda** [comment]
Error is fixed, also tested write access on organization, group and user levels, all seem to behave correctly on Builder. 

Tried on Editor, doesn't seem to be possible to edit, but also not possible on production. @xavijam says it doesn't matter so green light for me.

Good job @matallo 👌 🆒

**Comment by rjimenezda** [comment]
Build failed tho

**Comment by matallo** [comment]
damn linter

**Pull request merged**
