### PR TITLE
Get rid of overviews

### PR DESCRIPTION
**Pull request by dgaubert**

### CODE REVIEW

**Comment by dgaubert** [comment]
Yes, it's totally ok.

I was about to remove `raster_overviews`, luckily I realized that `raster_overviews` has to do nothing with `overviews`.

**Comment by juanignaciosl** [comment]
:+1: then. I'll do the acceptance as well if you want. Suggestions?

**Comment by dgaubert** [comment]
Acceptance: Create a map a with a table that has more than 0.5M points and check that everything is working and slower than `production`.

More advanced acceptance will come with Maps API PR

**Comment by juanignaciosl** [comment]
@dgaubert comparing speeds is very troublesome. What direct verification could be done?

**Comment by juanignaciosl** [comment]
Blocked after a converation with @dgaubert because this is blocked until some user checks are performed.

**Comment by alrocar** [comment]
@dgaubert I'm doing some housekeeping, is this still a thing we should pay attention?

**Comment by dgaubert** [comment]
You can drop out of the project but keep it open. We might have a chance to move this forward in the near future. 🤞

**Comment by gonzaloriestra** [comment]
I'm closing the PR. If someday we want to recover it, we can reopen it (I'm leaving the branch).

**Pull request closed without merging**
