### PR TITLE
Fix change privacy dialog issues

### LINKED ISSUE #2027: Hide write permission when user is changing the visualization privacy options
screen shot 2015-02-02 at 18 29 27

### LINKED ISSUE #2365: When having a map/dataset shared with some users we should show it on the privacy modal
It was designed, right?
Also when not having any user, we shouldn't show the small number as it looks the number of users with access to that item.

screen shot 2015-02-19 at 17 04 35

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2365 (hide the count that can be misinterpreted)
screen shot 2015-02-20 at 18 21 52

---

Fixes #2027 (hide write permissions for maps), i.e.:
For maps only display read toggler:
screen shot 2015-02-20 at 18 13 10

For datasets display both:
screen shot 2015-02-20 at 18 12 58

### CODE REVIEW

**Comment by viddo** [comment]
ok @saleiva ?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1821/))

**Comment by viddo** [comment]
FYI @xavijam

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
