### PR TITLE
Adds "group by" select in the sequential option of the connect with lines analysis

### LINKED ISSUE #9587: Add specs for the connect with lines analysis
Add missing specs for https://github.com/CartoDB/design/issues/105

### LINKED ISSUE #9702: Allow sequential connect with lines analysis to group by
Like it does on the To Source.

cc? @dgaubert

### LINKED ISSUE #9781: Analysis: Connect with lines - Type: Sequential ; feature request, GroupBy
This dataset for example is GPS tracks for WaiveCar, a car sharing service in Santa Monica. The cars each have a unique ID and a datetime stamp. The Connect with Lines tool, type: sequential is awesome. And it'd be really awesome to also allow the ability to connect with lines sequentially, but yet also GroupBy'ed each car's unique id. In this example its just taking any GPS point and connecting the next one with the next closest timestamp (ascending.)

screen shot 2016-09-15 at 7 14 39 pm

### PR DESCRIPTION
**Pull request by javierarce**
Besides allowing to "group by" in the sequential connect with lines analysis, this PR adds specs for that family of analyses.

screen shot 2016-09-20 at 16 32 57

Closes #9702 
Closes #9587 
Closes #9781

screen shot 2016-09-26 at 13 08 57

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam 

@dgaubert: I couldn't check if the analysis works with the new param, but I'm sending the `category_column`, so from the UI point of view it should be ready.

**Comment by xavijam** [comment]
And tests included ❤️ , 🇪🇸 .

**Comment by dgaubert** [comment]
@javierarce that is already implemented from backend side: https://github.com/CartoDB/camshaft/issues/190

**Comment by javierarce** [comment]
Ok, I tested it in staging but it didn't return anything different, so I assumed it wasn't ready. I guess the staging doesn't have the last version.

**Comment by javierarce** [comment]
It looks like after updating the internal dependencies I'm getting an error: `Duplicated dependencies found in npm-shrinkwrap.json`. I'm trying to figure out what's going on.

**Comment by xavijam** [comment]
do you need any help @javierarce?

**Comment by javierarce** [comment]
@xavijam: yes, whenever I try to update the internals, I get this error:

```
############### /!\ CAUTION /!\ #################
Duplicated dependencies found in npm-shrinkwrap.json file.
[
    {
        "name": "torque.js",
        "versions": [
            {
                "version": "git://github.com/cartodb/torque.git#01ffec1a345d06b5333f64ad7ba860ff6a2ee4ba",
                "from": {
                    "cartodb.js": "4.0.0-alpha.1"
                }
            },
            {
                "version": "https://registry.npmjs.org/torque.js/-/torque.js-2.15.1.tgz",
                "from": {
                    "cartodb-ui": "2.15.1"
                }
            }
        ]
    }
]
#################################################
```

**Comment by javierarce** [comment]
I think merging with master will fix the issue now.

**Comment by xavijam** [comment]
Yes, merging with master will do the trick, already fixed that :).

**Comment by javierarce** [comment]
Hound got stuck again, so merging.

**Pull request merged**
