### PR TITLE
disables scrollwhell in embeded maps

### PR DESCRIPTION
**Pull request by javisantana**
does someone can think any situation where the scrollwheel should be enabled in a embed map?

cc @saleiva @andrewxhill @jatorre @CartoDB/frontend

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1822/))

**Comment by jatorre** [comment]
But a no go. This should be disable on the options for it.

**Comment by rochoa** [comment]
Can we make this so it debounces the event? I hate when scrolling on a website and the embed captures the scroll and takes control because I was scrolling the full document. But I have the focus during X ms in the embed probably I like the scroll to take effect in the embed.

Just my two cents.

**Comment by xavijam** [comment]
I hate it too, but we should let people decide what to do with their maps...

**Comment by Ferdev** [comment]
Hey,

We took the decision already. It is to disable it by default. There is an option to enable or disable it on CartoDB, and now is set to enable by default, let's just change it to disable by default and that's it.

**Comment by xavijam** [comment]
:| ferdev?

**Comment by Ferdev** [comment]
No idea why ferdev was cc here!

**Comment by javierarce** [comment]
Who are you?!

**Comment by jatorre** [comment]
I am jatorre!

**Comment by fdansv** [comment]
Ref. https://github.com/CartoDB/blog/issues/176

**Comment by javisantana** [comment]
for me the @rochoa solution is the perfect one but hard to do  (specially for mobile). I will disable it by default

**Comment by javisantana** [comment]
@Kartones review this
@javierarce review frontend code please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1860/))

**Comment by Kartones** [comment]
+1 and thanks for adding me to this weirdly awesome thread :grinning:

**Comment by javierarce** [comment]
:+1:

**Pull request merged**
