### PR TITLE
Stops pecan analysis if the number of rows of the table is > MAX_PECAN_ROWS

### LINKED ISSUE #4320: stop analysis when table has more than N rows
Right now every column is analyzed, if the first analysis arrive and it has more than 7k rows all of them should stop.

Actually table model has a `row_count` attribute which is calculated by rails that can be used to not launch the analysis.

If thing adding a new check here https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/mapview.js#L662 would be enough, lile

```
- if (this.user.featureEnabled('pecan_cookies') && this.user.featureEnabled('new_modals') && this.options.table && this.options.table.data().fetched && this.options.table.data().length > 0) {
+ if (this.user.featureEnabled('pecan_cookies') && this.user.featureEnabled('new_modals') && this.options.table && table.get('row_count') > MAX_PECAN_ROWS) {
 ```

### PR DESCRIPTION
**Pull request by javierarce**

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4748/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4751/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4758/))

**Comment by javierarce** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4763/))

**Pull request merged**
