### PR TITLE
Adds centroid analysis

### LINKED ISSUE #8074: Implement centroid analysis
screen shot 2016-06-22 at 18 56 00

rel: https://github.com/CartoDB/camshaft/issues/77

### PR DESCRIPTION
**Pull request by javierarce**
screen shot 2016-07-01 at 16 37 00
screen shot 2016-07-01 at 16 37 10
screen shot 2016-07-01 at 16 37 21
screen shot 2016-07-01 at 16 37 34

Closes #8074

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @viddo (I merged your #8317-fix-analyses-definitions branch here to use your improvements)

**Comment by viddo** [comment]
👍 
Re: the merge I'll all for it, I'll close the other PR though to avoid confusion, I'll re-tackle the translations in a separate PR again. Thx! 😘

**Comment by saleiva** [comment]
Hey those checkboxes should be on the other side of the labels (like in the style panel with animated properties (for example)

**Comment by saleiva** [comment]
screen shot 2016-07-03 at 01 16 42

Hey @javierarce I've updated a bit the UI design to accommodate the aggregation option. I'd make that always present with COUNT by default (in order to make everything easier). How do you see it?

**Comment by javierarce** [comment]
@xavijam: after having had a look to the forms, I couldn't find a way to do what sergio asks here https://github.com/CartoDB/cartodb/pull/8407#issuecomment-230126551. Any clue how could we put the checkbox in the labels position or does it requires many changes?

**Comment by xavijam** [comment]
No, we agreed another easy way in the styles, using a enabler form component. I encourage you to take a look.

**Comment by javierarce** [comment]
Can we deploy this so the analysis (and an improvement on the analyses organization done by Nicklas)  is available and fix the styles in a later PR?

**Comment by saleiva** [comment]
sure

2016-07-04 11:53 GMT+02:00 Javier Arce <notifications@github.com>:

> Can we deploy this so the analysis (and an improvement on the analyses
> organization done by Nicklas) is available and fix the styles in a later
> PR?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/8407#issuecomment-230252018>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAIENVwucXp8akRZDQ3bx6tsgKAXE54-ks5qSNgHgaJpZM4JDM5V>
> .
>



-- 
Sergio Alvarez Leiva

**Pull request merged**
