### PR TITLE
4041 remove map from the default name of visualizations

### LINKED ISSUE #4041: Remove "Map" from the default name of visualizations
Of course it's a map! :)

screen shot 2015-06-12 at 11 35 57 am

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones take a look at this, more FYI than CR, just in case it's there for a dark, side-effect related reason :-). This closes #4041

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4614/))

**Comment by Kartones** [comment]
mm have you talked this with @saleiva? Because I think was him who made me add this suffix, initially automatically-created visualizations were the same name as the dataset but "was confusing".

For me +1000 with the change :D

**Comment by saleiva** [comment]
I did not!

**Comment by juanignaciosl** [comment]
Ok, don't start blaming each other, I'll merge the change then ;-)

**Pull request merged**
