### PR TITLE
New add custom basemap category for NASA maps

### PR DESCRIPTION
**Pull request by viddo**
screen shot 2015-05-25 at 19 14 57
screen shot 2015-05-25 at 19 15 02
screen shot 2015-05-25 at 19 16 39

- The existing _dates range picker_ (renamed in this PR) was too different to be able to reuse so I added a new one instead for this kind of single-date-picker use-case. Tried to minimize changes on existing styles, so left it as "default" and added modifiers to support the new cases.
- Apart from that, it's just an addition of a small view and (view-)model for the new category really.

@xavijam please review, cc @saleiva for the visual (implemented by looking at the sketch file and current modal behaviour, let me know if something should change)

### CODE REVIEW

**Comment by viddo** [comment]
Deploying on ded06, should be available in ~10 min after this post

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3868/))

**Comment by javisantana** [comment]
is the datepicker implemented using the forms/widgets way ?

**Comment by viddo** [comment]
Not sure what "forms/widgets" means exactly, I based it on the existing date-ranges-picker [(named custom_datepicker.js in master)](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/custom_datepicker.js).

**Comment by javisantana** [comment]
In cartodb the forms are defined by a "json" document (https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/menu_modules/carto_wizard_forms.js#L86)
that is interpreted by a class that generated the view and controls the models
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/old_common/forms/form.js
the datepicker would be the widget for the form so it's ok.

**Comment by viddo** [comment]
Ok, but I'm not sure what it is you want here then. Do you want the date picker to be implemented using this approach? Should all the forms be implemented this way?

**Comment by viddo** [comment]
After talking w/ @xavijam I understand that what you guys want is for a "widget" to be implemented as a standalone view that can be used as a _widget_, e.g. integrated with the forms. Correct? If so, then yes, that's how it currently works so all good, I guess. 

I changed the implementation slightly since your last comment though, it doesn't make sense that the date picker duplicates styles+behavior of a dropdown. I changed that part so the calendar dropdown is an isolated piece using the existing dropdown styles and behavior. See last commit for implementation details.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3894/))

**Comment by viddo** [comment]
friendly bump, any more todo/change before merging?

**Comment by xavijam** [comment]
Widget way -> :dancer: -> :es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3906/))

**Pull request merged**
