### PR TITLE
Add interactivity error infobox

### PR DESCRIPTION
**Pull request by rubenmoya**
Related to: https://github.com/CartoDB/cartodb/issues/13028

This needs some changes to wax and cartodb.js in order to work, but since we're going to remove wax and use a different approach maybe it's better to wait for it to be done.

When cartodb is not hosted:
screen shot 2017-11-02 at 17 30 22

When cartodb is hosted:
screen shot 2017-11-02 at 17 30 42

### CODE REVIEW

**Comment by rubenmoya** [comment]
We need to trigger the `featureError` event in cartodb.js with the new interactivity implementation like we were doing here with wax: this https://github.com/CartoDB/cartodb.js/pull/1799

**Comment by rjimenezda** [comment]
Last thing I remember about the featureError, it triggers very often because of the tile cache. How does it behave here? will the infobox show constantly if the user discards it?

**Comment by rubenmoya** [comment]
I didn't do anything because I was waiting for "the new wax", but we will have to handle it, not sure if a debounce will do it or we'll need anything else. Besides that, the infobox will show with any render, since the error will be in the collection, maybe we have to add some property like `seen:true` and filter it in the `findByType` so it's just shown once.

**Comment by rjimenezda** [comment]
I've made it so when discarding the limits infobox, the notification is removed. This means the user has to trigger another limit error to get it. 

If we don't do this, the infobox is kind of random, any render of the pane would show it again, like when removing a layer.

I think it's good enough to move to acceptance

**Pull request merged**
