### PR TITLE
Monday afternoon uuids party

### PR DESCRIPTION
**Pull request by juanignaciosl**
@rafatower @Kartones will wait for green tests and deploy

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3733/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3734/))

**Comment by Kartones** [comment]
ok your part :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3735/))

**Comment by rafatower** [comment]
ok

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3737/))

**Pull request merged**
