### PR TITLE
Avatar upload image render fixed

### LINKED ISSUE #5424: Improve way we render "upload image" block in user account page
- Before JS is loaded:
screen shot 2015-09-08 at 10 48 39
---
- After JS is loaded:
screen shot 2015-09-08 at 10 48 34

### PR DESCRIPTION
**Pull request by MariaCheca**
Fixes #5424

untitled

CR @xavijam

### CODE REVIEW

**Comment by MariaCheca** [comment]
_ping_

**Comment by xavijam** [comment]
Could you upload a gif to the description?

**Comment by MariaCheca** [comment]
Description updated! I've commited another css fix related to the width of the preview container.

**Comment by xavijam** [comment]
Could we improve it? Let's try to put elements in the same position before and after the JS is applied, please.

**Comment by MariaCheca** [comment]
Sure, I'll work on it.

**Comment by saleiva** [comment]
bump!

**Comment by saleiva** [comment]
bump!

**Comment by MariaCheca** [comment]
retests this, please

**Comment by matallo** [comment]
retest this, please

**Pull request merged**
