### PR TITLE
#4818 fixed formats list for dropbox

### LINKED ISSUE #4818: dropbox connector says you can connect GPX, it's not true
## str

1. go to new map > connectors
1. click on dropbox

screen shot 2015-07-31 at 10 56 18

1. connect dropbox where there's a .gpx file

**expected behaviour:**

gpx file to appear in the list

**actual behaviour**

gpx file won't appear in the list

screen shot 2015-07-31 at 10 57 54

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #4818

### CODE REVIEW

**Comment by Kartones** [comment]
@xavijam CR please

**Comment by xavijam** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5629/))

**Comment by saleiva** [comment]
ping!

**Pull request merged**
