### PR TITLE
Widget controller using WidgetPresenter fixes #6505

### LINKED ISSUE #6505: Widgets API should return JSON at `options`
Currently Widgets API doesn't parse `options` attribute, returning an string. It should return a JSON object instead.

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #6505.

@gfiorav CR this, please.

@viddo , would you merge this into your branch and check, please? I won't merge to master without your :+1:

### CODE REVIEW

**Comment by viddo** [comment]
works like a charm, thx! :ok:

**Comment by gfiorav** [comment]
Looks good to me :+1:

**Comment by viddo** [comment]
:tada: merge pretty please? :kissing_heart:

**Comment by juanignaciosl** [comment]
_at your command_

**Pull request merged**
