### PR TITLE
filter api_keys by type

### LINKED ISSUE #14904: [Professional Plan] Modify API Keys endpoint to add type as parameter
Current API keys endpoint sends a list of all API keys ordered according to type (master, default and regular) and accepts `page` and `per_page` parameters used for pagination in the frontend part.

Since the design team proposal includes a separation of the API keys in two sections: master and default first and then regular ones (See https://github.com/CartoDB/design/issues/1582), it would be very useful to **add a new parameter to the endpoint to ask for API keys depending on type.**

(*Note: We need to get the list for more than one type combined. i.e: [`master`, `default`]*)

### PR DESCRIPTION
**Pull request by alrocar**
Closes #14904

### CODE REVIEW

**Comment by alrocar** [comment]
retest this please

**Comment by alrocar** [comment]
retest this please

**Comment by lekum** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by csubira** [comment]
Acceptance done following the next steps after deploying branch in staging:

#### Check endpoint `/api/v3/api_keys` (Initially default params `per_page=5` `page=1`):
- [ ] Pass 1 type parameter `type=master` -> Check returns 200 and list with master API Keys.
- [ ] Pass 2 type parameters `type=default,regular`-> Check returns 200 and list with default and regular API Keys
- [ ] Pass wrong parameter `type=brgl` -> Check returns 400 and error
Screen Shot 2019-05-24 at 15 45 09

- [ ] Not passing any type parameter -> Check returns 200 and list with all API keys


#### Rebase frontend branch `2473-api-keys-page` and check that new implementation of API keys page works properly with the new endpoint:
- [ ] Section with Master and default API Keys -> Makes request to API with `type=master,default`, gets 200 and shows master and default API keys properly in page
- [ ] Section with Regular  -> Makes request to API with `type=regular`, gets 200 and shows regular default API keys properly in page
- [ ] Create new API key in regular section -> Gets 200 and adds new API key to regular list section in page
- [ ] Create more than 5 regular API Keys (to test pagination) -> Adds proper pagination to regular list section and change page works correctly.

Acceptance 🆗 !

**Comment by alrocar** [comment]
Thanks! I'll merge first thing on Monday.

**Comment by alonsogarciapablo** [comment]
👏👏👏

**Pull request merged**
