### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by nerik**
To comply with 
https://docs.npmjs.com/files/package.json#license

### CODE REVIEW

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by xavijam** [comment]
hey @nerik, thanks for the change, and sorry for the delay, let me merge it when travis tests pased.

**Pull request merged**
