### PR TITLE
Fix namedplaces tests #3024

### PR DESCRIPTION
**Pull request by rafatower**
@Kartones CR please

Note the gem is only added for tests (`group :test`)

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3263/))

**Comment by Kartones** [comment]
:+1: but can't add much here...

**Comment by rafatower** [comment]
retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3266/))

**Pull request merged**
