### PR TITLE
Rename cartodb3 to builder

### PR DESCRIPTION
**Pull request by elenatorro**
💖 Let's call a builder a builder 💖
captura de pantalla 2018-02-16 a las 16 17 16

### CODE REVIEW

**Comment by ivanmalagon** [comment]
Summoning @AleGoiko to take a look on how this can affect BCG.

**Comment by rjimenezda** [comment]
If the bundling works, the renames should all be fine

**Comment by AleGoiko** [comment]
lookin' good! and so very needed too :relaxed:

**Comment by elenatorro** [comment]
retest this please

**Comment by elenatorro** [comment]
Closing in favor of #13598

**Pull request closed without merging**
