### PR TITLE
4033 consistent remaining geocoding quota

### PR DESCRIPTION
**Pull request by rafatower**
Someone from @CartoDB/backend please review

### CODE REVIEW

**Comment by rafatower** [comment]
cc/ @viddo

**Comment by viddo** [comment]
:kiss:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4844/))

**Comment by Kartones** [comment]
:+1:

**Pull request merged**
