### PR TITLE
6427-Widgets_API migration. PR: #6439

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Ethervoid CR this, please. This is the migration for #6439. It's been CR'd by @gfiorav , so I won't request another CR, but you might want to take a look.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by ethervoid** [comment]
Great I'll take a look to it. Thx

**Comment by ethervoid** [comment]
:+1:

**Comment by juanignaciosl** [comment]
Retest this, please.

**Pull request merged**
