### PR TITLE
Fixes importing mapbox basemaps

### PR DESCRIPTION
**Pull request by javierarce**
### Changes:

- supports the v4 version of the Mapbox basemaps.
- adds a [new input field](https://github.com/CartoDB/cartodb/blob/1969-mapboxid/lib/assets/javascripts/cartodb/table/views/basemap/basemap_chooser_mapbox_pane.jst.ejs) for the required Mapbox access token
- changes the [capitalization of Mapbox](https://github.com/CartoDB/cartodb/commit/f34fcf22391948809df5b91eae0f6bfcbb9074bd) (from MapBox to Mapbox).
- updates [specs](https://github.com/CartoDB/cartodb/blob/1969-mapboxid/lib/assets/test/spec/cartodb/table/basemap_chooser_dialog.spec.js).

### Release

Ping @rochoa before releasing this feature, since it would be nice to have support for Mapbox URLs in the static map system.

### Design

screen shot 2015-02-11 at 18 57 08

screen shot 2015-02-11 at 18 56 59

Edit: I've also changed the capitalization of the "Access Token" text in the input placeholder.

Please, review it: @CartoDB/frontend & @CartoDB/design.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1535/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1536/))

**Comment by saleiva** [comment]
+1

**Comment by javierarce** [comment]
@CartoDB/frontend: I need you to look at this PR. Thanks!

**Comment by javisantana** [comment]
:ES: please, update news if needed and merge

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1695/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1720/))

**Pull request merged**
