### PR TITLE
Fixed typo in usage

### PR DESCRIPTION
**Pull request by azamorano**

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1537/))

**Comment by javisantana** [comment]
:es:

**Comment by javisantana** [comment]
@azamorano ping someone to review when you do the PR

**Comment by azamorano** [comment]
This was just a typo fix in the usage text from a previous PR where I mentioned some people but will do in the future even for small thing like this one. Thanks!!

**Pull request merged**
