### PR TITLE
Filter legacy remote visualizations

### LINKED ISSUE #5097: When an external_source has been used, can't be deleted
If a user has used an external_source to import a dataset, a row in `external_data_imports` is created. When we want to update the remote visualizations and external sources, if there are rows that isn't going to appear anymore we remove them but it they are linked by a row in `external_data_imports` its impossible to remove.

The best solution is to remove them logically

### PR DESCRIPTION
**Pull request by ethervoid**
Closes #5097

### CODE REVIEW

**Comment by ethervoid** [comment]
retest this please

**Comment by ethervoid** [comment]
retest this please

**Comment by ethervoid** [comment]
Please @Kartones check this PR

**Comment by Kartones** [comment]
+1

**Pull request merged**
