### PR TITLE
Basemaps urls

### PR DESCRIPTION
**Pull request by javitonino**
See CartoDB/cartodb#12845 CartoDB/cartodb/issues/13458

Best summary: https://github.com/CartoDB/cartodb/issues/12845#issuecomment-369961074

This does several things:
- Removes `url` parameter from basemaps. It was duplicated from with `urlTemplate` and only used in a couple of places (frontend)
- Add support for 2x (hdpi) basemaps
- Change some basemaps default config

**Note:** to be merged along with https://github.com/CartoDB/cartodb.js/pull/2065

## Acceptance steps:

* [ ] Editor: 
 *  user:  `basemaps-urls-editor`
  *Note:* retina basemaps are not enabled in editor, but we have to check that creating / importing a map does not break.
  - [ ] Change basemap for a dataset
  - [ ] Change basemap for a map
  - [ ] Select custom basemap
  - [ ] Anything you see missing from this list
  - [ ] Image export
* [ ] Builder:
 * user: `basemaps-urls`
  * *important*: use a screen with high resolution.
  * create a new map and go to dashboard
  * [ ] check if it is high resolution (tip: you can check if tile images have `2x.png` format)
  * go to basemap options
  * [ ] change basemap and check if it is high resolution. Test it with all the carto basemaps that have high resolution enabled (the ones that have high resolution are those that have a `urlTemplate2x` field in [app_config.yml.sample]()
 * [ ] check if labels are also rendered in high resolution
 * [ ] Choose a custom basemap
 * [ ] Image export (with/without retina basemap)

**In general: Test everything related to basemaps in editor and builder**

### CODE REVIEW

**Comment by javitonino** [comment]
> As a curiosity, I didn't know our basemaps support other multipliers than 2x (3x, 4x, etc.)

Very cool. The idea of this PR (and friends) is among others, to leave everything prepared to support those if needed. With this change, it should be as easy as adding the new urlTemplate.

**Comment by elenatorro** [comment]
I was going to update the acceptance to provide more steps. But I have a doubt about Editor, why should we test it? I thought this task was only for Builder.

**Comment by elenatorro** [comment]
High resolution:

captura de pantalla 2018-03-19 a las 15 26 51

Normal resolution:

captura de pantalla 2018-03-19 a las 15 28 40

**Comment by javitonino** [comment]
Although the change is only for Builder, the way it's implemented may affect Editor as well.

**Comment by ivanmalagon** [comment]
Spotted this. Exported image don't draw the labels as the ones you see in Builder

exported image
Exported image

image
Builder

**Comment by ivanmalagon** [comment]
Apart from that above, it works like a charm.

**Comment by javitonino** [comment]
This is expected. That export image is generated by windshaft, which doesn't know about the user browser, so it will always generate a low-res version (where labels look a lot worse). That's ok, it's not a part of the retina melon we want to achieve with this.

**Comment by elenatorro** [comment]
🚀

**Pull request merged**
