### PR TITLE
Chrome infowindow tooltip issue on Windows

### LINKED ISSUE #6285: Infowindow "change title labels" issue (updated Chrome in Windows 7)
Chrome version: 47.0.2526.80
SO: Windows 7 (from ModernIE)

In the infowindows tab, when clicking over the "change title labels", Chrome over IE is not showing the textboxes for editing the titles, as it does appropriately in Chrome over OS X. Therefore titles cannot be edited this way.

I have not seen any error in the console, besides a bunch of HTTPS warnings. I have recorded a video showing the process, so that you can see the behaviour (with dev tools open for you to check any possible message) [here](https://dl.dropboxusercontent.com/u/2879308/video-titles.mov). 

- 7594335

### PR DESCRIPTION
**Pull request by MariaCheca**
Fixes #6285 

untitled

CR @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
It happens in Chrome, not in Internet Explorer, doesn't it?

**Comment by xavijam** [comment]
LGTM 🚢  :it:

**Comment by MariaCheca** [comment]
Right, I mixed Windows with Internet Explorer 😅

**Comment by MariaCheca** [comment]
retest this please

**Comment by MariaCheca** [comment]
retest this please

**Comment by MariaCheca** [comment]
✨

**Pull request merged**
