### PR TITLE
Add layer selector shows only 300 tables

### LINKED ISSUE #1922: Add layer selector shows only 300 tables
/cc @saleiva

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #1922

### CODE REVIEW

**Comment by Kartones** [comment]
@xavijam CR please :P

**Comment by Kartones** [comment]
No, removing it defaults to backend one (300 also).

We can discuss if I should remove that hard default-backend-limit, or set it to something greater like 9999. @javisantana ?

**Comment by Kartones** [comment]
retest this please

**Comment by xavijam** [comment]
That 300 special number is getting me nervous...

**Comment by javisantana** [comment]
this is actually a design bug: it does not make any sense to show 300 tables in a combo cc @saleiva

**Pull request merged**
