### PR TITLE
Make all the widgets cards clickable in the Add widgets modal

### PR DESCRIPTION
**Pull request by jesusbotella**
Related to #13134  
----

This PR makes the whole widget cards clickable and adds an outline to the default card state.

I think we should add [these styles](https://github.com/CartoDB/cartodb/pull/13263/files#diff-3732d0053946863527fba6ff36284ccaR29) to a new mixing or common class to include them, instead of repeating all the code as it is used several times. I did not know where to put it, I need some help from @matallo or @rubenmoya (or anyone else) to know which would be the best place to do so.

### Acceptance
1. Try to create a new widget on any map
2. Repeat the following steps for all the widget types (Category, Histogram, Formula, Time-Series)
    2.1. Check that all the cards have the default outline applied
    2.2. Check that the whole widget card is clickable and selects the item successfully

### CODE REVIEW

**Comment by jesusbotella** [comment]
Yes, I saw that they were pretty similar but I wasn't prepared to take that risk alone already 😁.

**Comment by matallo** [comment]
don't worry, let's revisit this in the future!

**Comment by rubenmoya** [comment]
The dropdown to select the layer doesn't work, back to development!

widget_click

**Comment by jesusbotella** [comment]
The `ev` thing is because I saw it in other place and I thought it was the convention in our code, I will change it right away.

Which class would you check in the `.hasClass` method?
The thing is that the event target that I got in the event data was the label inside the button instead of the button itself, so I couldn't check that the button is being clicked, that is why I added that.

**Comment by jesusbotella** [comment]
@matallo I have come up with a much simpler approach (how it should have been in first place) which allows to remove that hard to understand code.

What I did is to listen the click event in the LayerSelectorView and stop its propagation, preventing it to bubble up to the Widget view.

I have checked that LayerSelectorView is only used in CategoryOptionView, HistogramOptionView, FormulaOptionView, and TimeSeriesOptionView, so it wouldn’t lead to unexpected issues in other views of the platform.

I’m going to add a test to ensure that this behaviour is not removed in future feature changes.

**Comment by matallo** [comment]
now I can't select an item in the list 🙈 

screen shot 2017-12-22 at 14 50 10

**Comment by jesusbotella** [comment]
@matallo You can't do it either right now on Builder. I told it to Rubén and we talked about opening an issue, but I completely forgot about it. I'll do right now

**Comment by matallo** [comment]
oooh, I see! my bad then, you're right 😝

**Pull request merged**
