### PR TITLE
Python install help

### PR DESCRIPTION
**Pull request by juanignaciosl**
@javitonino CR this, please.

PS: updating `app/controllers/home_controller.rb` versions, the ones that `/diagnosis` use, from time to time at any random PR would be nice ;-) . Sooner or later I'll do something at a leapfrog that updates it automatically, but until then, if any of us remembers to do it.. cc @CartoDB/backend

### CODE REVIEW

**Comment by javitonino** [comment]
Would be nice to also update the error:
`If this fails due to the installation of the gdal package not finding Python.h, you'll need to do this:`

Maybe:
`If this fails due to the installation of the gdal package not finding a .h file, you'll need to do this:`

Then :ship: it

**Comment by juanignaciosl** [comment]
@javitonino I suggested "... or any other header file".

**Comment by javitonino** [comment]
Sure, looks good :)

**Comment by juanignaciosl** [comment]
@javitonino I've also removed the old user creation. CR?

**Comment by javitonino** [comment]
:+1:

**Pull request merged**
