### PR TITLE
[HOLD] Let ogr2ogr import Excel files (and fallback to CSV if it has multiple sheets)

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones CR this closing #2709, please. @iriberri I'd need QA team to test Excel importing, please let me know when you have an slot.

What to test: Excel files should be imported at least as good as usual. There should be some improvement. For example, importing [this file](http://uat-catalog-fe-data.reisys.com/dataset/public-budget-database-governmental-receipts-1962-current) now detects first row as a header. Other imports should not be affected.

### CODE REVIEW

**Comment by Kartones** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2361/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2367/))

**Comment by saleiva** [comment]
bump!

**Comment by juanignaciosl** [comment]
@saleiva this was waiting for a QA slot.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2551/))

**Comment by juanignaciosl** [comment]
FYI @iriberri found a XLSX file that worked worse than before, so I've constrained this change to XLS files. Makes sens from a ogr2ogr point of view, since it uses different drivers for those formats, this might be because xls header detection is more polished. I'll hand this over to QA to keep testing.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2607/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2609/))

**Pull request closed without merging**
