### PR TITLE
update error pages

### LINKED ISSUE #4428: update 404

### PR DESCRIPTION
**Pull request by matallo**
close #4428

/cc @xavijam @carlostallon

### CODE REVIEW

**Comment by matallo** [comment]
CR @xavijam (tests are passing now)

**Comment by matallo** [comment]
ping!

**Comment by xavijam** [comment]
Could you add a screenshot?

**Comment by xavijam** [comment]
That new version is working properly for the [supported browsers](https://github.com/CartoDB/cartodb#requirements)?

**Comment by matallo** [comment]
plus mobile

screen shot 2016-02-01 at 11 12 37
screen shot 2016-02-01 at 11 15 34
screen shot 2016-02-01 at 11 16 49
screen shot 2016-02-01 at 11 18 10
screen shot 2016-02-01 at 11 21 34
screen shot 2016-02-01 at 11 22 30

**Comment by xavijam** [comment]
Don't we add public links to website sections?

**Comment by xavijam** [comment]
Thanks for the screenshots BTW :).

**Comment by matallo** [comment]
I don't think so, we'd need to add the js libraries, and prefer to direct them to the home then they'll go to wherever they wanted

**Comment by xavijam** [comment]
Ahhhh true. ok, ready to go then :).
Great job :+1:

**Comment by xavijam** [comment]
Oh, last one, how does HTML5 look like?

**Comment by xavijam** [comment]
yay! :+1:

**Pull request merged**
