### PR TITLE
ui-fixes

### PR DESCRIPTION
**Pull request by piensaenpixel**

### CODE REVIEW

**Comment by xavijam** [comment]
Ready to merge?

**Comment by xavijam** [comment]
Fixes #10887.

**Comment by piensaenpixel** [comment]
i want add other ticket @xavijam

**Comment by piensaenpixel** [comment]
@hacheka could you take a look?
Fix - https://github.com/CartoDB/cartodb/issues/10887
Fix - https://github.com/CartoDB/cartodb/issues/10849 sorry @jorgesancha !!!!
Fix - https://github.com/CartoDB/cartodb/issues/10870 cc @alonsogarciapablo 
points2

**Pull request merged**
