### PR TITLE
Clean up dirty body between test cases

### PR DESCRIPTION
**Pull request by viddo**
Related to the fix on the async test yesterday #4091, I noticed that there are tests that leave the document.body in a dirty state, that may affect the expectations that comes in tests after… this PR includes some `afterEach` call to make sure the tests' side-effects are cleaned up.

### CODE REVIEW

**Comment by viddo** [comment]
please review @xavijam 

Ideally we should wipe the document.body between each test, that's not content of the jasmine runner itself but not how to solve it. Ideas?

**Comment by xavijam** [comment]
I'd need some research, arggg.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4424/))

**Comment by viddo** [comment]
retest me please

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4429/))

**Comment by viddo** [comment]
@xavijam finally removed the test case, don't see how we can make it deterministic as it is now. Also, the behavior to hijack the given target is defined in the view inherited from cartodb.js, so I believe this behavior should already be covered by tests there and should not need to be re-tested here anyway. 

Either way, I still think it makes sense [to cleanup the DOM from cruft that were added by prior tests](https://github.com/CartoDB/cartodb/pull/4111/files#diff-95bfab881cddae4ef6d2e083d9c2c0b8R250) to avoid dirty state to affect sequent tests, what do you think?

**Comment by viddo** [comment]
retest this please

**Comment by xavijam** [comment]
We can move that behaviour to the "jasmine config" rules.

**Comment by viddo** [comment]
How?

**Comment by xavijam** [comment]
There is a SpecHelper.js file, could we try there?
```lib/assets/test/spec/SpecHelper.js```

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4432/))

**Comment by viddo** [comment]
screen shot 2015-06-18 at 12 57 28 that's where I added it now, so it's run after each test case.

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4438/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4439/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4440/))

**Pull request merged**
