### PR TITLE
Changed way to set categories with turbo-carto in the Builder

### PR DESCRIPTION
**Pull request by xavijam**
We decided to use all the power of Turbo-carto :tm:, but we realized there are some exceptions described in #10805. So we have taken the conservative decision of setting the categories manually in the generation of the CartoCSS.

screen shot 2016-12-05 at 18 50 08

**What should we test?**

We should style per value over string columns:
- Using different geometries (point, line or polygon datasets).
- Setting the style over columns with less than 10 categories.
- Setting the style over columns with more than 10 categories.
- Setting the style over columns with `null` values.

### CODE REVIEW

**Comment by nobuti** [comment]
Not sure if this is a colateral effect, but now when filtering the legend always shows an `Other` categories, even when there is no other. For example:

screen shot 2016-12-07 at 11 10 16

screen shot 2016-12-07 at 11 10 28

I couldn't spot any other issue, other than that it's working fine. Please let me know if I should deploy it.

**Comment by xavijam** [comment]
Ping @rochoa and/or @dgaubert, because I'm not sure about that.

**Comment by xavijam** [comment]
I've just checked it in production, with the same behaviour (applying a ramp using a color for each category), then filtering and the behaviour is happening too, so it is a current problem. Opening a ticket...

**Comment by xavijam** [comment]
Ticket: https://github.com/CartoDB/Windshaft-cartodb/issues/600
@nobuti in my opinion it is ready to go, bug is present right now in production.

**Comment by nobuti** [comment]
👍  I'll deploy it asap.

**Comment by nobuti** [comment]
Frontend tests passing 🚀

**Comment by saleiva** [comment]
Hi Guys, I don't think that having this legends behaving non dynamically is a good behaviour. I do think legends should be only showing the categories selected. If not they will be quite missleading

**Pull request merged**
