### PR TITLE
Cdb 1956 - hiding "account settings" link if it isn't SaaS

### PR DESCRIPTION
**Pull request by Xatpy**
Ticket [Ref.1956](https://github.com/CartoDB/cartodb/issues/1956) : **CartoDB editor: "account settings" not working in open-source version**

Assuming that:
SaaS ==> account_host: ‘cartodb.com’ in app_config.yml

Previews:

**Before:**
before

**After:**
screen shot 2015-02-27 at 12 55 47

### CODE REVIEW

**Comment by lbosque** [comment]
Ey @Xatpy @santisaez @azamorano do you think account_host is the best attribute to check for this?

Since this is related with common data credentials, in my opinion, the best thing to do is checking these attrs exist and are not empty:
common_data:
  username: ''
  host: ''
  api_key: ''

Don't you think?

This also applies to : 
https://github.com/CartoDB/cartodb/pull/2530/files
https://github.com/CartoDB/cartodb/pull/2508/files

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2050/))

**Comment by javisantana** [comment]
@lbosque I think this is related with central not with common data (the other ones are common data). What is the config to know if a central server is linked?

**Comment by lbosque** [comment]
Sorry, my bad. Moved the comment.

+1 to this PR

**Comment by javisantana** [comment]
but @lbosque I think it's better to check using your method instead of checking for "cartodb.com". In this PR I would disable if the central url is empty but I don't know what config value links a box to central

**Comment by lbosque** [comment]
You are right. It's not necessary to strictly check the value

**Comment by javisantana** [comment]
:es:

**Comment by Xatpy** [comment]
Closing this PR because it continues in [this 'general' one #2646](https://github.com/CartoDB/cartodb/pull/2646)

**Pull request closed without merging**
