### PR TITLE
Fix georeference modal, available geometry cards

### LINKED ISSUE #4262: Geocode fixes
So after test geocode I found a few little things:

- [x] `#666` header icons color and change header copy to `Transform your data into coordinates`: _fixed in #4370_
screen shot 2015-07-07 at 7 04 53 pm

- [x] Update points icon from: _fixed in #4372_
screen shot 2015-07-08 at 11 57 28 am
to this:
screen shot 2015-07-08 at 12 05 07 pm

- [x] Delete Learn more and its tooltip: _fixed in #4372_
screen shot 2015-07-08 at 11 16 46 am

- [x] To unify this type of boxes, we decided to make them one-click, just like Merge tables one behaves. So no confirm button needed.
  -  _fixed in #4372_

- [x] Subheader to go back: _fixed in #4380_
screen shot 2015-07-02 at 11 40 20 am

- [x]  Fix header tabs distance: _fixed in #4380_
(they are 20px and should be 30px)
screen shot 2015-07-07 at 5 34 04 pm

- [x] As @xavijam mentioned on #4255 here are some enhancements to the dropdown (the "arrow" should be the same):
screen shot 2015-07-02 at 12 11 32 pm

- [x] Header text to options space should be 40px:
This:
screen shot 2015-07-07 at 6 55 15 pm
instead of this:
artboard

 - [x] Spacings between options should be 28px:
screen shot 2015-07-08 at 12 32 49 pm
screen shot 2015-07-08 at 12 35 51 pm

- [x] Green icon when you select a column:
screen shot 2015-07-02 at 11 40 59 am

- [x] Thanks to @iriberri for spotting this) On small windows, footer's button does not show.
screen shot 2015-07-07 at 6 59 31 pm

### PR DESCRIPTION
**Pull request by viddo**
from #4262 

- [x] Changed icon
- [x] Changed title (size and color)
- [x] _To unify this type of boxes, we decided to make them one-click, just like Merge tables one behaves. So no confirm button needed._
- [x] Deleted Learn more and its tooltip on the _learn more_.

screen shot 2015-07-09 at 16 56 31
screen shot 2015-07-09 at 11 33 42

@xavijam please review cc @josecruz

### CODE REVIEW

**Comment by xavijam** [comment]
Looks good, but why do we have a georeference_points2.png and not using georeference_points.png? Is it already used?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4830/))

**Comment by viddo** [comment]
Because the old one was not correct apparently, see:
screen shot 2015-07-09 at 11 54 01

@josecruz can probably give more rationale to why

**Comment by xavijam** [comment]
Nah, it is fine, i was curious. But if the old one was not ok, why not delete it? Or the old one belongs to the old old geocoding dialog?

**Comment by viddo** [comment]
It's used by the old modal still, added it to the list to be removed later.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4841/))

**Comment by viddo** [comment]
@xavijam please re-check (found more stuff in the issue that was related to these cards so fixed them while at it

**Comment by xavijam** [comment]
Go!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4845/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4849/))

**Pull request merged**
