### PR TITLE
Fix public pages description

### LINKED ISSUE #2985: Longer descriptions seem to break the Profile html
screen shot 2015-04-01 at 10 05 41 am

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2985 
screen shot 2015-04-01 at 16 15 24

Also fixed the geocoder modal tab pane title while at it (#2985):
screen shot 2015-04-01 at 16 31 26

### CODE REVIEW

**Comment by xavijam** [comment]
:es:

**Comment by xavijam** [comment]
Go go go

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2735/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2736/))

**Pull request merged**
