### PR TITLE
Several fixes for new create dialog

### PR DESCRIPTION
**Pull request by xavijam**
- New paginator added for create dialog as well.
- Extra elements showing up when importing (#2554).
- Breadcrumb on create map modal (#2355).

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2018/))

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2020/))

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2021/))

**Pull request merged**
