### PR TITLE
Use new modal for confirm dataset rename on editor

### PR DESCRIPTION
**Pull request by viddo**
Replaces the existing confirmation modal:
screen shot 2015-05-12 at 12 45 35
With:
confirm-rename

### CODE REVIEW

**Comment by viddo** [comment]
Not completely done, created PR to get early feedback @saleiva @javierarce I have some questions

1. Is the text OK? Used what already existed, let me know what you want instead.
1. From notes from a week or two an "interrogation" glyph is supposed to be used as icon, do you have one prepared? :)
1. This modal can be be opened in two use-cases, either through the inline-edit (like in the gif above) or through "edit metadata". Considering this modal will be changed later and the post-save feedback still has the small thing "Saving.." label in the mid-top I think it's better to skip the typical full "Saving…" modal until we refactor the edit-metadata part. Ok with you?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3645/))

**Comment by javierarce** [comment]
I propose this shorter version that also reduces the repetition of 'name':

> Renaming dataset will affect your API calls
> If you are accessing this dataset via API don't forget to use the new name in your API calls afterwards.

current text: 

> Renaming dataset will affect your API calls
> If you are accessing your dataset via API don't forget to update the name in the API calls after changing the name

**Comment by viddo** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3647/))

**Comment by saleiva** [comment]
colors are a bit weird. Can we use the orange that we use on the small "geo" tag on the table??

**Comment by viddo** [comment]
Sure, I used this color because it was the one defined for "alert' color, and already used in [other places](https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=%24cHighlight-alert&type=Code), so if you find this color weird you might want to revisit those too. :)

**Comment by viddo** [comment]
ok? screen shot 2015-05-13 at 10 03 54

**Comment by viddo** [comment]
@javierarce I'm done so please code review too

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3650/))

**Comment by javierarce** [comment]
:+1:

**Comment by viddo** [comment]
Added an icon using, based on Lato bold: screen shot 2015-05-13 at 11 04 57

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3655/))

**Comment by saleiva** [comment]
awesome!

**Pull request merged**
