### PR TITLE
Editor backend refactor url

### PR DESCRIPTION
**Pull request by javisantana**
cc @rafatower

### CODE REVIEW

**Comment by rafatower** [comment]
Looks good to me but there are some failing tests

**Comment by rafatower** [comment]
retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2926/))

**Comment by javisantana** [comment]
@rafatower passed!

**Pull request merged**
