### PR TITLE
If layer is hidden, don't reset autoStyle.

### LINKED ISSUE #11137: Don't show auto-style button on widgets connected to hidden layers
### Steps to Reproduce
1. Create a map with 2 layers and add some widgets for some columns of both layers (as you can see in the [Attached .CARTO](https://github.com/CartoDB/cartodb/files/674180/Madrid.Airbnb.Listings.ct.on.2016-12-27.at.13.37.43.carto.zip) sometimes it makes sense)
2. Click on the auto-style button for one of the layers

### Current Result
Nothing happens - as it should be - but from the UX perspective is missleading

### Expected result
Auto-style button should be hidden on those widgets that are attached to a hidden layer

### PR DESCRIPTION
**Pull request by nobuti**
This PR implements #11137. It depends on https://github.com/CartoDB/deep-insights.js/pull/509.

Basically, we are adding an option to reset `autoStyle` when saving, in order to preserve the autoStyle when hidden/showing a layer. Also, with the changes in deep-insights, the autoStyle button is hidden if the layer is hidden.

### CODE REVIEW

**Comment by ivanmalagon** [comment]
Passed acceptance in DED02.

Can't deploy until CartoDB/deep-insights.js#509 is in production.

**Comment by xavijam** [comment]
Everything updated @ivanmalagon

**Comment by xavijam** [comment]
And it is being deployed to ded04

**Comment by xavijam** [comment]
I've just noticed that, if user hides the layer with the layers options (being inside the layer content), it removes the autostyle state.

**Comment by xavijam** [comment]
_Back to development again_

**Comment by xavijam** [comment]
For the next reviewer:

- We should check that it works as expected everywhere, it means, we should check that layer toggle works in any panel (legends, data, style, popup, analyses...).
- Check that when one layer is hidden or displayed, infobox with that info should appear or hide.

**Comment by xavijam** [comment]
The person in charge of the task of resolve conflicts of this PR, please, let me know before doing the task 💋 .

**Comment by matallo** [comment]
I like the approach, no comments on that, resolved conflicts myself 👍

**Comment by xavijam** [comment]
Perfect man 💋  👍 .

**Comment by javitonino** [comment]
Tests are failing after the merge. Can anyone take a look?

**Comment by matallo** [comment]
I'm on it

**Comment by ivanmalagon** [comment]
The last commit was aimed to fix the tests and the tests are passing, so nothing to review there.

Moving it to Acceptance again.

**Comment by xavijam** [comment]
:clap:

**Comment by xavijam** [comment]
So, fixed the problem that @ivanmalagon found in https://github.com/CartoDB/cartodb.js/pull/1563. So, once we merge the thing in v4, we should change package and update dependencies.

**Comment by xavijam** [comment]
Frontend tests passing, merging!

**Comment by nobuti** [comment]
\o/

**Pull request merged**
