### PR TITLE
Removed all references to Lato and Proxima Nova fonts

### LINKED ISSUE #10497: Remove the usage of Lato font to avoid the usage of external fonts
Discussing the load of fonts from outside sources with @xavijam, he told me that we're still using Lato although we're deprecating it.

I'm unsure if this is still an issue. Please feel free to close this ticket if it's already been solved.

### PR DESCRIPTION
**Pull request by xavijam**
Fixing #10497 for the next on-premises release, I've realized that we have several non-used fonts, like Proxima Nova, so I've decided to remove them from our fonts folder + delete the way we used to have to load them with the web-font-loader (cc @matallo) and remove fonts used for IE (what?). 

Included changes in CartoDB.css repository 😱 .

Tested several pages included the old editor and public pages. Also, do you remember @javierarce if we use the Lato font in any other place than the annotations font text?

screen shot 2016-11-21 at 12 46 07
screen shot 2016-11-21 at 12 46 13

CR: @matallo 
cc @piensaenpixel @javierarce 
_Sorry about adding all of you to this loop_

Fixes https://github.com/CartoDB/cartodb-platform/issues/2509.
Fixes #10497.

### CODE REVIEW

**Comment by xavijam** [comment]
Deployed in ded02, by the way.

**Comment by xavijam** [comment]
Hey guys, could you take a look in order to deploy it this morning? Pretty please 💋 .

**Comment by matallo** [comment]
LGTM, the places I remember using it was data library and explore, and it was replaced in both

**Comment by xavijam** [comment]
@javierarce, could you check the question in the description please? 🙏

**Comment by javierarce** [comment]
@xavijam: no, I can't remember other direct uses of the font files except for the annotations.

**Comment by xavijam** [comment]
Merging when travis is green.

**Pull request merged**
