### PR TITLE
Remove lighter font weights on new dashboard

### LINKED ISSUE #2335: Almost unreadable texts
With Linux at least (and I could bet with Windows will be similar), light grey and light green texts are really really hard to read... not sure if because of the combo bright+small or just bright but...

/cc @saleiva Reassign if @carlostallon doesn't knows how to do CSS anymore :trollface:

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2335 

Edit: Changed approach after review:
- Remove lighter font-weight on font-sizes <= 13px
- Apply special text-rendering overrides for smaller fonts to not have such a bold look.

New screenshots:
screen shot 2015-02-27 at 12 59 54
screen shot 2015-02-27 at 13 08 46
screen shot 2015-02-27 at 15 03 33
screen shot 2015-02-27 at 15 04 41
screen shot 2015-02-27 at 15 18 36
screen shot 2015-02-27 at 15 31 01
screen shot 2015-02-27 at 15 36 01

### CODE REVIEW

**Comment by viddo** [comment]
@carlostallon @xavijam @saleiva as instructed in the issue I've removed the lighter fonts. I'd suggest we do a deploy on staging (none available yet) to really check if this solves it. Thoughts?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1950/))

**Comment by xavijam** [comment]
It is a pity we have to "remove" it, but if some browsers don't render properly, this is the best solution.

**Comment by viddo** [comment]
bump, any feedback on this please?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1983/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1987/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1988/))

**Comment by saleiva** [comment]
Not the same, but... let's go with it :)

**Comment by piensaenpixel** [comment]
If we remove the lighter fonts, may be we could try use this property of css
text-rendering: optimizeLegibility;

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1992/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1998/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1999/))

**Comment by viddo** [comment]
@saleiva @piensaenpixel @xavijam changes based on feedback, see PR desc for screenshots. also deployed on staging (ded02) if you want to have a look yourself cc @Kartones

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2000/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2001/))

**Comment by viddo** [comment]
Screenshot from kartones with the new changes:
image

OK?

**Comment by xavijam** [comment]
:jp:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2013/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2014/))

**Pull request merged**
