### PR TITLE
Adds capability of switching back to marker from icon

### LINKED ISSUE #2668: Add button in wizards to remove an IMG icon once selected
From: https://github.com/CartoDB/cartodb/issues/2198

Once you select an icon in a wizard, you cannot get rid of it. Of course, you can edit CartoCSS but this is not user friendly :-)

### PR DESCRIPTION
**Pull request by fdansv**
Fixes #2668 

At the moment, in the simple point wizard, when changing the marker style so that it displays an icon instead of the elliptical marker, it's not possible to switch back to the default markers unless we tweak the stylesheet. This switches back to ellipses when selecting a colour.

@javisantana @iriberri

### CODE REVIEW

**Comment by saleiva** [comment]
:_)

**Comment by javisantana** [comment]
does this work in the same way category works?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3833/))

**Comment by fdansv** [comment]
@javisantana https://github.com/CartoDB/cartodb/issues/2668#issuecomment-104622959

**Comment by iriberri** [comment]
Like it!

**Comment by fdansv** [comment]
do not merge, adding test

**Comment by javisantana** [comment]
The thing is: you added it to a common place for all the wizards, so is it still needed to do for category? how category does it?

**Comment by fdansv** [comment]
This doesn't affect category. Category uses an extra view called ```cdb.admin.mod.CategoryWizard.CategoriesViewItem``` for every category, so marker styling is handled independently.

**Comment by javisantana** [comment]
ok, nice

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3855/))

**Pull request merged**
