### PR TITLE
Setup builder_enabled feature if environment BUILDER_ENABLED variable is set

### PR DESCRIPTION
**Pull request by santisaez**
It will set the `builder_enabled` attribute if the `BUILDER_ENABLED` environment variable is `true`.

I have tested and it works, but if I create a new user in the organization it doesn't work.

@javitonino can you review?

### CODE REVIEW

**Comment by javitonino** [comment]
I have been reading the linked ticket. Some thoughts:

 - We are going to change the default of builder_enabled to true before the onpremises freeze. So this change will not be too useful. Maybe we can improve this by allowing to force editor (disable builder_enabled) as well?
 - For organization users, they are created as builder_enabled = nil by default ([here](https://github.com/CartoDB/cartodb/blob/d50784b4b395d0e56ca5379bfe0286e634193195/app/models/user.rb#L235)). We should change the organization creation tasks in order to be able to set builder to true/false. This will also be changed to default to true soon.

I'd like to know why the change of plans to modify the tasks instead of just relying on the DB default.

**Comment by rporres** [comment]
@javitonino: We don't want to depend on a change that is getting delayed.

As an aside note, it could be also interesting to be able to use this rake to create editor users in the near future.

**Comment by luisbosque** [comment]
AFAIK and after a discussion with @juanignaciosl enabling the builder by default is something that will happen through the price plans in central. This means that a onpremise will still have the editor by default. Am I wrong?

**Comment by santisaez** [comment]
I have made a small change to support `builder_enabled` management also on organizations.

**Comment by javitonino** [comment]
:+1: this should work. I think it would be nice to have the possibility to also force the editor, but don't know if it would ever be used.

**Pull request merged**
