### PR TITLE
2407 fix vizjson caching in redis

### PR DESCRIPTION
**Pull request by rafatower**
@Kartones CR please

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1943/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1944/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1945/))

**Comment by javisantana** [comment]
did you test in staging the privacy problem?

**Comment by rafatower** [comment]
I tested locally, I have to fix some tests anyways. I'll do it tomorrow

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1946/))

**Comment by Kartones** [comment]
+1  I can help you test at staging if you want

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1960/))

**Pull request merged**
