### PR TITLE
Upgrade to cartodb-postgresql extension version 0.7.0

### PR DESCRIPTION
**Pull request by rochoa**

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1873/))

**Comment by rochoa** [comment]
This is failing due the changes in https://github.com/CartoDB/cartodb-postgresql/commit/0d5a1c3e499ac18f57ebade9b1869aa36d3df0c6

There is a test that has query that makes it to return an empty resultset.

**Comment by rochoa** [comment]
This is the problematic line: https://github.com/CartoDB/cartodb/blob/master/lib/cartodb/sql_parser.rb#L15

**Comment by rochoa** [comment]
@javisantana As we have discussed I'm proceeding to remove exceptions in Layer.affected_tables so there is no option to create a layer with invalid queries (cannot explain, does not exist, syntax error).

cc @Kartones

**Comment by javisantana** [comment]
nice, a step forwards

**Comment by Kartones** [comment]
Fine by me

**Comment by rochoa** [comment]
I would like to **validate** the affected tables before saving the layer, however we need a user to retrieve the affected tables and the user is not available until the layer is created because it relies on the user associated to its map (:many_to_many): https://github.com/CartoDB/cartodb/blob/master/app/models/layer.rb#L194-L200

@Kartones do you envision any alternative here?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1877/))

**Comment by rochoa** [comment]
Anyway I think we should do a full regression before pushing this to production after the changes I made in https://github.com/CartoDB/cartodb/commit/d7466049a87b878cd67f226d51f44fd8af122b84

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1882/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1897/))

**Pull request merged**
