### PR TITLE
fix small ui issues

### PR DESCRIPTION
**Pull request by rubenmoya**
Issue: #12227

- [x] Dataset view, when you open the column dropdown.

screen shot 2017-05-29 at 16 00 32

- [x]  Dashboard dropdown.

screen shot 2017-05-29 at 16 00 44

- [x] Color by value

screen shot 2017-05-31 at 15 30 35

- [x] "create/upload dataset" modal in Builder page.

dataset_loading

Depends on: https://github.com/CartoDB/CartoAssets/pull/163

### CODE REVIEW

**Comment by rubenmoya** [comment]
retest this please

**Comment by xavijam** [comment]
Going back to development because the modal we need to review is in Builder page, not in the dashboard.

**Comment by xavijam** [comment]
@nobuti mentioned an issue related to fill -> style -> icon. Is it fixed too'

**Comment by rubenmoya** [comment]
Seems like it is fixed too 👏 

screen shot 2017-05-30 at 15 23 18

**Comment by xavijam** [comment]
Tested in staging and working like a charm. Let's merge everything tomorrow!

**Comment by rubenmoya** [comment]
I've been talking with @piensaenpixel and we think the best way to fix it is by adding some more markup, for example, in this case moving the flex classes to other div:

screen shot 2017-05-31 at 12 01 27

I'll have to check the rest of the cases, if it works we won't need too add logic to the css, which is nice. What do you think @xavijam?

**Comment by rubenmoya** [comment]
Last changes fix it with markdown instead of changing cartoassets, the only one we can't fix this way is the loading icon, which has to be fixed using this PR: https://github.com/CartoDB/CartoAssets/pull/164

**Comment by xavijam** [comment]
Fantastic. I'm a bit worried about if we find more places where there are UI issues, but let's face them when appear.

**Comment by xavijam** [comment]
Hey, there is another place where we haven't fixed it 😬 

screen shot 2017-06-01 at 11 11 08

Back to development, come on!

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
