### PR TITLE
Fixed missing bottom padding in footer

### LINKED ISSUE #8876: Footer is wrong styled
screen shot 2016-07-14 at 16 26 48

### PR DESCRIPTION
**Pull request by MariaCheca**
Fixes #8876 

screen shot 2016-07-14 at 16 36 53

CR @matallo please

### CODE REVIEW

**Comment by matallo** [comment]
oop, it was on purpose, check public pages and fix

**Comment by matallo** [comment]
hey, that breaks public pages footer columns in mobile

**Comment by matallo** [comment]
LGTM

**Comment by MariaCheca** [comment]
Thank you for your feedback @matallo :) Please the next time you modify the styles take into account other views that could be affected.

**Comment by MariaCheca** [comment]
✨

**Pull request merged**
