### PR TITLE
Fix tooltips in size & color controls in mobile

### PR DESCRIPTION
**Pull request by VictorVelarde**
### Related to https://github.com/CartoDB/cartodb/issues/14098

This includes a fix for sticky tooltips in mobile and a little UI change (south instead of west gravity, for better readability)

### Acceptance
- Open any `map`
- Go to `Style` panel
- Dev tools > `Mobile`
- Toggle between size & color options (Fixed vs By value) clicking repeatedly the radio buttons.
- *Expected*: tooltips work but don't get stuck (no more 'sticky tooltips') and same tooltips also work fine in Desktop mode.

### CODE REVIEW

**Comment by VictorVelarde** [comment]
@rubenmoya after a little CR, this should be ready for acceptance in RT

**Comment by ramiroaznar** [comment]
What is the status of this one? @VictorVelarde @rubenmoya

**Comment by VictorVelarde** [comment]
AFAIK the biggest problem was already solved (overlapping tooltips when changing from 'fixed' to 'by value' mode or 'sticky' when changing from 'style panel' to others), but there was another minor issue in mobile that you found at acceptance

**Comment by VictorVelarde** [comment]
Hi @ivanmalagon I will go for this as it is. It improves the tooltip cleaning, not only for mobile.

**Comment by ivanmalagon** [comment]
That's what I'm doing. I spent yesterday a lot of time trying to fix the problem that shows up only in mobile with no success.

I'm passing this to acceptance as you left it.

**Pull request merged**
