### PR TITLE
Rake task to post-process ES requests logs #2305

### PR DESCRIPTION
**Pull request by rafatower**
@kartones code review, please

### CODE REVIEW

**Comment by Kartones** [comment]
+1

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1729/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1733/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1735/))

**Pull request merged**
