### PR TITLE
Support Node.js 10 and npm 6

### PR DESCRIPTION
**Pull request by dgaubert**
- Add support for `package-lock.json`
- Improve Travis configuration to run tests with Node.js 6 and 10
- look for duplicated dependencies in `package-lock.json`
- Make `shrinkwrap-dependencies.js` agnostic from the `lock file`

### CODE REVIEW

**Comment by dgaubert** [comment]
Please, @CartoDB/frontend-team! Can anyone take a 👀 on this? 🙏 🙏

**Comment by dgaubert** [comment]
FYI: On Monday, December 17th I'm going to merge and deploy this PR.

**Comment by dgaubert** [comment]
> Does the changes on travis.yml make it run with both node? Does it depend on what there's installed on travis?

I've created two different jobs for Travis to launch every time anyone pushes a change to the repository (Travis creates a VM installs what you've defined and runs the tests). The first one runs tests against Node 6 and npm@3. It needs to install dependencies through `npm install` command based on `npm-shrinkwrap.json` file. The second one runs the tests against Node.js 10 and npm@6. it installs dependencies through `npm ci` based on the new lock file called `package-lock.json`. 

I keep both jobs temporally, once we are migrated to Node.js 10 completely the idea is to remove the Node.js 6 & npm@3 job and the infamous `npm-shrinkwrap.json` file. The big pain here is in the meantime we need to keep both files synced (npm-shrinkwrap.json & package-lock.json) to be able to install the same versions of the dependencies for each job.

**Comment by dgaubert** [comment]
In summary:

- Job 1: 
  - Create VM, install Node.js 6 & npm 3
  - Install Node.js dependencies with `npm install` (read npm-shrinkwrap.json)
  - Runs tests
- Job 2: 
  - Create VM, install Node.js 10 & npm 6
  - Installs Node.js dependencies with `npm ci` (reads package-lock.json)
  - Runs tests

**Comment by dgaubert** [comment]
You can get more details here: https://travis-ci.org/CartoDB/cartodb/builds/465940491

**Comment by dgaubert** [comment]
Creating a new dedicated instance in staging (building assets) to check that it works with Node.js 6 and npm@6 so we can merge this branch to master safely.

http://deploy.int.cartodb.net/job/carto-deploy-to-a-new-staging-dedicated-instance/1225/console


@rjimenezda if it works, do you allow me to merge it?

**Comment by rjimenezda** [comment]
If everything's green, it deploys correctly and nothing is apparently broken, go for it :+1:

**Comment by dgaubert** [comment]
The build has finished successfully and everything looks great. You can check it [here](https://assets-build.carto-staging.com)  user: `assets-build`, pass: `assets-build123`

**Pull request merged**
