### PR TITLE
Unpacking zips with a fake password fixes #1978

### LINKED ISSUE #1978: Importing a password protected zip stucks importer at unpacking state
cc @xavijam

### PR DESCRIPTION
**Pull request by juanignaciosl**
@rafatower CR this, please.

Previously password protected zip files stuck importer, rising CPU up to 100% until killed.
*What should be tested*:
* Importing a password protected file should now fail and prompt a user message.
* Importing of other files should work as usual.
* Important: test one compressed file of every supported type (zip, tar, tgz...), since command is different and might fail.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1310/))

**Comment by rafatower** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1394/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1396/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1397/))

**Pull request merged**
