### PR TITLE
Freeze deps 

### PR DESCRIPTION
**Pull request by IagoLast**
🍈🍈🍈 BIG MELON FINALLY ADDRESSED 🍈🍈🍈
---

### What the heck did the update internal deps command?
```
"update-internal-deps": "rm -rf node_modules && npm install --production --no-optional --no-shrinkwrap && npm dedupe && npm prune && npm shrinkwrap && npm run fix-shrinkwrap-protocol && npm install",
```

- `rm -rf node_modules`: Ok first clean node modules
- `npm install --production --no-optional --no-shrinkwrap`: Install dependencies but only the required for production.
- `npm dedupe` : Fix the dep tree
- `npm prune`: Remove the installed deps that were not listed in the package.json (this is stupid, we just deleted all deps!)
- `npm shrinkwrap`: Take all installed deps and freeze them.
- `npm run fix-shrinkwrap-protocol `: Force to use https instead http
- `npm install`: Install everything again (but this time use deps listed in the shrinkwrap

I think this script was added because builds were not repeatable. This happened because some deps pointed to `#master` branch, just imagine the following:

1. I clone the repo at 9:00 in the morning when last commit in carto.js is the `commit-0`
2. While Im working fixing bugs, someone updates carto.js, now carto.js#master points to `commit-1`
3. I fix the bug and upload my code code that for some reason is not compatible with `commit-1`.
4. When the next developer downloads and installs the code, will fail because `carto.js#commit-1` will be downloaded 💥 

### How this situation can be fixed?

1. Point to fixed tags/versions
2. Add a yarn.lock/npm-shrinkwrap to freeze the dep-tree.

### Does this PR solve this issue?

Yep, we just need to update the shrinkwrap to ensure repetible builds!

### Are we missing something?

Probably, who knows but this reduces the development speed a lot.

5 developers doing a single `update-internal-deps`every day means almost 1h of work wasted, I think it worth try to fix this

cc @CartoDB/frontend

### CODE REVIEW

**Comment by ivanmalagon** [comment]
`npm install --production --no-optional --no-shrinkwrap` is done that way because shrinkwrap is not created equal from OSX or Linux. So this must added anyway.

Summoning @rochoa here because he has more context about this whole process and the problem it resolves. He can shed more light on this.

**Comment by IagoLast** [comment]
> First of all, what is the objective of this PR? Or to be more precise, what problem are we solving here?

We are blindly running a command that takes several minutes (depending on the network speed).  The objective of this PR is to understand the intention of the command and reduce the unnecessary part to improve speed.

> You don't need to run this script several times a day but just when you want to merge to master or update a dependency before deploying to production

IMO is a big PITA but we should ask `frontend` for more general feedback.

> This solves the problem with top-level dependencies. However, those dependencies might rely on non-fixed versions, you don't control them, and they will vary over time.

Right, that's why we keep [npm shrinkwrap && npm run fix-shrinkwrap-protocol](https://github.com/CartoDB/cartodb/pull/13943/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R170) in the scripts section

>Using npm shrinkwrap && npm run fix-shrinkwrap-protocol means that if you have something installed/linked locally, when you run the shrinkwrap you will put those locally installed/linked deps in the shrinkwrap file.

Ok we can add a `prune` step.

> just by looking at the changes in this very same PR, the carto, perfect-scrollbar, and torque.js packages are getting duplicated..

Ok we can keep the `dedupe` In any case Are you sure about the bundle size? 

> This PR includes several new packages in the shrinkwrap file

We are freezing devDeps too


> 2, what is worse, you could get into issues like an instance of one of those classes telling you is not an instance of those classes because they reference diffent packages —this has happened before.

This is the only thing that worries me, do you know how the old `update-internal-deps` fixes this? Maybe the dedupe command flattens the dep-tree before freezing.


For me the biggest issue here is: do we really need to remove all the  `node_modules` and install everything again as first step? 

For example when we update the `carto.js` version we only need to update the package.json referencing to the new tag and update the shrinkwrap accordingly. I don´t see why we have to reinstall everything.

**Comment by rochoa** [comment]
> IMO is a big PITA but we should ask frontend for more general feedback.

```
$ git log --oneline --since=2018-01-01 npm-shrinkwrap.json | wc -l
     289
```

Let's consider 90 working days since that date. That's around 3 changes per day. And that's considering version bumping.

> For me the biggest issue here is: do we really need to remove all the node_modules and install everything again as first step?

To have a command that is consistent for anyone executing it, **not having to think about it**, removing the uncertainty of what the status of your local environment is.

This PR is already polluting the shrinkwrap file. Imagine what will happen when those 5 people start executing this daily and every PR 200+ LOC changes. Nobody will evaluate the changes in the shrinkwrap file.

Feel free to modify the script, adding back `prune` and `dedupe` may solve some of the problems. As I was saying, my comment was informative. I wanted to share my experience and why we decided to go that path.

Thinking about and doing code reviews of a 3k LOC file might be more expensive than running a 2 minutes script three times per day.

**Comment by ivanmalagon** [comment]
First of all, we're putting off using Yarn until OnPremises releases the 2.2 version. That's taking way more time than expected. We didn't want to change something so critical that could affect a new package of OnPremises. Infra told us to wait until that.

So this process will be tackled when the time comes.

Specifically about this PR, as a I said in my first comment, we cannot rely on the current `node_modules` since Linux and OSX differ. To avoid that, a clean `npm install` with those options made the trick and since adding `--no-optional` we stopped seeing unwanted changes in shrinkwrap. I don't know if that can be achieved via other options.

Thanks @rochoa for the thorough explanation. We don't always have the vision / context of the decisions taken long time ago and the problems they solve.

**Pull request closed without merging**
