### PR TITLE
Change handler for unverified request

### PR DESCRIPTION
**Pull request by gfiorav**
cc/ @juanignaciosl

### CODE REVIEW

**Comment by gfiorav** [comment]
Could you review this please, @juanignaciosl ?

**Comment by juanignaciosl** [comment]
LGTM, I can't help too much here. Just test it :+1:

**Comment by gfiorav** [comment]
I've tested al POST endpoints we have and their neighbourhoods, tomorrow morning we deploy this cc/ @xavijam

**Comment by xavijam** [comment]
:racehorse:

**Pull request merged**
