### PR TITLE
Increases max zoom on plain color basemaps to 32

### LINKED ISSUE #4940: when user select plain color basemap the embed does not go further than zoom level 20
- create a map and add a point
- zoom to level 24
- go to embed map

it shows level 20. If you force with zoom=24 if shows level 20 and it should be unlimited (or something like 32)

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #4940

@javisantana 

CR please, @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
You can remove the comment :)

**Comment by xavijam** [comment]
And then :dancer:

**Comment by gfiorav** [comment]
Done, as soon as tests pass, I'll merge :+1: 

Thanks @xavijam

**Comment by javisantana** [comment]
I don't think this fixes the whole problem, did you try to go to and embed and set in the url ?zoom=29 ?

**Comment by gfiorav** [comment]
Could you provide more information on how you tested this?

It works on embedded for me

**Comment by javisantana** [comment]
send me the embed please

**Pull request merged**
