### PR TITLE
Adding more licenses for table metadata

### PR DESCRIPTION
**Pull request by iriberri**
Adds more licenses as accorded in https://github.com/CartoDB/cartodb/issues/5316

### CODE REVIEW

**Comment by iriberri** [comment]
cc @ethervoid, could you check? after this I'm testing in staging :-)

**Comment by ethervoid** [comment]
Looks good to by but: clear trailing spaces and if you can change to the Ruby 1.9 hash (as hound says) :+1:

**Comment by iriberri** [comment]
I'll do it. Didn't change the hash thing because I was respecting how you did it, but I'll do ;) thanks!

**Comment by iriberri** [comment]
Testing in staging

**Comment by iriberri** [comment]
image
image

**Comment by iriberri** [comment]
Front seems OK, no errors, and the save requests are ok:

````

**Comment by ethervoid** [comment]
:clap:

**Comment by iriberri** [comment]
Merging then :)

**Pull request merged**
