### PR TITLE
Add rake task to unshare all shared entities for an user

### PR DESCRIPTION
**Pull request by zenitraM**
This rake unshares everything the user might have shared with other members of the organization, and also removes ACL entries of elements shared with that user (useful for moving users around).

does this look fine @Kartones @rafatower?

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3229/))

**Comment by Kartones** [comment]
:+1: But have you tried what happens if there's a vis from B containing a table shared from A and you unshare that table? I don't recall if it just removes the layer or doesn't allows or what it did...

**Comment by Kartones** [comment]
Normal scenarios where you have shared things but noone has used them is perfect

**Comment by zenitraM** [comment]
I've tried when B has created a visualization having a table from A as the only table, and A gets "unshared", it drops B's visualization. (I guess this is something we expect when moving an user out of an org)

**Comment by zenitraM** [comment]
Going to try some other edge cases though.

**Comment by Kartones** [comment]
Yes, IIRC the UI warns about this (checking related visualizations, etc.). Maybe would be interesting to generate a log of "droppped related visualizations" then, to know if something was removed or not.

**Comment by rafatower** [comment]
Nothing to add here apart from what kartones said :+1:

**Comment by zenitraM** [comment]
@Kartones yes.. but for now we are going to use this only for cases where the users should be already warned of the consequences.

Tried some other cases and it seems to work fine, when there are multiple tables it drops only the affected layers so that's the expected behavior.

I'm currently logging which ACLs have changed, checking if there's an easy way to bring up the affected layers/vizs that are to be deleted on other users

**Comment by Kartones** [comment]
then :+1:

**Pull request merged**
