### PR TITLE
Adds random loading sentences

### PR DESCRIPTION
**Pull request by javierarce**
@CartoDB/frontend: can you review this, please?

I implemented this using a function instead of a backbone model or a backbone view. 

@CartoDB/design: can you review this too, please?

You can see the sentences we'll be using [here](https://github.com/CartoDB/cartodb/blob/2396-random-sentences/lib/assets/javascripts/cartodb/new_common/view_helpers/random_sentence.js).

sentence01
sentence02
sentences03

### CODE REVIEW

**Comment by javierarce** [comment]
Ups, I need to update some specs…

**Comment by viddo** [comment]
Yep, all good!  :+1:  (except for the broken specs :wink:)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1832/))

**Comment by javierarce** [comment]
@viddo, @xavijam: thanks!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1870/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1871/))

**Comment by javierarce** [comment]
@CartoDB/design ?

q01
q03
quotes4

**Comment by piensaenpixel** [comment]
Looks awesome :)

**Comment by carlostallon** [comment]
<3

**Comment by javierarce** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1951/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1952/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1953/))

**Pull request merged**
