### PR TITLE
Send page viewed when entering New Dashboard

### PR DESCRIPTION
**Pull request by jesusbotella**
This PR sends `visited_private_page` event to internal metrics when visiting Home Page in Dashboard.

Related to https://github.com/CartoDB/product/issues/209

### CODE REVIEW

**Comment by csubira** [comment]
### Tasks performed in acceptance:

Given `is_first_time_viewing_dashboard` is `true` (First time opening dashboard):

- [ ] Check that the Welcome module is the Welcome for first time module (blue)

- [ ] Check that the POST request sends the visited page metric.

Given `is_first_time_viewing_dashboard` is `false` (Not first time opening dashboard):

- [ ] Check that visiting the homepage does not trigger the request to send the visited page metric.

**Comment by alonsogarciapablo** [comment]
@csubira how did you test this? Did you create a new user or did you find a way to change `is_first_time_viewing_dashboard` (eg: in the DB)? Thank you! Let's ship it! 🚀

**Comment by csubira** [comment]
@alonsogarciapablo I changed it in the  Vue `store` (config) and then check that the POST was sent properly.

**Comment by alonsogarciapablo** [comment]
Thank you @csubira. I was asking just in case I have to do it sometime to test. Are we merging and deployin for today's usab test? Thanks!

**Comment by jesusbotella** [comment]
Yes!

**Comment by alonsogarciapablo** [comment]
:+1: Thank you!

**Pull request merged**
