### PR TITLE
codemirror: mustache template

### PR DESCRIPTION
**Pull request by matallo**
made changes in the codemirror parser to comply with this request in https://github.com/CartoDB/cartodb/pull/11939#issuecomment-292559200

> Change the text color to difference the text inside {{}} and the text outside. Maybe we can use the white for the text outside like a “{“

it's much less sophisticated now, so I'm not sure about it, what's your opinion @nobuti ?

screen shot 2017-04-11 at 18 04 41

/cc @urbanphes

### CODE REVIEW

**Comment by nobuti** [comment]
the simpler, the better. I think to show parsing errors is a nice thing though.

**Comment by matallo** [comment]
yeah, actually there's an ongoing discussion about syntax validation https://github.com/CartoDB/cartodb/pull/11939#issuecomment-293290750

I need to talk to @rochoa about that when he has a minute

**Comment by xavijam** [comment]
Hey guys, what about this PR? can we close it? Should we keep pushing?

**Comment by matallo** [comment]
it's done, pending feedback and/or acceptance as it changes a bit how moustache strings are validated. They slightly change the color for better represent the template (see attached)

screen shot 2017-07-06 at 15 05 37

this is prod ^^^

**Pull request closed without merging**
