### PR TITLE
update error pages [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by matallo**
close https://github.com/CartoDB/cartodb/issues/4428

CR @xavijam

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4942/))

**Comment by xavijam** [comment]
Maintenance page?

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5075/))

**Comment by matallo** [comment]
I think the tests errors have to do with page title, I'll take a look; in any case maintenance (and goodbye) have been redesigned so I'd wait until I update them, too

**Comment by javisantana** [comment]
retest this please

**Comment by matallo** [comment]
I have to fix the tests (will cloase as the error pages have been updated again)

**Pull request closed without merging**
