### PR TITLE
Add pointer cursor to the sliders

### PR DESCRIPTION
**Pull request by Jesus89**
Related to #12499

Added hand (pointer) cursor: slider and rangeslider

slider-hand

### CODE REVIEW

**Comment by Jesus89** [comment]
Good point! Let's add not-allowed cursor if disabled

**Comment by Jesus89** [comment]
Done.
slider-hand-disabled

**Comment by ivanmalagon** [comment]
In order to test the range slider, please deploy this PR in RUIs. This range control is only available in D.O. Please ask first @nobuti or @xavijam to know if you can override the RUI servers with your PR.

**Comment by rubenmoya** [comment]
Working perfectly, let's go to deploy!

**Comment by rubenmoya** [comment]
please retest this

**Comment by rubenmoya** [comment]
retest this please

**Comment by rubenmoya** [comment]
retest this please

**Pull request merged**
