### PR TITLE
3168 describe get api v1 viz

### LINKED ISSUE #3168: Move test suite describe 'GET /api/v1/viz/:id'

### PR DESCRIPTION
**Pull request by juanignaciosl**
@rafatower could you CR this, please. As you see this closes #3168 but it was actually done (by mistake) at #3124 . I've also deleted a (pending) test.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2983/))

**Comment by rafatower** [comment]
:+1: in case of doubt, I love good commit messages :)

**Comment by juanignaciosl** [comment]
@rafatower I forgot adding the new route to the js

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2985/))

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2987/))

**Pull request merged**
