### PR TITLE
Avoiding request other pages than the first one when a search is submitted

### LINKED ISSUE #4291: Trying to filter by tag the data library in the new dataset view if the page is higher than first it fails
@xavijam @juanignaciosl

Trying to filter by tag the data library in the new dataset view if the page is higher than first it fails

## Context

When you are in the dataset view and try to sort the data library using the tags there isn't problem if you are in the first page but if you change for example to the page 2 and try to sort, you get and empty list.

## Process

1. Go to `New Dataset`
2. Go to `Data Library`
3. Go down the page and go to page 2
4. Try to filter by tag

## Expected result

Should show all the datasets fot that tag paginated

## Current result

Empty list

## Screenshot

captura de pantalla 2015-07-03 a las 13 44 03

### PR DESCRIPTION
**Pull request by xavijam**
This was fixed in the dashboard search and now it is fixed in the create dialog search.

REVIEWER: @ethervoid :dancer: 
Fixes #4291.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4787/))

**Comment by xavijam** [comment]
@ethervoid ping!

**Comment by xavijam** [comment]
retest this please

**Comment by ethervoid** [comment]
I was waiting the test to pass. LGTM :)

**Comment by xavijam** [comment]
If frontend tests pass, it is ready to go :).

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4795/))

**Pull request merged**
