### PR TITLE
remove-layers-v1_1-step-1

### PR DESCRIPTION
**Pull request by Kartones**
1st step of https://github.com/CartoDB/cartodb/issues/4621

### CODE REVIEW

**Comment by Kartones** [comment]
@juanignaciosl CR please

**Comment by juanignaciosl** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5371/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5373/))

**Pull request merged**
