### PR TITLE
4921 fix geometry type icons

### PR DESCRIPTION
**Pull request by josecruz**
update corner radius + white background missing on red icons

### CODE REVIEW

**Comment by josecruz** [comment]
@xavijam take a look at this pls :pray:

**Comment by xavijam** [comment]
It has to be exactly 200px, not 201px.
In the retina the same, 400px, not 401px.

**Comment by josecruz** [comment]
done @xavijam

**Comment by xavijam** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5645/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5647/))

**Pull request merged**
