### PR TITLE
Redirecting to shared section when user doesn't have any dataset but there is any shared dataset

### LINKED ISSUE #3179: Go to shared datasets instead of Data Library if user hasn't created datasets
Just an scenario I saw right now:

A user has no datasets yet, but it's an organisation user and has 4 shared datasets from other person in the same team.

The dashboard goes automatically to Data Library, instead of to "shared datasets".

It's just a small detail, but wouldn't it be more interesting to guide the user to the shared datasets of his/her organisation? :-)

@saleiva 

image

### PR DESCRIPTION
**Pull request by xavijam**
Fixes #3179 

Could you check it @javierarce please :)?
cc @iriberri

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3736/))

**Comment by iriberri** [comment]
Awesome!

**Comment by xavijam** [comment]
ping @javierarce :)

**Comment by javierarce** [comment]
:balloon: Lo veo *fine*.

**Comment by xavijam** [comment]
Merging then :)

**Pull request merged**
