### PR TITLE
Delete organization PG role on organization deletion

### LINKED ISSUE #12642: Organization PG role is not deleted on organization deletion
### Context

Detected on #12254 development, because of an error trace exporting and importing in the same server.

### Steps to Reproduce

1. Create an organization.
2. Write down its role (`@organization.owner.db_service.organization_member_group_role_member_name`)
3. Destroy the organization.
4. `select * from pg_roles where rolname = 'cdb_org_member_feb819abd9df123fc6a5df88ce19df26'`

### Current Result

One record.

cc @CartoDB/builder-backend

### PR DESCRIPTION
**Pull request by alrocar**
Closes #12642
Code might look weird, but I wrote first a failing test to make sure it's working

### CODE REVIEW

**Comment by amiedes** [comment]
I think there is a problem with the introduced changes. I'm trying to delete an organization in staging but it fails due to active DB connections to the user database.

I checked this a couple of times to ensure the open connections where not related to me "taking a look" in the server.

**The procedure I followed was:**

1. Create the org and ensure that the DB role existed in the user database:

```bash
# Get the IP from: https://carto-staging.com/superadmin/users/558
ssh <db_server_ip> 
```

```
postgres=# select * from pg_roles where rolname = 'cdb_org_member_9d9d4a6620678144513906e20c616b72';
-[ RECORD 1 ]--+------------------------------------------------
rolname        | cdb_org_member_9d9d4a6620678144513906e20c616b72
....
oid            | 333225
```

2. Ensure all connections to the user DB are closed before deleting the org (the `datname` string is the name of the user Database, I took it from Rollbar):

```
postgres=# SELECT * FROM pg_stat_activity where datname = 'cartodb_staging_user_75a91d15-ec2a-499f-93f5-851c0353ec3e_db';
(0 rows)
```

3. Try to delete the org from superadmin (fails with [this Rollbar](https://rollbar.com/carto/CartoDB/items/41256/?item_page=0&item_count=100&#instance))
4. You can see that two DB connections are open:

```
postgres=# SELECT count(*) FROM pg_stat_activity where datname = 'cartodb_staging_user_75a91d15-ec2a-499f-93f5-851c0353ec3e_db';
-[ RECORD 1 ]
count | 2
```

@alrocar @gonzaloriestra is there any difference between staging and development/test that may cause this to behave differently between the two environments?

I've done a rollback of the staging deploy and organization deletion is succeeding again, so the bug is probably related to the changes in this PR:

```ruby
def drop_owner_database(conn)
  org_member_role = organization_member_group_role_member_name
  @user.in_database.disconnect
  conn.run("DROP DATABASE \"#{@user.database_name}\"")
  conn.run("DROP OWNED BY \"#{org_member_role}\" CASCADE")
  conn.run("DROP ROLE IF EXISTS \"#{org_member_role}\"")
end
```

**Comment by gonzaloriestra** [comment]
I guess @alrocar will know better what could be happening, but maybe we can do something [like this](https://stackoverflow.com/a/17461681/2436061).

**Comment by alrocar** [comment]
I recall an error like that when testing locally (that I fixed in the current PR), but since the environment is different in staging I might be missing something.

This is not super-important anyhow, so let's keep it on hold and I'll take a look when I have time.

Thanks!

**Comment by gonzaloriestra** [comment]
ClubHouse story: [ch83613](https://app.clubhouse.io/cartoteam/story/83613/organization-pg-role-is-not-deleted-on-organization-deletion)

**Comment by amiedes** [comment]
😢

**Pull request closed without merging**
