### PR TITLE
Remove Windshaft deprecated routes

### LINKED ISSUE #2745: Remove Windshaft deprecated routes
See [Routes list](https://github.com/CartoDB/Windshaft-cartodb/blob/master/docs/Routes.md).

A check yielded two points where now deprecated routes are being used:
```
> app/models/table.rb
> delete_tile_style()
if owner.organization.nil?
      tile_request('DELETE', "/tiles/#{self.name}/style?map_key=#{owner.api_key}")
    else
      tile_request('DELETE', "/tiles/#{qualified_table_name}/style?map_key=#{owner.api_key}")
    end

> services/named-maps-api-wrapper/lib/named-maps-wrapper/named_maps.rb 
  + models/named_maps_spec.rb
> initialize()
@url = [ @host, 'tiles', 'template' ].join('/')
```

Implement required changes so we don't use deprecated routes

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #2745

### CODE REVIEW

**Comment by Kartones** [comment]
@rafatower CR please, as this removes both the style change call and that dead `tile_request` method from Table model.

cc @iriberri Rochoa told me this can be pushed right away, but just in case you see problems with named maps/private tables or table destructions.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2284/))

**Comment by iriberri** [comment]
Got it :-) I'll keep an eye on that.

**Comment by rafatower** [comment]
:+1:

**Comment by Kartones** [comment]
@rochoa deploying right now to live, so REST APIs backend clean

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2287/))

**Pull request merged**
