### PR TITLE
Offer dates shortcuts within dates range picker

### LINKED ISSUE #3952: Offer an easy way to get last hour(s) tweets in the twitter connector
Like: Gimme last 10 hours

### PR DESCRIPTION
**Pull request by xavijam**
screen shot 2015-08-04 at 21 41 16

Apart from adding those news fast dates shortcuts, we set the initial date ranges checking user timezone and setting them with UTC 0, trying to avoid the confusion with the GMT conversions.

Fixes #3952.

REVIEWER: @javierarce 
cc @javisantana @saleiva

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5578/))

**Comment by saleiva** [comment]
@miguelarias is gonna love this :)

**Comment by javierarce** [comment]
:cool:

**Comment by xavijam** [comment]
retest this please

**Comment by javierarce** [comment]
:cool: :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5583/))

**Comment by miguelarias** [comment]
Yay!, but this is not solving @andrewxhill issue yet right?, frontend is still user time zone-centric?

**Pull request merged**
