### PR TITLE
fixed spelling of occurred

### PR DESCRIPTION
**Pull request by csobier**
@xavijam , minor typo fix

### CODE REVIEW

**Comment by xavijam** [comment]
Hey @csobier, there is a conflict and also you have changed something from the cdb submodule. we can't deploy this.

**Comment by csobier** [comment]
@xavijam , it was a conflict in the NEWS.md file. Is it okay now?

**Comment by xavijam** [comment]
Nope, it is appearing there are changes in the cdb submodule.

**Comment by csobier** [comment]
Ok, closing this PR without merging and creating a new one with just text changes, to be sure ;-) Thanks!

**Pull request closed without merging**
