### PR TITLE
Defaults "Time Column" in torque wizards to first date column or cartodb_id

### LINKED ISSUE #3895: Torque wizard should take the first date type column by default and no cartodb_id
cartodb_id should be the default just in case there is no date type columns.

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #3895.

@xavijam this one is for you my friend! Thanks!

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4451/))

**Comment by alonsogarciapablo** [comment]
retest this please

**Comment by xavijam** [comment]
Good addition :es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4452/))

**Pull request merged**
