### PR TITLE
Add webpack-dashboard

### PR DESCRIPTION
**Pull request by rjimenezda**
This PR adds webpack-dashboard in the most non-intrusive way possible.

Because we are bundling CSS through webpack (**for now!**), we can't directly run webpack-dashboard, but we run add the plugin through a port & run the dashboard on a different terminal.

I added the necessary plugin to webpack.dev.config & an extra command to run the dashboard `npm run dashboard`

This is what the dashboard looks like:
screen shot 2017-07-07 at 16 07 56

All those panels are scrollable if you have mouse support on your terminal emulator

It could be run for the tests as well, if there's interest.

### CODE REVIEW

**Comment by nobuti** [comment]
Tests?

**Comment by rjimenezda** [comment]
@CartoDB/frontend 

If we add this to the other webpack runner we have (affected_specs) we should probably pick another port, since it's common to run both at the same time.

In order to connect to another port we can:

a) add another command to package.json

```
...
"dashboard": "webpack-dashboard -p 1987",
"dashboard-affected": "webpack-dashboard -p 2017",
...
```

b) Keep one command

```
...
"dashboard": "webpack-dashboard"
...
```

and pass the port as an argument.
 
There are two ways of doing this:

- `npm run dashboard -- -p 1987`
- `WEBPACK_DASHBOARD_PORT=1987 npm run dashboard` and then the command should be `dashboard: webpack-dashboard -p $WEBPACK_DASHBOARD_PORT`

Thoughts?

**Comment by xavijam** [comment]
Better to leave it like a separated task than adding it by default. But as you wish man!

**Comment by rjimenezda** [comment]
I prefer explicit commands as well, I'll leave like that unless someone objects

**Comment by rjimenezda** [comment]
Closing this, it's not that useful

**Pull request closed without merging**
