### PR TITLE
Remove carousel view when geometry type is different than points

### LINKED ISSUE #8105: Polygons aggregation options shouldn't exist
since it's just a simple mode right now
screen shot 2016-06-23 at 14 53 48

### PR DESCRIPTION
**Pull request by xavijam**
screen shot 2016-08-11 at 11 41 46
screen shot 2016-08-11 at 11 41 53

Fixes #8105.
CR: @nobuti

### CODE REVIEW

**Comment by xavijam** [comment]
CR @nobuti

**Comment by nobuti** [comment]
👍

**Comment by saleiva** [comment]
No way, can we remove that module until we implement the aggregation methods?

**Comment by xavijam** [comment]
Ok, removing carousel for polygon and line options 💋

**Comment by xavijam** [comment]
It looks a bit empty @saleiva, but it is ok, let's wait for those new aggregation methods.

**Comment by saleiva** [comment]
Hey, is it hard to change the Style to Polygon styles and Line styles?

**Comment by xavijam** [comment]
No problem ™️

**Comment by xavijam** [comment]
CR @nobuti again please :) 💋

**Comment by nobuti** [comment]
LGTM

**Comment by xavijam** [comment]
Merging in 9010-delete-whatever

**Pull request merged**
