### PR TITLE
Aborting old and unfinished visualization requests in new dashboard

### LINKED ISSUE #2737: Dashboard attempts to import existing dataset
1. Go to datasets with 'http://_server_/dashboard/datasets' and before list appears, click 'Data Library'.
2. It will show user datasets before data library. If you click an existing user dataset dashboard triggers an import (just as if it were an external source).

### PR DESCRIPTION
**Pull request by xavijam**
When a user clicks over new dashboard tabs, several times, it makes several requests. Sometimes new ones finish before old ones, and UI could show wrong info. Aborting old requests avoid this problem.

#### PROS:
- User will see what he/she wants, related with the current selected section (or filter).
- It will work for **new** and **old dashboard**.

#### CONS:
- Unfortunately we need to check if the error comes from an 'abort' action before showing the error state.

REVIEWER: @javisantana 

Fixes #2737

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2467/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2468/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2469/))

**Comment by javisantana** [comment]
:es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2471/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2472/))

**Pull request merged**
