### PR TITLE
Fixed styles within Notifications dropdown

### PR DESCRIPTION
**Pull request by xavijam**
Related ticket: https://github.com/CartoDB/cartodb/issues/12045

screen shot 2017-04-28 at 14 05 06
screen shot 2017-04-28 at 14 09 08

### CODE REVIEW

**Comment by xavijam** [comment]
I feel it is not needed to change the NEWs.

**Comment by javitonino** [comment]
Italic works fine, but bold text does not display correctly in the notifications bubble. Also, we do not support code (fixed-width) text, which maybe we should.

screenshot_20170428_130447

I think this is back to dev, although this is not explicitly stated in the ticket, I feel it should be addressed here. 🔴

**Comment by xavijam** [comment]
Agree! Not sure about the code one but, yeah, let's check it.

**Comment by nobuti** [comment]
Works great ✨

**Pull request merged**
