### PR TITLE
Remove back arrow and add a tooltip to editor logo

### PR DESCRIPTION
**Pull request by rubenmoya**
Related to: #13047 

backtodashboard

cc @urbanphes

### CODE REVIEW

**Comment by piensaenpixel** [comment]
love it.

**Comment by rubenmoya** [comment]
Oooops 😅

**Comment by urbanphes** [comment]
@rubenmoya We're going to maintain the same behavior in both cases, using the tooltip.

**Comment by rubenmoya** [comment]
So, just to be clear, `tooltip without arrow` in the layers/layer view, and `arrow without tooltip` in the dataset/show view, right?

**Comment by piensaenpixel** [comment]
hey @rubenmoya we never want the arrow :)
thanks dude

**Pull request merged**
