### PR TITLE
bump private submodule

### PR DESCRIPTION
**Pull request by ilbambino**

### CODE REVIEW

**Review by alberhander — APPROVED** [review]
:+1:

**Review by alberhander — APPROVED** [review]
:+1:

**Comment by Stivens73** [comment]
This PR broke the whole repository #16051, need to revert

**Comment by sabman** [comment]
@Stivens73 actually this is the PR that originally added the submodule: https://github.com/CartoDB/cartodb/pull/16023 I am wondering if there are any ideas on a better way to manage this?

For now i could either clone without the `--recursive` flag and also comment out the private submodule from the `.submodule` file.

```bash
sed -i '.bak' 's/\[submodule "private"\]/#&/' .gitmodules
sed -i '.bak' 's/^[[:space:]]*url = git@github.com:CartoDB\/cartodb-private\.git/#&/' .gitmodules
sed -i '.bak' 's/^[[:space:]]*path = private/#&/' .gitmodules
```

**Pull request merged**
