### PR TITLE
Accounts UI enhancements

### LINKED ISSUE #5507: Minor user account enhancements
In order to have all the UI unified, I propose some changes for the user account:

- [ ] ~~Add `min-width: 3px;` to the used quota progress bar on the side menu, so even if the user has no quota used, there's always a minimum colored bar exposed.~~
- [x] Delete `min-width: 3px;` from the used quota progress bar on the side menu.
screen shot 2015-09-14 at 17 59 16

- [x] Set `width: 260px` to the side menu bar to avoid leaps while the page is loading.
screen shot 2015-09-14 at 18 01 37

- [x] Show only 2 decimals when displaying a float value for the quotas data and avoid a blank space between the value and the scale ("100MB" instead "100 MB"), as it is set in the header downmenu.
screen shot 2015-09-14 at 18 04 27

cc/ @xavijam

### PR DESCRIPTION
**Pull request by MariaCheca**
Closes #5507 

- No `min-width` property to show quota progress bar:
screen shot 2015-09-14 at 17 59 16

- User account views side menu width now is 260px:
screen shot 2015-09-16 at 10 44 30

- Float numbers for quota progress showing 2 decimal numbers (if any):
screen shot 2015-09-16 at 10 44 21

~~I was unable to separate value and value due to `number_to_human_size` doesn't allow to edit text format.~~ **Solved**

CR @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
Which enhancements? where is the screenshot? which staging server?

**Comment by xavijam** [comment]
Looks great, what about those changes over IE ?

**Comment by MariaCheca** [comment]
On my way to do them, I'll ping you when I'm finished :)

**Comment by MariaCheca** [comment]
Found some UI bugs running on IE10, working on them:

screen shot 2015-09-17 at 14 50 23

screen shot 2015-09-17 at 14 52 10

**Comment by xavijam** [comment]
go go go

**Comment by MariaCheca** [comment]
:sparkles:

**Pull request merged**
