### PR TITLE
When a new property is set, we have to check if any custom category is applied

### PR DESCRIPTION
**Pull request by javierarce**
Original issue: https://github.com/CartoDB/cartodb/issues/4642

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5585/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5586/))

**Comment by javierarce** [comment]
Have a look, @xavijam.

**Comment by xavijam** [comment]
Add a test please :)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5607/))

**Comment by javierarce** [comment]
:gift: added spec, please check again @xavijam.

**Comment by saleiva** [comment]
ping!

**Comment by javierarce** [comment]
This is a PR for a ticket of the new milestone.

**Comment by xavijam** [comment]
we need another spec we discussed yesterday :)

**Comment by saleiva** [comment]
bump!

**Comment by javierarce** [comment]
This is not urgent and is going to take me a while to add the spec needed, so I'm closing it to avoid getting spammed by the "bump" bot :dancers:

**Comment by saleiva** [comment]
closing without merging? why? How are you gonna remind?

**Comment by javierarce** [comment]
Because the original ticket is open.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5723/))

**Pull request closed without merging**
