### PR TITLE
Background importer + drag and drop mamufas ready

### PR DESCRIPTION
**Pull request by xavijam**
- Possibility to drag and drop files to be imported in the new dashboard.
- New background importer, supporting several uploads at the same time.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1324/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1330/))

**Comment by xavijam** [comment]
Thanks @cartofante, I'll wait the whole suite :)

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1332/))

**Pull request merged**
