### PR TITLE
Escape + and / symbols in Surrogate Keys on Varnish HTTP and Telnet invalidation - fixes #7868

### LINKED ISSUE #7868: Varnish invalidations triggers should escape special regex symbols
Steps to reproduce:
- have a table that ends with a surrogate key containing a `+` with an environmnet configured with 
- invalidate that table

The `+` on the [Varnish HTTP trigger](https://github.com/CartoDB/cartodb/blob/master/app/models/user/db_service.rb#L1311) is sent unescaped; causing the regex to incorrectly match.

We should make the script replace at least `+` by `\+` and any other base64 characters that match special regex chars.

### PR DESCRIPTION
**Pull request by zenitraM**
Fixes #7868.

I'm not entirely sure on how to make a spec for this, but I've tested manually (by crafting by brute force tables whose Surrogate-Key ends up containing + and /) and it works fine.

could you review @rochoa @luisico?   🙏😄

### CODE REVIEW

**Comment by xavijam** [comment]
Could we close this @luisbosque '

**Comment by zenitraM** [comment]
or, you know, merge it :D

**Comment by zenitraM** [comment]
@luisico @rochoa Closing this as I'm cleaning up open things on my GH, though this still might be a bug! 😅

**Comment by rochoa** [comment]
Who are you? 😂

**Comment by xavijam** [comment]
💃

**Pull request closed without merging**
