### PR TITLE
Several videoplayer fixes

### PR DESCRIPTION
**Pull request by javierarce**
See original issue: https://github.com/CartoDB/cartodb/issues/2958

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2647/))

**Comment by javierarce** [comment]
Have a look, @xavijam, please.

Also, this is the CSS change: https://github.com/CartoDB/cartodb.css/commit/4816584e33f98f6d07d920eccab5112888470247

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2680/))

**Comment by xavijam** [comment]
:uk:

**Pull request merged**
