### PR TITLE
Several new dashboard issues

### PR DESCRIPTION
**Pull request by xavijam**
- Filters order tooltips only displayed when filters view is not fixed
- Add hover/selected geometry type icons (finally images).
screen shot 2015-03-10 at 14 48 23
- Problem in OAuth page with form label in two lines.
- Filter tooltip, when element is fixed, doesn't appear correctly (it appears cut).
- Titles in error modals differ from non-error modals.

Fixes https://github.com/CartoDB/cartodb/issues/1786

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2171/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2172/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2173/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2177/))

**Comment by xavijam** [comment]
@CartoDB/frontend, what does it look like?

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2183/))

**Comment by xavijam** [comment]
@viddo or @javierarce, please. :)

**Comment by viddo** [comment]
:+1:  for me

**Comment by viddo** [comment]
More an observation than a comment-to-fix, since I added the LayoutIcon component because they icons are defined in the style guide and I notice that it was removed in this changeset. I added it because I thought it would be preferred to have the styles defined in the style guide implemented once and reused. I'm not sure that is the best approach though, but if not I would like to know your point of view?

**Comment by xavijam** [comment]
LayoutIcon is perfect, but with new changes done over DatasetsList-itemCategory, it doesn't make any sense to use it there. If so we need to override so many attributes.

**Comment by viddo** [comment]
Thanks for clarification :)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2189/))

**Pull request merged**
