### PR TITLE
wordsmithed confusing timezone text

### PR DESCRIPTION
**Pull request by csobier**
Text edit related to issue #7025. 

@iriberri , edited as discussed (except I did not make it Twitter specific, as this may appear in other areas).

### CODE REVIEW

**Comment by iriberri** [comment]
"Dates must be specified in GMT+0" or something similar :-) (or UTC directly, which is more "new")

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by iriberri** [comment]
:+1: here!

**Comment by csobier** [comment]
@xavijam , Carla and I want to apply a minor context update in the Editor (and I'll enhance the Twitter doc too, for consistency).  Okay if we merge this?

**Comment by xavijam** [comment]
:+1

**Pull request merged**
