### PR TITLE
#4462 bugfixed

### PR DESCRIPTION
**Pull request by Kartones**
Fixes https://github.com/CartoDB/cartodb/issues/4462

### CODE REVIEW

**Comment by Kartones** [comment]
@alonsogarciapablo CR please

**Comment by alonsogarciapablo** [comment]
I don't know much about sequel but your comments makes sense, so :+1: if it works.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5087/))

**Comment by Kartones** [comment]
works nice at staging \o/

**Pull request merged**
