### PR TITLE
Shows an error if the vis is private

### PR DESCRIPTION
**Pull request by javierarce**
Right now we can't make a map preview of a private visualization, so instead we show the error image of the map preview.

### CODE REVIEW

**Comment by javierarce** [comment]
@CartoDB/frontend: review this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1709/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1711/))

**Comment by viddo** [comment]
:+1:

**Comment by saleiva** [comment]
Ouch, this is something we didn't expect. We need a workaround

**Comment by javierarce** [comment]
Yeah, we didn't realised that we couldn't create thumbnails of private or password protected visualizations. We are talking about ways to solve this (using the api_key, auth token, etc)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1722/))

**Comment by javierarce** [comment]
@saleiva: https://github.com/CartoDB/cartodb/issues/2306

**Pull request merged**
