### PR TITLE
Removing hack for node 6.9.2 migration

### PR DESCRIPTION
**Pull request by xavijam**
Thanks to our system engineers, we don't need those suffixed shrinkwraps anymore. So, when we need to update our dependencies, we just have to run the previous command:

`npm run-script update-internal-deps`

That's all!

@CartoDB/frontend @jvillarf @azamorano

### CODE REVIEW

**Comment by nobuti** [comment]
happy-birthday

**Comment by alonsogarciapablo** [comment]
Thanks!

**Comment by xavijam** [comment]
Added the `.nvmrc` file in order to load this version automatically cc @nobuti .

**Comment by xavijam** [comment]
Merging and removing the "hack".

**Comment by xavijam** [comment]
Waiting until @jvillarf and @azamorano gives the 💚  light.

**Comment by azamorano** [comment]
:green_heart: from us!

**Comment by xavijam** [comment]
yay!

**Comment by xavijam** [comment]
Removing hack @CartoDB/frontend!

**Pull request merged**
