### PR TITLE
Refactor /api/v1/users/:user_id/assets

### LINKED ISSUE #3765: Refactor /api/v1/users/:user_id/assets
- [X] create route
- [x] refactor code (if needed)
- [x] create/adapt specs to be shared

Branch: `3765-refactor-assets-endpoint`

### PR DESCRIPTION
**Pull request by Kartones**
Closes #3765

### CODE REVIEW

**Comment by Kartones** [comment]
@juanignaciosl CR please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3961/))

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3962/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3963/))

**Comment by juanignaciosl** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3965/))

**Pull request merged**
