### PR TITLE
Delete user enabled for standard or organization users

### LINKED ISSUE #2728: Clicking on the "Data library" link on the create modal removes the number on the shared datasets

### PR DESCRIPTION
**Pull request by xavijam**
- New delete modal window (for standard or organization user).
- Make it work with the backend part.
- Delete button for organization user.

Also:
- Fixes 'shared' datasets count within visualization API.

Fixes https://github.com/CartoDB/cartodb/issues/2622.
Fixes https://github.com/CartoDB/cartodb/issues/2714.
Fixes #2728.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2218/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2248/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2251/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2252/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2253/))

**Comment by xavijam** [comment]
retest this please

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2261/))

**Comment by xavijam** [comment]
@juanignaciosl, once tests pass, we will go live :dancer:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2263/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2264/))

**Comment by xavijam** [comment]
ring ring @iriberri and @juanignaciosl :)

**Comment by iriberri** [comment]
ring ring, :banana: :phone:  :notes:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2269/))

**Pull request merged**
