### PR TITLE
Escape filename when downloading exports

### LINKED ISSUE #7565: S3 download of files with comma fail
STR:

1. Create a map named "This, then"
2. Export it.

It fails because of the comma in the name.

cc @gfiorav @javitonino @xavijam

### LINKED ISSUE #7672: Wrong map export name on Firefox
When downloading a map export using Firefox, the filename is truncated at the first space. So if the map has spaces in its name, it will only have the first word of the map name. It neves has date nor .carto extension (so you cannot reimport it without renaming it first).

cc @gfiorav

### PR DESCRIPTION
**Pull request by javitonino**
Closes #7672 
Closes #7565 

Bit of escaping solves everything

### CODE REVIEW

**Comment by javitonino** [comment]
Can you CR @gfiorav ?

**Comment by javitonino** [comment]
ping @gfiorav

**Comment by gfiorav** [comment]
Sorry! Forgot, doing it now

**Comment by gfiorav** [comment]
📦 it!

**Pull request merged**
