### PR TITLE
Adds X-Frame-Options for embedded maps

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes [#99](https://github.com/CartoDB/cartodb-platform/issues/99)

Please CR @Kartones :)

cc @zenitraM @javisantana

### CODE REVIEW

**Comment by Kartones** [comment]
:+1:

**Comment by gfiorav** [comment]
@Kartones like we spoke, I extended securization to all `/admin`. Please give a final :+1: so I can deploy! Thanks! :smiley:

**Comment by xavijam** [comment]
Probably arriving late to this party, but, what about redirecting those public_maps embeded pages to the embed_map page?

**Comment by gfiorav** [comment]
@xavijam AFAIK this can only be detected in the client side. Maybe we could create another ticket for the frontend to implement the redirection on public maps upon detection of being embedded? That would save all the grey boxes

**Comment by xavijam** [comment]
Ok :+1:, in my opinion we should do that before merging this thing, shouldn't we?

**Comment by Kartones** [comment]
:+1: to the code. 

And yep, this is for client-side, especifically for the browsers, we cannot control serverside if a page is inside a frame :disappointed:

**Comment by xavijam** [comment]
Go ahead, no more to say.

**Pull request merged**
