### PR TITLE
Showing/hiding layers

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Close https://github.com/CartoDB/cartodb/issues/7830#event-691650936.

@piensaenpixel I'm using the `CDB-IconFont-eye` and `CDB-IconFont-eyeDisabled` for the icons... The first one works but doesn't look very nice and we have to add the second icon to CartoAssets. Can you please take care of this? Thanks 💋

### CODE REVIEW

**Comment by piensaenpixel** [comment]
sure i take care now

**Comment by javisantana** [comment]
could we merge this and do the styling afterwards?

**Comment by alonsogarciapablo** [comment]
Yes. Working on it.

**Comment by alonsogarciapablo** [comment]
Deployed. Thanks @piensaenpixel

**Pull request merged**
