### PR TITLE
Allow creating categories from boolean columns

### LINKED ISSUE #8496: [FILL COMPONENT] Category styling doesn't work with more than 10 categories

### PR DESCRIPTION
**Pull request by javierarce**
Fixes #8496

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam

**Comment by xavijam** [comment]
:es:

**Comment by saleiva** [comment]
DALE!

**Comment by javierarce** [comment]
I'll fix the conflicts, but let's wait until rochoa finishes his work in turbo-carto before merging.

**Comment by xavijam** [comment]
Ready to be merged (after conflicts)?

**Comment by javierarce** [comment]
I'll have a look.

**Pull request merged**
