### PR TITLE
3987 adding jsonp response to oembed

### PR DESCRIPTION
**Pull request by stuartlynn**
Adding jsonp response to oembed controller in response to #3987. Added tests to check that both jsonp and json responses function as expected.

@xavijam @javierarce @viddo This is my first pull request for CartoDB can you review and comment for style etc?

### CODE REVIEW

**Comment by xavijam** [comment]
Superb @stuartlynn! Adding @javisantana as reviewer.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4377/))

**Comment by javisantana** [comment]
nice @stuartlynn, next time ping someone in @CartoDB/backend

**Comment by Kartones** [comment]
:+1:

**Comment by saleiva** [comment]
bump! @Kartones merge it!

**Pull request merged**
