### PR TITLE
Override analysis based on natural id

### LINKED ISSUE #8764: Analysis ids can't be duplicated for the same visualization
Analysis ids can't be duplicated for the same visualization. In case of duplication, keep the newest.

From #6856. cc @viddo

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #8764.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
@javitonino CR this, please.

cc @viddo

**Comment by viddo** [comment]
👍

**Comment by javitonino** [comment]
A couple of comments:
 - This only checks the top level ID of the analyses. So we can still have duplicated analyses trees. For example, if A3 is persisted, and a new request arrives to create A4, it will create a new one, not update A3 (which would make sense, I think). I guess the behaviour with this PR is enough, but I wanted to mention it.
 - This opens the door to marking the natural_id index as unique (including visualization_id).

Anyway, code LGTM. If we are all aware of the first comment, I'd say merge this as it is now, as complete checking of subtrees is more complicated and maybe unnecessary (could be done efficiently with jsonb in postgres 9.5, but probably not on 9.3).

**Comment by juanignaciosl** [comment]
@javitonino yep, baby steps. In addition, we're likely to redesign part of the API and it might be affected. Anyway, added at #8788.

**Comment by viddo** [comment]
@javitonino 

> This only checks the top level ID of the analyses. So we can still have duplicated analyses trees.

True, but this gets really complicated to handle client-side. As I mentioned [in a parent issue (#6856)](https://github.com/CartoDB/cartodb/issues/6856#issuecomment-231791751), right now there's one analysis persisted per layer to KISS implementation of the remove-layer and drag'n'drop-analysis-to-create-layer user actions. 
I'm open to change this premise but then we need to figure out how to avoid duplicated logic of when/how analysis should be persisted.

**Pull request merged**
