### PR TITLE
Set higher contrast for nav buttons

### LINKED ISSUE #2429: Low contrast in the lateral nav arrows.

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2429 

Default color is now `#BBB`, and `#888` on hover, e.g.:

screen shot 2015-03-10 at 15 53 50
screen shot 2015-03-10 at 16 06 46
screen shot 2015-03-10 at 16 09 44
screen shot 2015-03-10 at 16 09 47
screen shot 2015-03-10 at 16 09 53

### CODE REVIEW

**Comment by viddo** [comment]
ping @saleiva @carlostallon, and @xavijam for CSS changes.

Btw, if these buttons are considered to have low contrast you should probably review other components that have the [same color](https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=%23ccc), no?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2188/))

**Comment by saleiva** [comment]
It really depends on the size of the elements. I'd merge this and see if we detect anything else later

**Comment by viddo** [comment]
Sounds good, yeah, I was going to suggest to create new issues in that case, just wanted to make sure you were aware :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2192/))

**Comment by viddo** [comment]
bump, good to go?

**Pull request merged**
