### PR TITLE
Forcing null for empty tags hopefully fixes #3252

### LINKED ISSUE #3252: Fix Explore API empty tag load
```
PG::Error: ERROR:  cannot determine type of empty array
LINE 1: ...11e4-8b89-0e49835281d6', 'isavia', NULL, 'table', ARRAY[], '...
                                                             ^
HINT:  Explicitly cast to the desired type, for example ARRAY[]::integer[].
````

### PR DESCRIPTION
**Pull request by juanignaciosl**
@rafatower or @Kartones , CR this fix for #3252, please. I haven't been able to reproduce it locally.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3087/))

**Comment by Kartones** [comment]
:+1:

**Comment by rafatower** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3089/))

**Pull request merged**
