### PR TITLE
Fixed published date too long copy

### LINKED ISSUE #9804: Change copy "Published a few seconds ago" on layer view
Hi!

Whenever you publish changes, the message "Published a few seconds ago", creates two lines.   

screen shot 2016-09-19 at 11 08 46

Can you change it to "Published seconds ago" to keep it in one line? 

screen shot 2016-09-19 at 11 09 11

Thank you!

### PR DESCRIPTION
**Pull request by MariaCheca**
Fixes #9804 

Added ellipsis and max width to the div containing the text for `'Published x time ago'` text.

screen shot 2016-09-27 at 17 18 25

CR @piensaenpixel

### CODE REVIEW

**Comment by MariaCheca** [comment]
ping @piensaenpixel please

**Comment by piensaenpixel** [comment]
🇪🇸

**Comment by piensaenpixel** [comment]
wait :) can we use the helper?

**Comment by MariaCheca** [comment]
Helper added! thanks @piensaenpixel :)

**Pull request merged**
