### PR TITLE
Fix style issues

### PR DESCRIPTION
**Pull request by Jesus89**
### Related to:
- https://github.com/CartoDB/support/issues/1619
- https://github.com/CartoDB/support/issues/1607
- https://github.com/CartoDB/support/issues/1617

### Fix max-width text inputs

selection_176
selection_177

### Fix column range width

selection_178

### Fix choropleth legends margin: https://github.com/CartoDB/carto.js/pull/2157
selection_179

### CODE REVIEW

**Comment by Jesus89** [comment]
@ramiroaznar I leave the staging deploy in the oven for tomorrow...

**Comment by Jesus89** [comment]
@ramiroaznar ready!

https://carto-staging.com/login

user: styles
pass: styles123

**Comment by ramiroaznar** [comment]
*NO LGTM:*

The *text boxes* in LEGENDS and other analysis (i.e. Create centroids from geometries) are shorter:

image

image

The issues related to the style point size by decimal values and legends looks good to me.

**Comment by Jesus89** [comment]
Re-deployed. Please test it again ;). Thanks

https://carto-staging.com/login

user: styles
pass: styles123

**Comment by ramiroaznar** [comment]
LGTM!

**Comment by Jesus89** [comment]
:rocket:

**Pull request merged**
