### PR TITLE
Adds static maps export dialog

### PR DESCRIPTION
**Pull request by javierarce**
This PR introduces the new Static maps export dialog, that allows to request an image of the map the user is working on. 

### Important files

- [static_image_dialog.js](https://github.com/CartoDB/cartodb/blob/84adbec35bee383b75bc52d54ec7f181089f6bab/app/assets/stylesheets/table/static_image_dialog.css.scss)
- [static_image_dialog.css.scss](https://github.com/CartoDB/cartodb/blob/84adbec35bee383b75bc52d54ec7f181089f6bab/app/assets/stylesheets/table/static_image_dialog.css.scss)
- [mapview.js](https://github.com/CartoDB/cartodb/blob/84adbec35bee383b75bc52d54ec7f181089f6bab/lib/assets/javascripts/cartodb/table/mapview.js)

### Screenshots

export_01
export_02
export_03
export_04

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1540/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1542/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1571/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1581/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1585/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1586/))

**Comment by javierarce** [comment]
Could you please review it, @CartoDB/frontend & @CartoDB/design?

**Comment by javierarce** [comment]
Could you please review it, @CartoDB/frontend & @CartoDB/design?

**Comment by saleiva** [comment]
+1

**Comment by viddo** [comment]
Code wise looks legit :+1: 
Only one question, _Don't forget to give proper attribution:_, where/how should one "give proper attribution"?

**Comment by javierarce** [comment]
Thanks, @viddo! 

Regarding the attribution: I guess it's up to them (they could add it on top of the map, next to it, in an index, etc.), but maybe we could clarify the importance or the need to do that or extend a little the information we give them. What do you think, @saleiva, @jatorre, @javisantana, @andrewxhill?

**Comment by andrewxhill** [comment]
No, I think it is enough!

**Comment by javisantana** [comment]
:es: please, update news if needed and merge

**Comment by saleiva** [comment]
Can we prioritize this?

**Comment by saleiva** [comment]
Hey @andrewxhill we might want to do a blogpost, right? We take care of the assets.

**Comment by andrewxhill** [comment]
totally!

On Tue, Feb 17, 2015 at 10:14 AM, saleiva <notifications@github.com> wrote:

> Hey @andrewxhill <https://github.com/andrewxhill> we might want to do a
> blogpost, right? We take care of the assets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/2199#issuecomment-74682962>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by javierarce** [comment]
@saleiva: I'm going to release a new version of cartodb.js, release to production and then I'll take care of this.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1701/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1702/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1707/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1712/))

**Comment by javierarce** [comment]
Released!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1719/))

**Comment by matallo** [comment]
\o/

**Pull request merged**
