### PR TITLE
Repositions view to inbounds coordinates when adding a new feature

### LINKED ISSUE #3507: Editing a map is not centering it in the "initial map"
If you have a table with geometries and you move the world a couple of times to any side, clicking on "add feature" should move the map to the center (according to @javisantana).

This is not happening, so when you add a feature:
1. It's appearing in the table as a new record, with coordinates out of bounds (+-180)
2. It's not appearing in the map because the_geom_webmercator is generated as null

### PR DESCRIPTION
**Pull request by fdansv**
Fixes #3507 

@javisantana

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3805/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3806/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3808/))

**Comment by saleiva** [comment]
\o/

**Comment by javisantana** [comment]
@viddo review please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3824/))

**Comment by viddo** [comment]
Not much to review, but looks legit, although I must say I don't know these concepts to really value if the changes is "good" or not. 
Also for the future, probably better to review before merging. ;)

**Pull request merged**
