### PR TITLE
Region mandatory

### LINKED ISSUE #12354: Make the Region dropdown mandatory
Right now we have this implementation:

screen shot 2017-06-20 at 10 39 24

After the yesterday's agreement, we should not let the user select a measurement until a region is selected. So our proposal here is don't display the measurements list until a region is selected.
What do you think @saleiva? 
cc @nobuti

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #12354.

mandatory-region

### CODE REVIEW

**Comment by xavijam** [comment]
We should change the SQL in order to obtain the available regions in our infrastructure. Could you help us here @CartoDB/builder-backend ?

**Comment by juanignaciosl** [comment]
We've been doing some research for this. There is one "working" (more on this, later) solution, using *obs_getavailablenumerators*:

```sql
gis=# explain analyze select * from (SELECT jsonb_object_keys(numer_tags) as x FROM cdb_observatory.obs_getavailablenumerators(st_makeEnvelope(-180,-90,180,90,4326))) a where a.x like 'section/%' group by a.x;
                                                                      QUERY PLAN                                                                                                                     
-------------------------------------------------------------------------------------------------------------------------------------------------------
 HashAggregate  (cost=1759.00..1759.01 rows=1 width=32) (actual time=2639.981..2639.982 rows=12 loops=1)
   Group Key: a.x
   ->  Subquery Scan on a  (cost=0.25..1757.75 rows=500 width=32) (actual time=2494.869..2630.706 rows=17845 loops=1)
         Filter: (a.x ~~ 'section/%'::text)
         Rows Removed by Filter: 79195
         ->  Function Scan on obs_getavailablenumerators  (cost=0.25..507.75 rows=100000 width=32) (actual time=2494.863..2606.775 rows=97040 loops=1)
 Planning time: 0.137 ms
 Execution time: 2640.762 ms
(8 rows)
```

The problem is that the query, as you see, takes more than 2.5 seconds, which is prohibitive for this.


This is the "good" solution:

```sql
gis=# explain analyze select * from observatory.obs_tag where type = 'section';
                                             QUERY PLAN                                             
----------------------------------------------------------------------------------------------------
 Seq Scan on obs_tag  (cost=0.00..4.25 rows=9 width=121) (actual time=0.012..0.035 rows=12 loops=1)
   Filter: ((type)::text = 'section'::text)
   Rows Removed by Filter: 88
 Planning time: 0.075 ms
 Execution time: 0.057 ms
(5 rows)
```

The problem is that this requires q new function in the extension, which is not something that we can do _that_ quick. Can you continue with this PR without that, and later we'll add the improvement?

**Comment by xavijam** [comment]
👍, could we create a ticket for that please?
Thanks for the research and info mates.

**Comment by xavijam** [comment]
Merging and waiting for the backend one 💋 .

**Comment by ethervoid** [comment]
Oh I though you're going to change the query with what we said in the ticket. I'll take care of it :)

**Pull request merged**
