### PR TITLE
fix perfect scrollbar width in carousel

### PR DESCRIPTION
**Pull request by matallo**
re: https://github.com/CartoDB/cartodb/issues/11018

better set the min width in the perfect scrollbar initialization than in the CSS

scroll

### CODE REVIEW

**Comment by xavijam** [comment]
Hey, could we fix the basemaps list scroll? It is the same bug...

**Comment by matallo** [comment]
fixed in the same PR 🙌 

scroll

**Comment by xavijam** [comment]
Grande!

**Comment by xavijam** [comment]
Running on-premises tests again, acceptance passed.

**Pull request merged**
