### PR TITLE
Added Mapbox client token

### LINKED ISSUE #13425: Add Mapbox client keys
Pretty much the same as https://github.com/CartoDB/cartodb/issues/12296 but for the Mapbox Access token

### PR DESCRIPTION
**Pull request by antoniocarlon**
Closes #13425

Note for the acceptance: we must see a JavaScript variable `mapboxApiKey` with the configured API key

### CODE REVIEW

**Comment by antoniocarlon** [comment]
cc: @ivanmalagon

**Comment by ethervoid** [comment]
@elenatorro or @nobuti could you take a look to this CR. Thank you!

**Comment by nobuti** [comment]
Done!

**Comment by antoniocarlon** [comment]
We will get rid of the mapzenApiKey as soon as we complete the migration

**Comment by javitonino** [comment]
Deploying the changes, but we still need to update configuration: https://github.com/CartoDB/cartodb-management/issues/5090

**Pull request merged**
