### PR TITLE
Codecov workflow

### PR DESCRIPTION
**Pull request by gonzaloriestra**

### CODE REVIEW

**Comment by alrocar** [comment]
@gonzaloriestra Will this PR supersede https://github.com/CartoDB/cartodb/pull/15079?

**Comment by gonzaloriestra** [comment]
@alrocar, yes this one now includes the other. I've closed the old one.

**Comment by gonzaloriestra** [comment]
The codecov report is generated when passing the tests, so it should be uploaded after that (added to the google cloud builds). Right now it's not finding a report to upload because it's run on an isolated worker.

**Comment by gonzaloriestra** [comment]
https://blog.codecov.io/2020/04/21/new-test-only-what-you-change-with-carryforward-flags/

**Pull request closed without merging**
