### PR TITLE
Complete missing dataservice configuration rake tasks

### LINKED ISSUE #11777: Rake task for soft geocoding limits
Hi guys,

related with ticket https://github.com/CartoDB/onpremises/issues/273 it would be nice to have a **rake task** to set **soft geocoding** limit values per user:

````
soft_here_isolines_limit
soft_obs_general_limit
soft_obs_snapshot_limit
soft_mapzen_routing_limit
````

Thanks!

### LINKED ISSUE #11823: Support mapzen_routing_quota on set_org_quota rake
## Description

**Related ticket**: https://github.com/CartoDB/onpremises/issues/273

Hi,

we've realized today that the following rake tasks are outdated, since they doesn't support ```mapzen_routing_quota```:
- ```set_user_quota```: https://github.com/CartoDB/cartodb/blob/master/lib/tasks/services.rake#L64
- ```set_org_quota```: https://github.com/CartoDB/cartodb/blob/master/lib/tasks/services.rake#L90

Would you please update them to support ```mapzen_routing_quota```? I'm not sure if there is any other **quota** variable that i could be missing. Is there any for **mapzen isolines**?

The parent ticket belongs to the **Onpremises LDS** milestone, so if possible, this ticket should be implemented by April, 7th.

Thanks a lot.

### PR DESCRIPTION
**Pull request by jgoizueta**
Fixes #11777
Fixes #11823

### CODE REVIEW

**Comment by jgoizueta** [comment]
@rafatower if you care to take a final look, I've cleaned up the code to comply with hound (and tidied up things a bit while I was at it) and added some documentation.

**Comment by rafatower** [comment]
:+1:

**Comment by jgoizueta** [comment]
Acceptance plan:

This could be performed in staging, with some staging user with a proper dataservices configuration (ping me if you need assistance with this).

Check the user configuration using the `cdb_dataservices_client.cdb_service_quota_info()` function; then use all of the six following rake tasks to make configuration changes and check with said SQL function that the changes are effective.

* ``cartodb:services:set_user_provider[username,service,provider]``
* ``cartodb:services:set_organization_provider[orgname,service,provider]``
* ``cartodb:services:set_user_quota[username,service,quota]``
* ``cartodb:services:set_org_quota[orgname,service,quota]``
* ``cartodb:services:set_user_soft_limit[username,service,soft_limit_status]``
* ``cartodb:services:set_org_soft_limit[orgname,service,soft_limit_status]``

It should be also checked that when not passing one of the parameters or when passing invalid values a proper error message is shown, and the configuration isn't changed.

The `mapzen_routing` service must be explicitly tested for changing its quota and soft limit.

**Comment by jgoizueta** [comment]
Acceptance approved!! Everything working as expected in staging tests.

**Comment by jvillarf** [comment]
@jgoizueta sorry to bring bad news again... There is an issue around (https://github.com/CartoDB/cartodb/commit/575e5ce446ca5972097f0f965fc85d4b46324c60#diff-b9a50e367735318a20a042098a0be3fcL148)

```` bash
# sudo su - carto -s /bin/bash -c "cd /opt/carto/builder/embedded/cartodb ; RAILS_ENV=production RAILS_CONFIG_BASE_PATH=/data-builder/production/config/builder RAILS_LOG_BASE_PATH=/data-builder/log/builder SUBDOMAIN=carto PASSWORD=location EMAIL=carto@example.com /opt/carto/builder/embedded/bin/bundle exec rake cartodb:services:set_org_soft_limit['organization',geocoding,true]"
rake aborted!
undefined method `soft_geocoding_limit=' for #<Organization:0x00000006d35e18>

Tasks: TOP => cartodb:services:set_org_soft_limit
(See full trace by running task with --trace)
````

**Comment by jgoizueta** [comment]
This is rather lame: I implemented a rake task to set a configuration parameter that doesn't exist 😞 

Service **soft limits** are only per-**user** parameters. There are columns for soft limits in the users tables of central and metadata and the values are stored in redis too. But organization soft limits are not a thing: such parameters do not exist!

You can only enable soft limits for a given service to individual users, not for a whole organization.

I'm very sorry for this time-wasting confusion; please do not use the `set_org_soft_limit`. I'll proceed to remove any trace of it from the code and documentation and thus bury this shameful episode as soon as possible.

**Comment by jvillarf** [comment]
Ok, cristal clear now!!! Thanks @jgoizueta

**Pull request merged**
