### PR TITLE
Add new design for OAuth consent screen

### PR DESCRIPTION
**Pull request by VictorVelarde**
### Tasks
Screen 1. "When the user is asked for one":
- [x] Basic style
- [x] Avatars
- [x] Guard clauses to enable / disable UI partials
- [x] Dynamic scopes

Screen 8. "Error":
- [x] Basic style
- [x] Dynamic error

We have also implemented some other tasks (for the rest of screen states, nº 2 to nº 7):
- [x] icons per scope category and scope
- [x] collapsable sections
- [x] fix font issues (--> cartoassets v0.2.5)

### Acceptance
- [x] Pablo's tests at staging
- [x] Design review from Emilio

---

### Current status

pretty_oauth

### CODE REVIEW

**Comment by VictorVelarde** [comment]
@javitonino screens for states nº 1 and nº 8 are quite ready. 

We have just a few points to talk together (basically to agree on some common variables) so we can finish them:
1. good / wrong request (errors variable?)
2. application data: name, creator and avatar
3. scope (dynamic, structure?)

**Comment by alonsogarciapablo** [comment]
cc: @piensaenpixel @urbanphes

**Comment by VictorVelarde** [comment]
`OpenSans` font family was already included in *CartoAssets*, but not `Montserrat`. We are going to add it in that project, to easily consume it from this screen

**Comment by VictorVelarde** [comment]
Hi @javitonino, the new `cartoassets` v0.2.5 should deal with the missing font problem we saw. To update the package locally run `npm update cartoassets`

**Comment by alonsogarciapablo** [comment]
@VictorVelarde Screen looks really nice! I'm only missing one thing: the `Hey Ho, Lets Go!` permission 😉. I'm checking out the branch locally to give it a try!

**Comment by alonsogarciapablo** [comment]
I'm testing this and I discovered that `icon_url` field cannot be empty/null. IMO not every app will have an icon so I would make it optional and provide some sort of placeholder icon for those cases.

**Comment by VictorVelarde** [comment]
There is already an empty placeholder designed for "unknown app" that might work, but now it is reserved for 'error screen'. It is just a simple gray circle [here](https://github.com/CartoDB/cartodb/blob/14221-oauth_pretty_consent/app/assets/images/oauth_provider/unknown_app_avatar.svg)). 

If we want that change, @javitonino and me should make some changes (`_avatars.html.erb`)

**Comment by javitonino** [comment]
I always prefer to have everything not-null at the beginning. If we figure out that we need a default icon, I prefer to add that at creation time (set a default placeholder in the UI) than at display time.

**Comment by alonsogarciapablo** [comment]
Attaching a couple of screenshots here so that @piensaenpixel can check it out:

screen shot 2018-08-21 at 11 55 14

screen shot 2018-08-21 at 11 55 23

Thank you! ❤️

**Comment by alonsogarciapablo** [comment]
Thanks for your feedback @piensaenpixel!

**Comment by VictorVelarde** [comment]
Hi @alonsogarciapablo and @piensaenpixel. I have fixed the design issues detected in your revision, and I made a new deployment (same staging: `oauth-consent-screen`).

Here it is how it looks now:

image

Some notes:
- The font-weight was wrong, and it looks lighter now as it should.
- I have removed *cartoassets.css* from the page, making the css much smaller.
- I added an hyperlink to "Powered by CARTO".

If everything is fine and you give your acceptance, we could try to merge this in for the current cycle.

**Comment by alonsogarciapablo** [comment]
Thanks @VictorVelarde! I only noticed that the `chevron--up` is not quite vertically aligned with the text:

screen shot 2018-08-24 at 10 31 56

Let's see what @piensaenpixel says!

**Comment by VictorVelarde** [comment]
That definitively must be aligned!

**Comment by VictorVelarde** [comment]
If your fine with this, then we'll ask @javitonino or @alrocar to merge the PR, to deal confidently with some recent backend changes.

**Comment by alonsogarciapablo** [comment]
@piensaenpixel approves, so 👍. Great job @VictorVelarde!

**Comment by VictorVelarde** [comment]
Thx for making it green again @javitonino 😄

**Pull request merged**
