### PR TITLE
Fix logic for render.

### LINKED ISSUE #9677: Loading state for DATA panel
I'm missing the blue loader bar @piensaenpixel introduced some time ago, and also I miss the placeholder we used to use for other panels, like in the styles. It would be great to add it back 💋 .

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #9677.
This is In ded06.

cc @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
Preview? :)

**Comment by nobuti** [comment]
data-loading

and the photo finish:

screen shot 2016-09-06 at 12 21 33

**Comment by xavijam** [comment]
:joy:, that's a good one, Bolt won.

**Comment by xavijam** [comment]
:es:

**Pull request merged**
