### PR TITLE
1462 make sure geocoder ui sends correct queries

### LINKED ISSUE #1462: Make sure geocoder UI sends correct queries to nokia/here API
Numbers are pretty bad for high-res geocoding in terms of geocoded rows. Make sure stats and queries are ok or fix them if they are not.

### PR DESCRIPTION
**Pull request by juanignaciosl**
@xavijam CR this, please. It fixes #1462 , you have a LONG discussion with for more information.

Additional info for QA test:
* What has changed:
  * Only the pattern sent to the backend for high-resolution geolocation.
* What I think should be tested additionally, at least:
  * Smoke tests about high resolution geolocation.
  * High resolution geolocation request with close data: a couple of points in the same street should be located close but not together.
  * High resolution geolocation request with not high resolution information: a couple of rows in the same street, without number, must be placed together.
  * High resolution geolocation requests with different combinations of fields for correct data. Results should be "good enough".
    * 5 fields.
    * 4 fields.
    * 3 fields.
    * Every combination of 2 fields.
  * High resolution geolocation requests with wrong data: nulls, not maching (numbers in country field, for example...). Geolocation must not work, but in a user-friendly way.

There's no need for bulk testing,

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details]())

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1290/))

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1312/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1316/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1318/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1320/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1322/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1323/))

**Pull request merged**
