### PR TITLE
If a KML dont have id in a document style now raises an error

### LINKED ISSUE #4822: Show a better user import error for: ERROR Parseing kml Style: No id
It's being common these days the import error `ERROR Parseing kml Style: No id`. After taking a look at the KML Style specification (https://developers.google.com/kml/documentation/kmlreference?hl=en#style) it seems that style tags must have an ID, but we're receiving some files that haven't.

cc @ethervoid

### PR DESCRIPTION
**Pull request by ethervoid**
We have customized this kind of error to improve the feedback to the user

Fixes #4822 

Please @Kartones review this PR :)

### CODE REVIEW

**Comment by Kartones** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5516/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5517/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5521/))

**Pull request merged**
