### PR TITLE
Adds new "confirm type change" modal

### PR DESCRIPTION
**Pull request by javierarce**
screen shot 2015-06-22 at 12 32 33

Original ticket: https://github.com/CartoDB/cartodb/issues/4110

### CODE REVIEW

**Comment by javierarce** [comment]
@viddo: can you review this thing, please?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4465/))

**Comment by viddo** [comment]
Considering it's a type change and not a destructive action like a delete, perhaps we should use the "warning" styles instead? E.g. like a dataset rename:
screen shot 2015-06-22 at 13 08 09

**Comment by viddo** [comment]
cc @saleiva

**Comment by saleiva** [comment]
+1 viddo

**Comment by javierarce** [comment]
Oops, sorry. Fixed.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4469/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4470/))

**Comment by viddo** [comment]
:ok:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4476/))

**Pull request merged**
