### PR TITLE
append_from_importer and append_to_table are no longer used, removing…

### LINKED ISSUE #4649: Table#append_to_table
I've found something strange while testing Ruby 2.2.2. `Table#append_to_table`:

new_schema        = from_table.schema(reload: true)
new_schema_hash   = Hash[new_schema]

That should extract a table schema into a hash. Test example output:

[[:cartodb_id, "number"], **[:the_geom, "geometry", "geometry", "geometry"]**, [:artistas, "string"], [:club_id, "number"], [:club_imagen, "string"], [:club_nombre, "string"], [:direccion, "string"], [:direccion_completa, "string"], [:estilo, "string"], [:fecha, "date"], [:horario, "string"], [:id_evento, "number"], [:nombre, "string"], [:pais, "string"], [:poblacion, "string"], [:provincia, "string"], [:created_at, "date"], [:updated_at, "date"]]

Take a look at bold text. With geometry types row tuple has 4 elements. With Ruby 1.9.3 `Hash[new_schema]` dismisses that tuple (since it hasn't 2 elements he can't convert to key --> value) O_o.

Nevertheless Ruby 2.2.2 crashes: 
`*** ArgumentError Exception: invalid number of elements (4 for 1..2)`.

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #4649. @javisantana , table merge was previously done with this code? Now it's done with the SQL API, and I can't find any usage of these methods. :fire: ? Both fail with Ruby 2.2.2 because of the problem explained in #4649.

cc @Kartones @rafatower @ethervoid

### CODE REVIEW

**Comment by javisantana** [comment]
table merge never worked actually, it's curious because we had it like for 2 years disabled in the editor XD

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5354/))

**Comment by juanignaciosl** [comment]
I think you mean _append_, because _dataset merge_ is a working icon at bottom right of the editor.

Deleting then.

**Comment by Kartones** [comment]
go for it :fire:

**Comment by ethervoid** [comment]
:shipit:

**Comment by javisantana** [comment]
yes, append :rambo:

**Comment by rafatower** [comment]
:fire:

**Pull request merged**
