### PR TITLE
Fix dataset preview

### LINKED ISSUE #9672: Map preview not working after importing a dataset
### STR
1. Create a dataset, for example using one from Data library (I used `ny_policeprecints` dataset).
2. Go to the dataset view (if you are not there yet).
3. Open chrome console.
4. Click over preview button.
5. Dataset features are not rendered, check console.

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #9672 

Related Cartodb.js issue: https://github.com/CartoDB/cartodb.js/issues/1403

Backend CR please @juanignaciosl 
Can you have a look at the front @xavijam ?

### CODE REVIEW

**Comment by xavijam** [comment]
:+1: by the way, the ticket related for CartoDB.js, could you point me to that one please? 💋

**Comment by gfiorav** [comment]
@xavijam I updated the description 💋

**Comment by xavijam** [comment]
:es: 💋  🚢 🇮🇹

**Comment by juanignaciosl** [comment]
LGTM 👍

**Pull request merged**
