### PR TITLE
Styles selects and input numbers

### PR DESCRIPTION
**Pull request by javierarce**
Adds a temporary style for selects and customises number input.

screen shot 2016-02-23 at 18 14 40
screen shot 2016-02-23 at 18 14 46

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam 
CC: @piensaenpixel

**Comment by xavijam** [comment]
Oh `cartodb_id` appears with the system style :P.

**Comment by xavijam** [comment]
:+1: :dancer: :dancers: :100: :top:

**Comment by javierarce** [comment]
Damn, didn't notice… fixing it.

**Comment by javierarce** [comment]
Fixed! :relaxed:

**Pull request merged**
