### PR TITLE
Point to developer center instead old docs

### PR DESCRIPTION
**Pull request by IagoLast**
https://github.com/CartoDB/design/issues/1328
---

@jesusbotella @rjimenezda does this affect to the migration in some way?

### CODE REVIEW

**Comment by jesusbotella** [comment]
Yes, we'll need to check if there is any other link pointing to the developers section in the pages that are not merged yet. You have already changed the links that I can think of at a first glance, but there can be more that I am not aware of.

**Comment by rubenmoya** [comment]
What's the status of this? Is it ready to move forward?

**Comment by IagoLast** [comment]
@rubenmoya I think the links covered in the issue are fixed but probably there are some other needs that can be replaced

**Comment by elenatorro** [comment]
LGTM 👌

**Pull request merged**
