### PR TITLE
Fix scroll-view margin

### PR DESCRIPTION
**Pull request by rubenmoya**
Related to: https://github.com/CartoDB/cartodb/issues/13308

All the paddings in ScrollView are `18px`, by having the `margin-top: 19px` we were off by `1px`

### CODE REVIEW

**Comment by matallo** [comment]
So, the problem at hand is that the analysis placeholder doesn't have a scrollview, thus the margin difference

Besides changing the margin in the ScrollView I'd also add the scrollview to the analysis placeholder, just for consistency with every other panel view

how does that sound?

**Comment by rubenmoya** [comment]
Sounds good! Maybe we should revisit the panel view in the future so everything inside is a ScrollView by default.

**Comment by matallo** [comment]
that sounds awesome, add it now just for this, or review the whole panel view, up to you!

**Comment by rubenmoya** [comment]
So, it seems like the `ScrollView` expects a proper `Backbone.View`, I've tweaked it a little bit so it also accepts templates, and it renders perfectly, the problem comes when cleaning the subviews, as it is just a template, it doesn't have the `clean` method. I'm not sure how to approach this, it feels weird to modify both, the `ScrollView` and the `CoreView` to make it work, the other alternative I can think of is creating a view for each template (we have 2 currently), what do you think @matallo?

**Comment by rubenmoya** [comment]
Deployed in `ded13` could you have a look @urbanphes?

**Comment by urbanphes** [comment]
Yeah! The button placement is perfect!
GO

**Pull request closed without merging**
