### PR TITLE
Disable tests for organization user mover

### PR DESCRIPTION
**Pull request by gfiorav**

### CODE REVIEW

**Comment by gfiorav** [comment]
All backend tests are 🍏 , @azamorano 

I'll merge this on your and @javitonino approval.

**Comment by azamorano** [comment]
Thanks! :+1: 

/cc @santisaez

**Comment by gfiorav** [comment]
No problem 😄, will merge tomorrow morning and advise every open PR to merge
master.

On May 12 2016, at 7:17 pm, Antonio Zamorano &lt;notifications@github.com&gt;
wrote:  

> Thanks! 

>

> /cc [@santisaez](https://github.com/santisaez)

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/CartoDB
/cartodb/pull/7390#issuecomment-218824865)

**Comment by javitonino** [comment]
:+1: Don't forget to enable them back when fixed!

**Comment by santisaez** [comment]
FYI: org tests issues fixed, these tests will be enabled back again once [PR#7395](https://github.com/CartoDB/cartodb/pull/7395) is merged.

**Comment by gfiorav** [comment]
Great stuff! Thanks for taking care of it 🌴

**Pull request merged**
