### PR TITLE
Fix WMS basemaps to work for WMTS kinds too

### LINKED ISSUE #2749: Incorrect parameters sent to WMS proxy for WMTS URLs
http://leafletjs.com/reference.html#tilelayer-tms

This can be useful in order to get tilelayers directly exported from gdal into CartoDB (with y axis inverted). :-)

@rochoa @javisantana @javierarce @zenitraM

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2749 

screen shot 2015-06-01 at 16 55 14
_example using the URL from the issue_

- The required changes on the WMS proxy to handle projections are already deployed (backward compabitble). Returns an expected `template_url` to be used in the cases where unsupported projections don't work.
- Frontend check if should proxy (if supports projections), otherwise use the provided template URL, going straight to the tiles w/o passing through the proxy.
- Only implemented it for the new modal, since the old one would require more work and will soon be replaced anyway.

@javisantana please review, deployed on ded06 if you want to give it a try yourself.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4036/))

**Comment by viddo** [comment]
friendly bump for review ;)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4081/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4090/))

**Comment by saleiva** [comment]
bump!

**Comment by viddo** [comment]
Discussed and OK'd in person w/ @javisantana, so will merge promptly

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4287/))

**Pull request merged**
