### PR TITLE
Fix for undefined method `*' for nil:NilClass

### PR DESCRIPTION
**Pull request by rafatower**
exception when using google geocoder.

@ethervoid can you please review?

cc/ @javisantana

### CODE REVIEW

**Comment by ethervoid** [comment]
:shipit:

**Comment by javisantana** [comment]
remember to do the same PR to master

**Comment by rafatower** [comment]
cherry-picked here: https://github.com/CartoDB/cartodb/pull/6771

**Comment by rafatower** [comment]
there are some broken tests due to this changeset: 4426c73f08cefc5fc3d105022b720f30f858c398

gonna fix them and keep moving ahead.

**Comment by rafatower** [comment]
retest this, please

**Comment by rafatower** [comment]
retest this, please

**Comment by rafatower** [comment]
retest this, please

**Comment by rafatower** [comment]
The same patch passed tests in master. It did not pass here because of running against 9.5, which is not supported in this branch (schema_trigger extension). Therefore I'm merging.

**Pull request merged**
