### PR TITLE
Fixes "all" infowindow field switch

### LINKED ISSUE #3008: "all" infowindow field switch no longer working in production
see GIF:

all_infowindow

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #3008. The internal `sortedFields` attribute was not being properly set when no fields were selected. I have added a test that reproduces the bug :)

@xavijam can you please take a look? thx!

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2774/))

**Comment by xavijam** [comment]
:us:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2782/))

**Comment by xavijam** [comment]
:dancer:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2787/))

**Pull request merged**
