### PR TITLE
time series: layer reference

### PR DESCRIPTION
**Pull request by matallo**
re: CartoDB/cartodb#12446

changes in deep-insights.js to add support for layer reference in time-series widgets 

- https://github.com/CartoDB/deep-insights.js/pull/560

this will probably get affected by https://github.com/CartoDB/cartodb/issues/12387

### CODE REVIEW

**Comment by rubenmoya** [comment]
LGTM

**Comment by rubenmoya** [comment]
Working in staging. Let's move it to deploy!

screen shot 2017-07-13 at 10 54 46

screen shot 2017-07-13 at 10 55 17

**Comment by matallo** [comment]
- no need to update NEWS, as it was added in a prior PR https://github.com/CartoDB/cartodb/blame/master/NEWS.md#L20

**Comment by xavijam** [comment]
Guys, we have to be more picky with our reviews, the action buttons when you are within a layer appears too close to the map limits.

**Pull request merged**
