### PR TITLE
Adding display_name as field within edit vis metadata

### LINKED ISSUE #5033: Added new field 'display name' for modal when edit a dataset
Add a new modal field to support the "pretty" name for **datasets only for datasets**. 

We need this new field because we are working to deprecate the common-data's `meta_dataset` table and use the canonical visualizations for this purpose so we are going to use this name when we want to display the name of the dataset in the `data library` section

image

Add one new fields:

* source
   free text input

cc @saleiva @viddo

### PR DESCRIPTION
**Pull request by xavijam**
screen shot 2015-12-14 at 13 13 11

- Field only available when user has "display_name" feature flag enabled.
- Fixed style problem within editor.

Fixes #5033
REVIEWER: @javierarce 

cc @ethervoid @iriberri

### CODE REVIEW

**Comment by ethervoid** [comment]
:+1: LGTM

**Comment by javierarce** [comment]
:+1:

**Comment by iriberri** [comment]
Thanks a lot! :)

**Comment by xavijam** [comment]
Changed only package version avoiding merge conflict with master, checked in staging, so merging and deploying!

**Pull request merged**
