### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by saleiva**

### CODE REVIEW

**Comment by saleiva** [comment]
hey @xavijam quick CR?

**Comment by xavijam** [comment]
Smells good.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2769/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2771/))

**Pull request merged**
