### PR TITLE
[DO] Validate metadata before purchasing

### PR DESCRIPTION
**Pull request by gonzaloriestra**
Closes https://github.com/CartoDB/cartodb/issues/15141

Some DO datasets don't have information yet for `available_in` (it's NULL) or other required fields, and because of that the subscribe operation fails with an undescriptive error: https://rollbar.com/carto/CartoDB/items/40314

Now, if any required field is missing, it will raise a 404 error with a proper message and it will be logged in Rollbar.

### CODE REVIEW

**Comment by gonzaloriestra** [comment]
It was a suggestion by @Jesus89, but now I'm thinking that maybe it's better to fail in this case... :thinking:

Users won't notice that the dataset doesn't have the `avaiable_in` property (it's internal), and they will think it's succesfully purchased, but nothing will happen (no BQ views and no Redis metadata).

Of course, metadata will be completed and we will notice errors like this with [this issue](https://github.com/CartoDB/cartodb/issues/15141), but maybe it's better to raise a proper error here instead of doing nothing. What do you think @alrocar?

**Comment by alrocar** [comment]
yep, the point is that the catalog must be complete... silently failing does not seem a good alternative to that to me.

**Comment by gonzaloriestra** [comment]
OK, I've changed the code and the description.

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
@oleurud good point. Not sure about how these errors are being managed from CARTOframes, @Jesus89 should I better return more user-friendly messages?

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by oleurud** [comment]
I did not realize about the conflicting file

**Comment by oleurud** [comment]
I am getting a 403 error with a "DO licensing not enabled" message in staging with the user `simon-admin` (who has the `do-licensing` FF enabled). Not sure about the real problem. The code is in staging cloud is someone wants to check it

**Comment by gonzaloriestra** [comment]
That error is only thrown when the FF is not enabled. Have you checked it
in the staging cloud? It could be out of sync with Central.

**Comment by gonzaloriestra** [comment]
@oleurud the FF was restricted and only enabled for my user. Now it's enabled for everybody in staging. Could you please try again?

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by oleurud** [comment]
## Acceptance OK
Returns the proper message and the error appears in rollbar. If the dataset has all the data, returns the expected information (we only have 7 datasets with all info and 0 geographies right now)

**Pull request merged**
