### PR TITLE
764 twitter improvements

### PR DESCRIPTION
**Pull request by Kartones**
This PR contains a bugfix, small improvements and activating DEBUG mode (leaving intermediate json and CSV files) to be able to debug any issue.

### CODE REVIEW

**Comment by Kartones** [comment]
@rafatower CR please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4307/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4311/))

**Comment by rafatower** [comment]
:+1:

**Comment by Kartones** [comment]
@CartoDB/systems This changes will not delete temporally files from `/tmp/csv_file_dumper` at queue servers, until we can fully assest if this is a GNIP issue or our issue (peaks with lots of tweets return gaps in results but after a while get fixed so we need "data logs").

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4436/))

**Pull request merged**
