### PR TITLE
Adding mail chimp video data

### PR DESCRIPTION
**Pull request by saleiva**

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3261/))

**Comment by saleiva** [comment]
pending @namessanti's link to the resulting map

**Comment by xavijam** [comment]
:us: :

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3262/))

**Pull request merged**
