### PR TITLE
Allow to fetch redirected URL from new static_map endpoint

### LINKED ISSUE #4234: Allow to fetch redirected URL from new static_map endpoint
- friendly url for public api
- internal (and faster) url for internal things

### PR DESCRIPTION
**Pull request by Kartones**
Closes #4234

### CODE REVIEW

**Comment by Kartones** [comment]
@juanignaciosl CR please

@matallo  You can now do directly:
 `Carto::StaticMapsURLHelper.new.url_for_static_map(request, @visualization, map_width, map_height)`  to avoid the 302 and get the final url

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4620/))

**Comment by javisantana** [comment]
thanks!

**Comment by juanignaciosl** [comment]
LGTM

**Pull request merged**
