### PR TITLE
Fixes npm-shrinkwrap

### PR DESCRIPTION
**Pull request by javierarce**
Generates `npm-shrinkwrap.json`.

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam

**Comment by xavijam** [comment]
But it doesn't remove those 13K lines, I'm a bit worried.

**Comment by javierarce** [comment]
Damn, I'll have a look as soon I get home

**Comment by javierarce** [comment]
Well, I just tried to remove `npm-shrinkwrap.json` plus the `node_modules` folder (just in case), do a `npm install` and a `npm shrinkwrap` , but the problem persists :| 

I also did the same operation without the `carto-color` package, with same results. Maybe is something in my system?

I'm using npm v2.15.1 and node  v0.10.44.

**Comment by xavijam** [comment]
@viddo or @rochoa any clue?

**Comment by viddo** [comment]
I'm using a slightly newer version of npm (v2.15.4), not sure if that could be related?

**Comment by javierarce** [comment]
@viddo: I'll try upgrading and see if that does the trick.

**Comment by javierarce** [comment]
It didn't work :/

**Comment by javierarce** [comment]
Now the file has `1422` and no dev related stuff @xavijam

**Comment by xavijam** [comment]
What should we do with this one?

**Comment by viddo** [comment]
Hm.. I think if the shrinkwrap was already solved through another PR we
could close this one. Do we still have those dev-deps present on master?

On Wednesday, June 22, 2016, Javier Álvarez Medina <notifications@github.com>
wrote:

> What should we do with this one?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/7898#issuecomment-227717809>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA7uHWPU5sVv8tHl_hF25BR_6v0qEMO6ks5qOR5ZgaJpZM4I3nG6>
> .
>


-- 

*Nicklas Gummesson*, software engineer
*CartoDB* — Map Your World's Data

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by xavijam** [comment]
Yes, I feel it is not solved yet.

**Comment by rochoa** [comment]
I would close this PR as we've already generated npm-shrinkwrap.json in other PRs.

**Comment by rochoa** [comment]
And closing it.

**Pull request closed without merging**
