### PR TITLE
2537 update common data metadata task

### LINKED ISSUE #2537: Update common data metadata task
Metadata will be updated by demand with the changes at #2661 . Remaining:
- [X] Delete remotes when they no longer exist.
- [X] Trigger update.
- [X] Front changes

Common data will be loaded/updated monthly, when a user enters his dashboard.

Maybe we should change the Data Library message to "Our elves are adding this data right now, please come back a little later and you'll enjoy their work" or something similar. What do you think?

### PR DESCRIPTION
**Pull request by juanignaciosl**
@viddo could you make front part consistent with this? I'd only change "Data Library" text message, but you're free to add whatever you want. When we launch this, common data loading/update will be triggered when a user has not loaded it or has not updated it in a month. Load time is in the order of one minute.

edit: fixes #2537 (for reference) /viddo

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2272/))

**Comment by viddo** [comment]
Initially I think the proposal (to change the message communicated there), I'd get back to this after I finish the current issue I'm working on :+1:

**Comment by viddo** [comment]
ETA later today.

**Comment by viddo** [comment]
screen shot 2015-03-13 at 10 26 39
Good enough?

**Comment by viddo** [comment]
Anyway, you can change the texts directly on the file on Github if you want a slightly different text, see https://github.com/CartoDB/cartodb/blob/2537-Update_common_data_metadata_task/lib/assets/javascripts/cartodb/new_dashboard/views/content_no_results.jst.ejs (line 25 and 42) by clicking the pen icon in the top-right corner ("Edit in file"), and change the corresponding text.

**Comment by viddo** [comment]
reassigned back to you @juanignaciosl merge whenever you consider it to be done :)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2307/))

**Comment by juanignaciosl** [comment]
@saleiva we can enable this whenever you want.

**Comment by saleiva** [comment]
Hey one last comment, could we put the loading indicator instead of the icon? Makes sense, right?

**Comment by juanignaciosl** [comment]
IMHO, in that case, since a user might stare the loading icon mesmerized waiting to end, maybe we should add a polling that waits for available data.

**Comment by viddo** [comment]
Agree. Reassigning it to myself again then. Btw, @juanignaciosl, if you don't have more changes TBD I can take care of doing the merge and release if you prefer?

**Comment by juanignaciosl** [comment]
Take care of it if you want, thank you very much!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2409/))

**Comment by viddo** [comment]
Changed the no-results view to a loading view for this use-case. Library data is polled until there are at least one item (every 10 sec, to avoid hammering servers) and/or the user navigates elsewhere. See gif for example below (changed the poll to 2sec for demonstration purposes):
common-data

**Comment by viddo** [comment]
...cc @juanignaciosl @saleiva, if you're OK with this I'll merge & deploy tomorrow morning.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2410/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2412/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2416/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2418/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2424/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2432/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2434/))

**Pull request merged**
