### PR TITLE
Fix icons in the notification list panel

### LINKED ISSUE #4918: Fix icons in the notification list panel
A recent PR change the `content` values of the icon font that is being used In https://github.com/CartoDB/cartodb/blob/master/app/assets/stylesheets/common/notifications-dropdown.css.scss.

### PR DESCRIPTION
**Pull request by javierarce**
Result:

screen shot 2015-08-06 at 16 48 01

Original issue: https://github.com/cartodb/cartodb/issues/4918

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5640/))

**Comment by javierarce** [comment]
retest this please

**Comment by javierarce** [comment]
Have a look, @xavijam

**Comment by xavijam** [comment]
Much appreciated :pray:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5643/))

**Pull request merged**
