### PR TITLE
Entry for common_data manual

### PR DESCRIPTION
**Pull request by ethervoid**
This is the config for the new common data service

I'd love If some with better english level than me like @agnesATcartoDB could take a look and correct the errors that I could make :)

// @javisantana

### CODE REVIEW

**Comment by ethervoid** [comment]
Bump @brittanymicek

**Comment by brittanymicek** [comment]
Got it!

On Mon, Aug 31, 2015 at 6:28 AM, Mario de Frutos <notifications@github.com>
wrote:

> Bump @brittanymicek <https://github.com/brittanymicek>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/5221#issuecomment-136326747>.
>



-- 
*Brittany Micek*
Content Writer

*CartoDB—Map Your World's Data*
143 Roebling St 2A, New York, 11211, USA
T: + <%2B34695497365>19174633232
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by brittanymicek** [comment]
Here are my suggested changes. If there is time @csobier should also take a look at this. Thanks @ethervoid 

All of this is can be configured through the ''common_data'' settings section. If the ''base_url''  option is set, this will be the base url the service is going to use to build the URL to retrieve datasets.

"Use ''https://common-data.cartodb.com'' as the base url to retrieve all the public datasets from that user."

This is the default behavior in CartoDB, but if you want to use your own system and user for this purpose you have to define the ''username'' property pointing to the user that will provide the datasets in your own instance.

The system populates the data library with public datasets from ''http://common-data-user.example.com...''

The ''format'' option is used to define the format of the file generated when you are importing one dataset from the data library.

**Comment by ethervoid** [comment]
Thank you for your help @brittanymicek :)

**Comment by brittanymicek** [comment]
You are so welcome! Glad to be of service!

On Thu, Sep 3, 2015 at 8:47 AM, Mario de Frutos <notifications@github.com>
wrote:

> Thank you for your help @brittanymicek <https://github.com/brittanymicek>
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/5221#issuecomment-137427591>.
>



-- 
*Brittany Micek*
Content Writer

*CartoDB—Map Your World's Data*
143 Roebling St 2A, New York, 11211, USA
T: + <%2B34695497365>19174633232
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Pull request merged**
