### PR TITLE
[New Dashboard] Fix drag and drop behaviour

### PR DESCRIPTION
**Pull request by jesusbotella**
This PR fixes this issue that @ramiroaznar posted on the Feedback Form:

> After importing a .carto into the home, the list of Your maps is not updated. Same is happening when importing a dataset. But the import also generates a map which I think it is not the expected behavior. Should we allow users to import stuff into the home? Should CARTO understand what is a dataset and what is a .carto?

The new behaviour is:
- Drag and drop from Home:
    - When importing a dataset, it doesn't create a new visualization.
    - When importing a .carto or .zip, it creates a new visualization.

- Drag and drop from Maps Page:
    - When importing a dataset, a .carto, or a .zip, it creates a new visualization.

- Drag and drop from Dataset Page:
    - When importing a dataset, it doesn't create a new visualization.
    - When importing a .carto or .zip, it creates a new visualization.

### CODE REVIEW

**Comment by ramiroaznar** [comment]
Maybe this is a long shot but... could it be possible to avoid generating a new dataset (like `table_1`) if the table already exists when importing a .carto?

cc @javitonino

**Comment by jesusbotella** [comment]
That may be a reaaaally long shot :P, because I suppose that we'd have to check that the table is actually identical, not only by name or something naïve.

**Comment by javitonino** [comment]
Yeah, what @jesusbotella said. There is a parameter to the import API that can be used for this (`collision_strategy=skip`) but it matches only by name. So that's why it's not the default.

**Comment by ramiroaznar** [comment]
carton

**Comment by jesusbotella** [comment]
retest this please

**Pull request merged**
