### PR TITLE
Updating to latest version (HEAD) of DI

### PR DESCRIPTION
**Pull request by viddo**
cc @xavijam @rochoa

### CODE REVIEW

**Comment by viddo** [comment]
as I wrote in the commit, I did this to update the deps:

```bash
npm install --save-dev CartoDB/deep-insights.js#855c27b
npm install --save-dev CartoDB/cartodb.js#f09747f
npm shrinkwrap
```

**Comment by xavijam** [comment]
:+1:

**Comment by viddo** [comment]
from what I can see, this uses the fixes @acanimal and I did in https://github.com/CartoDB/cartodb.js/pull/1095 and https://github.com/CartoDB/deep-insights.js/pull/194 works, can you verify @xavijam that this fixes your issues with the named maps? you'd still have to do a npm instal after checking this branch out.

**Comment by viddo** [comment]
will redo the PR, to re-create the shrinkwrap properly

**Pull request closed without merging**
