### PR TITLE
iconfont

### LINKED ISSUE #4722: update icons sprite

### PR DESCRIPTION
**Pull request by matallo**
close #4722

CR @viddo

### CODE REVIEW

**Comment by viddo** [comment]
Will be fixed in a55825315baebd595922d37a1e69a53f3dced6ca

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5430/))

**Comment by matallo** [comment]
ok, take into account now the icons are in a grid

**Comment by viddo** [comment]
yes I know

On Tue, Jul 28, 2015 at 2:24 PM, Carlos Matallín <notifications@github.com>
wrote:

> ok, take into account now the icons are in a grid
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/4723#issuecomment-125582140>.
>



-- 

*Nicklas Gummesson*, software engineer
*CartoDB* — Map Your World's Data

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5432/))

**Pull request closed without merging**
