### PR TITLE
Ellipsis.

### PR DESCRIPTION
**Pull request by nobuti**
This PR implements #11451.

### CODE REVIEW

**Comment by matallo** [comment]
🤔 I think just one `u-ellipsis` in the element to cut is enough

**Comment by nobuti** [comment]
we still need `overflow: hidden` in the container, do we have a helper to do that? it's the easy way I found to achieve it without creating a new selector.

**Comment by matallo** [comment]
GO then! If this is a recurrent case I'd consider adding an utility for the overflow, or if these two are usually accompanied to have the ellipsis parent, and ellipsis child

**Comment by nobuti** [comment]
Getting @piensaenpixel into the loop, I feel we need his expertise.

**Comment by piensaenpixel** [comment]
+1 to @matallo's comment, i think we can merge this one and I can prepare this helper in cartoAssets.

**Comment by nobuti** [comment]
Are you guys saying I'm too lazy?!?

**Comment by piensaenpixel** [comment]
hahahahaah yes. Nah merge this fix and i'll take care.

**Pull request merged**
