### PR TITLE
Fixes overflowing input field

### PR DESCRIPTION
**Pull request by javierarce**
Original issue: #5118 

Before the fix:
screen shot 2015-08-19 at 18 52 38

After the fix: 
screen shot 2015-08-19 at 18 57 00

### CODE REVIEW

**Comment by javierarce** [comment]
@viddo: have a look, please.

**Comment by javierarce** [comment]
Have a look to this PR, @viddo.

**Comment by viddo** [comment]
The icon looks wrong, right? Also not very much in favor of these fixed widths if we can avoid them, would it be possible to let the container handle the overflow using CSS attrs? E.g.

```
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
```

**Comment by javierarce** [comment]
Sorry, I uploaded the wrong capture.

The h6 element that contains the URL has already the properties you list (.u-ellipsLongText). If I move it to the parent element we'd get this: 

screen shot 2015-08-19 at 19 00 58

If I apply the .u-ellipsLongText to both elements I get this instead… I find it a bit ugly, but maybe is better than specifying the width manually.

screen shot 2015-08-19 at 19 02 34

**Comment by viddo** [comment]
Yeah, agree… if the box has a specific size then I think it's fine, but otherwise I'd let the container define the available size and use width: 100% to fill up the container (so the overflow applies correctly), but perhaps not doable in this case. If that's the case then go ahead. :+1:

**Pull request merged**
