### PR TITLE
Changes the color from #666666 to #DDDDDD

### PR DESCRIPTION
**Pull request by javierarce**
screen shot 2015-07-30 at 11 36 13

Left: hovered. Right: selected.

### CODE REVIEW

**Comment by javierarce** [comment]
cc @josecruz

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5481/))

**Comment by josecruz** [comment]
Thank you so much Arce! :raised_hands:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5501/))

**Pull request merged**
