### PR TITLE
Fix minor new modals stuff

### LINKED ISSUE #4579: New modals fixes
## Privacy modal
- [x] In this modal, all green buttons should be blue `#0090d7`.

- [x] Header margins + header icon `#666`:
                        There are wrong margins here. First, icon to text should be 12px (as in connect dataset)
screen shot 2015-07-20 at 3 42 28 pm
screen shot 2015-07-20 at 3 42 43 pm
- [x] Also, we're going to remove the footer tip and align cancel button to the left.

- [x] Font should be Lato and the text color should match the rest of the modals
screen shot 2015-07-20 at 5 03 35 pm

- [x] Header size should be the same as connect dataset one:
screen shot 2015-07-20 at 3 41 45 pm

## Delete modal
- [x] Line width is not the same:
artboard

## Lock/Unlock dataset
- [x] Unlock button should be blue `#0090d7`
screen shot 2015-07-20 at 4 07 41 pm

## Add custom basemap
- [x] Header icon should be `#666`
screen shot 2015-07-20 at 6 16 58 pm

- [x] All footer buttons should be blue `#0090d7`
screen shot 2015-07-20 at 6 31 16 pm

- [x] Deactivate Add Basemap button on Mapbox tab:
                        We actually deactivate all buttons when there's an empty form on all tabs but the Mapbox one
addcustombasemap

## Marker image selector

- [x] Set image button should be blue `#0090d7`

- [x] Scroll on icon selector cuts the image:
marker image

## Sync Dataset
- [x] Save settings button should be blue `#0090d7`.

## Edit Metadata
- [x] Header and header icon properties should be the same as in `Connect Dataset` modal
screen shot 2015-07-21 at 1 23 18 pm

## Connect dataset
- [x] Footer tip needs the same margins as the rest of footer elements:
screen shot 2015-07-21 at 2 33 58 pm

### PR DESCRIPTION
**Pull request by viddo**
Fixes #4579

Since the list was rather long and some things were downright bug reports I created [separate issues](https://github.com/CartoDB/cartodb/issues?q=is%3Aopen+assignee%3Aviddo+milestone%3ACorcos), since they'll require more investigation.

The others were minor visual bugs, which should not be fixed.

E.g.:
screen shot 2015-07-22 at 15 00 11
screen shot 2015-07-22 at 15 30 07
screen shot 2015-07-22 at 16 09 18

@xavijam can you code review?
cc @josecruz @saleiva for visuals, deployed on ded04 for testing

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5244/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5256/))

**Comment by viddo** [comment]
FYI, based on the [decision to make the header inconsistencies](https://github.com/CartoDB/cartodb/issues/4175#issuecomment-115157973) I've also taken care of them in this PR, so that fixes #4175

**Comment by josecruz** [comment]
:+1: on this! But just figured out that we could use the same margins size in delete dataset as in privacy one (28px):

screen shot 2015-07-22 at 7 16 43 pm

screen shot 2015-07-22 at 7 17 29 pm

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5259/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5260/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5262/))

**Comment by xavijam** [comment]
:es:

**Comment by xavijam** [comment]
Bad part is I'll have some problems to merge this branch with [templated-worklogs branch](https://github.com/CartoDB/cartodb/tree/templated-workflows). I :heart: you! (#no).

**Pull request merged**
