### PR TITLE
2603 fix caching geometry types [do NOT merge yet]

### PR DESCRIPTION
**Pull request by rafatower**
I need to run existing tests and write some tests. Aside fix key generation (hitting DB)

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2068/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2075/))

**Comment by rafatower** [comment]
After these changes I see it does not query DB for cached geometry_types but there's no difference in the total number of queries for the table request with respect to master :(

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2086/))

**Comment by rafatower** [comment]
I'm closing this for the moment. See discussion in the ticket for more info

**Pull request closed without merging**
