### PR TITLE
Default value in dropdowns

### PR DESCRIPTION
**Pull request by rubenmoya**
Related to: https://github.com/CartoDB/cartodb/issues/12451

As you can see in the gif below, the dropdown value is the selected one, and you can "edit" it without having to write it down again, I say "edit" because you're just adding a new value since you can't edit it, that's why there are all there when you type "Test".

dropdown-value

### CODE REVIEW

**Comment by rubenmoya** [comment]
What do you think about this approach? @CartoDB/design / @noguerol

**Comment by noguerol** [comment]
perfecto.

**Comment by saleiva** [comment]
Cannot we add the Custom value small text when a custom value is selected? It looks weird that after changing the text, that small caption appeaars

**Comment by rubenmoya** [comment]
So when you add a custom value and open the dropdown again it should show "Custom value" and the value, and then when you change it, it should show "Add custom value"? Is that what you mean?

**Comment by noguerol** [comment]
I think that is what he means, yes.

**Comment by rubenmoya** [comment]
Something like this?

screen shot 2017-07-26 at 15 49 11

**Comment by saleiva** [comment]
but only for the first one, right?

**Comment by rubenmoya** [comment]
I think we've had a miss understanding here with the custom values and value edition, I'll try to drop some light to the subject:

When the dropdown renders, it loads the `N` most used values to suggest them when the user types in the input, if the user types something that it's not in that `N` values, the "Add custom value" caption will appear, even if that value is stored already in the DB, so I have no way to know if the value is "custom" or not, if the value is really a custom value, after the user clicks on "Add custom value" and "Save" it is stored in the database, and in the next fetch that value is not custom anymore.

About editing the values, since it's just a list of plain text values, I have no way to know which one you're trying to edit, so the dropdown will just add a new value if it doesn't exist, but you can't edit a specific one

I've found a case when the current value is not in the `N` fetched values, and when you open the dropdown it will have the "Add custom value" caption, but I fixed it yesterday.

**Comment by rubenmoya** [comment]
I've deployed the last changes are to `ded02` if you want to test it!

**Comment by noguerol** [comment]
Is working as expected. Good job guys.

**Pull request merged**
