### PR TITLE
Make header title inline

### PR DESCRIPTION
**Pull request by javierarce**
Makes the header titles inline so only clicking in the title opens the map.

This is just https://github.com/CartoDB/cartodb/pull/2672 (which was reverted because of an onpremise build)

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2749/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2755/))

**Comment by saleiva** [comment]
bump!

**Comment by javierarce** [comment]
retest this please.

**Comment by javierarce** [comment]
@jmedina: can you review this, please? I found a problem with my first solution (also, this approach is simpler and doesn't require the `display-inline-flex` mixin)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2841/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2842/))

**Comment by xavijam** [comment]
Have you tested it with shared maps? (not being the owner i mean)

**Comment by javierarce** [comment]
You mean to test the case where there's an item to the right side of the title? I did a fake test adding the element manually and worked fine.

**Comment by xavijam** [comment]
Ok, yep, that was my concern. :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2850/))

**Comment by javierarce** [comment]
Meh, in Firefox doesn't work for long titles :(

screen shot 2015-04-07 at 18 30 12

**Comment by xavijam** [comment]
Maybe a max-width could do the trick

**Comment by xavijam** [comment]
But only in that sittuation, of course :S

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2857/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2860/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2863/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2868/))

**Pull request merged**
