### PR TITLE
Adding moment library to account and organization pages

### LINKED ISSUE #3270: Avatar error set as avatar_url
`:avatar_url=>"#<ActionDispatch::Http::UploadedFile:0x0000000d7e2568>",`

image

It seems that something failed when setting the avatar (PNG image) through the account settings. Trying to set it again fails again, so I forced the url finally.

SB/5120740

### PR DESCRIPTION
**Pull request by xavijam**
Basically JS is failing because moment.js is not loaded.
This is happening to some users because our notifications view is checking when trial is gonna expired, and that's the case for this user, he is on trial. And that's why for example in production is not failing for our users.

```js
Uncaught ReferenceError: moment is not defined
```

Fixes #3270

### CODE REVIEW

**Comment by xavijam** [comment]
cc @iriberri

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3226/))

**Comment by iriberri** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3227/))

**Pull request merged**
