### PR TITLE
Force resize when a widget is added/removed and there is a time-series or advanced mode selected

### PR DESCRIPTION
**Pull request by Jesus89**
Related to: #12655, ~~#12124~~

- Changes in deep-insights.js: https://github.com/CartoDB/deep-insights.js/pull/579
- Fix Time Series resize when switching to advanced mode
- Little refactor in CartoDB

For the acceptance:

- Create a time-series widget
- The time-series is forced to resize when a widget is added or removed:

force-resize-widgets

- The time-series is forced to resize when switching to advanced mode:

resize-adv-mode

- The time-series is forced to resize when the window is resized

### CODE REVIEW

**Comment by Jesus89** [comment]
No tests required here, only DI :wink:

**Comment by Jesus89** [comment]
I have also added this issue https://github.com/CartoDB/cartodb/issues/12124 in the PR because it is very similar

**Comment by Jesus89** [comment]
Found that Histogram widgets are not resizing properly. Back to development

**Comment by nobuti** [comment]
🚀

**Comment by xavijam** [comment]
🥒  fix

**Pull request merged**
