### PR TITLE
Organization shared vizs should not count or display owned

### LINKED ISSUE #3980: Organization-wide shares are count for owner user
Steps to reproduce:
- User 1 shares table A with the org and table B with user 2.
- User 2 shares table C with the org and table D with user 1.

Dataset listing for user 2 is ok (displays 2 rows) but count displays 3 (probably because it counts table C sharing).

Inconsistence happens only on old endpoint. Nevertheless, "shared with you" should exclude the ones you own.

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones, @xavijam CR this, please. This fixes #3980.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4235/))

**Comment by xavijam** [comment]
I feel @kartones should take care of it.

**Comment by juanignaciosl** [comment]
@xavijam np, I mostly added you to know about this, since we've already spoken a lot about this counting, and to be sure that previous behaviour was wrong.

**Comment by Kartones** [comment]
:+1:

**Pull request merged**
