### PR TITLE
Add Snowflake, Redshift connectors UI

### PR DESCRIPTION
**Pull request by Jesus89**
- Refactor connectors UI
  - Custom grid style (3xn)
  - Custom order
  - Custom placeholder query
  - Custom parametric form params
  - Add optional values
  - Hide titles of empty sections
  - Fix "more features" upgrade link
  - Review connectors visibility logic
  - Add custom sql-hint for Snowflake
- Add Snowflake connector UI
  - Server
  - Database
  - Username
  - Password
  - Warehouse (optional)
- Add Redshift connector UI
  - Cluster
  - Port
  - Database
  - Username
  - Password
- Add Dashboard notification (only with `carto-connectors` FF)

### CODE REVIEW

**Comment by VictorVelarde** [comment]
I reviewed this yesterday, but it looks like my comment was not recorded... anyway good job on that params generalization.
I have no accounts for testing, any option to have it deployed at staging + some connection strings for acceptance?

**Comment by Jesus89** [comment]
Thanks!. And yes, you can test this in staging: https://snowtest2.carto-staging.com/.

More info here:
- https://app.clubhouse.io/cartoteam/story/101109/qa-snowflake-connector
- https://app.clubhouse.io/cartoteam/story/103896/qa-redshift-connector

**Comment by VictorVelarde** [comment]
I could run the acceptance on snowflake, but I wasn't able to get redshift running. I can try again after your checks

**Review by VictorVelarde — APPROVED** [review]
Code LGTM, Nice additions!. Just double-check with QA the redshift connector

**Comment by VictorVelarde** [comment]
Check travis!  👀

**Pull request merged**
