### PR TITLE
Providing the proper google maps api key to the frontend

### PR DESCRIPTION
**Pull request by xavijam**
Related ticket: https://github.com/CartoDB/support/issues/724

In case the user belongs to the organization.
cc @juanignaciosl because you proposed a solution, and it is likely this one is not a valid one.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Yep, but I'll summon @rafatower , @ethervoid or @jgoizueta for confirmation. Could any of you take a look at this, including [my comment](https://github.com/CartoDB/support/issues/724#issuecomment-304651481), please? I'm pretty sure that components (geocoder?, Maps API?...) that need `google_maps_key` don't understand about organizations, so this fix is useless, and the actual fix would be update users `google_maps_key` when organization one changes, wouldn't it?

**Comment by juanignaciosl** [comment]
@xavijam corollary: you can check your fix:

1. Create a new organization without google api key and with one user (beyond owner).
2. Assign the key to the org.
3. Operations depending on it won't work for that user.

**Comment by xavijam** [comment]
I'm testing that. Take into account that user "attribute" will be only used for image-export. It is not being used in any other place in the Frontend side. No idea about what you have mentioned above.

**Comment by xavijam** [comment]
After checking it with a ded03 account under an organization, it works 👌 . If you want to check it too, let me know, but it is in ded03 as I've mentioned @juanignaciosl.

**Comment by javitonino** [comment]
I'll let @juanignaciosl take this one (as I suggested the fix). Just adding a comment that might be useful. IIRC Image export with google maps works client-side, meaning two requests are made from the browser: one to the tiler for the data layers, and one to google for the basemap. Then, the two images are composed in JS land to generate the image. Meaning that it doesn't matter for this if windshaft has access to the correct api key or not.

**Comment by juanignaciosl** [comment]
If this works for you, go for this 💪

**Comment by ethervoid** [comment]
Hello!

In dataservices-api [we use] the google api key of the organization, instead of the user one, if its defined.

The old geocoder [uses the user google api key](https://github.com/CartoDB/cartodb/blob/master/services/table-geocoder/lib/table_geocoder_factory.rb#L45-L46), which as @juanignaciosl pointed is inherited from the organization if the user is a org user.

**Comment by ethervoid** [comment]
For the export image, it's using the user config for it as you can see [here](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/export-image-pane/export-image-pane.js#L383) to get the base map tile.

**Comment by juanignaciosl** [comment]
👍  to backend. @xavijam says that frontend is trivial, so to acceptance.

**Comment by ethervoid** [comment]
From my point of view the user model should try to get the organization api_key instead of having a copy of it in its model

**Comment by juanignaciosl** [comment]
@ethervoid it does that, at [`google_maps_api_key`](https://github.com/CartoDB/cartodb/blob/228e875a319df28e32e15e6d99aba96b00bb8ead/app/models/carto/user.rb#L188). We need `google_maps_key` to be the column for Central sync to work consistently.

**Comment by javitonino** [comment]
Tested in staging, with org and user keys, in editor and builder.Everything looks good 👍

**Pull request merged**
