### PR TITLE
Check if calling save_named_map on Viz member invalidate_cache is needed

### LINKED ISSUE #4107: Check if calling save_named_map on Viz member invalidate_cache is needed
Now that we assume all viz have named maps, the old logic of "sometimes having named maps" no longer applies, so probably `invalidate_cache` shouldn't have this update call to named maps, as a change in a related table privacy shouldn't affect the named map itself (it will still be there always).

### PR DESCRIPTION
**Pull request by Kartones**
Closes #4107

### CODE REVIEW

**Comment by Kartones** [comment]
In the end, it wasn't needed. Table privacy changes trigger proper viz. updates and any viz update triggers named map change so no need to call it again with cache invalidations as those don't affect named maps.

Manually checked all scenarios (privacy changes, deletions, etc.) with diferent layers and works as expected (but will try at staging too)

@juanignaciosl CR please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4460/))

**Comment by juanignaciosl** [comment]
:heart: . I had to patch this in another branch indeed.

**Comment by Kartones** [comment]
Going live with it then (staging went fine also)

**Pull request merged**
