### PR TITLE
Removing model and views related with old tags endpoint

### LINKED ISSUE #3691: Deprecate tags endpoint
As seen in #3652 tag endpoint seems unused. We should delete both JS and backend code.

### PR DESCRIPTION
**Pull request by xavijam**
- [x] Removed tags model and views in frontend code.
- [x] Removed tags endpoint in backend code (@juanignaciosl).
- [x] Removed other unnecessary views from old common.
- [x] Using correctly Moment.js subtract method.

Fixes #3691

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3756/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3778/))

**Comment by juanignaciosl** [comment]
@Kartones CR this, please. @xavijam I've removed the backend code, take a look, and I don't know if you want to add anybody else to the CR.

**Comment by xavijam** [comment]
@javierarce, could you take a look?

**Comment by Kartones** [comment]
backend part :+1:

**Comment by xavijam** [comment]
@viddo, could you take a look?

**Comment by viddo** [comment]
Looks legit! :fire: :dancer: :fire:

**Comment by xavijam** [comment]
Thanks @viddo, merging master.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3801/))

**Pull request merged**
