### PR TITLE
3863 slow quota checks

### LINKED ISSUE #3863: Slow quota checks
Some quota checks (tweets, geocodings) are done often and involve a sum of each user data. It makes some interactions slower and might be a concern. Not high priority for the moment anyway. 
- [X] Tweets.
- [X] Geocodings.

See #3992 for checks involving owner but not users.

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #3863. @Kartones CR this, please.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4226/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4229/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4231/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4237/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4239/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4242/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4246/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4247/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4248/))

**Comment by Kartones** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4254/))

**Comment by juanignaciosl** [comment]
@zenitraM , @Kartones , I've just updated one test gem but `Gemfile.lock` has many updates. Could you take a look at gem updates just in case you know any might be risky? Thanks!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4259/))

**Comment by Kartones** [comment]
This two are the only ones worrying me a bit: 
`db-query-matchers` from 0.3 to 0.4 (but no idea of its use)
`jwt` is a big one too, from 1.0 to 1.5 (again no idea)

So I'd check what they do and try to test, but apart from that... the others are minors and *shouldn't* break anything

**Comment by juanignaciosl** [comment]
@Kartones the matcher one is the one I needed. Just testing, safe. Do you know our about jwt usage?

**Comment by Kartones** [comment]
uhm, no idea :/ But the rubygems description is not very encouraging: `JSON Web Token implementation in Ruby`. Don't know what we use "json web tokens" for

**Comment by Kartones** [comment]
uhm, no idea :/ But the rubygems description is not very encouraging: `JSON Web Token implementation in Ruby`. Don't know what we use "json web tokens" for

**Comment by zenitraM** [comment]
`jwt` seems to be a dependency of `google-api-client` and `signet`, seems to be related to Oauth signing: http://jwt.io/

Don't think we use it

**Comment by juanignaciosl** [comment]
Ok, @zenitraM , @Kartones , I've tested it in staging and looks fine. Will merge&deploy tomorrow morning.

**Pull request merged**
