### PR TITLE
Removes unnecessary binding + adds explanation

### PR DESCRIPTION
**Pull request by javierarce**
This PR fixes an extra reloading of the maps in the new dashboards and adds an explanation for a binding.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2154/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2155/))

**Comment by javierarce** [comment]
@xavijam: can you :eyes: review this, please?

**Comment by xavijam** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2165/))

**Pull request merged**
