### PR TITLE
Adding default fallback basemap attribute for public organization 

### LINKED ISSUE #3162: Fallback basemap attribute is not available in public organization page
```ruby
  def set_new_layout_vars_for_organization(org, content_type)
    set_new_layout_vars({
        most_viewed_vis_map: org.public_vis_by_type(Visualization::Member::TYPE_DERIVED, 1, 1, nil, 'mapviews').first,
        content_type:        content_type,
      })
    set_shared_layout_vars(org, {
        name:       org.display_name.blank? ? org.name : org.display_name,
        avatar_url: org.avatar_url,
      })
    # default_fallback_basemap var not defined :( 
  end

  def set_new_layout_vars(required)
    @most_viewed_vis_map = required.fetch(:most_viewed_vis_map)
    @content_type        = required.fetch(:content_type)
    @maps_url            = CartoDB.url(view_context, 'public_visualizations_home', {}, required.fetch(:user, nil))
    @datasets_url        = CartoDB.url(view_context, 'public_datasets_home', {}, required.fetch(:user, nil))
    @default_fallback_basemap = required.fetch(:default_fallback_basemap, {})
  end
```

cc @kartones @viddo @lbosque

### PR DESCRIPTION
**Pull request by xavijam**
review: @lbosque or @Kartones 

Fixes #3162

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2974/))

**Comment by xavijam** [comment]
@luisico?

**Comment by xavijam** [comment]
ping @kartones please :)

**Comment by Kartones** [comment]
:+1:

**Pull request merged**
