### PR TITLE
Add not null constraint to layers kind

### PR DESCRIPTION
**Pull request by gfiorav**
Makes 'layers.kind` not null.

CR please, @juanignaciosl

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Although I've seen no such thing, having nulls is technically possible, I'd set 'carto' where it's null and then add the constraint.

This constraint might cause table lock, speak to devops.

**Comment by gfiorav** [comment]
Added.

Have another look please, @juanignaciosl

**Comment by juanignaciosl** [comment]
:+1:

**Comment by gfiorav** [comment]
We're on high load this week, waiting for a better time.

**Pull request merged**
