### PR TITLE
URI encode more problematic characters

### PR DESCRIPTION
**Pull request by javitonino**
Closes https://github.com/CartoDB/cartodb-management/issues/4756

Encodes more characters. URI::Encode has an unsafe parameter which takes a regex on which characters to encode. By default, it takes al URL safe characters, this changes it to all special characters including things like comma or " which have special meaning in headers (but not in URLs)

**Acceptance**
Rename a map with some special characters and try to export it as .carto. Test at least the following characters: quotes (" and '), space, comma/semicolon (, ;), star (*), spanish characters, chinese characters, emoji.

It's important to test with different browsers. At least Chrome (as it was the one giving issues), but it would be great to cover the major browsers as well.

### CODE REVIEW

**Comment by MariaCheca** [comment]
The test I made in Chrome for OS X/Windows and Opera for Windows made struggles in the filename.

1. Created a new map and renamed it to **Untitled "map'**
2. Exported the map as a .carto
3. The file was downloaded succesfully but the name is a bit weird: `Untitled _map' (on 2017-01-19 at 10.08.45).carto;filename-=utf-8''Untitled _map' (on 2017-01-19 at 10.08.45).carto`

The rest of the browsers (tested in Chrome, Firefox, Safari, IE (only Windows, the rest in OS X) and Opera) where ok.

**Comment by javitonino** [comment]
Good catch :). Some quotes were missing. I added them back and tested with Firefox + Chrome on Linux and it works fine now. Thanks 💋

**Comment by MariaCheca** [comment]
Yay!

**Comment by MariaCheca** [comment]
Now acceptance is fully passing 🇩🇰

**Pull request merged**
