### PR TITLE
Fixes blurry patterns + updates copy

### PR DESCRIPTION
**Pull request by javierarce**
This PR removes the blurriness from the patter thumbnails (caused by a difference between the default size of the thumbnails and the actual one). It also updates the title of the pattern library.

Original issue: https://github.com/CartoDB/cartodb/issues/3761

screen shot 2015-08-03 at 17 16 02

/cc: @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
Do we have them ready for retina?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5548/))

**Comment by javierarce** [comment]
No, we don't.

**Comment by xavijam** [comment]
For me there is no problem, so :jp:.

**Pull request merged**
