### PR TITLE
Some software extends dbf standard with extra encoding files, fixing #449

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones, @rafatower CR this fix for #449, please. I didn't know about those extra encoding files and it's pretty common (and useful for us). For example, QGIS save it. It's a workaround for DBase encoding support (I realised looking at the [supported encodings table of dbf gem](https://github.com/infused/dbf/blob/master/docs/supported_encodings.csv).

What to test: importing .shp y .tab. All should work at least as good as always, and those that contains .cpg or .cst should be encoded more accurately.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1778/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1785/))

**Comment by rafatower** [comment]
:+1: good research!

**Comment by Kartones** [comment]
+1 nice!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1789/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1792/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1880/))

**Comment by juanignaciosl** [comment]
@Kartones could you CR this again? QGIS allows many exotic encodings not supported by PG, so I had to filter them and code has changed.

**Comment by Kartones** [comment]
+1

**Pull request merged**
