### PR TITLE
[Do not merge] Torque tooltips

### PR DESCRIPTION
**Pull request by fdansv**
Ref #2753 

* [x] Build BoundingBox value calculation logic in Torque - https://github.com/CartoDB/torque/pull/156
* [x] Create tooltip in editor that reflects value on hover
* [ ] Change tooltip tab so that only ```value``` appears
* [ ] Add changes to viz.json

### CODE REVIEW

**Comment by fdansv** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2579/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2658/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3032/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3072/))

**Pull request closed without merging**
