### PR TITLE
Delete affected widgets by a source change and then recreate them when new layer and source are created

### LINKED ISSUE #10099: Problem changing layer_id for a widget
## STR
- Create a map of points.
- Apply a category widget.
- Apply an analysis (subsample is ok).
- Drag out the source node to a new layer.
- Go to widgets list and check that the widget is pointing to the incorrect layer (check layer color and so on).

cc @saleiva @javisantana

### PR DESCRIPTION
**Pull request by xavijam**
Basically, when a node that has widgets associated is moved to a new layer, those widgets have to be remove and then recreated with the new layer_id and source.
Changed tests and added a notification that mentions widgets are being restored...

cc @javisantana @nobuti @javierarce @matallo 

Fixes #10099

### CODE REVIEW

**Comment by xavijam** [comment]
If you see something weird, let me know...

**Comment by xavijam** [comment]
@nobuti, one important thing. I've realized while testing this functionality that we were fetching query-schema-model for the widgets-view, and we needed to fetch the query-geometry-model. NFI why I didn't change that when I was doing last changes over those premises, but anyway, fixed. Take a look in case you can find something wrong :kiss:.

**Comment by nobuti** [comment]
@xavijam yeah, because if query-schema model has a sql error, we don't allow the user to interact with that view, adding or deleting widgets.

**Comment by xavijam** [comment]
Arg, so... ha... we will need to fetch both then?

**Comment by nobuti** [comment]
I guess so...

**Comment by xavijam** [comment]
😱 , ok!

**Comment by nobuti** [comment]
Confirmed, nothing related with query errors. all we need is geometry https://github.com/CartoDB/cartodb/issues/9653

**Comment by xavijam** [comment]
:+1:, so after merging master, do you see any problem with those changes?

**Comment by nobuti** [comment]
No, it's looking good 👍

**Comment by xavijam** [comment]
Fixing the last (hopefully) bug I found with this issue. That one fixed the problem creating widgets belonging to a layer where the head node was moved. 💋

**Comment by xavijam** [comment]
Passing specs 🚀

**Pull request merged**
