### PR TITLE
Don't concatenate numbers to candidate map names fixes #2846

### LINKED ISSUE #2846: Don't concatenate new numbers on "Untitled Map"
Right now:

image

This is something that happened months ago too with table names, if I'm not confused: `untitled_table_1_2_3``

@kartones @juanignaciosl

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones CR this, please.

@xavijam Now when I create a new map (new dashboard) it gets 'Untitled Map' by default. Bug or feature? I guess it happens since map creation allows multi dataset selection.

### CODE REVIEW

**Comment by Kartones** [comment]
That's a feature. Upon importing a dataset, it will create a default "xxx Map" Map/Visualization if you're in the new dashboard (or use an import flag).

**Comment by xavijam** [comment]
It is a feature because we have removed the step where user can set the name of the new map.

**Comment by Kartones** [comment]
:+1:

**Comment by juanignaciosl** [comment]
@xavijam  Why it does not take (first) dataset name? It would be more meaningful.

**Comment by xavijam** [comment]
Because it could be confused, imagine first dataset is called "Untitled dataset"...

**Comment by juanignaciosl** [comment]
:sparkles:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2743/))

**Pull request merged**
