### PR TITLE
9482 private datasets warning

### PR DESCRIPTION
**Pull request by hacheka**
This pull request has been created as a result of a challenge sent by @javisantana and @xavijam 
It resolves CartoDB/cartodb#9482 

There are changes in two places:
- In private builder, when exporting a map with private datasets, a warning shows up.
- In a map public page, when exporting the map it shows different warning depending on the private datasets ownership: it they are yours, it warns you that the private datasets will be exported. If you don't own them, the dialog warns you that not all the data will be exported.

You can find the GIFs of the different scenarios below.

Some notes about this pull request:
- There are tests for the new view logic. Anyway, no tests have been created related to code where no previous tests exist. This code only makes minor changes in existing logic, so no new specs have been created because it'd been implied to write tests for logic not related to the issue.
- An iteration of this PR could be to apply these changes to organizations, where users can have access to datasets not owned by them.
## Changes explained

There have been changes in private builder page and map public page.
### Private builder

New render option passed to modal-export-map-view indicating if the map contains private datasets.

**Map with public datasets**

public dataset

**Map with private datasets**

private dataset
### Map public page

Two data attributes rendered at the export map link: `data-private-datasets` and `data-owning-private-datasets` These attributes are filled at controller level and retrieved in the link event handling function. Passed to the modal view constructor.

**Map with public datasets**

public export

**Map with private datasets owned by the current user**

owning private

**Map with private datasets owned by another user**

not owning private

I guess that @xavijam is the one to review this PR. Be nice! ;)

Regards,
Ivan

### CODE REVIEW

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by xavijam** [comment]
Closing since we would manage in a short term properly.

**Pull request closed without merging**
