### PR TITLE
Explicit error message for 401, 404 and not resolved download errors

### LINKED ISSUE #2952: Improve feedback in imports in non-accessible datasources
Specially when people try MapServer URLs, this week is being common the following error:

```
2015-03-27 21:30:29 UTC: DOWNLOAD ERROR: Code:0 Body:
```

Example: `739cf84b-8540-4f73-9a5d-3cc015523775`

The issue here uses to be that URLs are private (or may need some authentication).

cc @Kartones @juanignaciosl

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones CR this, please. @iriberri do you think user messages are appropriate? I tend to be too technical :_). This fixes #2952.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4202/))

**Comment by iriberri** [comment]
:+1:

**Comment by Kartones** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4211/))

**Pull request merged**
