### PR TITLE
8415 map options

### LINKED ISSUE #8415: Design map options block
We haven't found any design about the image below in the builder.

@nobuti has implemented it but we need some better looking :).

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #8415.

options

Not sure if we are going to implement the snapshot content view, but there it is.

cc @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
IMO snapshots should be disabled, for the moment, and we could add the message about we will release it soon. (@saleiva)
Then, about map options, I'd disable those components we don't have it yet, but I'd show them, because, for now, we could enable/disable, scroll-wheel, search and zoom.
Also, about the logo, where should it be placed? (@saleiva @javisantana).

**Comment by xavijam** [comment]
About code 🇪🇸  ❤️

**Comment by javisantana** [comment]
just to be sure @gfiorav are the map options included in map caps?

**Comment by gfiorav** [comment]
@javisantana 

Yes they are!

**Comment by nobuti** [comment]
Already working persisting map options and included editor header:

map-options-revamp

We need https://github.com/CartoDB/cartodb.js/pull/1333 in order to make the vis responsive to overlays addition/deletion.

**Comment by xavijam** [comment]
Any answer about the **logo**?

**Comment by xavijam** [comment]
Ok, logo position will be showed up first in a design, we will add it later. @urbanphes ticket for reference?

**Comment by urbanphes** [comment]
@piensaenpixel ask me for the visual design

**Comment by xavijam** [comment]
I forgot to mention that logo can be only "disabled" if use has a "paid" account :S.

**Comment by nobuti** [comment]
Done.

**Comment by xavijam** [comment]
Merge when green :)

**Comment by xavijam** [comment]
Frontend tests in our CI passed, ready to go man!

**Pull request merged**
