### PR TITLE
Don't let change/add/remove icon within fill component when layer is autostyled

### PR DESCRIPTION
**Pull request by xavijam**
Related with: #11761.

Basically that ^^^.

#### STTest

- Check #11761 issue and check those steps, easy.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
I think that there's an issue. It now works for STR. Nevertheless, I can't manage to get IMG selection back after removing autostyle. Neither clicking in the autostyle button nor setting a color would bring it back.

It seems related to the fact that autostyle is not reseted:

```js
layersData[1].options.style_properties.properties.autoStyle
"a4762d66-0b04-4a8c-a501-e1b73440af3f"
```

```ruby
irb(main):015:0> v.layers[1]['options']['style_properties']['properties']['autoStyle']
=> "a4762d66-0b04-4a8c-a501-e1b73440af3f"
```

In the `PUT`, it's still sent:

captura de pantalla 2017-03-20 a las 10 41 47

Keeping this in Acceptance for the moment, as this might be out of scope. Feel free to move to deploy and create a new issue if it is.

**Comment by xavijam** [comment]
Uhm, let me take a look.

**Comment by nobuti** [comment]
@juanignaciosl I can't reproduce it, do you have a specific STR?

**Comment by juanignaciosl** [comment]
Sure!

1. Create a map of points (having at least a string column).
2. Add a category widget.
3. Go to the style tab, being there, apply the auto-style from the widget button.
4. In the style tab, open the fill component. IMG is not there (that's ok, because of autostyle applied).

A)
5. Click auto-style button in order to disable it.
6. At style, IMG should be back (because there's no autostyle applied), but it's not.

B)
5. Set a plain color (this disables the autostyling).
6. At style, IMG should be back (because there's no autostyle applied), but it's not.

**Comment by xavijam** [comment]
Thanks @nobuti for taking care of it. Makes sense to not repeat the same action twice in different places 👍 .

**Comment by xavijam** [comment]
Do you mind to take a look again @juanignaciosl ? (Because you found the problem) If not there is no problem 💋 .

**Comment by juanignaciosl** [comment]
Works \o/

**Comment by xavijam** [comment]
Ole! :). Moving to deploy then?

**Pull request merged**
