### PR TITLE
default marker-line-width to 1

### PR DESCRIPTION
**Pull request by saleiva**

### CODE REVIEW

**Comment by saleiva** [comment]
@javierarce can you take a look?

**Comment by saleiva** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5000/))

**Comment by javierarce** [comment]
This defaults are also intentend for the pecan previews, right?

**Comment by saleiva** [comment]
Uhm... good idea

**Comment by javierarce** [comment]
Ok, I'll change the pecan default then.

:+1: code looks fine.

**Pull request merged**
