### PR TITLE
Redesign add buttons

### PR DESCRIPTION
**Pull request by rubenmoya**
Related to: #13122

## Add new layer
screen shot 2017-12-14 at 13 06 59

## Add new widget
screen shot 2017-12-14 at 13 07 18

## Add new analysis
screen shot 2017-12-14 at 13 07 53

### CODE REVIEW

**Comment by matallo** [comment]
ready to be accepted at ded10 @arianaescobar

**Comment by matallo** [comment]
with latest changes in layers the colors in the analysis and the layers differ as the layer color is somehow persisted, I made the changes in https://github.com/CartoDB/cartodb/pull/13215/commits/f396753b25799f79198415d93469a551227e69aa to color the layer as per this reference, as we do with the analyses

@juanignaciosl do you have any hint why we'd want to persist these colors, instead of do this with the reference?

screen shot 2017-12-14 at 18 08 20


btw, @arianaescobar told me to promote every color but the blue one in third position

**Comment by juanignaciosl** [comment]
> @juanignaciosl do you have any hint why we'd want to persist these colors, instead of do this with the reference?

@matallo no idea :-\ I could come up with some guesses, but it'd be only guessing. Could it be related to keeping the color on layer reordering? @xavijam , @ivanmalagon , any clue?

**Comment by rubenmoya** [comment]
Btw, I've realised we forgot to add the loading/error states to the analyses view, back to development!

**Comment by matallo** [comment]
@juanignaciosl I already asked several people and we are as clueless, the thing is the letter is persisted, and the color reference is consistent per the letter, so I'm pushing this, thanks!

**Comment by juanignaciosl** [comment]
@matallo ok. Sorry about asking about this, but I'm lacking some context and information:

1.- Is this something that we must address within this PR, or can it be tackled independently?
2.- How urgent is this?

**Comment by matallo** [comment]
ha, not that urgent, @arianaescobar asked if we could tackle at the time of doing her acceptance and I kinda sneaked it in, I'm creating a separate PR for this 👍

**Comment by juanignaciosl** [comment]
Great, thanks! 🤗

**Pull request merged**
