### PR TITLE
Deprecate old visualization enpoint

### LINKED ISSUE #3045: Deprecate old visualization enpoint
After deploying #2937 there're a couple of new errors because of usage of the API with wrong syntax. Previously those requests returned no data because `visualizations.id` was `text`, but now it's `UUID` and fails.

Errors:

https://rollbar.com/vizzuality/CartoDB/items/5392/
```
Sequel::DatabaseError: PG::Error: ERROR: invalid input syntax for uuid: "2266"
LINE 1: ...*) AS "count" FROM "visualizations" WHERE ("id" = '2266') LI...
^

... 23 non-project frames
24
File "/app/models/visualization/collection.rb", line 88 in fetch
25
File "/app/models/visualization/locator.rb", line 54 in get_by_id
26
File "/app/models/visualization/locator.rb", line 34 in visualization_from
27
File "/app/models/visualization/locator.rb", line 17 in get
28
File "/app/controllers/api/json/visualizations_controller.rb", line 213 in vizjson1
... 6 non-project frames
35
File "/app/controllers/application_controller.rb", line 41 in wrap_in_profiler
... 68 non-project frames
```

https://rollbar.com/vizzuality/CartoDB/items/5391/

```
Sequel::DatabaseError: PG::Error: ERROR: invalid input syntax for uuid: "nonuuidstring"
LINE 1: ...) AS "count" FROM "visualizations" WHERE (("id" = 'nonuuidstring...
^

... 23 non-project frames
24
File "/app/models/visualization/collection.rb", line 88 in fetch
25
File "/app/models/visualization/locator.rb", line 54 in get_by_id
26
File "/app/models/visualization/locator.rb", line 34 in visualization_from
27
File "/app/models/visualization/locator.rb", line 17 in get
28
File "/app/controllers/admin/visualizations_controller.rb", line 420 in resolve_visualization_and_table
29
File "/app/controllers/admin/visualizations_controller.rb", line 81 in public_table
... 6 non-project frames
36
File "/app/controllers/application_controller.rb", line 41 in wrap_in_profiler
... 68 non-project frames
```

If they correspond to deprecated APIs they might be finally deleted. If they are legit endpoints, it should return a 400 (bad request) because of id format.

### PR DESCRIPTION
**Pull request by Kartones**
Closes #3045

### CODE REVIEW

**Comment by Kartones** [comment]
@juanignaciosl CR please!

**Comment by javisantana** [comment]
\o/

**Comment by juanignaciosl** [comment]
:+1: for the changes. Have you checked whether all errors because of `visualizations.id` format are because of this endpoint?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2874/))

**Comment by Kartones** [comment]
No, not all are from here, but I wanted first to remove this from the equation. Now I'll check the others and fix at another ticket.

**Comment by juanignaciosl** [comment]
Ok, great :-)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2877/))

**Pull request merged**
