### PR TITLE
Add pecan specs

### PR DESCRIPTION
**Pull request by javierarce**
Adds specs for the PecanView view.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5195/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5199/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5202/))

**Comment by javierarce** [comment]
Mind to have a look, @xavijam?

**Comment by xavijam** [comment]
tests always welcome :de:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5203/))

**Pull request merged**
