### PR TITLE
Remove duplicated notification in application layout

### PR DESCRIPTION
**Pull request by csubira**
https://github.com/CartoDB/cartodb/issues/14936

### CODE REVIEW

**Comment by csubira** [comment]
Ready as well in staging with a _green_ notification to do the Acceptance step using `u-duplicated`(as regular user) and/or `o-duplicated-admin`(as organization admin user)

**Comment by csubira** [comment]
@gonzaloriestra Thanks for reviewing! I've been checking past issues and this notification banner was added via this ticket https://github.com/CartoDB/cartodb/issues/14859. Apparently, there wasn't any implementation in Central. So, go ahead and open the new issue there! 
Is it needed for this week as well?

**Comment by gonzaloriestra** [comment]
@csubira great, thanks! I'll add an issue. Regarding the priority, I'd say is not so urgent. What do you think @ana-md?

**Comment by gonzaloriestra** [comment]
Wait, we don't even show the billing page for On-premises, so for sure it's not urgent!

**Comment by ana-md** [comment]
Yeah, not urgent at all! :) Thank you!

**Comment by gonzaloriestra** [comment]
Issue to fix the billing page: https://github.com/CartoDB/cartodb-central/issues/2599

**Pull request merged**
