### PR TITLE
2585 csv regression fix

### PR DESCRIPTION
**Pull request by rafatower**
@Kartones CR please

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2458/))

**Comment by Kartones** [comment]
:+1:

**Comment by rafatower** [comment]
This is the difference between production and clinker:
* clinker:
```
17:14:39 + ruby --version
17:14:39 ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-linux]
```
* production:
```
$ ruby --version
ruby 1.9.3p550 (2014-10-27) [x86_64-linux] Brightbox
```

This affects the CSV implementation, which is part of ruby's stdlib. I'm deactivating that test for the moment, once merged in master for a while I'm gonna ask them to modify their installation in order to avoid disruption in the release process

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2461/))

**Pull request merged**
