### PR TITLE
Doesn't add trails when the heatmap is static

### PR DESCRIPTION
**Pull request by fdansv**
Ref. #3333 

@javisantana

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3228/))

**Comment by javisantana** [comment]
does make sense for cumulative?

**Comment by fdansv** [comment]
@javisantana i think it does, they look good with trails!

**Comment by javisantana** [comment]
I don't it makes sense but ok :es:

**Comment by fdansv** [comment]
OK, just changed it so that there are no trails by default on cumulative. Merging.

**Pull request merged**
