### PR TITLE
Optimize table geometry types

### PR DESCRIPTION
**Pull request by rafatower**
@rochoa code review please

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1479/))

**Comment by javisantana** [comment]
are we totally sure that a connection for each table to varnish is going to improve performance?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1481/))

**Comment by rochoa** [comment]
I see two extra issues:

1. Moving all sql api requests from POST to GET
1. Moving all sql api requests from v1 to v2

That's without considering if it's worthy to use the SQL API or not. Now...

Caching at SQL API level through /api/v2/sql could improve the situation:
 - if we could reuse the connection to the SQL API with a high keep alive
 - and same tables are accessed multiple times (I'm not aware of how frequently that method is used)
 - but since we have to use a different host for each user I don't know if it will be worthy in production environment

**Comment by rafatower** [comment]
Replying first to the second: I'll try to think of a better solution.

**Pull request closed without merging**
