### PR TITLE
Move google button outside login/signup form

### LINKED ISSUE #10242: Google signup shouldn't require username
STR

1. Go to /signup
2. Leave username empty and press Google signup button.

Username should not be required. It should try with the email username first and fail only if there's a collision (at least, this  was the previous behaviour and I don't know that it has changed on purpose).

cc @MariaCheca @javitonino @xavijam

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #10242

### CODE REVIEW

**Comment by javitonino** [comment]
CR @MariaCheca

**Comment by MariaCheca** [comment]
A screenshot to see everything's in its place would be great 🤗

**Comment by javitonino** [comment]
Sure!, there you go

screenshot_20161019_132133

**Comment by MariaCheca** [comment]
👍

**Pull request merged**
