### PR TITLE
Add headers for caching

### PR DESCRIPTION
**Pull request by amartinj**
Closes https://github.com/CartoDB/product/issues/127

### CODE REVIEW

**Comment by javitonino** [comment]
Who is going to test this?

**Comment by amartinj** [comment]
@owayss told me he would be doing the final acceptance. I've added the PR to infra kanban ;)

**Comment by owayss** [comment]
LGTM, and we tested in staging. @javitonino, please deploy whenever you feel ready:)

**Comment by javitonino** [comment]
Will deploy after Varnish update.

**Comment by owayss** [comment]
@javitonino, we have upgraded Varnish in all production clouds :rocket:

**Pull request merged**
