### PR TITLE
Fix firefox scroll in new modal layout #9859

### LINKED ISSUE #9859: Analysis window won't scroll in Firefox
### STR

Issue discovered during this training https://github.com/CartoDB/solutions/issues/540#issuecomment-248969728

* Open CARTO in Mozilla Firefox (`v48.0`).
* Add an analysis to a layer
* Scrolling does not work in the "Add a new analysis" modal.

cc @CartoDB/support for awareness

### PR DESCRIPTION
**Pull request by piensaenpixel**
@xavijam could you take a look?

Firefox:
image

Chrome
image

Fix - https://github.com/CartoDB/cartodb/issues/9859

### CODE REVIEW

**Comment by xavijam** [comment]
👍 , cc @nobuti who knows a lot about custom scroll problems with firefox :9.

**Comment by nobuti** [comment]
LGTM

**Comment by xavijam** [comment]
You can merge, don't take into account on premise fail.

**Comment by piensaenpixel** [comment]
@xavijam but deault is fail :(

**Comment by xavijam** [comment]
No no, it fails because frontend onpremises issues has not been passed, don't worry about them.

**Comment by xavijam** [comment]
I've restarted it in any case, just for you :)

**Comment by piensaenpixel** [comment]
cool thanks :*

**Pull request merged**
