### PR TITLE
Splits track.js errors into multiple apps

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Refs #2658.

### CODE REVIEW

**Comment by xavijam** [comment]
I like the approach, @viddo, what do you think?

**Comment by viddo** [comment]
:ok_hand:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2723/))

**Comment by alonsogarciapablo** [comment]
@javisantana PTAL at this. It's ready to be merged but first we need to setup those keys in production. @viddo can help me with that. Thx

**Comment by javisantana** [comment]
:es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2757/))

**Pull request merged**
