### PR TITLE
Carousel component

### PR DESCRIPTION
**Pull request by xavijam**
screen shot 2016-05-03 at 18 09 40

The way should be as in:

https://github.com/CartoDB/cartodb/blob/ae8c42155fb418a42c062e58f916362eebc10c29/lib/assets/javascripts/cartodb3/editor/widgets/widgets-form/widgets-form-content-data-view.js#L39

`template` attribute could be a label or directly a HTML piece of code.

CR: @matallo
cc @javierarce  @piensaenpixel @viddo

### CODE REVIEW

**Comment by xavijam** [comment]
retest this please

**Comment by xavijam** [comment]
@jvillarf happening the same problem with on-premises backend tests.

**Comment by jvillarf** [comment]
@xavijam this is not the same issue. It's another server, with Internet access and if you take a look, only backend **user_mover** tests have failed.

**Comment by matallo** [comment]
@xavijam shouldn't the component be added to CartoAssets? at least the styling (mind my ignorance)

**Comment by xavijam** [comment]
@jvillarf: there isn't any change in backend code, so I don't know what is going on here.
@matallo: no, there shouldn't be there. Because CartoAssets should only contain the stuff that all compents need to share, this carousel is only for the Editor.

**Comment by matallo** [comment]
spectacular

just curious about the style living in the editor, instead of the CartoAssets, and the highlight attribute for the hover, can't that be accomplished by just using CSS?

**Comment by xavijam** [comment]
With only using CSS, rest of elements wouldn't notice if there was any change/update over those items. 
Adding that attribute lets those components know if there is any component being highlighted.

**Comment by matallo** [comment]
roger that! applying to the infowindows asap it's available ^___^

**Comment by xavijam** [comment]
retest this please

**Comment by jvillarf** [comment]
retest this please

**Comment by jvillarf** [comment]
@xavijam , not sure why "restest" it's not working. I have relaunched the tests on https://ci.cartodb.net/job/CartoDB-PR-Onpremise/213/console (it's a completely different slave, so we'll see if it fails in the same user_mover step)

**Comment by jvillarf** [comment]
@xavijam it has failed again with the same tests. As far as i know, other PRs are working fine for **user_mover** specs : https://github.com/CartoDB/cartodb/pull/7286

Will try to re-launch those that worked yesterday, to see if they are still working.

**Comment by xavijam** [comment]
Really weird :(

**Comment by jvillarf** [comment]
Hey, i'm not sure why, but user_mover are always failing now... It'll be possibly related with a code update. Will talk with zenitram about it.

Sorry for the inconveniences, i think you are safe to merge :)

**Comment by xavijam** [comment]
👍

**Pull request merged**
