### PR TITLE
Added custom attribution of layers to viz.json

### LINKED ISSUE #5216: Display dataset attribution in maps
Datasets can now have custom attribution (editable from the Edit Metadata dialog). This is stored at the visualization level in the DB. The current version of the `viz.json` doesn't expose the attribution of individual "CartoDB" layers so that will be the first thing that needs to be done (both for layer_groups and named_maps).

This is the current format of the viz.json for named_maps:

```
  ...
  "layers": [
    {
      "layer_name": "untitled_table",
      "interactivity": "cartodb_id",
      "visible": true,
      "legend": {}
    }
  ]
  ...
```
And for layer_groups:

```
...
"layer_definition": {
  "stat_tag": "0f75ae92-4b3a-11e5-9c1d-080027880ca6",
  "version": "1.0.1",
  "layers": [
    {
      "id": "bd2230ca-d28c-41e7-9331-9fa69f015f60",
      "parent_id": null,
      "children": [],
      "type": "CartoDB",
      "infowindow": {
        "fields": [],
        "template_name": "table/views/infowindow_light",
        "template": "<div class=\"cartodb-popup v2\">\n  <a href=\"#close\" class=\"cartodb-popup-close-button close\">x</a>\n  <div class=\"cartodb-popup-content-wrapper\">\n    <div class=\"cartodb-popup-content\">\n      {{#content.fields}}\n        {{#title}}<h4>{{title}}</h4>{{/title}}\n        {{#value}}\n          <p {{#type}}class=\"{{ type }}\"{{/type}}>{{{ value }}}</p>\n        {{/value}}\n        {{^value}}\n          <p class=\"empty\">null</p>\n        {{/value}}\n      {{/content.fields}}\n    </div>\n  </div>\n  <div class=\"cartodb-popup-tip-container\"></div>\n</div>\n",
        "alternative_names": {},
        "width": 226,
        "maxHeight": 180
      },
      "tooltip": {
        "fields": [],
        "template_name": "tooltip_light",
        "template": "<div class=\"cartodb-tooltip-content-wrapper\">\n  <div class=\"cartodb-tooltip-content\">\n  {{#fields}}\n    {{#title}}\n    <h4>{{title}}</h4>\n    {{/title}}\n    <p>{{{ value }}}</p>\n  {{/fields}}\n  </div>\n</div>",
        "alternative_names": {},
        "maxHeight": 180
      },
      "legend": {
        "type": "none",
        "show_title": false,
        "title": "",
        "template": "",
        "visible": true
      },
      "order": 1,
      "visible": true,
      "options": {
        "sql": "select * from untitled_table_1",
        "layer_name": "untitled_table_1",
        "cartocss": "#untitled_table_1 {\n // points\n [mapnik-geometry-type=point] {\n    marker-fill: #FF6600;\n    marker-opacity: 1;\n    marker-width: 12;\n    marker-line-color: white;\n    marker-line-width: 3;\n    marker-line-opacity: 0.9;\n    marker-placement: point;\n    marker-type: ellipse;marker-allow-overlap: true;\n  }\n\n //lines\n [mapnik-geometry-type=linestring] {\n    line-color: #FF6600; \n    line-width: 2; \n    line-opacity: 0.7;\n  }\n\n //polygons\n [mapnik-geometry-type=polygon] {\n    polygon-fill:#FF6600;\n    polygon-opacity: 0.7;\n    line-opacity:1;\n    line-color: #FFFFFF;\n   }\n }",
        "cartocss_version": "2.1.1",
        "interactivity": "cartodb_id",
        "table_name": "\"\"."
      }
    }
  ]
}
...
```
cartodb.js will need to display this attribution in the map and show/hide it as the layer is shown/hidden.

Things to do:

- [ ] Include this new attribution in the viz.json (inside the layers in layer_groups and named_maps).
- [ ] Update cartodb.js so that the attribution of these layers is set on the map.

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #5216.

@Kartones or @juanignaciosl, would any of you take a look at this please? It took me a while to write the test, but finally got some integration tests :weary:. Thanks for your help!

### CODE REVIEW

**Comment by Kartones** [comment]
:+1:  although that test is only testing the `Carto::Visualization` model, not the old one... 

Could you try building one forr https://github.com/CartoDB/cartodb/blob/master/spec/models/visualization/relator_spec.rb ? (even if with some heavy stubbing should be possible) I fear  old backend bugs

**Comment by alonsogarciapablo** [comment]
retest this please

**Comment by alonsogarciapablo** [comment]
@Kartones Please take a look at [this commit](https://github.com/CartoDB/cartodb/commit/c0f5940c4f41d101130ceef708185064b9b219b7) that adds a very basic test for `CartoDB::Visualisation::Relator#related_visualizations`. I'm not very familiar with the underlying models so any feedback about how to improve that test will be welcome. Thanks!

**Comment by Kartones** [comment]
:+1: is just to be sure it doesn't breaks until we're able to get rid of that backend

**Pull request merged**
