### PR TITLE
Reduce the number of parallel deletions

### LINKED ISSUE #5967: Buggy map remains if all of it's layer's datasets are removed at once
If you delete all the datasets forming the layers of a multilayered map at once, the map they belonged to is not deleted and can be accessed.

Steps to reproduce this:

1. Create a multilayered map with imported datasets
2. Delete all datasets making the layers of the map in one go (multiple selection)
3. Go to Maps and see a "phantom" map with no layers

screen shot 2015-10-20 at 12 32 31

### PR DESCRIPTION
**Pull request by ethervoid**
Closes #5967 

Please @viddo check this PR

### CODE REVIEW

**Comment by viddo** [comment]
Verified actually working too?
Code-wise :+1:

**Comment by ethervoid** [comment]
It's working but I'm have to fix some tests

**Comment by viddo** [comment]
:tada:

**Comment by ethervoid** [comment]
retest this please

**Pull request merged**
