### PR TITLE
Loading user for organization public pages fixes #4563

### LINKED ISSUE #4563: ActionView::Template::Error: undefined method `public_url' for nil:NilClass
cc @xavijam 

https://rollbar.com/vizzuality/CartoDB/items/8089/occurrences/6603219043/

```
ActionView::Template::Error: undefined method `public_url' for nil:NilClass
1
File "/home/ubuntu/www/production.cartodb.com/releases/20150720083924/app/views/layouts/public_dashboard.html.erb", line 94 in _app_views_layouts_public_dashboard_html_erb__1450709936428760668_90375480
... 23 non-project frames
25
File "/home/ubuntu/www/production.cartodb.com/releases/20150720083924/app/controllers/admin/pages_controller.rb", line 248 in block (2 levels) in render_maps
... 2 non-project frames
28
File "/home/ubuntu/www/production.cartodb.com/releases/20150720083924/app/controllers/admin/pages_controller.rb", line 247 in render_maps
29
File "/home/ubuntu/www/production.cartodb.com/releases/20150720083924/app/controllers/admin/pages_controller.rb", line 120 in maps_for_organization
30
File "/home/ubuntu/www/production.cartodb.com/releases/20150720083924/lib/cartodb/controller_flows/public/maps.rb", line 12 in organization_content
31
File "/home/ubuntu/www/production.cartodb.com/releases/20150720083924/lib/cartodb/controller_flows/public/content.rb", line 20 in render
32
File "/home/ubuntu/www/production.cartodb.com/releases/20150720083924/app/controllers/admin/pages_controller.rb", line 88 in public
... 6 non-project frames
39
File "/home/ubuntu/www/production.cartodb.com/releases/20150720083924/app/controllers/application_controller.rb", line 74 in wrap_in_profiler
```

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #4563 . @xavijam please CR this.

### CODE REVIEW

**Comment by xavijam** [comment]
Sounds good

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5148/))

**Comment by juanignaciosl** [comment]
@xavijam I just realized a much simpler fix can be done. Could you please CR this again? If you want to check, this is deployed at ded01 and will be until your +1.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5152/))

**Comment by xavijam** [comment]
ok!

**Comment by xavijam** [comment]
Does it solve the 'public_url' thing then?

**Comment by juanignaciosl** [comment]
Yes, [that line](https://github.com/CartoDB/cartodb/pull/4566/files#diff-881062bd28607952eb5b4458fcebbec8L94) was recently added but it looks like it was not actually needed, that's why I pinged you. You can check ded01 if you want.

**Comment by xavijam** [comment]
Like a charm!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5182/))

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5184/))

**Pull request merged**
