### PR TITLE
Monkeypatch ActiveRecord PostgreSQL adapter for reopening connections (fixes #4362) (do not merge)

### LINKED ISSUE #4362: New AR models won't work until restarting Rails after metadata failure
```
ActiveRecord::StatementInvalid (PG::Error: connection not open
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = '"data_imports"'::regclass
               AND a.attnum > 0 AND NOT a.attisdropped
             ORDER BY a.attnum
):
  app/services/carto/data_imports_service.rb:14:in `process_recent_user_imports'
  app/controllers/carto/api/imports_controller.rb:10:in `index'
  app/controllers/application_controller.rb:74:in `wrap_in_profiler'
```

It seems ActiveRecord cannot handle gracefully a metadata connection closed - it won't work until restarting Rails

### PR DESCRIPTION
**Pull request by zenitraM**
This patches the default behavior of ActiveRecord not recovering from PG::Error connection failures.
When an ActiveRecord connection to PostgreSQL fails, it returns a PG::Error: connection not open.

However, this does not close the failed connection, which is reused over and over, causing a failure even if the PostgreSQL server is already back.

The original code was taken from https://github.com/rails/rails/pull/6557 which was not merged for some reason - instead https://github.com/rails/rails/pull/6654 was merged, which fixes a related issue (yet as, even though verify! now works, it is never called actively by Rails).

### CODE REVIEW

**Comment by zenitraM** [comment]
original class is at https://github.com/rails/rails/blob/v3.2.20/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4856/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4860/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4865/))

**Comment by zenitraM** [comment]
cc @CartoDB/backend if you find this fine I'll merge on Monday :)

**Comment by Kartones** [comment]
I am not a monkey-patching expert, @rafatower and @juanignaciosl have deeper knowledge of past AR errors/issues so I'll let them judge, for me looks as ok as this can look X)

**Comment by rafatower** [comment]
I'm ok with it.

No big mysteries in monkey patching, just "opening classes and redefining stuff", simple when you have everything in mind.But breaks the "closed" part of the open/closed principle...

**Comment by juanignaciosl** [comment]
:+1: I don't know if logging the retry might be interesting, but it's entirely up to you.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4962/))

**Pull request merged**
