### PR TITLE
updated cdb to fix cdn issues with torque layer in development

### PR DESCRIPTION
**Pull request by javisantana**

### CODE REVIEW

**Comment by javisantana** [comment]
cc @fdansv

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3091/))

**Comment by saleiva** [comment]
bump!

**Comment by fdansv** [comment]
Sorry, thought I'd answered this. All good to me :shipit:

**Pull request merged**
