### PR TITLE
No data available

### LINKED ISSUE #8155: If there is no data available, we should show the "loading" state + infobox with a message
"There is no data available to be displayed" for example.
In any case it is weird we can't show any data about "european countries", cc @fdansv.

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #8155, #8174, #8049.

cc @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
I miss a screenshot 😬 , but 🚢 :it:

**Comment by nobuti** [comment]
data-columns

**Comment by xavijam** [comment]
👏

**Comment by saleiva** [comment]
👍

**Pull request merged**
