### PR TITLE
Fix SAML & LDAP integrations for on-prem

### PR DESCRIPTION
**Pull request by rafatower**
Story details: https://app.clubhouse.io/cartoteam/story/144728

### CODE REVIEW

**Comment by rafatower** [comment]
@amiedes the test build timed out after 40 min
```
FATAL:  the database system is shutting down
```

**Review by amiedes — APPROVED** [review]
👍

**Comment by rafatower** [comment]
NOTE: The ruby timeouts do not work 100% of the time, definitely not in this case, I think because of the threading model, they cannot interrupt the ruby process when it is in a "native" section (most likely sequel pg client waiting for db)

**Comment by rafatower** [comment]
@amiedes I'm pretty sure it's that evil `until` provoking the stuck situation: https://github.com/CartoDB/cartodb/blob/37dd9d3bfa0c61c3dc23d7902d8519220b84bde7/spec/models/carto/user_creation_spec.rb#L245

I mean, I think I know now how to fix it, but a CI is not very robust if we can get it stuck like that.

**Comment by rafatower** [comment]
I decided to remove the timeouts code in tests ( https://github.com/CartoDB/cartodb/commit/95a1506f5939622da3fbd326f66807e9d5d2df1d and https://github.com/CartoDB/cartodb/commit/bf573f53741f3ae062d339ffc44db4280d2e0814 ) because it does not really work and it can be misleading.

**Pull request merged**
