### PR TITLE
DO UI fixes

### LINKED ISSUE #12352: Data Observatory UI fixes
- There is an empty pixel between the loader and the green indicator.
- Don't display the placeholder (or change the text) for the normalize input when it is disabled because there is no values.

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #12352.

normalize

### CODE REVIEW

**Comment by xavijam** [comment]
What do you think about the normalize placeholder text @CartoDB/design ?

**Comment by urbanphes** [comment]
@nobuti and @xavijam, for me it's fine. The hint says what you have to do.

**Comment by nobuti** [comment]
Good catch @matallo! Fixed.

**Comment by saleiva** [comment]
Text might not be correct. @kevin-reilly can you take a look?

**Comment by kevin-reilly** [comment]
When the check-box is unchecked, the text should read "Enable Normalization"

When the check-box is checked, the text should read "Metric for Normalization"

**Comment by xavijam** [comment]
> When the check-box is unchecked, the text should read "Enable Normalization"
When the check-box is checked, the text should read "Metric for Normalization"

:+1:

**Comment by xavijam** [comment]
screen shot 2017-06-27 at 18 12 26
screen shot 2017-06-27 at 18 12 31

**Pull request merged**
