### PR TITLE
add drag icon

### PR DESCRIPTION
**Pull request by piensaenpixel**
Move https://github.com/CartoDB/cartodb/pull/6984
cc @javierarce

### CODE REVIEW

**Comment by javierarce** [comment]
Should we make the whole item draggable or just use the handler instead?

**Comment by piensaenpixel** [comment]
Really the icon is only information

**Comment by javierarce** [comment]
Which means… :)

**Comment by piensaenpixel** [comment]
hahaha, that the whole item :) not the icon

**Comment by javierarce** [comment]
Ok, :+1: then :)

**Pull request merged**
