### PR TITLE
Rename "Torque Heat" to "Heatmap"

### PR DESCRIPTION
**Pull request by fdansv**
Also removes the check for Heat feature flag, since this feature is irrevocably public  :stuck_out_tongue: 

screen shot 2015-03-16 at 14 29 24

@saleiva @javisantana

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2364/))

**Comment by fdansv** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2369/))

**Comment by javisantana** [comment]
:es:

**Pull request merged**
