### PR TITLE
Updates export dataset copy

### PR DESCRIPTION
**Pull request by javierarce**
Original issue: #4986

Updated in the two export dialogs: 

Public page: 

screen shot 2015-08-19 at 13 05 31

CartoDB Editor:

screen shot 2015-08-19 at 13 06 47

Updated: the title of the captures was wrong, I changed the order

### CODE REVIEW

**Comment by saleiva** [comment]
In the public page doesn't make sense, right? I mean, you cannot select it...

**Comment by javierarce** [comment]
Well, in the particular case of my capture you can't, but in general you do and the current text is "Click on the preferred format to export the dataset to.".

**Comment by saleiva** [comment]
Ok

**Pull request merged**
