### PR TITLE
Exclude failed data library imports

### LINKED ISSUE #9418: Data library loses dataset after import fails
## STR

1. Go to `Data Library` and look for a dataset, e.g. "NYC School Districts".
1. Select and `Connect dataset`.
1. Make the import fail [0].
1. Get an error like "Ouch! Error connecting nyc_school_districts".
1. Do a fresh search for "NYC School Districts" again.

## Current result
`0 NYC School Districts datasets found`.

## Expected result
"NYC School Districts" should be present in data library results.

cc @xavijam 

[0] I raised an exception as per:

```diff
diff --git a/services/datasources/lib/datasources/datasources_factory.rb b/services/datasources/lib/datasources/datasources_factory.rb
index 5829257..778d129 100644
--- a/services/datasources/lib/datasources/datasources_factory.rb
+++ b/services/datasources/lib/datasources/datasources_factory.rb
@@ -37,6 +37,8 @@ module CartoDB
             additional_config[:http_connect_timeout] = HTTP_CONNECT_TIMEOUT
           end

+          raise MissingConfigurationError.new("unrecognized datasource #{datasource_name}", NAME)
+
           case datasource_name
             when Url::Dropbox::DATASOURCE_NAME
               Url::Dropbox.get_new(DatasourcesFactory.config_for(datasource_name, user), user)
```

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #9418

cc @rochoa

### CODE REVIEW

**Comment by javitonino** [comment]
CR @gfiorav

**Comment by gfiorav** [comment]
Maybe paste the query time increase for cold and hot requests. Just for the record in case we want to come back in the future and evaluate the impact of this and if we should optimise it or not.

📦 it!

**Comment by javitonino** [comment]
Original query:
```
                                                                                   QUERY PLAN                                                                                   
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Right Join  (cost=3667.72..4375.35 rows=1 width=689) (actual time=55.306..55.448 rows=149 loops=1)
   Hash Cond: (edi.external_source_id = es.id)
   Filter: (edi.id IS NULL)
   Rows Removed by Filter: 1
   ->  Seq Scan on external_data_imports edi  (cost=0.00..680.70 rows=35900 width=32) (actual time=0.004..26.216 rows=37547 loops=1)
   ->  Hash  (cost=3666.79..3666.79 rows=264 width=705) (actual time=2.101..2.101 rows=150 loops=1)
         Buckets: 1024  Batches: 1  Memory Usage: 50kB
         ->  Nested Loop Left Join  (cost=17.00..3666.79 rows=264 width=705) (actual time=0.104..1.764 rows=150 loops=1)
               ->  Bitmap Heap Scan on visualizations  (cost=16.89..1523.11 rows=264 width=689) (actual time=0.088..0.416 rows=150 loops=1)
                     Recheck Cond: (user_id = 'XXX'::uuid)
                     Filter: ((NOT locked) AND (type = 'remote'::text) AND ((type <> 'remote'::text) OR ((type = 'remote'::text) AND (display_name IS NOT NULL))))
                     Rows Removed by Filter: 29
                     ->  Bitmap Index Scan on visualizations_user_id_locked_idx  (cost=0.00..16.87 rows=381 width=0) (actual time=0.053..0.053 rows=179 loops=1)
                           Index Cond: ((user_id = 'XXX'::uuid) AND (locked = false))
               ->  Index Scan using external_sources_visualization_id_idx on external_sources es  (cost=0.11..8.12 rows=1 width=32) (actual time=0.005..0.006 rows=1 loops=150)
                     Index Cond: (visualization_id = visualizations.id)
 Total runtime: 55.608 ms
```


Addind the subquery (this PR):
```
 Hash Right Join  (cost=3667.72..294824.16 rows=1 width=689) (actual time=348.123..348.334 rows=149 loops=1)
   Hash Cond: (edi.external_source_id = es.id)
   Filter: (edi.id IS NULL)
   Rows Removed by Filter: 1
   ->  Seq Scan on external_data_imports edi  (cost=0.00..291129.65 rows=35720 width=32) (actual time=0.020..318.464 rows=35247 loops=1)
         Filter: ((SubPlan 1) <> 'failure'::text)
         Rows Removed by Filter: 2300
         SubPlan 1
           ->  Index Scan using data_imports_uuid_key on data_imports  (cost=0.09..8.09 rows=1 width=8) (actual time=0.005..0.006 rows=1 loops=37547)
                 Index Cond: (id = edi.data_import_id)
   ->  Hash  (cost=3666.79..3666.79 rows=264 width=705) (actual time=2.115..2.115 rows=150 loops=1)
         Buckets: 1024  Batches: 1  Memory Usage: 50kB
         ->  Nested Loop Left Join  (cost=17.00..3666.79 rows=264 width=705) (actual time=0.097..1.767 rows=150 loops=1)
               ->  Bitmap Heap Scan on visualizations  (cost=16.89..1523.11 rows=264 width=689) (actual time=0.082..0.414 rows=150 loops=1)
                     Recheck Cond: (user_id = 'XXX'::uuid)
                     Filter: ((NOT locked) AND (type = 'remote'::text) AND ((type <> 'remote'::text) OR ((type = 'remote'::text) AND (display_name IS NOT NULL))))
                     Rows Removed by Filter: 29
                     ->  Bitmap Index Scan on visualizations_user_id_locked_idx  (cost=0.00..16.87 rows=381 width=0) (actual time=0.049..0.049 rows=179 loops=1)
                           Index Cond: ((user_id = 'XXX'::uuid) AND (locked = false))
               ->  Index Scan using external_sources_visualization_id_idx on external_sources es  (cost=0.11..8.12 rows=1 width=32) (actual time=0.005..0.006 rows=1 loops=150)
                     Index Cond: (visualization_id = visualizations.id)
 Total runtime: 348.571 ms
```

**Comment by rochoa** [comment]
BTW Thank you very much for taking care of this so promptly ❤️ .

**Pull request merged**
