### PR TITLE
Moving tweet searches and geocodings to org owner in case of user deletion

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones could you please CR this?

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2795/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2804/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2805/))

**Comment by Kartones** [comment]
:+1:

**Pull request merged**
