### PR TITLE
Exec save action on enter-key on open dialogs

### LINKED ISSUE #2126: Pressing enter when deleting a table opens a new modal
Steps:

* Select a dataset
* Click on "Delete dataset"
* Press enter 5 times
  * The system is just opening new windows. My expected behaviour is that the table gets deleted with the enter.
* Then, I try to manually click on the "Ok, Delete" button. After 1 or 2 clicks, the table gets deleted but the window doesn't close. As the system continues trying to delete an already deleted dataset: 
`DELETE https://ded01testorg.cartodb-staging.com/u/ded01orguser/api/v1/viz/2f197ca6-adf1-11e4-b77a-040120e0c101 404 (Not Found)`
* After this, you need to click those 5 times on the "X" button to hide the delete modal and get back to your dashboard.

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2126 and #2341

### CODE REVIEW

**Comment by viddo** [comment]
ping @xavijam @iriberri

**Comment by iriberri** [comment]
:smile:

**Comment by xavijam** [comment]
:dancer: :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1777/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1780/))

**Pull request merged**
