### PR TITLE
Fix advanced SQL breaking bugs

### PR DESCRIPTION
**Pull request by Jesus89**
Related to: https://github.com/CartoDB/cartodb/issues/13603, https://github.com/CartoDB/cartodb/issues/9974.

Changes:
- Fix `infinite loop` bug introduced in #12916.
- Fix `blank panels` bug introduced in #13324.
- Fix `Fix them` redirection bug. Related to #13090.
- Better error handling: `the_geom`, `the_geom_webmercator`, `cartodb_id`.

**Acceptance**

BEFORE

|   | SQL                                          | UI message                                                                                                                                                                                                            | Blank panels | Inf. loop |
|---|----------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------|-----------|
| 1 | `SELECT x FROM`                              | Error in SQL query: column "x" does not exist                                                                                                                                                                         | Yes          | No        |
| 2 | ` SELECT the_geom FROM`                      | The column "the_geom_webmercator" does not exist                                                                                                                                                                      | No           | No        |
| 3 | ` SELECT the_geom_webmercator FROM`          | -                                                                                                                                                                                                                     | No           | Yes       |
| 4 | `SELECT the_geom, the_geom_webmercator FROM` | lineas_metro_madrid: Postgis Plugin: ERROR: column "cartodb_id" does not existLINE 1: ...e_geom_webmercator",0.001),0.001,true),3) AS geom,"cartodb_i... ^in executeQuery Full sql was: 'SELECT ST_AsTWKB(ST_Simplify | No           | No        |
| 5 | `SELECT cartodb_id FROM`                     | -                                                                                                                                                                                                                     | Yes          | Yes       |
| 6 | `SELECT 1 as x FROM`                         | -                                                                                                                                                                                                                     | Yes          | Yes       |
| 7 | `SELECT * FROM wrong_table`                  | Error in SQL query: relation "wrong_table" does not exist                                                                                                                                                             | Yes           | No        |

AFTER

|   | SQL                                          | UI message                                                |
|---|----------------------------------------------|-----------------------------------------------------------|
| 1 | `SELECT x FROM`                              | Error in SQL query: column "x" does not exist             |
| 2 | ` SELECT the_geom FROM`                      | The column "the_geom_webmercator" does not exist          |
| 3 | ` SELECT the_geom_webmercator FROM`          | The column "cartodb_id" does not exist                    |
| 4 | `SELECT the_geom, the_geom_webmercator FROM` | The column "cartodb_id" does not exist                    |
| 5* | `SELECT cartodb_id FROM`                     | The column "the_geom_webmercator" does not exist          |
| 6* | `SELECT 1 as x FROM`                         | The column "the_geom_webmercator" does not exist          |
| 7 | `SELECT * FROM wrong_table`                  | Error in SQL query: relation "wrong_table" does not exist |

![sql-fix-them](https://user-images.githubusercontent.com/2227572/36968855-0fefa7b8-2064-11e8-97a7-f643970b7792.gif)

**NOTE**

The cases 5* and 6* have the `blank panels` bug and `infinite loop` bug FIXED, but a review is needed in the returned error, because now it returns an `Error in SQL query` error and they should return a `The column does not exist` warning. This may be related with the Maps API responses. New ticket: https://github.com/CartoDB/cartodb/issues/13642.

### CODE REVIEW

**Comment by rubenmoya** [comment]
Tested in staging, looks pretty good, I've found a problem when having an analysis applied, if you're in the `data` tab and reload the page, it renders nothing:

screen shot 2018-03-05 at 09 49 26

If then you click on the `map <-> data` switch it renders, so I think it's missing a listener somewhere to trigger a render after something loads.

**Comment by ivanmalagon** [comment]
Acceptance

Good job. Now nothing breaks badly as before and the user can continue working and she's notified on what's wrong (the SQL query).

However, blank panels are still happening on 2, 3 and 4. I don't consider them critical because now it's shown blank, but it doesn't break the layout and at least there is an infobox telling the user that something is wrong with the query.

Bandera 🇯🇲

**Comment by ivanmalagon** [comment]
The icon of `empty layer` shows up but it'll be tackled in another issue. Don't find it critical neither because the layer is broken in any case.

**Comment by Jesus89** [comment]
Hi @rubenmoya. Good catch! I'll take a look.

Hi @ivanmalagon. The `blank panels` bug is not happening anymore. The behavior that you saw in cases 2,3,4 is the expected behavior. When there is a Warning message (`the_geom_webmercator` or `cartodb_id`) the DATA tab should be empty until the SQL query is updated and the rest of the tabs should work without any error message.

Thanks for the acceptance!

**Comment by Jesus89** [comment]
I'm going to deploy to staging the fix for the empty DATA on reload.

fix-data-reload

**Pull request merged**
