### PR TITLE
Use package.json version for frontend assets

### PR DESCRIPTION
**Pull request by viddo**
Removes the need to have that config/frontend.yml file and duplicate the version nr. From what I can see there's no reason to have both really.

### CODE REVIEW

**Comment by viddo** [comment]
@CartoDB/frontend + @javisantana

**Comment by javisantana** [comment]
<3

**Comment by xavijam** [comment]
\o/

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3658/))

**Comment by viddo** [comment]
Clinker passed and deploy on staging too, so unless you have any more feedback I'd say it should be good to go :)

**Pull request merged**
