### PR TITLE
Upgrade cartodb extension to 0.19.0

### PR DESCRIPTION
**Pull request by jgoizueta**
Use version 0.19.0 of the SQL extension, which includes a new function `CDB_EstimateRowCount`.

### CODE REVIEW

**Comment by jgoizueta** [comment]
@rafatower can you take a quick look?

**Comment by rafatower** [comment]
LGTM. Nevertheless it is worth adding a note to the `README.md` regarding the changed dependency.

**Comment by jgoizueta** [comment]
I'll put a notice in NEWS.md (@rafatorre you meant NEWS, not README, right?)

**Comment by rafatower** [comment]
right, sorry I'm sometimes a bit dyslexic with TEXT IN CAPS :smile:  :+1:

**Pull request merged**
