### PR TITLE
Detect max named map templates import error

### PR DESCRIPTION
**Pull request by iriberri**
Fixes https://github.com/CartoDB/cartodb/issues/6275

### Description
In its configuration, Windshaft states a maximum number of `maxUserTemplates`. This is typically set to 4096.

When a dataset is imported, CartoDB creates a named map for it. If the named maps limit has been reached, the named maps wrapper was raising an HTTP exception that was understood as an unknown import error by the platform.

### Proposed solution
In order to detect this limit, two new exceptions have been defined.

The first one, `TooManyTemplatesError` is created [in the wrapper side](https://github.com/CartoDB/cartodb/blob/8c4ea94398cbda7af93fda603d5464aae8e76cb7/services/named-maps-api-wrapper/lib/named-maps-wrapper/exceptions.rb#L18) and it's raised [when it detects the limit error in the response of the named map creation](https://github.com/CartoDB/cartodb/blob/8c4ea94398cbda7af93fda603d5464aae8e76cb7/services/named-maps-api-wrapper/lib/named-maps-wrapper/named_map.rb#L49). In the near future, this part should be re-done and we should  take care of comparing the status code `409: Conflict` which will be added in the Named Maps API. (More info about the open issue in CartoDB-Windshaft [here](https://github.com/CartoDB/Windshaft-cartodb/issues/346)).

In the import side, I have defined a new exception `TooManyNamedMapTemplatesError` [here](https://github.com/CartoDB/cartodb/blob/8c4ea94398cbda7af93fda603d5464aae8e76cb7/services/importer/lib/importer/exceptions.rb#L39), that will be responding to the import error code `6670` (the next number, following the already existent list of import codes related to limits).

A rescue will recover the `CartoDB::NamedMapsWrapper::TooManyTemplatesError` from Windshaft, and the import process will then handle the error by using the  `CartoDB::Importer2::TooManyNamedMapTemplatesError` exception, as can be seen [here](https://github.com/CartoDB/cartodb/blob/8c4ea94398cbda7af93fda603d5464aae8e76cb7/app/models/data_import.rb#L199).

I tested the solution by forcing the exception in the wrapper at first. Then in staging I reached the maximum number of templates by creating them programatically with the named maps API, and the result was as follows:

image

````
irb(main):001:0> DataImport['85fe4f0a-51c8-4064-9349-f6279f836547'].log
=> #<CartoDB::Log @values={:id=>"5ce2002e-9fb7-438f-a29b-2b8cc7ef0f9f", :type=>"import", :user_id=>"367c0edc-b2ad-4bab-ad43-3d58a6179a93", :created_at=>2015-12-23 15:25:03 +0000, :updated_at=>2015-12-23 15:25:06 +0000, :entries=>"2015-12-23 15:25:04 UTC: Running on server cdb with PID: 2570\n2015-12-23 15:25:04 UTC: new_importer()
2015-12-23 15:25:04 UTC: Fetching datasource public_url metadata for item id /home/ubuntu/www/production.cartodb.com/current/public/uploads/37f53b29756028fdb325/cositis.csv
2015-12-23 15:25:04 UTC: File will be downloaded from /home/ubuntu/www/production.cartodb.com/current/public/uploads/37f53b29756028fdb325/cositis.csv
2015-12-23 15:25:04 UTC: Before importer run\n2015-12-23 15:25:04 UTC: Starting import for /home/ubuntu/www/production.cartodb.com/current/public/uploads/37f53b29756028fdb325/cositis.csv
2015-12-23 15:25:04 UTC: Unpacking /home/ubuntu/www/production.cartodb.com/current/public/uploads/37f53b29756028fdb325/cositis.csv
2015-12-23 15:25:04 UTC: Filename: /tmp/imports/20151223-2570-19ta0p4/cositis.csv Size (bytes): 25
true: Importing data from /tmp/imports/20151223-2570-19ta0p4/cositis.csv
true: File-based import load\ntrue: Detected encoding ISO-8859-1
true: Using database connection with {:adapter=>\"postgres\", :encoding=>\"unicode\", :host=>\"localhost\", :port=>5432, :database=>\"cartodb_dev_user_367c0edc-b2ad-4bab-ad43-3d58a6179a93_db\", :username=>\"postgres\", :conn_validator_timeout=>900, :user=>\"development_cartodb_user_367c0edc-b2ad-4bab-ad43-3d58a6179a93\"}\nfalse: ogr2ogr call:            OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=ISO-8859-1  /usr/bin/ogr2ogr -f PostgreSQL   PG:\"host=localhost port=5432 user=development_cartodb_user_367c0edc-b2ad-4bab-ad43-3d58a6179a93 dbname=cartodb_dev_user_367c0edc-b2ad-4bab-ad43-3d58a6179a93_db password=-b2ad-4bab-ad43-3d58a6179a93\"  -lco DIM=2 -lco PRECISION=NO /tmp/imports/20151223-2570-19ta0p4/cositis.csv  -nln cdb_importer.importer_57588876a98911e5b085080027880ca6 -nlt PROMOTE_TO_MULTI  
true: ogr2ogr output:          
true: ogr2ogr exit code:       0
true: Georeferencing...
true: Disabling autovacuum for \"cdb_importer\".\"importer_57588876a98911e5b085080027880ca6\"
true: Trying ip guessing...
true: Trying country guessing...
true: country_proportion(carla) = 0.0
true: country_proportion(pepe) = 0.0
true: Creating the_geom column
true: Enabling autovacuum for \"cdb_importer\".\"importer_57588876a98911e5b085080027880ca6\"
true: Georeferenced\ntrue: Finished importing data from /tmp/imports/20151223-2570-19ta0p4/cositis.csv
2015-12-23 15:25:06 UTC: Proceeding to register
2015-12-23 15:25:06 UTC: Before renaming from importer_57588876a98911e5b085080027880ca6 to cositis
2015-12-23 15:25:06 UTC: Before moving schema 'cositis_1' from cdb_importer to public
2015-12-23 15:25:06 UTC: Before persisting metadata 'cositis_1' data_import_id: 85fe4f0a-51c8-4064-9349-f6279f836547
2015-12-23 15:25:06 UTC: Exception: User reached the limit on number of templates
2015-12-23 15:25:06 UTC: ERROR!

"}>
````

### CODE REVIEW

**Comment by iriberri** [comment]
@rafatower CR please. Not very happy with the code in `data_import.rb`, so I'm open to all feedback. :-)

**Comment by rafatower** [comment]
Looks good to me :+1: 

Bear in mind that improving the code in data_import is not really possible without a complete overhaul of exception handling. I'd leave it as it is for now.

**Comment by iriberri** [comment]
I will deploy this tomorrow morning first time.

**Comment by iriberri** [comment]
I did a quick change here in order to check for the error code 409, which is the one that the API is expected to give from now on on these cases. After tests pass this should be fine to deploy I guess.

**Comment by iriberri** [comment]
Docs update is being taken care of in: https://github.com/CartoDB/docs/pull/674

**Pull request merged**
