### PR TITLE
Adds bodies and subjects to the feature request demo buttons

### PR DESCRIPTION
**Pull request by javierarce**
This PR prepopulates the subject and body of the emails that the users need to send to enable a connector.

Original issue: https://github.com/CartoDB/cartodb/issues/4868
Proposed solution: https://github.com/CartoDB/cartodb/issues/4868#issuecomment-127642038

Example of one of the emails:

screen shot 2015-08-05 at 18 16 48

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5611/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5610/))

**Comment by javierarce** [comment]
Hi, I need some reviews: 

- code: @xavijam 
- text: @brittanymicek or @csobier

**Comment by xavijam** [comment]
Frontend: :+1:

**Comment by csobier** [comment]
My only suggestion is to use Global English whenever possible, and avoid [contractions](https://github.com/CartoDB/website/wiki/Stylish-Writing-Guide#contractions-technical-documentation). 

Subject: *I would like to test the SalesForce Connector*

OR even better, use [Active Voice](https://github.com/CartoDB/website/wiki/Stylish-Writing-Guide#contractions-technical-documentation)

Subject: * I am interested in the SalesForce Connector*

Email body:
*I am interested in....*

**Comment by javierarce** [comment]
Thanks, @csobier. I have updated the texts with your suggestions.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5612/))

**Comment by brittanymicek** [comment]
Sorry, late on this! +1 @csobier suggestions.

Also make sure that "Connector" is capitalized.

Yay!


On Thu, Aug 6, 2015 at 3:02 AM, Javier Arce <notifications@github.com>
wrote:

> Merged #4892 <https://github.com/CartoDB/cartodb/pull/4892>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/4892#event-375001292>.
>



-- 
*Brittany Micek*
Content Writer

*CartoDB—Map Your World's Data*
143 Roebling St 2A, New York, 11211, USA
T: + <%2B34695497365>19174633232
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5671/))

**Pull request merged**
