### PR TITLE
Changes border link to #666

### PR DESCRIPTION
**Pull request by javierarce**
This PR changes the border of the selected option to gray (#666).

screen shot 2015-07-29 at 17 26 21

Non-selected, selected and hovered icons, respectively.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5471/))

**Comment by javierarce** [comment]
@josecruz: can you review this, please?

**Comment by josecruz** [comment]
:green_heart:

**Comment by javierarce** [comment]
Arigato!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5474/))

**Pull request merged**
