### PR TITLE
add upgrade link to public dashboard

### LINKED ISSUE #12929: upgrade link not appearing in static dashboard
upgrade link is not appearing in when user hits quota limits, similarly to static profile

screen shot 2017-10-09 at 11 10 00

### PR DESCRIPTION
**Pull request by elenatorro**
Fixes #12929 

captura de pantalla 2017-10-10 a las 19 36 21

### CODE REVIEW

**Comment by matallo** [comment]
- NEWS.md missing
- Frontend and Backend tests missing (this might not be related to the bugfix)
- good to have the new view added to the suite, but I think it should be added as a new spec (we're not testing wether it works when it should work, but given `isCloseToLimits` it works always)

**Comment by elenatorro** [comment]
Retest this, please

**Comment by elenatorro** [comment]
Retest this, please 🎉

**Comment by matallo** [comment]
@elenatorro bump assets and 🚢 🇮🇹 

the quota attributes in the spec are not needed anymore

**Pull request merged**
