### PR TITLE
Load gmaps lib before cartodb.js for public pages

### LINKED ISSUE #3074: cdb.js:17 you must include google maps library _before_ include cdb
Found in https://team.cartodb.com/u/rochoa

Highlighted map is using gmaps.

### PR DESCRIPTION
**Pull request by viddo**
Fixes #3074, using same gmaps lib include as on old public pages, https://github.com/CartoDB/cartodb/blob/master/app/views/admin/pages/public_dashboard.html.erb#L27

### CODE REVIEW

**Comment by viddo** [comment]
@xavijam ok?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2879/))

**Comment by xavijam** [comment]
I wouldn't load gmaps script unless highlight map uses it. As we do in embed page:
```rails
...
<% if @visualization.map.provider == 'googlemaps' %>
  <script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=false&v=3.12"></script>
<% end %>
...
```

**Comment by viddo** [comment]
Good point, fixed in f0f5930

**Comment by xavijam** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2880/))

**Pull request merged**
