### PR TITLE
Dashboard search being in locked datasets/maps working again

### LINKED ISSUE #4094: Search in locked datasets is enabled but doesn't search
**Steps:**
* Go to the locked datasets section
* Try to search, I used "carla":

The list of datasets remain as it was (there's no search), but the URL applies the "search path":

image

### PR DESCRIPTION
**Pull request by xavijam**
Fixes #4094.

Reviewer: @viddo 
cc @iriberri

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4419/))

**Comment by viddo** [comment]
:+1: code-wise, although I don't think it's clear why it was failing before and what the changes actually do to fix it, care to give some insights? :)

**Comment by xavijam** [comment]
When a search is submit, it generates the url in base of the router model attributes. In that case, if locked attribute is enabled, it will take it in that process and generate the url with the /locked/ string.

**Comment by viddo** [comment]
Aight, thx!

**Pull request merged**
