### PR TITLE
[NOMERGE] only_liked search doesn't filter by user ownership

### LINKED ISSUE #2440: Liked maps / datasets must show all liked maps / datasets by the user
His own ones, and others ones.

### PR DESCRIPTION
**Pull request by juanignaciosl**
@xavijam would you continue with this to close #2440? First check it works, as usual :) Then you'll have to apply the UI interaction you decide. Map link works (goes to the public map page), but datasets fail.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2433/))

**Comment by juanignaciosl** [comment]
@Kartones could you CR this? In addition take a look at the change of meaning of user_id with only_liked: now it means "liked by me", whoever owns it. I don't like overloading parameters, but I think `only_liked` leave me no choice. I would refactor this replacing `only_liked` by `liked_by_user_id`, but this is not the time to do it.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2439/))

**Comment by Kartones** [comment]
Careful, `only_liked` means "show my visualizations with at least 1 like (by others or by myself), while `liked_by_user_id` would be used to "show visualizations I've liked" (from anybody).

So... you need both :(

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
@Kartones and me have lost a tough negotiation with @xavijam and meaning of `user_id` is changed according to this branch: when you set `only_liked` to `true` the meaning of `user_id` is not "the owner of the visualization" but "the user that liked something", so it will return what the current user has liked.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2442/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2445/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2446/))

**Comment by xavijam** [comment]
Closing this pull request because it is already merged in another [branch](https://github.com/CartoDB/cartodb/pull/2786).

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2459/))

**Pull request merged**
