### PR TITLE
Map switch button bottom position fixed

### LINKED ISSUE #8894: Vertical alignment the buttons over map
The zoom control buttons and the change view buttons don't have the same vertical alignment. We should lower 7px the change view buttons.

image

### PR DESCRIPTION
**Pull request by MariaCheca**
Fixed #8894

screen shot 2016-07-18 at 12 45 17
screen shot 2016-07-18 at 15 24 59

CR @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
Could we move it a bit when table view is visible? It is too close to the scroll bar :).

**Comment by MariaCheca** [comment]
Done, added some extra bottom spacing in table view :)

**Comment by xavijam** [comment]
:es:

**Comment by xavijam** [comment]
Merge lady!

**Comment by xavijam** [comment]
EO!

**Comment by MariaCheca** [comment]
✨

**Pull request merged**
