### PR TITLE
Layers order

### PR DESCRIPTION
**Pull request by donflopez**
To improve how the layers are being created to "abcdary" style I'm deleting the rest of the layers with the incorrect letters and their child nodes, recreating them with the correct letter, order and source.

### CODE REVIEW

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by xavijam** [comment]
Let me close this pull request in the meantime @donflopez 💃 . We will open a new one if we decide to tackle the problem :).

**Pull request closed without merging**
