### PR TITLE
Make new widgets appear on top

### PR DESCRIPTION
**Pull request by jesusbotella**
Related to https://github.com/CartoDB/cartodb/issues/13244
----

This PR changes the current behaviour when adding new widgets to any map. From now on, the created widgets will appear on top of the previous ones in the widget list as well as in the widget canvas.

This change required modifications in DeepInsights too, here is the DI PR: https://github.com/CartoDB/deep-insights.js/pull/643

### CODE REVIEW

**Comment by jesusbotella** [comment]
retest this please

**Comment by matallo** [comment]
not sure about this approach, which needs to update (thus make a request) for every existing widget; why not just reverting the order before rendering and do it from bigger order to lower?

**Comment by jesusbotella** [comment]
Yes, I am not a big fan either, I tried to use `this.sync()` to make just one request but it raised an exception and didn't work.

I think your approach is better than mine, but what about the existing widgets? If I have a map with previously created widgets, it will reverse the order of the widgets the first time. But it is true that it will only be the first time and will be easier to handle. What do you think?

**Comment by matallo** [comment]
true dat, I think it is acceptable tough, I'd go for the option preventing a cascade of requests

**Comment by jesusbotella** [comment]
Ok, I think it is better too :)

I am going to make some changes here to leave the code as it was, except for the change of the DeepInsights version. I will ask you for review again when I make the change to render widgets in reverse order in DeepInsights.

**Comment by matallo** [comment]
awesome, thanks mate

**Comment by jesusbotella** [comment]
retest this please

**Comment by rubenmoya** [comment]
Working like a charm! ✨  To deploy! 🚢  it

**Comment by jesusbotella** [comment]
💪

**Pull request merged**
