### PR TITLE
Reenable tests

### PR DESCRIPTION
**Pull request by javitonino**
This reenables a bunch of tests that were disabled because they were missing from the Makefile. Most of them work with minor or no changes at all.

There are still some disabled tests that are old, using minitest, and probably not worth to fix right now. I have deleted the ones that obviously don't do anything, but left the rest in, just in case.

### CODE REVIEW

**Comment by javitonino** [comment]
retest this please

**Comment by javitonino** [comment]
retest this please

**Comment by javitonino** [comment]
retest this please

**Comment by javitonino** [comment]
Also should fix tests in master.

Please CR @gfiorav

**Comment by gfiorav** [comment]
Looks 📦 

Have you checked why they were removed?

**Comment by javitonino** [comment]
Most of them were never enabled in the first place, so probably, forgot to add to the Makefile. Some of them were added as a directory, which works for `make check` but not for parallel execution. Didn't found any test that was purposely disabled, but it is hard to find something in the Makefile log.

**Comment by gfiorav** [comment]
Ok, I guess 🍏 is 🍏 

📦 it when tests pass!

**Pull request merged**
