### PR TITLE
tooltip: fix empty template

### PR DESCRIPTION
**Pull request by matallo**
close https://github.com/CartoDB/cartodb/issues/7736

it was setting an empty template (i.e. `''`) thus not rendering properly the tooltips, this is needed for the click infowindows, but not really for the tooltips at this point

CR @gfiorav

### CODE REVIEW

**Comment by gfiorav** [comment]
Hey @matallo I'm not sure I can do a frontend CR! Maybe ping someone from the frontend team, I'm just a casual visitor 😅

**Comment by alonsogarciapablo** [comment]
👍

**Comment by matallo** [comment]
🚀

**Pull request merged**
