### PR TITLE
Added icon font for editing

### PR DESCRIPTION
**Pull request by xavijam**
- Added sketch file for editing.
- Added [howto](https://github.com/CartoDB/cartodb/blob/187780b3e6a5e182216a82fed4972ae920ef1598/app/assets/fonts/icon_font/README.md) guide for everybody.
- Icon font stylesheet auto-generated each time task is run.

### CODE REVIEW

**Comment by xavijam** [comment]
@saleiva, @carlostallon, @piensaenpixel, could you check if [instructions](https://github.com/CartoDB/cartodb/blob/187780b3e6a5e182216a82fed4972ae920ef1598/app/assets/fonts/icon_font/README.md) are ok?

@viddo, @javisantana, @javierarce and @matallo, do you think I've put the "icon-font stuff" in the correct place? I really look forward to deleting rest of fonts as soon as possible :).

**Comment by viddo** [comment]
I think it's fine, updated the README to [list the advices](https://github.com/CartoDB/cartodb/blob/f7013bb92b6f42ac48a7d266cde962ee585b15f4/app/assets/fonts/icon_font/README.md) properly though :)

**Comment by piensaenpixel** [comment]
It's ok for me :D

**Comment by xavijam** [comment]
Merging

**Pull request merged**
