### PR TITLE
Checking impact of removing reset_user_schema_permissions 

### PR DESCRIPTION
**Pull request by juanignaciosl**
Checking impact of removing reset_user_schema_permissions from setup_organization_user_schema.

Testing this.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
@zenitraM , I've talked to @luisbosque and we think that disabling `reset_user_schema_permissions` could be a valid solution. That solves mover issue, isn't it? Commenting it keeps test passing, and I've been able to create an organization with a user having a function in his original schema, and function is moved and accessible. I don't know if you can think about any issue that might arise.

cc @javitonino , brainstorming here.

**Comment by zenitraM** [comment]
Not sure how it might affect... to be extra-safe we could take it out from the `configure_database` but still call it from the function that calls `configure_database` during the user creation, this way it will not be inside the moving flow, only the initial one

**Comment by javitonino** [comment]
The revocation was added here: https://github.com/CartoDB/cartodb/commit/e96f73d8134765ff870399a4920cddb4cd42ad7c It appears to try to block the user from accessing triggers/functions for quota checking. Is this still an issue? Could the user modify this functions to abuse the limits?

**Comment by juanignaciosl** [comment]
@zenitraM your suggestion makes sense, I'll try it.
PS: 👏 @javitonino for his time travel to 2011 xD I got tired of searching ~2014

**Comment by zenitraM** [comment]
Not sure how it might affect quotas... but any permission changes to things outside the extension should be getting migrated using the migrator so we should be safe by revoking it only on initial exportAFAIK

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
@javitonino, @zenitraM  , CR this, please.

**Comment by zenitraM** [comment]
LGTM

**Comment by javitonino** [comment]
LGTM :+1:

**Comment by juanignaciosl** [comment]
FYI I've also fixed an small bug about dropping functions when schema has dashes. Deploying after tests pass.

**Pull request merged**
