### PR TITLE
Only guesses maps when all columns have been analysed

### LINKED ISSUE #4307: Guess maps when all columns have been analysed
(Moved https://github.com/CartoDB/cartodb.js/issues/560 here)
Implementing the decision tree described in the wiki is being blocked due to the fact that, at the moment, we're generating the maps with each asynchronous column analysis. This is incompatible with a lot of future implementations, which imply the use of other columns in the dataset. At the moment the guessing functions only have access to the description information of the current column, but has no access to the rest.

This first async step should only include discarding columns we don't need and obtaining relevant info about the current column (using the describe methods). Only once all columns have been analysed should we start guessing maps.

### PR DESCRIPTION
**Pull request by fdansv**
Closes #4307 

This allows for full implementation of the decision trees, by gaining access to the analyses obtained from all columns.

CR @javierarce please? ;)
cc @javisantana @saleiva

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4719/))

**Comment by javierarce** [comment]
I think we could use the `this.columns` collection to bind the `change:analyzed` event and launch the analysis instead of using an array.

Have a look to the `_onChangeColumns` method here: https://github.com/CartoDB/cartodb/blob/4307-postguess/lib/assets/javascripts/cartodb/common/dialogs/pecan/pecan_view.js#L128

**Comment by fdansv** [comment]
That makes a lot of sense, hadn't noticed that binding!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4721/))

**Comment by javierarce** [comment]
Merged manually to 4299-pecan-fixes, thanks!

**Pull request closed without merging**
