### PR TITLE
adds fix to user basemap for new code

### PR DESCRIPTION
**Pull request by javisantana**
cc @Kartones 

this is a fix I did in user model, so this is the update for the refactor

### CODE REVIEW

**Comment by Kartones** [comment]
+1

**Comment by javisantana** [comment]
restest this please

**Comment by javisantana** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3486/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3487/))

**Pull request merged**
