### PR TITLE
Fixes unlogged links for likes and Login dropdown

### PR DESCRIPTION
**Pull request by javierarce**

### CODE REVIEW

**Comment by ethervoid** [comment]
Maybe what @xavijam said was related with the Login header too :\

**Comment by xavijam** [comment]
Yep, both, likes (login url if you are not authenticated) and big login button in the header.

**Comment by javierarce** [comment]
Ok, I'll change the title and fix the dropdown here too.

**Comment by javierarce** [comment]
@ethervoid, @xavijam: please have a look

**Comment by xavijam** [comment]
LGTM!

**Comment by ethervoid** [comment]
:+1:

**Pull request merged**
