### PR TITLE
Prevents an error when deleting an overlay

### PR DESCRIPTION
**Pull request by javierarce**
This PR adds some conditions to avoid trying to access a non-existent overlay.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2994/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2995/))

**Comment by javierarce** [comment]
@xavijam: can you have a look, please?

**Comment by xavijam** [comment]
Preventing guy! :es:

**Pull request merged**
