### PR TITLE
Add another OOM check

### PR DESCRIPTION
**Pull request by javitonino**
Pretty error message for https://github.com/CartoDB/cartodb-platform/issues/4810#issuecomment-416592516

### CODE REVIEW

**Comment by javitonino** [comment]
retest this please

**Comment by javitonino** [comment]
GH integration is wonky. Here are the passing tests: https://ci.cartodb.net/job/CartoDB-PR-testing-backend/8885/

**Comment by juanignaciosl** [comment]
I think that this doesn't deserve acceptance. Up to you.

**Comment by javitonino** [comment]
Nope. :rocket:

**Pull request merged**
