### PR TITLE
4690 fix upload file

### PR DESCRIPTION
**Pull request by javierarce**
This PR solves a couple of issues:

* A bug that prevented uploading a dataset after going back to the file dataset selector.
* A bug that prevented uploading the same dataset twice.

The problem with #1 was that the [_checkState method](https://github.com/CartoDB/cartodb/blob/4690-fix-upload-file/lib/assets/javascripts/cartodb/common/dialogs/create/listing/imports/import_data_view.js#L122) left the model in an invalid state (type == 'url' and value == '', which is an invalid URL). 

Original issue: #4690

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5422/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5424/))

**Comment by javierarce** [comment]
@viddo: can you review this PR, please?

**Comment by viddo** [comment]
:+1:

**Pull request merged**
