### PR TITLE
Removing the key binding properly

### PR DESCRIPTION
**Pull request by nobuti**
This PR implements #7327.

The problem was the way we add the `keydown` handler. We used the `bind` method, that returns a new function. But when we tried to remove the binding, that function didn't exist. The implemented solution set a reference to the binded function, and we use it to add and remove the handler.

Also, in order to avoid unnecessary operations, we only respond to the keyup handler only if the select is open.

### CODE REVIEW

**Comment by nobuti** [comment]
Review this please @xavijam

**Comment by nobuti** [comment]
Implemented highlight on show @xavijam

**Comment by xavijam** [comment]
Marvellous 👏 . 🚢  🇮🇹  when tests are passed.

**Comment by xavijam** [comment]
Bump package.json version before merge please (https://github.com/CartoDB/cartodb/blob/master/CONTRIBUTING.md#submitting-contributions).

**Comment by alonsogarciapablo** [comment]
Ole!

**Pull request merged**
