### PR TITLE
Remove synchronizations v1.1 endpoint - Step 1

### PR DESCRIPTION
**Pull request by Kartones**
Step 1 of https://github.com/CartoDB/cartodb/issues/4935

### CODE REVIEW

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5674/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5677/))

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5682/))

**Comment by saleiva** [comment]
buuuump! :)

**Pull request merged**
