### PR TITLE
Increases row data results to 100 for the filter analysis

### LINKED ISSUE #8529: Increase ColumRowData results for filter analysis to 100

### PR DESCRIPTION
**Pull request by javierarce**
Closes #8529

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam 
CC: @saleiva

**Comment by xavijam** [comment]
Wait for our frontend tests

**Comment by saleiva** [comment]
It was @javisantana :)

**Comment by javisantana** [comment]
github does not say that

**Pull request merged**
