### PR TITLE
Remove superfluous close/cancel buttons

### LINKED ISSUE #4378: Remove close button in footer of some modals
So, we're keeping "close" button when it's the only action. So we're going to remove from this modals:

- [x] Dataset metadata:
screen shot 2015-07-09 at 10 57 31 am

- [x] Point metadata
screen shot 2015-07-09 at 12 24 02 pm

- [x] Also, we could change the header icons color to `#666` as well

Thanks to @piensaenpixel for spot this!

### PR DESCRIPTION
**Pull request by viddo**
Fixes #4378 

screen shot 2015-07-16 at 18 16 18
screen shot 2015-07-16 at 18 27 08

### CODE REVIEW

**Comment by viddo** [comment]
ping @josecruz

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5065/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5066/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5069/))

**Comment by viddo** [comment]
bump!

**Comment by josecruz** [comment]
:+1:!

Thanks for the button color change!<3

**Pull request merged**
