### PR TITLE
Adjust tablename limit to 63 chars (as per docs) fixes #3747

### LINKED ISSUE #3747: Ghost tables breaks when renaming to a long name
How to reproduce:
rename a table to a name with 60 chars through the sql api:
```
create table my_table();
select cdb_cartodbfytable('my_table');
alter table my_table rename to this_is_my_table_with_a_long_name_f6mnr990vl8t732bztip0s43hk;
```

Expected:
Table is renamed correctly, after a few seconds it is shown in the dashboard and does not lose any capability

Actual:
Table renamed in the dashboard but cannot be accessed anymore. Inconsistent metadata and name in user DB. ghost tables stuck trying to rename and register it.

There must be some limitation in length of table names.

### PR DESCRIPTION
**Pull request by rafatower**
@javisantana I think this should be fine. The `alter table` through the sql api should fail in other cases. I'm testing it locally and waiting for this to pass the tests.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3866/))

**Comment by rafatower** [comment]
retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3867/))

**Comment by rafatower** [comment]
@juanignaciosl or @Kartones please review (whoever is faster :smile:)

I already tested it in staging so I can tell you it is ok and removes and annoying corner case.

**Comment by Kartones** [comment]
:+1:

**Comment by juanignaciosl** [comment]
:+1:

**Pull request merged**
