### PR TITLE
[NO MERGE] 2202 cast date to number

### PR DESCRIPTION
**Pull request by rafatower**
@Kartones can you please review?

### CODE REVIEW

**Comment by Kartones** [comment]
Uhm, but the original issue is that somehow we didn't had properly installed the extension? because you're basically extracting the logic from the SQL to Ruby but is exactly the same, so I don't know why we don't keep using the extension function...

**Comment by Kartones** [comment]
I mean, the function exists... https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_DateToNumber.sql

**Comment by rafatower** [comment]
Okay, I've look for that and did not found it. The problem are types. A `timestamp with time zone` is different from a `timestamp`

**Comment by rafatower** [comment]
Fixed in the cdb extension.

**Pull request closed without merging**
