### PR TITLE
Legends toggle fix

### PR DESCRIPTION
**Pull request by mbektas**
This is to fix the Legends toggle on Options menu not working.

### CODE REVIEW

**Comment by mbektas** [comment]
@javisantana this was a request that I fixed on our fork. you can merge to main branch with this PR.

**Comment by javisantana** [comment]
I don't know if this is the way to fix this.

The legend should be shown or hidden based on the model, a user action should never change a view directly (specially in this case where we are using a global variable `table`). The view shoudl listen to map changes and hide/show the legend

**Comment by mbektas** [comment]
OK, I will update the fix and have it work based on model changes

**Comment by mbektas** [comment]
Fix based on model change is at PR #7363

**Pull request closed without merging**
