### PR TITLE
npm-shrinkwrap

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Includes:

https://github.com/CartoDB/cartodb.js/pull/1366

@rochoa could you please review changes to `npm-shrinkwrap.json`? thx!

### CODE REVIEW

**Comment by rochoa** [comment]
This is changing deep-insights.js also, is that expected?

**Comment by alonsogarciapablo** [comment]
> This is changing deep-insights.js also, is that expected?
Yes, cause deep-inshights.js depends on cartodb.js#v4 too

**Comment by rochoa** [comment]
But the commit for deep-insights.js itself is changing, not just its cartodb.js#v4 dependency.

Changes in DI.js:

```patch
git diff 4e87dfc..db79b0
diff --git a/src/widgets/histogram/chart.js b/src/widgets/histogram/chart.js
index 9105dff..06b82f4 100644
--- a/src/widgets/histogram/chart.js
+++ b/src/widgets/histogram/chart.js
@@ -164,7 +164,6 @@ module.exports = cdb.core.View.extend({
     this.selectRange(lo_index, hi_index);
     this._adjustBrushHandles();
     this._selectBars();
-    this.trigger('range_updated', lo_index, hi_index);
     this.trigger('on_brush_end', lo_index, hi_index);
   },

diff --git a/src/widgets/histogram/content-view.js b/src/widgets/histogram/content-view.js
index 11461f6..c25d5e7 100644
--- a/src/widgets/histogram/content-view.js
+++ b/src/widgets/histogram/content-view.js
@@ -166,7 +166,6 @@ module.exports = cdb.core.View.extend({
     this.$('.js-content').append(this.histogramChartView.el);
     this.addView(this.histogramChartView);

-    this.histogramChartView.bind('range_updated', this._onRangeUpdated, this);
     this.histogramChartView.bind('on_brush_end', this._onBrushEnd, this);
     this.histogramChartView.bind('hover', this._onValueHover, this);
     this.histogramChartView.render().show();
@@ -255,8 +254,7 @@ module.exports = cdb.core.View.extend({

   _onBrushEnd: function (loBarIndex, hiBarIndex) {
     var data = this._dataviewModel.getData();
-
-    if (!data || !data.length) {
+    if ((!data || !data.length) || (this.model.get('lo_index') === loBarIndex && this.model.get('hi_index') === hiBarIndex)) {
       return;
     }

@@ -283,18 +281,6 @@ module.exports = cdb.core.View.extend({
     }
   },

-  _onRangeUpdated: function (loBarIndex, hiBarIndex) {
-    var self = this;
-    if (this.model.get('zoomed')) {
-      this.model.set({ zoom_enabled: false, lo_index: loBarIndex, hi_index: hiBarIndex });
-    } else {
-      this.model.set({ lo_index: loBarIndex, hi_index: hiBarIndex });
-    }
-
-    var updateStats = _.debounce(function () { self._updateStats(); }, 400);
-    updateStats();
-  },
-
   _onChangeFilterEnabled: function () {
     this.$('.js-filter').toggleClass('is-hidden', !this.model.get('filter_enabled'));
   },
```

**Comment by alonsogarciapablo** [comment]
Also, I see there's https://github.com/CartoDB/deep-insights.js/pull/432, which was merged recently.

**Comment by saleiva** [comment]
which could eventually broke all widgets :^
But, we're here to play.

**Comment by javisantana** [comment]
screen shot 2016-07-22 at 11 18 50 am

**Comment by saleiva** [comment]
screen shot 2016-07-22 at 11 20 49

**Pull request merged**
