### PR TITLE
Update data_import_log_expiration.rake

### PR DESCRIPTION
**Pull request by amnesic**
fix wrong name

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1442/))

**Comment by javisantana** [comment]
@juanignaciosl can you review, sounds good for me

**Comment by juanignaciosl** [comment]
:+1:

**Comment by javisantana** [comment]
thanks!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1691/))

**Comment by vhamer** [comment]
@amnesic we've received your CLA. Thank you!

**Pull request merged**
