### PR TITLE
Update browserify

### LINKED ISSUE #2447: Build failing due to browserify on clinker
[Last case on clinker failing](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1840/console)
```bash
...
Running "browserify:new_dashboard" (browserify) task
00:01:30.649 >> Error: Cannot find module 'new_dashboard/router' from '/home/administrador/jenkins/workspace/CartoDB-PR-testing/lib/assets/javascripts/cartodb/new_dashboard'
00:01:30.651 Warning: Error running grunt-browserify. Use --force to continue.
00:01:30.652 
00:01:30.653 Aborted due to warnings.
00:01:30.661 make: *** [check-frontend] Error 6
00:01:30.678 Build step 'Execute shell' marked build as failure
...
```

However, the file do exist and re-trigger a build seems to fix it on clinker. So far only @xavijam have been able to reproduce it locally, and fixed by re-installing npm packages (i.e. deleting node_modules dir and run `npm install`). Unfortunately he doesn't have a backup of that dir so we could do a diff to see what changed.

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2447 

Ditch `remapify` (in favor of default, relative, requires), since the author don't seem to have time to keep it up-to-date with browserify (and we don't either). This allows us to also update to latest version of browserify that don't seem to have this issue, [and also contain quite a lot of fixes](https://github.com/substack/node-browserify/blob/master/changelog.markdown).

Considering we are a few touching these files and the changes are only for the require calls I don't expect much problems upon updating to master in existing dev branches.

Will re-run clinker a few times to make sure there are no more failures before merging.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1842/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1843/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1844/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1851/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1853/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1854/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1857/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1859/))

**Comment by viddo** [comment]
@xavijam seems we have a winner, I'll merge tomorrow, ok?

**Comment by xavijam** [comment]
ok! :dancer:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1865/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1866/))

**Comment by viddo** [comment]
@CartoDB/frontend FYI, this should fix the broken builds on clinker, read PR desc for info

**Comment by xavijam** [comment]
:dancer:

**Pull request merged**
