### PR TITLE
4586 error after 20 imports through api of table with the same name

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones , @javisantana , what do you think about this solution? It triggers ghost tables synchronously if there's a name collision on a "wrong" user_table (a user_table without matching physical table). I agree this is "leaking knowledge", as Kartones said, but since underlying system doesn't guarantee metadata consistency this might be a good and safe tradeoff.

### CODE REVIEW

**Comment by javisantana** [comment]
I understand that code will run always in a worker, right?

sounds good to me

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5241/))

**Comment by juanignaciosl** [comment]
@javisantana : yep, it's part of the importer.

**Comment by Kartones** [comment]
Don't especially like it but can fix the issue for now (until we have DDL triggers or similar), so :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5309/))

**Pull request merged**
