### PR TITLE
Add deep linking

### PR DESCRIPTION
**Pull request by rubenmoya**
Related to: #13115

### CODE REVIEW

**Comment by jesusbotella** [comment]
I have found a weird/awkward behaviour when adding a new analysis in a layer.

To reproduce it:
1. Click the add button to an analysis from any layer on a map
2. Select any analysis in the modal and click continue
3. Hit the browser back button without adding the new analysis and see that nothing happens

There should be an unwanted blank back state which does nothing instead of taking you to the analysis tab in its initial state. If you hit the back button once again, it will take you to the style tab in the pane.

**Comment by rubenmoya** [comment]
Tests look good, let's go to acceptance! 🏁

**Comment by rubenmoya** [comment]
Back to development, something happened with the disabled tabs:

disabled_tabs

**Comment by rubenmoya** [comment]
Found another issue, when clicking on "Geocode" the "back" link is not working but it is working in production:

goback

**Comment by matallo** [comment]
back to development after this small nit

**Comment by rubenmoya** [comment]
VAMOOOS! 🎉

**Comment by rjimenezda** [comment]
👏 👏 

🌴

**Pull request merged**
