### PR TITLE
publicuser has the cdb_dataservices_client in the search_path

### PR DESCRIPTION
**Pull request by oleurud**
From: https://github.com/CartoDB/cartodb/issues/14283

### CODE REVIEW

**Comment by oleurud** [comment]
You are right

**Comment by juanignaciosl** [comment]
As explained offline, I wasn't right :sweat_smile: 
1.- For organization users behavior doesn' change.
2.- For non-organization users, the build path for database_public_username will prepend `public`, which is not a problem.

Back to acceptance, sorry for the noise.

**Comment by juanignaciosl** [comment]
Acceptance:

Search path of the public user before the deploy: `[{"search_path":"\"$user\",public,cartodb"}],`

Search path of the public user after the deploy: `[{"search_path":"public, cartodb, cdb_dataservices_client, public"}]`

I'm not sure about why `$user` is dropped and replaced by `cartodb`. I'm not 100% sure whether this is fine or not. cc @javitonino

**Comment by oleurud** [comment]
I think there isn't a problem. 

Form the [docs about search_path](https://www.postgresql.org/docs/current/static/runtime-config-client.html):

- `If one of the list items is the special name $user, then the schema having the name returned by SESSION_USER is substituted, if there is such a schema and the user has USAGE permission for it`

This what we are doing on the `build_search_path` method

- `The default value for this parameter is "$user", public`

`$user` is a default value, but we are removing it for every user (less the `publicuser`, until now).

---------------

I am going to make some test too to be more confident.

**Pull request merged**
