### PR TITLE
Limit public maps

### PR DESCRIPTION
**Pull request by gonzaloriestra**
Related to https://github.com/CartoDB/cartodb/issues/14861

`/viz` endpoint now returns a 403 error when changing a visualization's privacy to non-private (public, protected or link) and there is not enough quota.

Still pending to show the proper message by the frontend.

### CODE REVIEW

**Comment by gonzaloriestra** [comment]
@alrocar Yes, privacy can be changed for an unpublished map, but it doesn't make much sense to have a public map not published. So I think it's enough to just check the privacy changes.

**Comment by gonzaloriestra** [comment]
@alrocar no, the behavior is the same as before (but still pending to show a specific message).

**Comment by alrocar** [comment]
Looks like the visualization attached to a map is being made public when a dataset is public, so we should figure out how to avoid that.

**Comment by gonzaloriestra** [comment]
@alrocar I can't approve my own PR, but I approve your latest changes :heavy_check_mark:

**Comment by alejandraarri** [comment]
Acceptance done. Having already 10 public maps, I’ve tried to:
✅  Create a new map. I creates it private by default so no problem here.
✅  Change the privacy of a map from private to public. Got a 403 response and couldn’t change it.
❌  I could duplicate a public map, getting more than 10 public maps. I could do it from dashboard and from builder. 
❌ I could import a public map dragging it into Import API.

**Comment by alrocar** [comment]
On it!

**Comment by alejandraarri** [comment]
> I still have another pending test to do which is sharing a map with colleagues when you are an organization user.

✅ Tested! What happens in this case is that the map is shared internally within the organization, but the map remains private. So no problem here, either.
Screenshot 2019-05-23 at 14 28 40

**Comment by alrocar** [comment]
I addressed both cases to take into account the public map quota:

- Importing a .carto
- Duplicating a map

**Comment by alrocar** [comment]
@gonzaloriestra not sure why there's a `user_mover` test failing, but I guess this is ready for another round of CR

**Comment by gonzaloriestra** [comment]
:heavy_check_mark: LGTM

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
:heavy_check_mark: Acceptance OK (tested everything again)

**Pull request merged**
