### PR TITLE
14052 visualization privacy on migration after downgrade

### PR DESCRIPTION
**Pull request by amartinj**
Close https://github.com/CartoDB/cartodb/issues/14052

### CODE REVIEW

**Comment by amartinj** [comment]
retest this please

**Comment by amartinj** [comment]
retest this, please

**Comment by javitonino** [comment]
I'm picking this up, to have it available for the next migration

**Comment by javitonino** [comment]
Fun fact, Rails 4 tests are completely broken until this is merged, because unlike Rails 3, it has decent error handling when a nested model (UserTable in this case) fails to save :tada:

**Comment by AleGoiko** [comment]
acceptance worked like a charm :sparkles:

**Pull request merged**
