### PR TITLE
2644 geocoding error zipcodes country column

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones could you review this fix for #2644, please? I know changing batch sizes is quite arbitrary, maybe you can suggest a more precise strategy. I've debugged this and saw the SQL API query is HUGE, and error response, after a long wait, was 395K because of the request body. It looks like it got stuck somewhere, since we (neither @rochoa nor me) found no error at SQL API. This is the beginning of the response:
```
#<Typhoeus::Response:0x00000007b14bd8 @options={:httpauth_avail=>0, :total_time=>601.036274, :starttransfer_time=>0.364483, :appconnect_time=>0.0, :pretransfer_time=>0.300692, :connect_time=>0.300668, :namelookup_time=>0.251129, :effective_url=>"http://geocoding.cartodb.com/api/v2/sql", :primary_ip=>"94.23.210.5", :response_code=>503, :redirect_count=>0, :re    turn_code=>:ok, :response_headers=>"HTTP/1.1 100 Continue\r\n\r\nHTTP/1.1 503 Service Unavailable\r\nServer: openresty\r\nDate: Tue, 24 Mar 2015 15:26:47 GMT\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: 418\r\nConnection: keep-alive\r\nRetry-After: 0\r\nX-Varnish: 690082056\r\nAge: 600\r\nX-Cache: MISS\r\n\r\n", :response_body=>"\n<?xml versi    on=\"1.0\" encoding=\"utf-8\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html>\n  <head>\n    <title>503 Service Unavailable</title>\n  </head>\n  <body>\n    <h1>Error 503 Service Unavailable</h1>\n    <p>Service Unavailable</p>\n    <h3>Guru Meditation:</h3>\n    <p>XID: 69008205    6</p>\n    <hr>\n    <p>Varnish cache server</p>\n  </body>\n</html>\n", :debug_info=>#<Ethon::Easy::DebugInfo:0x0000000285a488 @messages=[]>}, @request=#<Typhoeus::Request:0x0000000285b2c0 @base_url="http://geocoding.cartodb.com/api/v2/sql", @original_options={:method=>:post, :body=>"q=WITH+geo_function+AS+%28SELECT+%28geocode_postalcode_points%28Array%5B%2    7SG19+2EA%27%2C%27CO4+5ZJ%27%2C%27CO7+9AB%27%2C%27NR17+1LE%27%2C%27CO1+2BE%27%2C%27CO3+9TH%27%2C%27CM2+8DP%27%2C%27CO9+1UY%27%2C%27CO4+5PR%27%2C%27CO5+7EW%27%2C%27IP7+7BA%27%2C%27CO10+9HZ%27%2C%27CO10+1QP%27%2C%27CO13+0RD%27%2C%27CO2+8NE%27%2C%27CO4+5GT%27%2C%27CO4+5DE%27%2C%27CO6+1LA%27%2C%27CO10+5JW%27%2C%27CM9+8SN%27%2C%27CB25+9NF%27%2C%27CO6+1PS%27%2C%27    CO10+9LD%27%2C%27se249be%27%2C%27CO6+1EQ%27%2C%27CO16+8QH%27%2C%27CO7+8HW%27%2C%27SS17+7JY%27%2C%27CO9+3SA%27%2C%27CM3+2LB%27%2C%27CO16+9QT%27%2C%27CO6+2QA%27%2C%27CO6+2BD%27%2C%27IP21+4LR%27%2C%27CO2+8BB%27%2C%27CO4+3BY%27%2C%27CO9+2AZ%27%2C%27CM7+9UR%27%2C%27CO2+8PS%27%2C%27CM1+4HP%27%2C%27CO12+4UR%27%2C%27ip146ez%27%2C%27CO7+9AP%27%2C%27NR31+9QR%27%2C%27S    W15+6SU%27%2C%27CO15+6EJ%27%2C%27CO6+3JP%27%2C%27CO2+9FJ%27%2C%27CO3+3EZ%27%2C%27Co4+0jw%27%2C%27CO7+0HG%27%2C%27CO3+9AX%27%2C%27CO7+6P
```

many bytes later, this is the end:

```
%5D%29%29.*%29+SELECT+q%2C+c%2C+geom%2C+success+FROM+geo_function&api_key=dcf2fb59f96c1fbc25a6e7fedc5a036ab5905f59&format=csv", :headers=>{"User-Agent"=>"Typhoeus - https://github.com/typhoeus/typhoeus", "Accept-Encoding    "=>"gzip,deflate"}, :maxredirs=>50}, @on_headers=[], @response=#<Typhoeus::Response:0x00000007b14bd8 ...>, @on_complete=[], @on_failure=[]>>
```

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2513/))

**Comment by Kartones** [comment]
Geocoder stuff is more suited for @rafatower who operated with it. I'd say 1k is too low as we're going to do tons of batches with big tables, but again there's no single solution for all scenarios so...

Take into account that from what I see it waited 600 seconds, which is the timeout IIRC for transactions and the like, so yes, something got stuck and just unstuck upon DB timeout.

**Comment by juanignaciosl** [comment]
I'll wait for @rafatower CR then.

**Comment by rafatower** [comment]
I guess it's ok, as you said batch sizes are quite arbitrary.

Just in case I checked the functions and the table it's using and its indexes and they seem to be ok.

**Comment by juanignaciosl** [comment]
Great, @rafatower , thank you very much for the check.

**Pull request merged**
