### PR TITLE
public datasets: fix license icons

### PR DESCRIPTION
**Pull request by matallo**
compromise solution for https://github.com/CartoDB/cartodb/issues/6413

I'll leave the issue open, to create the new icons or replace them with a more general one

CR @xavijam @juanignaciosl

### CODE REVIEW

**Comment by xavijam** [comment]
Screenshot?

**Comment by juanignaciosl** [comment]
Strictly speaking `license_info` can be nil, so it should be checked, but since old code hadn't the check I guess it can be skipped :+1:

**Comment by matallo** [comment]
sure, ded01

screen shot 2016-01-18 at 16 21 23

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
