### PR TITLE
Adds more reserved keywords 

### LINKED ISSUE #2718: Import error by importing file named "fetch"
Steps:

1. Create any CSV file with name `fetch`. The same happens, for example, with a GeoJSON file. I suppose is a general thing.
2. Import it to CartoDB.

````
2015-03-11 11:18:50 UTC: Exception: PG::Error: ERROR:  syntax error at or near \"fetch\"\nLINE 2:           ALTER TABLE fetch
 2015-03-11 11:18:50 UTC: [\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/database/logging.rb:33:in `log_yield'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:411:in `_execute'\"

[...]
````

DataImport ID example: 
` irb(main):002:0> DataImport['8e0c020b-2cea-4f5f-8460-b7408c45dcc4'].log `

### PR DESCRIPTION
**Pull request by iriberri**
Fixes #2718 

I've added a selection of keywords from the complete list of reserved and non-reserved Postgres keywords (below). Not all of them fail in the import process, so I have selected the most common ones which fail.

`all and any array as asc before both cast desc end fetch for from group intersect not offset on or select table then to union when where with`

Complete list:

````
PASSWORD, MODE, ABORT, ABSOLUTE, ACCESS, ACTION, ADD,
 ADMIN, AFTER, AGGREGATE, ALL, ALSO, ALTER, ANALYSE,
 ANALYZE, AND, ANY, ARRAY, AS, ASC, ASSERTION, ASSIGNMENT,
 ASYMMETRIC, AT, BACKWARD, BEFORE, BEGIN, BOTH, BY, CACHE,
 CALLED, CASCADE, CASE, CAST, CHAIN, CHARACTERISTICS, CHECK,
 CHECKPOINT, CLASS, CLOSE, CLUSTER, COLLATE, COLUMN,
 COMMENT, COMMIT, COMMITTED, CONNECTION, CONSTRAINT,
 CONSTRAINTS, CONVERSION, COPY, CREATE, CREATEDB, 
CREATEROLE, CREATEUSER, CSV, CURRENT_DATE,
 CURRENT_ROLE, CURRENT_TIME, CURRENT_TIMESTAMP,
 CURRENT_USER, CURSOR, CYCLE, DATABASE, DAY, DEALLOCATE,
 DECLARE, DEFAULT, DEFAULTS, DEFERRABLE, DEFERRED,
 DEFINER, DELETE, DELIMITER, DELIMITERS, DESC, DISABLE,
 DISTINCT, DO, DOMAIN, DOUBLE, DROP, EACH, ELSE, ENABLE,
 ENCODING, ENCRYPTED, END, ESCAPE, EXCEPT, EXCLUDING,
 EXCLUSIVE, EXECUTE, EXPLAIN, EXTERNAL, FALSE, FETCH,
 FIRST, FOR, FORCE, FOREIGN, FORWARD, FROM, FUNCTION,
 GLOBAL, GRANT, GRANTED, GROUP, HANDLER, HAVING,
 HEADER, HOLD, HOUR, IMMEDIATE, IMMUTABLE, IMPLICIT,
 IN, INCLUDING, INCREMENT, INDEX, INHERIT, INHERITS, INITIALLY,
 INPUT, INSENSITIVE, INSERT, INSTEAD, INTERSECT, INTO, INVOKER,
 ISOLATION, KEY, LANCOMPILER, LANGUAGE, LARGE, LAST,
 LEADING, LEVEL, LIMIT, LISTEN, LOAD, LOCAL, LOCALTIME,
 LOCALTIMESTAMP, LOCATION, LOCK, LOGIN, MATCH, MAXVALUE,
 MINUTE, MINVALUE, MONTH, MOVE, NAMES, NEW, NEXT, NO,
 NOCREATEDB, NOCREATEROLE, NOCREATEUSER, NOINHERIT,
 NOLOGIN, NOSUPERUSER, NOT, NOTHING, NOTIFY, NOWAIT, NULL,
 OBJECT, OF, OFF, OFFSET, OIDS, OLD, ON, ONLY, OPERATOR,
 OPTION, OR, ORDER, OWNER, PARTIAL, PLACING, PREPARE,
 PREPARED, PRESERVE, PRIMARY, PRIOR, PRIVILEGES, PROCEDURAL,
 PROCEDURE, QUOTE, READ, RECHECK, REFERENCES, REINDEX,
 RELATIVE, RELEASE, RENAME, REPEATABLE, REPLACE, RESET,
 RESTART, RESTRICT, RETURNS, REVOKE, ROLE, ROLLBACK,
 ROWS, RULE, SAVEPOINT, SCHEMA, SCROLL, SECOND, SECURITY,
 UNTIL, SELECT, SEQUENCE, SERIALIZABLE, SESSION, SESSION_USER,
 SET, SHARE, SHOW, SIMPLE, SOME, STABLE, START, STATEMENT,
 STATISTICS, STDIN, STDOUT, STORAGE, STRICT, SUPERUSER,
 SYMMETRIC, SYSID, SYSTEM, TABLE, TABLESPACE, TEMP, TEMPLATE,
 TEMPORARY, THEN, TO, TOAST, TRAILING, TRANSACTION, TRIGGER,
 TRUE, TRUNCATE, TRUSTED, TYPE, UNCOMMITTED, UNENCRYPTED,
 UNION, UNIQUE, UNKNOWN, UNLISTEN, UPDATE, USER, USING,
 VACUUM, VALID, VALIDATOR, VALUES, VARYING, VIEW, VOLATILE,
 WHEN, WHERE, WITH, WITHOUT, WORK, WRITE, YEAR, ZONE
````

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4039/))

**Comment by iriberri** [comment]
This test " 1) Table table setups can create a table called using a reserved postgresql word as its name" fails because I'm blocking "where", but importing a table with name "where" fails in production.

**Comment by iriberri** [comment]
This test is failing but I don't know how it worked before, as you cannot create a table called "as" or "where" from the editor:

https://github.com/CartoDB/cartodb/blob/master/spec/models/table_spec.rb#L550

**Comment by saleiva** [comment]
bump!

**Comment by iriberri** [comment]
"right" should be here too. I'll block this PR until @Kartones works in the importer sprint so that we could check the test that is failing, which makes no sense for me but we'd need to check :)

**Comment by Kartones** [comment]
Ok, but from my ignorance, if now `where` is blocked, you should invert the expectation no?
```
Table table setups can create a table called using a reserved postgresql word as its name
Failure/Error: user_database.table_exists?('where'.to_sym).should be_true
expected false to be true
```

**Comment by iriberri** [comment]
Yes, but the nice part is that uploading a file called where fails in production, so I wonder which path does this test follow to pass it :) We discussed this in NY, remember?

**Comment by Kartones** [comment]
Ah, true. Ok, then if you want next sprint we can check in 15 minutes why this used to work, maybe is skipping some step (like manually creating the table). But sure, poke me thursday or friday and we can see

**Comment by saleiva** [comment]
bump!

**Comment by saleiva** [comment]
bump!

**Comment by javisantana** [comment]
retest this please

**Pull request closed without merging**
