### PR TITLE
Add healthcheck fail flag file

### PR DESCRIPTION
**Pull request by zenitraM**
This allows to set a config flag (disable_file on app_config) that will, on each health check, check for the existance of a given file.

If this file exists, the /status route will not perform any additional healthcheck and be forced to return 500.

cc @lbosque @Kartones

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2507/))

**Comment by Kartones** [comment]
:+1: only you use that endpoint so...

**Comment by javisantana** [comment]
why don't we use a code != 500, like 503 so we can know if there is and actual error

**Comment by zenitraM** [comment]
Fair enough, we check for != 200 so that will also do

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2510/))

**Pull request merged**
