### PR TITLE
Updates deepinsights and cartodb.js

### PR DESCRIPTION
**Pull request by fdansv**
Following up from yesterday's https://github.com/CartoDB/deep-insights.js/pull/287 and https://github.com/CartoDB/cartodb.js/pull/1196

@xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
Weird it shows the git://github.com/CartoDB/... have you checked everything is ok in staging?

**Comment by xavijam** [comment]
Hey, CartoDB.js versions differs here and in [Deep-insights](https://github.com/CartoDB/deep-insights.js/blob/master/package.json#L26). They have to be the same.

**Comment by fdansv** [comment]
> Weird it shows the git://github.com/CartoDB/... have you checked everything is ok in staging?

@xavijam according to @rochoa that's due to using a newer version of npm, I'm checking now...

**Comment by rochoa** [comment]
I think @xavijam refers to another thing: you should keep in sync cartodb.js version here and your deep-insights branch.

**Comment by fdansv** [comment]
@xavijam I think I got it now

**Comment by xavijam** [comment]
:+1:, shrinkwrap udpated with your last steps then?

**Comment by fdansv** [comment]
Yesss

**Comment by xavijam** [comment]
:es:

**Pull request merged**
