### PR TITLE
update npm-shrinkwrap.json

### PR DESCRIPTION
**Pull request by gfiorav**
@xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
UPDATE THE WORLD!

**Comment by viddo** [comment]
_How_ did you update the shinkwrap file? manually or running a command? if the latter, which one? I Know that helps to review the change.

**Comment by gfiorav** [comment]
@viddo 

I did 
```
npm run preupdate-internal-deps
npm run update-internal-dept
```

**Comment by viddo** [comment]
👍 btw, preupdate is run implicitly on the 2nd command

That said, seem to have been changes in those updates that breaks some definitions… please look into those

**Comment by xavijam** [comment]
Hey @viddo, we have not updated any dependency in deep-insights, last commit:

https://github.com/CartoDB/deep-insights.js/commit/37c7e5af2f2871bcfc7dd3c3380f0fdfebbdf683

It was only code.

**Comment by xavijam** [comment]
BTW, could you (@viddo) help @gfiorav with those failed tests?

**Comment by xavijam** [comment]
Ready to go then?

**Comment by viddo** [comment]
🚀 ;)

**Pull request merged**
