### PR TITLE
Get rid of a lot annoying console errors.

### PR DESCRIPTION
**Pull request by nobuti**
This PR deletes a lot of console messages when passing tests. Most of them derived from the last change in the modal service module that I introduced a few weeks ago.

### CODE REVIEW

**Comment by xavijam** [comment]
Ah yeah, I saw that recently, :+1: thanks @nobuti 💋 .

**Comment by xavijam** [comment]
Hey mates, this is the perfect PR for using with new tests improvement, cc @ivanmalagon.

**Comment by xavijam** [comment]
:+1:

**Comment by ivanmalagon** [comment]
Tested merging this branch with new affected ones.

Very useful because this discovered a problem with JSON locale files in the new task. Those file were not taken into account neither in copy nor watch.

I'll deploy this ticket to be sure that it doesn't break anything in CI.

**Pull request merged**
