### PR TITLE
Fix pagination for layers with analyses or custom SQL

### LINKED ISSUE #14169: Paging at Builder visualization map view doesn't work with analyses
### Steps to Reproduce

1. Create a table with more than 40 rows.
2. Create a map with it, go to the data view. Table works and can be paged.
3. Add an analysis (trave distance, for example).
4. Try paging. 

{"error":["syntax error at end of input"]}

### current behavior

It won't work, buttons are disabled. It's likely related to this error:

`https://juanignaciosl-2.carto-staging.com/api/v2/sql?api_key=cad05a2079b675c4e77b93d669b913bbf96fc6de&q=select+count(*)+from+`

image

### expected behavior

Pagination should work.

### .carto

[Untitled Map 8 (on 2018-07-16 at 15.21.23).carto.zip](https://github.com/CartoDB/cartodb/files/2198173/Untitled.Map.8.on.2018-07-16.at.15.21.23.carto.zip)

### additional info

* related to https://github.com/CartoDB/cartodb/pull/14139

cc @ramiroaznar

### PR DESCRIPTION
**Pull request by rjimenezda**
Fix #14169 

@Jesus89 requesting your review since you're the original author of this, what do you think?

### CODE REVIEW

**Comment by rjimenezda** [comment]
Acceptance steps:

1 - Create a map with a dataset with more than 40 rows
2 - Add an analysis like buffer, open the data tab, you should be able to click on the next / prev page (original bug)
3 - Remove analysis
4 - Change query to `SELECT * FROM other_dataset` other_dataset being one with less rows.
5 - The paging should work correctly

**Comment by rjimenezda** [comment]
@ramiroaznar staging username: paging-dr-analysis

**Comment by ramiroaznar** [comment]
Checking.

**Comment by ramiroaznar** [comment]
LGTM!

**Pull request merged**
