### PR TITLE
Feature/ch91500/automatically enable do connector for do

### PR DESCRIPTION
**Pull request by juanrmn**
https://app.clubhouse.io/cartoteam/story/91500/automatically-enable-do-connector-for-do-users

### CODE REVIEW

**Review by jgoizueta — CHANGES_REQUESTED** [review]
Good job, this is basically what I had in mind, and checking do availability via gcloud_settings is the way to go.

I think we need to include here also changes to `Visualization::Member#get_connector` (and that will require duplicating `get_provider_name_from_id`; it would be nice to share that code with `DataImport`, but as we already have a lot of redundancy between those two classes I think it's better to leave for a separate task)

**Comment by juanrmn** [comment]
> Good job, this is basically what I had in mind, and checking do availability via gcloud_settings is the way to go.
> 
> I think we need to include here also changes to `Visualization::Member#get_connector` (and that will require duplicating `get_provider_name_from_id`; it would be nice to share that code with `DataImport`, but as we already have a lot of redundancy between those two classes I think it's better to leave for a separate task)

I didn't find a get_connector method in Visualization::Member, did you mean the `Syncronization::Member#get_connector`?

**Comment by jgoizueta** [comment]
Yes, sorry juanrmn, Visualization -> Synchronization, my bad

**Comment by jgoizueta** [comment]
Regarding the failing tests:

```
Failures:

  1) CartoDB::DataMover::ExportJob should move a whole organization
     Failure/Error: group_1 = carto_org.create_group(String.random(5))
     ActiveRecord::StatementInvalid:
       PG::InternalError: ERROR:  spiexceptions.InternalError: plpy.Error: Fatal Group API error: [Errno 111] Connection refused
       CONTEXT:  Traceback (most recent call last):
         PL/Python function "_cdb_group_creategroup_api", line 7, in <module>
           plpy.execute(query)
       PL/Python function "_cdb_group_creategroup_api"
       SQL statement "SELECT cartodb._CDB_Group_CreateGroup_API(group_name, group_role)"
       PL/pgSQL function cdb_group_creategroup(text) line 7 at PERFORM
       :  select cartodb.CDB_Group_CreateGroup('VUnPsc') 
     # ./config/initializers/zz_patch_reconnect.rb:30:in `block in execute'
     # ./config/initializers/zz_patch_reconnect.rb:49:in `with_auto_reconnect'
     # ./config/initializers/zz_patch_reconnect.rb:29:in `execute'
     # ./app/models/carto/group.rb:171:in `create_group_extension_query'
     # ./app/models/carto/group.rb:48:in `block in create_group_with_extension'
     # ./app/models/carto/user_service.rb:186:in `block in in_database'
     # ./lib/carto/db/connection.rb:32:in `connect'
     # ./app/models/carto/user_service.rb:184:in `in_database'
     # ./app/models/carto/group.rb:47:in `create_group_with_extension'
     # ./app/models/carto/organization.rb:121:in `create_group'
     # ./services/user-mover/spec/user_mover_spec.rb:150:in `block (3 levels) in <top (required)>'
     # ./config/initializers/01_app_config.rb:100:in `with_config'
     # ./services/user-mover/spec/user_mover_spec.rb:136:in `block (2 levels) in <top (required)>'

  2) Carto::Api::Public::DataObservatoryController subscriptions checks if DO is enabled
     Failure/Error: central_mock.expects(:check_do_enabled).once.returns(true)
     Mocha::ExpectationError:
       not all expectations were satisfied
       unsatisfied expectations:
       - expected exactly once, not yet invoked: #<Mock:0x5580019973d0>.check_do_enabled(any_parameters)
       satisfied expectations:
       - allowed any number of times, not yet invoked: #<AnyInstance:CartoDB::UserModule::DBService>.enable_remote_db_user(any_parameters)
       - allowed any number of times, not yet invoked: #<AnyInstance:Carto::NamedMaps::Api>.destroy(any_parameters)
       - allowed any number of times, not yet invoked: #<AnyInstance:Carto::NamedMaps::Api>.update(any_parameters)
       - allowed any number of times, not yet invoked: #<AnyInstance:Carto::NamedMaps::Api>.create(any_parameters)
       - allowed any number of times, not yet invoked: #<AnyInstance:Carto::NamedMaps::Api>.show(any_parameters)
       - allowed any number of times, invoked 5 times: #<Mock:0x5580019411d8>.sync(any_parameters)
       - allowed any number of times, invoked once: Carto::DoSyncServiceFactory.get_for_user(any_parameters)
       - allowed any number of times, not yet invoked: Cartodb::Central.new(any_parameters)
     # ./spec/requests/carto/api/public/data_observatory_controller_spec.rb:141:in `block (3 levels) in <top (required)>'

  3) Carto::Api::Public::DataObservatoryController subscription_info checks if DO is enabled
     Failure/Error: central_mock.expects(:check_do_enabled).once.returns(true)
     Mocha::ExpectationError:
       not all expectations were satisfied
       unsatisfied expectations:
       - expected exactly once, not yet invoked: #<Mock:0x5580048b0c48>.check_do_enabled(any_parameters)
       satisfied expectations:
       - allowed any number of times, not yet invoked: #<AnyInstance:CartoDB::UserModule::DBService>.enable_remote_db_user(any_parameters)
       - allowed any number of times, not yet invoked: #<AnyInstance:Carto::NamedMaps::Api>.destroy(any_parameters)
       - allowed any number of times, not yet invoked: #<AnyInstance:Carto::NamedMaps::Api>.update(any_parameters)
       - allowed any number of times, not yet invoked: #<AnyInstance:Carto::NamedMaps::Api>.create(any_parameters)
       - allowed any number of times, not yet invoked: #<AnyInstance:Carto::NamedMaps::Api>.show(any_parameters)
       - allowed any number of times, not yet invoked: Cartodb::Central.new(any_parameters)
     # ./spec/requests/carto/api/public/data_observatory_controller_spec.rb:333:in `block (3 levels) in <top (required)>'

Finished in 1 minute 43.54 seconds
61 examples, 3 failures
```

2 and 3 are simply a matter of adjusting the mocking, since `Central#check_do_enabled` is not called anymore and `User#do_enabled?` is called instead.

1 seems unrelated to this PR

**Review by jgoizueta — APPROVED** [review]
LGTM

**Comment by rafatower** [comment]
Too bad this adds new functionality to a Sequel model (imports)

**Pull request merged**
