### PR TITLE
Feature flags can't be configured in app_config

### PR DESCRIPTION
**Pull request by juanignaciosl**
:eyes: @viddo

### CODE REVIEW

**Comment by viddo** [comment]
:ok:

**Comment by juanignaciosl** [comment]
I _think_ nothing actually uses sample file, but, just in case, let's honor the protocol :sweat_smile: ... Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Pull request merged**
