### PR TITLE
Sanitize columns during import #4049

### PR DESCRIPTION
**Pull request by rafatower**
There are a few changes in this commit:
- Added a new class method `Table#sanitize_columns`
- Added a call to it during import process
- TABLENAME_MAX_LENGTH renamed to PG_IDENTIFIER_MAX_LENGTH
- Fixed a bug in the typecaster: always reload the schema

@Kartones can you please review?

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4985/))

**Comment by Kartones** [comment]
:+1:

**Comment by rafatower** [comment]
As we talked, this needs a small fix: distinguish between reserved names for imports and reserved names for updates. E.g: when copying a table the column name `the_geom` is perfectly legit and should not be renamed.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5039/))

**Pull request merged**
