### PR TITLE
Fixes checkbox alignment issue in the legends panel

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes this alignment issue:

captura de pantalla 2015-05-13 a las 15 30 13

So that it looks :+1: 

captura de pantalla 2015-05-13 a las 15 54 06

Ping @viddo.

### CODE REVIEW

**Comment by viddo** [comment]
Do you have `new_modals` feature flag activated?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3664/))

**Comment by alonsogarciapablo** [comment]
@viddo yes.

**Comment by viddo** [comment]
Re-asking the question with more info: Do you have `new_modals` feature flag activated? Because there are likely some things that are unaligned due to the introduction of the new base styles that clashes with the existing ones in the editor. The `line-height: 1` hints that this is the case.

I setup a file where old styles are overriden to work with the new ones, so I suggest to add the selector class to [the list in the table_overrides.css.scss](https://github.com/CartoDB/cartodb/blob/master/app/assets/stylesheets/editor/table_overrides.css.scss). 

This way the existing styles will continue to work for the users who don't have the new styles, and we can simply remove the old files (+the table overrides) eventually.

**Comment by alonsogarciapablo** [comment]
Great point @viddo. I moved the selector to the css with the overrides.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3666/))

**Pull request merged**
