### PR TITLE
Checking user relationship fixes #3260

### LINKED ISSUE #3260: Fix for visualizations with wrong user_ids
Explore API rake fails because of visualizations with user_id without user

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones @rafatower we NEED FKs :'(

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3092/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3093/))

**Comment by Kartones** [comment]
:+1:  :(

**Comment by rafatower** [comment]
totally agree :+1:

**Pull request merged**
