### PR TITLE
reviewed Help dialog content for Docs. Andy will review for Academy next

### PR DESCRIPTION
**Pull request by csobier**
For [Docs issue#695](https://github.com/CartoDB/docs/issues/695)

@ohasselblad , ready for review from an Academy perspective.  Feel free to edit, I just tried to consolidate and trim down some of the text. The only Help dialog I couldn't find in the UI was the [Adding images to your infowindows](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/help/infowindow_with_images.jst.ejs) dialog. I think it used to appear when "image header" was selected for a Click infowindow? We can confirm with the Editor team before merging.

### CODE REVIEW

**Comment by ohasselblad** [comment]
LGTM!

**Comment by csobier** [comment]
Great! Thanks.

@MariaCheca, can you confirm if the  the [Adding images to your infowindows](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/help/infowindow_with_images.jst.ejs) Help dialog is still in use in the Editor?  
Otherwise, Andy and I would like to merge these Help dialog content changes if you approve?

**Comment by MariaCheca** [comment]
Better @javierarce to solve your question guys :)

**Comment by javierarce** [comment]
Yep, it's still in use. Here's how to get it: 

infowindow

**Comment by csobier** [comment]
Ah, there it is!  Thanks.  
@ohasselblad , do you want to add anything to this dialog or is it good for you?

**Comment by csobier** [comment]
@javierarce , Andy and I have both reviewed all the Editor Help dialogs.  Can you please merge if everything looks okay to you?

**Comment by javierarce** [comment]
retest this please

**Comment by javierarce** [comment]
There are some issues with the build. Would you mind to update this branch with master?

**Comment by csobier** [comment]
@javierarce , I merged the latest Master in this WIP branch, as requested. See results. (I do not feel comfortable correcting the hound violations found, I think that is beyond the scope of what I should be doing, right?). Can you fix/merge?

**Comment by javierarce** [comment]
@csobier I'm not sure what was going on with this PR, so I've created a new one [over here](https://github.com/CartoDB/cartodb/pull/6737) with your changes and I'm closing this one.

I noticed that there are some markdown links in the `.jst` templates that should be transformed to regular HTML links (like I did [here](https://github.com/CartoDB/cartodb/commit/5c80f80b0931f346506a9d82af749f075b8fc4e0) before we can merge that new PR.

**Pull request closed without merging**
