### PR TITLE
Small fixes to widgets

### PR DESCRIPTION
**Pull request by rubenmoya**
Related to: https://github.com/CartoDB/cartodb/issues/13579, https://github.com/CartoDB/cartodb/issues/12918 and https://github.com/CartoDB/support/issues/913

### Description
This PR fixes multiple things related to widgets:

- Category widget not using collapsed state when refreshing
- Formula widget showing `No data available` when data was `0` (js falsy values <3) (https://github.com/CartoDB/cartodb/issues/13579)
- Widgets not being collapsed In responsive mode (https://github.com/CartoDB/cartodb/issues/12918)
- Formula widget showing value instead of title when collapsed (https://github.com/CartoDB/support/issues/913)
- Category widget showing stats when collapsed

### Screenshots
screen shot 2018-03-12 at 12 56 48
screen shot 2018-03-12 at 12 56 56
screen shot 2018-03-12 at 12 57 20

### CODE REVIEW

**Comment by ramiroaznar** [comment]
LGTM!

BUT can you test if this is working on your side? I found very difficult to get to that popup.

image

**Comment by rubenmoya** [comment]
Mmmm, maybe that's why it wasn't collapsing in responsive 😂

**Comment by rubenmoya** [comment]
Just talked to @piensaenpixel. 

We're always showing the widget in small viewports and hiding the `Toggle` button.

**Comment by ramiroaznar** [comment]
@rubenmoya what does it mean?

**Comment by rubenmoya** [comment]
That means the widgets will always be shown in responsive mode (no toggle), and the toggle button will be hidden.

**Comment by ramiroaznar** [comment]
OK, can I test that as well?

**Comment by rubenmoya** [comment]
Not yet, let me fix it and deploy it again

**Comment by ramiroaznar** [comment]
:boom: LGTM! Amazing job mate!!!

**Pull request merged**
