### PR TITLE
#3811 Follow redirects on URL imports

### LINKED ISSUE #3811: Follow redirects on URL imports (yes, again!)
@Kartones thought we already did, but in this case the URL is failing.

If we use the URL that makes the redirect, the import fails:
http://water.weather.gov/ahps/download.php?data=kmz_obs

If we use the direct URL, it works:
http://water.weather.gov/ahps2/worldfiles/ahps_national_obs.kmz

Same happens for the zipped version of the URL:
http://water.weather.gov/ahps/download.php?data=tgz_obs

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #3811

### CODE REVIEW

**Comment by Kartones** [comment]
@rafatower CR please

/cc @iriberri when this goes live you can tell the affected user their urls will work

**Comment by rafatower** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4594/))

**Comment by iriberri** [comment]
Awesome! Thanks for the concurrent import thing too :)

**Pull request merged**
