### PR TITLE
Don't enable background importer polling when it is initialized in table view

### LINKED ISSUE #3827: Looks like importing a dataset with a map opened in another tab is also adding that dataset as a layer on that map

### LINKED ISSUE #3837: When finishing an import started from the dashboard and being in a dataset view, it throws an error modal and it shouldn't

### PR DESCRIPTION
**Pull request by xavijam**
Not starting the polling is the key, it won't check if any import is in process and it will only listen to imports created in that dataset/map view.

Fixes #3827 and fixes #3837.

REVIEW: @viddo 

cc @saleiva

### CODE REVIEW

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3982/))

**Comment by viddo** [comment]
Seems simple enough, although it's not clear to me that this is the side-effect by simply remove this method call. To avoid problems in the future, how about adding a comment on that method explaining why it should not be called in the editor context in addition to this change?

**Comment by xavijam** [comment]
Agree! Adding comments.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3987/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3988/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3989/))

**Pull request merged**
