### PR TITLE
3140 viz tests fixes

### PR DESCRIPTION
**Pull request by rafatower**
First part of the ticket. This method has the advantage that there's no inconsistency when creating URL's with the helper methods of the type `api_v1_visualizations_index_url`.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2992/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3000/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3004/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3006/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3040/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3065/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3067/))

**Comment by rafatower** [comment]
@Kartones or @juanignaciosl can you please review?

There are some test files deleted, I checked they did not work before changes and they are not executed by the Makefile.

**Comment by juanignaciosl** [comment]
If those deleted tests are hard (>10 minutes, IMHO) to make them work, :+1: . Otherwise I'd fix them instead of deleting (in a similar fashion that we've already enabled older, disabled specs).

**Comment by Kartones** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3097/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3098/))

**Pull request merged**
