### PR TITLE
Type guessing is wrongly disabled by default

### LINKED ISSUE #2649: Type guessing is wrongly disabled by default
In some of the multiple refactors of params and options passing it has been broken
```
$ git log -Stype_guessing 
```
commit 9f57e19e6200733db47ff76574f6cda67909c5bd
commit c2ec8a135fcb051f338ee2d8c48b0eff9669460c
commit 9b6c519daf0e1a723e35a54bd3661fe7ae67288a
commit bf885b73b84b3ee88c4d12658ddebee7cd24ff63
commit e253fde5f35728d166a9df2adfcfe6d377a53584

cc/ @Kartones

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #2649

### CODE REVIEW

**Comment by Kartones** [comment]
@rafatower CR please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2124/))

**Comment by saleiva** [comment]
hotfix! Deploy ASAP please!

**Comment by rafatower** [comment]
:+1:

**Comment by saleiva** [comment]
bump!

**Comment by Kartones** [comment]
deploying right now ;)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2126/))

**Pull request merged**
