### PR TITLE
Moving notification after Central creation fixes #3022

### LINKED ISSUE #3022: Mail notification for a new sub-user in an org is sent before the creation actually works
I tried to create a sub-user in the Adidas org and both attempts failed (because of quota and repeated email).

Nevertheless, I got both notification emails in my inbox

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones CR this fix for #3022, please. I don't like moving logic from model to controller, but since user creation and Central synchronization is also done in the opposite way (from Central to box) moving it to the model would probably imply flags to avoid sync and so on. :(

### CODE REVIEW

**Comment by Kartones** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2776/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2780/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2796/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2801/))

**Pull request merged**
