### PR TITLE
Enrich downloaded layer event

### PR DESCRIPTION
**Pull request by elenatorro**
Related issue: https://github.com/CartoDB/cartodb/issues/13391

Add "from_view" field to Download Layer event

### CODE REVIEW

**Comment by elenatorro** [comment]
I have a couple of questions about this issue:

Right now, we only track these events if we have a defined layer model, which we do not always have. That is why I changed a the code to send the event even though there is no layerModel, because otherwise we are not tracking a lot of events.

captura de pantalla 2018-04-24 a las 11 20 23


While testing it, I am having an error when sending the event because of the new field added, `from_view`. I guess it is something related with Segment configuration, but I might be wrong. I am not sure if this is something that can be configured in Segment or in our backend, here: https://github.com/CartoDB/cartodb/blob/master/lib/carto/tracking/formats/segment.rb

Thank you very much cc @msaenzde11 @ethervoid

**Comment by msaenzde11** [comment]
Hey @elenatorro, shouldn't be Segment. Segment adapts itself to what you send, so if you send an event with a new field, it just creates a new column in the schema.

At a first glance it comes from here: https://github.com/CartoDB/cartodb/blob/31c9e1f88df4b83a53a3caabcebfba07fd9aab34/lib/carto/tracking/events.rb#L85

Didn't get deeper to it as I don't know Ruby, so it's probabl harder for me to debug, but lmk if you needed some help :)

**Comment by ethervoid** [comment]
I've added [this commit](https://github.com/CartoDB/cartodb/pull/13879/commits/e4acb263c284648dac904d536b06ed24dfb74e76) that should fix the problem.

**Comment by elenatorro** [comment]
Just noticed after you added it, I also pushed the change 🙈

**Comment by ethervoid** [comment]
Yep, I see it. I was going to ask you if you consider it a required or optional property but I thought that when you see it you could change it in the way you needed it :)

**Comment by elenatorro** [comment]
I added you as a reviewer 👀

**Pull request merged**
