### PR TITLE
Use locally installed grunt instead of global for tests

### PR DESCRIPTION
**Pull request by zenitraM**

### CODE REVIEW

**Comment by zenitraM** [comment]
cc @viddo @xavijam 

This removes the need to install grunt-cli globally, so root or `sudo npm` is not needed to pass specs on CI. :sparkles:

**Comment by viddo** [comment]
Fine by me. But we still have the issue with npm version, don't we?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by xavijam** [comment]
so?

**Comment by zenitraM** [comment]
so should we merge this?

**Comment by viddo** [comment]
Updated w/ master, to have this change also being run on Travis to make sure it works there too… if it works I'd say :shipit:

**Comment by viddo** [comment]
@zenitraM see anything weird on https://ci.cartodb.net/job/CartoDB-PR-Onpremise/1844/consoleFull ? If not then :shipit:

**Comment by zenitraM** [comment]
It passed so :shipit:

**Pull request merged**
