### PR TITLE
Move play/pause button to the side of time series

### PR DESCRIPTION
**Pull request by rjimenezda**
re: https://github.com/CartoDB/cartodb/issues/12387

---

Cartodb PR: https://github.com/CartoDB/cartodb/pull/12482
Deep-insights.js PR: https://github.com/CartoDB/deep-insights.js/pull/561
Cartodb.js PR: https://github.com/CartoDB/cartodb.js/pull/1701

---

This PR integrates all changes in deep-insights to move the play / pause button to besides the time-series.

it also includes some other changes regarding the animation duration as discussed in https://github.com/CartoDB/cartodb/issues/12449

### CODE REVIEW

**Comment by matallo** [comment]
code looks legit (approved the PRs in cartodb.js and deep-insights)

however I found setting everything up we don't have any margin/padding between the button and the first vertical axis tick

screen shot 2017-07-20 at 14 06 18

disable button until we have the animation duration stuff sorted out works great

**Comment by matallo** [comment]
the UI artefact just seem to be happening with a dev branch of Windshaft, to be fixed then, works like a charm with master branch, promoting to acceptance then

**Comment by xavijam** [comment]
Deploying it to ded02 with last changes in DI and Carto.js.

**Comment by xavijam** [comment]
I've seen several small UI issues in the acceptance, so I've mentioned (offline) @urbanphes. Let's wait for his review.

**Comment by urbanphes** [comment]
I see a bit of weird some spaces inside the widget:

slice

if you have any comment, tell me, please.

**Comment by xavijam** [comment]
Already fixed those problems, I feel really comfortable deploying this tomorrow morning, cc @matallo @rubenmoya.

**Pull request merged**
