### PR TITLE
Catching and displaying Central errors fixes #2229

### LINKED ISSUE #2229: Multiuser: creation errors in Central aren't caught by the box
An user created an account with an email that already existed in Central. This was due to the account being an inactive one: it didn't exist in the box but failed Central validations.

However it didn't warn the user about this and let him create the account, which didn't work due to the lack of DNS.

To replicate, just create a multiuser account using an email which already exists in Central.

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones CR this fix for #2229 and #1945, please.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1595/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1597/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1601/))

**Comment by Kartones** [comment]
+1

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1619/))

**Comment by juanignaciosl** [comment]
@Kartones CR this again, please. Organization user deletion wasn't implemented.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1629/))

**Comment by Kartones** [comment]
+1

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1646/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1647/))

**Pull request merged**
