### PR TITLE
Start analysis animation when hovering the whole element + adds link to breadcrumb

### LINKED ISSUE #10211: Make analysis animation work when hovering the whole card
Right now it only works when hovering the animation area, but its very normal to go to the analysis description directly, so seeing the animation in that case would be helpful.

Adding here as part of the same ticket the need of making the breadcrumb active.

### PR DESCRIPTION
**Pull request by javierarce**
Start analysis animation when hovering the whole element + adds link to breadcrumb.

I've decided to add a link to "All" in the breadcrumb:

screen shot 2016-10-17 at 17 11 40

Closes #10211

### CODE REVIEW

**Comment by javierarce** [comment]
CC: @piensaenpixel @saleiva 
CR: @xavijam

**Comment by javierarce** [comment]
CC: @piensaenpixel @saleiva 
CR: @xavijam

**Comment by xavijam** [comment]
No tests for click back to category?

**Comment by javierarce** [comment]
Yes, sorry, I submitted the comment by accident when I closed the PR :_( not my day

**Comment by javierarce** [comment]
Frontend is green, merging.

**Pull request merged**
