### PR TITLE
Create dialog fixes [no merge]

### PR DESCRIPTION
**Pull request by xavijam**
- UI bug styles (https://github.com/CartoDB/cartodb/issues/2330).
- Add submit button near the URL input when connecting a dataset (https://github.com/CartoDB/cartodb/issues/2398).
- Incorrect link on connect dataset modal (https://github.com/CartoDB/cartodb/issues/2397).
- Disable click on the dataset title on the create new map modal window (https://github.com/CartoDB/cartodb/issues/2393).
- Typo in services header template ((https://github.com/CartoDB/cartodb/issues/2350)

### CODE REVIEW

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1855/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1856/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1874/))

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1875/))

**Pull request merged**
