### PR TITLE
add hover icons

### PR DESCRIPTION
**Pull request by piensaenpixel**
@xavijam could you take a look?

image

### CODE REVIEW

**Comment by xavijam** [comment]
Yay! icons for tooltips! 💃 , but they should not have the tail/tick right? @urbanphes?

**Comment by piensaenpixel** [comment]
you're right :) 5 minutes :)

**Comment by piensaenpixel** [comment]
@xavijam take a look :)

image

**Comment by xavijam** [comment]
👍 🆗

**Pull request merged**
