### PR TITLE
Purge http and https redis vizjson #3346

### PR DESCRIPTION
**Pull request by rafatower**
@Kartones please review

### CODE REVIEW

**Comment by Kartones** [comment]
:+1: for you :-1: for me for leaving this bug

**Comment by rafatower** [comment]
retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3257/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3264/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3265/))

**Pull request merged**
