### PR TITLE
Iri/tables dataset

### PR DESCRIPTION
**Pull request by iriberri**
@xavijam 

Not sure if I've changed more than needed. I'd wait for full tests here...

### CODE REVIEW

**Comment by xavijam** [comment]
In JS part is ok, but maybe any backend guy should review it too
@juanignaciosl @Kartones @rafatower

**Comment by juanignaciosl** [comment]
LGTM

**Comment by Kartones** [comment]
ok

**Comment by iriberri** [comment]
Ops :(

**Comment by rafatower** [comment]
`git grep` is your friend :)

**Comment by xavijam** [comment]
Frontend tests btw, you have to fix them iri, sorry :dancer:

**Comment by iriberri** [comment]
Sure :-) but won't be able until the night, so wait for them!

**Comment by iriberri** [comment]
Should work now. Let's see :smile:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2871/))

**Comment by iriberri** [comment]
Bieeeeen :-) @xavijam

**Comment by xavijam** [comment]
:dancer:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2875/))

**Pull request merged**
