### PR TITLE
Remove synchronizations v1_1 endpoint - Step 2

### PR DESCRIPTION
**Pull request by Kartones**
Closes https://github.com/CartoDB/cartodb/issues/4935
To be released wed 12 to leave 24h of no longer existing JS code redirecting to v1_1 endpoint

### CODE REVIEW

**Comment by Kartones** [comment]
@juanignaciosl CR please

**Comment by juanignaciosl** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5737/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5781/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5782/))

**Pull request merged**
