### PR TITLE
Fix random failures in CI

### PR DESCRIPTION
**Pull request by gonzaloriestra**
Tests related to user imports (in `spec/models/carto/user_migration_spec.rb ` or `services/user-mover/spec/user_mover_spec.rb`) are failing randomly in CI.

The error happens when running the `pg_restore` command ([full log](https://ci.cartodb.net/job/CartoDB-PR-testing-backend/11901/console)):
```
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 4570; 2606 167754782 CONSTRAINT with_link_table with_link_table_pkey test_cartodb_user_3740d73a-bd02-4c8d-8a47-9e0ba5374a59
pg_restore: [archiver (db)] could not execute query: ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
CONTEXT:  SQL statement \"INSERT INTO cartodb.cdb_ddl_execution VALUES (txid_current(), tg_tag) ON CONFLICT (txid) DO NOTHING\"
PL/pgSQL function cartodb.cdb_saveddltransaction() line 3 at SQL statement
Command was: ALTER TABLE ONLY \"with_link_table\"
ADD CONSTRAINT \"with_link_table_pkey\" PRIMARY KEY (\"cartodb_id\");

pg_restore: finished item 4574 CONSTRAINT public_table public_table_pkey
pg_restore: launching item 4575 INDEX public_table_the_geom_idx
pg_restore: creating INDEX \"public.public_table_the_geom_idx\"
pg_restore: [parallel archiver] a worker process died unexpectedly
```

The solution is to [change the Ghost Tables event trigger definition from `cartodb-postgresql`](https://github.com/CartoDB/cartodb-postgresql/pull/360), which seems to be causing this, to add the constraint name explicitly (although they should be equivalent).

### CODE REVIEW

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by gonzaloriestra** [comment]
retest this please

**Comment by alrocar** [comment]
Tested with the cartodb-postgresql extension v0.27.2 in staging and it works fine.

Just deployed the extension to production, now I'm deploying this and then I'll upgrade the extension for all users

**Pull request merged**
