### PR TITLE
Backported user export/import fixes from master branch

### PR DESCRIPTION
**Pull request by zenitraM**
cc @jvillarf

### CODE REVIEW

**Comment by jvillarf** [comment]
Hey @zenitraM as far as i know, is better to not touch the frozen 3.12.X branch, taking into account that this only affects to Jenkins Slaves. The PR is still useful because what we use to do is:
- Make a new branch based on 3.12.X (for instance, 3.12.X_new_user_mover), then merge you branch into it
- After this, we will cook the new cartodb_installer, based on our new branch

Thanks a lot!!!

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by xavijam** [comment]
ping! pong!

**Comment by zenitraM** [comment]
cc @jvilarf can we close this?

**Comment by jvillarf** [comment]
@zenitraM Yes, i think you can go ahead and close this ticket :)

**Pull request closed without merging**
