### PR TITLE
secure cookies for non-dev/test environments

### LINKED ISSUE #4771: secure cookies for non-dev/test environments
Closes https://github.com/CartoDB/cartodb-management/issues/4033

### PR DESCRIPTION
**Pull request by Kartones**
Closes #4771

### CODE REVIEW

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5466/))

**Comment by Kartones** [comment]
@CartoDB/frontend  @CartoDB/systems Do you feel this could break something? I've tried at staging and everything works fine, public map works fine, editor, embeds... Am I missing some scenario?

**Comment by Kartones** [comment]
@juanignaciosl CR please

**Comment by javierarce** [comment]
I'm afraid I don't know what side effects could have this change, sorry :/

**Comment by juanignaciosl** [comment]
AFAIK this might break something if a) cookie is needed under http (without https) because of `secure` or b) cookie is read from JS (because of `httponly`), isn't it, @Kartones ?

I think a) is safe. Check homepage errors and login, but doesn't look dangerous.
I don't know about cookie access (b). I'd check SQL edition and geocoding from the editor. Maybe also accessing "deep linking urls" (http://subdomain.cartodb.com/tables/<name>.

Nothing else to add about the code.

**Comment by Kartones** [comment]
nah, actually behaviour of a) happens if you jump from https to http, that was already there due to the ssl_only/ssl_required at Rails, etc.

b) I've checked and both work nicely

**Comment by Kartones** [comment]
@javisantana please confirm me it is then ok to go as nobody else says anything

**Comment by Kartones** [comment]
ok, @zenitraM pointed out the only two issues we're going to have:
- HTTP public pages won't have logged in users ever, as they use HTTPS for retrieving authenticated sessions
- We allow vizjson endpoint to read the cookie in order to allow fetching private ones if you have a valid session. With this secure change, this will only work if both source and vizjson fetch call use https.

If we are ok with both scenarios... for me good to go. 1st case should already be forbidden because anyway doesn't works currently due to http-https calls, 2nd is probably not even used as was requested by @javisantana IIRC more or less recently.

@saleiva @javisantana ?

**Comment by zenitraM** [comment]
first scenario is broken anyway now as we don't serve `get_authenticated_users` with CORS (maybe we should setup it to only allow *.cartodb.com or $USER.cartodb.com)

**Comment by Kartones** [comment]
... or `$ORG.cartodb.com`. But anyway it will get broken now with the secure flag... I really don't remember or see why we'd like to have public pages with http if the whole editor uses https and embeds/public_maps go separate and don't care much.

The sooner we enforce an https-only policy the better (and public pages are "ours" so is not like touching something in the embed/publicmap), but I'm not the one to make the call

**Comment by zenitraM** [comment]
With the secure flag it won't be broken if we throw the `get_authenticated_users` request always over https

**Pull request merged**
