### PR TITLE
Cc1024 central destroys user even after an error

### PR DESCRIPTION
**Pull request by juanignaciosl**
Error on user destroy should trigger 500. That's handled by `respond_with`, no need to wrap.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
@ethervoid CR this, please.

**Comment by ethervoid** [comment]
I'd love to know more about this change more to know the internals of that magic method than the solution is wrong
https://github.com/CartoDB/cartodb/pull/6525/files#diff-c508ccd140372d4af8b0f4e26df9f09aL56

**Comment by juanignaciosl** [comment]
@ethervoid after a second look, respond_with failed with a 500 because of exception propagation, I think last change should be clearer.

**Comment by ethervoid** [comment]
works for me :+1:

**Comment by juanignaciosl** [comment]
Thanks! Merging after minor Hound fix.

**Pull request merged**
