### PR TITLE
Explicit resque queues. See CartoDB/cartodb-platform#907

### PR DESCRIPTION
**Pull request by juanignaciosl**
Closes CartoDB/cartodb-platform#907.

@rafatower CR this, please.

cc @CartoDB/backend , @MariaCheca

### CODE REVIEW

**Comment by juanignaciosl** [comment]
cc @xavijam

**Comment by juanignaciosl** [comment]
cc @zenitraM

**Comment by zenitraM** [comment]
:+1:

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
