### PR TITLE
Sanitizes output

### PR DESCRIPTION
**Pull request by javierarce**
Fixes: https://github.com/CartoDB/cartodb/issues/4784

### CODE REVIEW

**Comment by javierarce** [comment]
cc @matallo

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5480/))

**Comment by matallo** [comment]
tested it :+1:

**Comment by javierarce** [comment]
Oh, you went the extra mile, thanks!

**Pull request merged**
