### PR TITLE
Updated shrinkwrap

### LINKED ISSUE #11246: autostyle not working when rows have `'` character
### Context
When trying to autostyle a map, the next error will appear in the notifications:

> rutas_pirineos_tracks_posets_por_refugio_angel_orus_waypoints: Failed to parse expression: "([mapnik::geometry_type] = 1) and ([name] = 'Cascada d\\'Espigantosa')" in style '91cd9fd0-e625-4191-b869-1b28d82b9a4e' in Style

10a04654-ed90-4aef-afc3-47060b5e0473

it will happen randomly as not always the same values will appear in a widget

no error will be shown in the console

### Steps to Reproduce

1. create a map
2. fill a row with the `'` character
3. add a widget
4. click autostyle

### Current Result
cartocss error
 
### Expected result
applied autostyle
 
### .carto file

[Rutas Pirineos Tracks Posets Por Refugio Angel Orus Waypoints (on 2017-01-12 at 17.55.30).carto.zip](https://github.com/CartoDB/cartodb/files/702473/Rutas.Pirineos.Tracks.Posets.Por.Refugio.Angel.Orus.Waypoints.on.2017-01-12.at.17.55.30.carto.zip)

### PR DESCRIPTION
**Pull request by MariaCheca**
Closes #11246

Updated shrinkwrap to apply changes made in https://github.com/CartoDB/deep-insights.js/pull/512

cc @matallo @xavijam

### CODE REVIEW

**Comment by matallo** [comment]
what about package.json? 😬

**Comment by MariaCheca** [comment]
On my way!

**Comment by xavijam** [comment]
It is not extremely necessary, but it would be convenience.

**Comment by MariaCheca** [comment]
I've also tested it in staging and works perfectly 🌈

**Pull request merged**
