### PR TITLE
Changing default styles for point, line and polygon geometries

### PR DESCRIPTION
**Pull request by xavijam**
Related ticket: https://github.com/CartoDB/design/issues/983#issuecomment-333587970

For the Voyager release we needed these cartography changes, so here we go!

cc @makella @noguerol @piensaenpixel

### CODE REVIEW

**Comment by piensaenpixel** [comment]
\o/

**Comment by xavijam** [comment]
@makella, if you want to try it, it is available in ded10 (let me know if you need more info).

**Comment by xavijam** [comment]
cc @javitonino mate 💋

**Comment by makella** [comment]
hey @xavijam sorry not sure what you mean by available in ded10 - yes please to more info!

**Comment by xavijam** [comment]
it is in production already @makella 🎉

**Pull request merged**
