### PR TITLE
Add hot reload of code changes for Resque

### PR DESCRIPTION
**Pull request by ethervoid**
After been upset for the time wasted in reload Resque every time I change code, I've found a [solution](https://github.com/resque/resque/issues/447) to make hot reload in `development` environment.

I've test it and works

Pls @CartoDB/backend take a look to this solution :)

### CODE REVIEW

**Comment by Kartones** [comment]
For me +100 as it doesn't breaks anything and surely helps speeding up development time

**Comment by juanignaciosl** [comment]
:+1:

**Comment by ethervoid** [comment]
@zenitraM could you take a look to this just to have a devops person taking a look to it

**Comment by zenitraM** [comment]
looks good to me :eyes:

**Comment by ethervoid** [comment]
Ok ,thank you guys. When the CI tests passed I'll merge it to master :)

**Comment by rafatower** [comment]
:heart_eyes:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5229/))

**Pull request merged**
