### PR TITLE
Revert "clear localstore on version modification"

### LINKED ISSUE #3359: CARTODB_UI_VERSION is "undefined" in embed maps and IE
https://my.trackjs.com/messages/filtered?message=%27CARTODB_UI_VERSION%27+is+undefined

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #3359.

This reverts commit 5eb10e67ad16d829b5f9f517708f0ff1b053c8fd.

cc/ @xavijam @viddo

### CODE REVIEW

**Comment by javisantana** [comment]
:es:

**Comment by viddo** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3267/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3268/))

**Pull request merged**
