### PR TITLE
Fixed problems with custom scroll in generic dropdown

### PR DESCRIPTION
**Pull request by xavijam**
Related: https://github.com/CartoDB/cartodb/issues/11598.

So, discovered that until the element is not rendered in the DOM, scroll is not calculated correctly and it was not displayed. That was the first problem, solved with a 0 timeout. Then I've realized there was several CSS in the `custom-list` class that were not needed, like the min-height, because the perfect-scrollbar already provide a way to set the min length of the scroll.
Also, `_checkScroll` function was not used and it is not needed, because scroll is only displayed when it is needed.
And finally, bonus thing, operators dropdown was not being displayed correctly, fixed too.

screen shot 2017-02-22 at 11 55 30

**THINGS TO CHECK:**
- [x] Check dropdowns display custom scrolls correctly. For example, map options, table view menu options,... (there are tons in the application).
- [x] Apply an aggregation style (squares, hexabins,...), then change the aggregation operation and check that the element is rendered correctly with a different operation (SUM for example).

cc @nobuti @piensaenpixel

### CODE REVIEW

**Comment by javierarce** [comment]
### Acceptance: :1st_place_medal: 👌

**Comment by javierarce** [comment]
screen shot 2017-02-22 at 17 18 20

Mmm, there seems to be a failing spec :/ Maybe after merging with master?

**Comment by xavijam** [comment]
Yep, that comes from master :(. Also there are tests failing from the importer (backend) :(x2.

**Comment by rafatower** [comment]
The shp test has been identified as one of the flaky ones when ran on parallel (see https://github.com/CartoDB/cartodb/issues/6754)

I triggered the [BE tests build again](https://ci.cartodb.net/job/CartoDB-PR-testing/8629/)

**Comment by javierarce** [comment]
Front and backend tests are ok now, but I still see the error I mentioned before in the Travis CI build. I don't know what to make of that :|

**Comment by xavijam** [comment]
@javierarce, tests passed finally, probably a cache issue in Travis, so 👍 .

**Pull request merged**
