### PR TITLE
Using learn guides in all onboarding analyses

### PR DESCRIPTION
**Pull request by xavijam**
Related ticket: #11193.

So I've replaced/added those available guides in each proper analysis onboarding. Except cluster, where the onboarding is not available (should we create it?).

Could you take a look @namessanti or @andy-esch? Is it ok?

cc @javierarce

### CODE REVIEW

**Comment by andy-esch** [comment]
Woohoo! @mehak-sachdeva will review as she wrote most of the guides

**Comment by mehak-sachdeva** [comment]
@xavijam - Thank you, this looks amazing! I reviewed all the links and everything looks good to me. Since the calculate clusters analysis is not very common, I feel it would be great to have an on-boarding for that for the users, as and when the schedule permits.
This is great! :)

**Comment by nobuti** [comment]
I've found an issue:

screen shot 2017-03-07 at 11 11 21

not sure if we should tackle it in this issue or in a new one @xavijam

**Comment by nobuti** [comment]
LGTM. Waiting green and 🚀

**Comment by nobuti** [comment]
Vamos

**Comment by namessanti** [comment]
Vamos! Nice push everyone. It looks great @xavijam 

@mehak-sachdeva we have clustering in a learn milestone already right?

**Comment by mehak-sachdeva** [comment]
@namessanti : We have a guide on clustering already on the Learn platform - I guess what they meant was we don't have an on-boarding page for that yet after the analysis is done. The moment we do, we can link the guide straight it! :)

**Pull request merged**
