### PR TITLE
Improve empty layer onboarding

### PR DESCRIPTION
**Pull request by jesusbotella**
Related to #11876
----

This PR implements onboarding changes for empty layers. This changes consist of:

### DataContentView
- **New placeholder for empty layers in data tab**

    screen shot 2018-01-11 at 23 15 20

   As the new placeholder contains three icons inside its text content, I thought the best way to include them was into language translations with a placeholder. That placeholder will be later transformed by `_t` function which inlines icons in the code by requiring them via webpack loaders.

    This behaviour allow us to reuse these icons all over the platform, but it has a downside, which is that we will have a new _icons_ folder in our `lib/assets` folder. I don't know if this is OK, or not. Please tell me what you think about that.

### LayerHeaderView
- **Add warning icon and 'Empty Layer' tooltip**

   layerheader

### DataLayerView
- **Add warning icon and 'Empty Layer' tooltip**

    layerlist

I introduced an UX improvement when it comes to user feedback. Until now, if you remove the last row of the dataset while editing data in the table, the sidebar won't update until the whole page is refreshed. So now, when the last row is deleted, _queryGeometryModel is reset and fetched so that the sidebar is updated.

resetfetch

### CODE REVIEW

**Comment by rubenmoya** [comment]
Deployed to `ded11` :)

cc @arianaescobar

**Comment by arianaescobar** [comment]
This one should be reviewed by @urbanphes

**Comment by urbanphes** [comment]
Hi, I see 3 things:

1. The geometry icons render is not good.
captura de pantalla 2018-01-16 a las 12 58 52
captura de pantalla 2018-01-16 a las 12 59 03

2. We should disable de Analysis tab.
captura de pantalla 2018-01-16 a las 13 04 13

3. We shouldn't show the switcher (map-table)
captura de pantalla 2018-01-16 a las 13 00 11

**Comment by jesusbotella** [comment]
Yes, @urbanphes, you are totally right.

I need you (or someone) to send me the proper icons because I saw that the ones that we have are not the same ones :(

**Comment by matallo** [comment]
back to development!

**Comment by jesusbotella** [comment]
@urbanphes Which should be the behaviour in this case? If I remove the last element in the dataset and I change to the map view, the switcher should be hidden?

table

**Comment by urbanphes** [comment]
Hi @jesusbotella:

1. Here are the icons as a svg:
[Lines.svg.zip](https://github.com/CartoDB/cartodb/files/1638490/Lines.svg.zip)
[Points.svg.zip](https://github.com/CartoDB/cartodb/files/1638493/Points.svg.zip)
[Polygons.svg.zip](https://github.com/CartoDB/cartodb/files/1638494/Polygons.svg.zip)

2. In that case, when the user has a table with one row, I'ld avoid removing the last one, this way we never permit to have an empty table by the way and possible errors in the future. What do you think? 

cc/ @CartoDB/design @ramiroaznar

**Comment by ramiroaznar** [comment]
Looking good!

**Comment by jesusbotella** [comment]
Thank you very much @urbanphes! I have just swapped the icons for the new ones you attached.

Regarding the empty table case, I don't know what to do here.
I think we should allow the user to remove that last row. We have a nice placeholder there to tell the user that the table has no data, and it could be useful for the user to see which were the columns of the table.

screen shot 2018-01-17 at 15 17 24

I'd vote for allowing to remove the row, but I don't know what to do from a UX point of view. Maybe we can always show the context switcher and let the user decide how to manage its layer data.

**Comment by matallo** [comment]
I'd agree with @jesusbotella here, I wouldn't block the user from manipulating his data, it being adding, or removing rows.

paging @alonsogarciapablo for insight.

In any case in order to better scope the feature, would it be possible to leave it out for now and create a new task in that case, when we have it sorted out?

**Comment by urbanphes** [comment]
I understand yours approachs and I tell you at the beginning was design with the same idea than map view: 
- A message informing the user what happens and how to solve.
- Actions to add rows and columns to the table in the same place where we have the actions on the map view to add any geometry.

These were the screens:
01 layers - 10-03 empty_layer - table
01 layers - 10-04 empty_layer - add_col
01 layers - 10-05 empty_layer - add_row




But we decided to remove it to reduce the scope and go with this version and test it.

What do you think?

**Comment by jesusbotella** [comment]
Yes, these add data buttons are missing to make user experience better, definitely. But I do agree with you that it is too much to be done at this moment.

I do not see how this is linked to what we were talking before about letting the user remove the last row.

My point was that maybe it would be better to let context switcher as is (always shown), because I think it would be weird if I switch to the map view when there is no data and the switcher is hidden.

**Comment by urbanphes** [comment]
I just see the new icons (SVG) and It looks like great. Thanks @jesusbotella 

Regarding the switcher (map-data); on this 1st approach:
- If the user adds an empty layer, I wouldn't allow changes to the table view.  
- If the user has a table and tries to remove the last row I wouldn't allow to remove it. This way, we don't allow possible errors.

And in another ticket, question us whether if it is or not necessary to let see an empty table.

cc/ @CartoDB/design @matallo @alonsogarciapablo

**Pull request merged**
