### PR TITLE
Fix account settings order

### LINKED ISSUE #2616: change order and copy on the user dropdown
screen shot 2015-03-04 at 17 43 59

to...

"View your public profile"
"Your Account" -> https://team.cartodb.com/u/`username`/profile
"Your API Keys"
"Close session"

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2616 

screen shot 2015-03-10 at 17 45 37

For organization admin:
screen shot 2015-03-10 at 17 45 48

### CODE REVIEW

**Comment by viddo** [comment]
ping @saleiva

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2200/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2201/))

**Comment by saleiva** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2205/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2206/))

**Pull request merged**
