### PR TITLE
[Vector] Remove default ccss from vector

### PR DESCRIPTION
**Pull request by donflopez**
Remove no supported ccss features in vector

### CODE REVIEW

**Comment by donflopez** [comment]
Fix https://github.com/CartoDB/cartodb.js/issues/1670

**Comment by alonsogarciapablo** [comment]
@donflopez are these styles the ones used by the auto-style feature? Thanks!

**Comment by donflopez** [comment]
The autostyle styles are in DI @alonsogarciapablo, I did another PR there https://github.com/CartoDB/deep-insights.js/pull/550

**Comment by alonsogarciapablo** [comment]
👍 

cc: @makella

**Comment by xavijam** [comment]
Already taking care of it in https://github.com/CartoDB/cartodb/pull/12439.

**Pull request closed without merging**
