### PR TITLE
Get viz api calls correctly

### PR DESCRIPTION
**Pull request by lbosque**
Move api calls fetch to lib so it can be used from different places

@Kartones @rafatower @zenitraM please CR

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3441/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3443/))

**Comment by rafatower** [comment]
:+1: I like it, if for only because of getting it out of User model. Wait for kartones so he's aware (but I don't think it affects the refactor at this point and should make it a bit easier in the near future).

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3451/))

**Comment by Kartones** [comment]
Marked so tomorrow I either coordinate with @juanignaciosl or fix it myself, but this was 
a) needed
and
b) eases things a lot, changes are minimal in both User and Visualization models and new code is really smal

That's why I gave him green light on my side

**Pull request merged**
