### PR TITLE
CartoDB/cartodb-central#854 Google maps config propagation on user creation

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes CartoDB/cartodb-central#854.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
@Kartones CR this, please.

**Comment by Kartones** [comment]
:+1:

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by jesusvazquez** [comment]
retest this please

**Pull request merged**
