### PR TITLE
Color variables refactor

### PR DESCRIPTION
**Pull request by alejandraarri**
I have refactored color variables `variables.scss` and the affected components. The structure of the resulting file is as follows:
- First are the tokens with the color palette.
- Then variables to be used in components and in pages. This gives an extra level of security and flexibility if the palette changes or a new color appears.
- Finally there are two deprecated variables, which are being used in many components and I have not been able to change them.

### Acceptance
Check that the New Dashboard is displayed correctly.

### Related Issue
https://github.com/CartoDB/cartodb/issues/14670

### CODE REVIEW

**Comment by alejandraarri** [comment]
Retest this please

**Comment by alejandraarri** [comment]
Retest this please

**Comment by alejandraarri** [comment]
Good catch!! Corrected two first variables.

> * $code__border-color: ~$neutral--400~ #D9D9D9;

I changed that color expressly to not have an extra gray just for that.

**Comment by Jesus89** [comment]
> I changed that color expressly to not have an extra gray just for that.

Yep, I thought that was the reason for the change, but just in case :smile:

**Pull request merged**
