### PR TITLE
Autologin for just created users closes #4180

### LINKED ISSUE #4180: Google signup auto login after completion
When a user signs up in a organization with Google button he should be automatically logged in when user creation ends.

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones , @viddo , what do you think about this approach for autologin at organization signup?

Some context:

Normal, Central signup direct authentication works because it can authenticate before actual user creation: a Central-created user is always valid. If creation doesn't work because of whatever reason it doesn't mind, and if it works final redirection to dashboard will be authenticated thanks to Central cookie.

Box-centric signup, nevertheless, creates users that can't be authenticated in advance, because of the need for email validation (`enable_account_token `) and because box-central communication might fail, so I think the polling for user creation state might be a good place for a one-shot authentication. Since it's performed through https and based on user creation uuid it can't be intercepted, and time constraint, `enable_account_token` and `dashboard_viewed_at` checks make it safer.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
PD: I've been thinking about a way to do this and experimenting for a while, if you think this is fine I'll add some tests.
PD2: this should cover LDAP and any other authentication mechanism transparently without any additional effort.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Kartones** [comment]
As long as there is no way the user creation id can be stolen (e.g. sent by email as the token etc.) so an attacker might hijack the account upon provisioning ending, I'm more than fine :+1:

**Comment by juanignaciosl** [comment]
Ok, @Kartones , @viddo , now formal CR after tests :)

**Comment by viddo** [comment]
Looks legit, but I'm afraid I don't know too much about our current login system actually works to be able to say yes or no with confidence.

**Comment by Kartones** [comment]
:+1:

**Pull request merged**
