### PR TITLE
Add db setup before migrate

### PR DESCRIPTION
**Pull request by amnesic**

### CODE REVIEW

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by juanignaciosl** [comment]
@javitonino you changed this at CartoDB/cartodb/pull#6666. How come the solution was removing setup, [which also loads the schema](http://edgeguides.rubyonrails.org/active_record_migrations.html#setup-the-database) instead of removing migrate? I'm pretty sure we spoke about that but I can't remember.

**Comment by javitonino** [comment]
Running `db:setup` as a first step fails loading the schema, as the postgis extension is not loaded before. Also, running `db:migrate` after `db:setup` fails on duplicated tables. However, the current steps do not create a database, so I would suggest running `db:create` + `db:migrate` as that seems to work well.

```sh
$> dropdb -U postgres carto_db_staging
$> RAILS_ENV=staging bundle exec rake db:setup
[sequel] Created database 'carto_db_staging'
createdb: database creation failed: ERROR:  database "carto_db_staging" already exists
[sequel] Created database 'carto_db_staging'
rake aborted!
PG::Error: ERROR:  type "geometry" does not exist
LINE 1: ... "active_child" uuid, "attributions" text, "bbox" geometry, ...
                                                             ^

Tasks: TOP => db:setup => db:schema:load
(See full trace by running task with --trace)
$> dropdb -U postgres carto_db_staging
$> RAILS_ENV=staging bundle exec rake db:migrate
rake aborted!
PG::Error: FATAL:  database "carto_db_staging" does not exist

Tasks: TOP => db:migrate
(See full trace by running task with --trace)
$> RAILS_ENV=staging bundle exec rake db:create
[sequel] Created database 'carto_db_staging'
$> RAILS_ENV=staging bundle exec rake db:migrate
$>
```

**Comment by juanignaciosl** [comment]
@amnesic can you confirm that `db:create` + `db:migrate` works for you, instead?

**Comment by amnesic** [comment]
Yes db:create + db:migrate is working on my side too.

**Comment by juanignaciosl** [comment]
@amnesic ok, if you change the PR to create + migrate we'll merge this, Thank you!

**Pull request closed without merging**
