### PR TITLE
Use same config name as for production

### PR DESCRIPTION
**Pull request by viddo**
related to a4a637885e3a01b8d4c88671f31d41b102c9baf6 the public pages also needs to use the correct config (since not enabled for any users have not failed yet).

I.e. use the non-lowercased string as key. Also updated the app config sample to be consistent with this change.

### CODE REVIEW

**Comment by viddo** [comment]
ping @lbosque @xavijam related to the hotfix a few min ago (use https://github.com/CartoDB/cartodb/pull/2086/files?w=0 to skip whitespace changes)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1423/))

**Comment by xavijam** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1424/))

**Pull request merged**
