### PR TITLE
Adds default to geocoding_quota for organisations

### LINKED ISSUE #6180: undefined method '-' for nil:NilClass when geocoding in organization
This happens when organisations have `geocoding_quota` set to `NULL` instead of `0`.

cc/ @juanignaciosl

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #6180

This is set to fix problems like [these](https://rollbar.com/vizzuality/CartoDB/items/8843/). Bare in mind that `geocoding_quota` is non null default 0 for users already.

Pending tests in Staging to verify everything works.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
It looks ok, but remember we need to deploy migrations in a separate PR, before code. Check this in staging and split this :+1:

**Comment by xavijam** [comment]
ping!

**Comment by gfiorav** [comment]
I'm looking into a Org-creation failure related to this PR, @xavijam ! Hang on!

**Comment by xavijam** [comment]
:+1:

**Comment by gfiorav** [comment]
Deploying after successful migration in production.

**Pull request merged**
