### PR TITLE
georeference analysis: postal codes: country suggest

### PR DESCRIPTION
**Pull request by matallo**
re: https://github.com/CartoDB/cartodb/issues/12334 https://github.com/CartoDB/cartodb/issues/12403

on a first approach I tried making it work with `country` and `country_column` only, but as `country` has the Enabler editor in the schema, whenever you entered the free text once it rendered again the checkbox appeared, thus I added a new `postal_code_country` with "Suggest" type (and editor)

in order to georeference with a postal code which is not a a string but a number I think this would need changes in camshaft-reference [1] but it is out of the scope of this PR and being discussed in a separate issue [2]

[1] https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.55.1/reference.json
[2] https://github.com/CartoDB/cartodb-management/issues/4834

### CODE REVIEW

**Comment by matallo** [comment]
some tests pending

**Comment by rjimenezda** [comment]
Frontend looks good (ded04) but it doesn't actually work, because I guess data-services is not enabled. Will try locally 🤔

**Comment by saleiva** [comment]
is this change going to be propagated to every component like this? This behaviour is a problem in all of them. cc/ @noguerol

**Comment by matallo** [comment]
> is this change going to be propagated to every component like this?

you mean country field? I purposefully added a new field so I can use a "Suggest" editor, leaving the checkboxes in other georeference forms

**Comment by matallo** [comment]
updated the "Suggest" editor after discussion with @saleiva and @noguerol 

it is working in the ruis, in case you want to do the acceptance again, the Edit feature panel where the Suggest is also used may be worth taking a look

**Comment by rjimenezda** [comment]
Tried locally on my data-services & it completes the analysis correctly. 

However, the resulting polygons are empty, so there might be something wrong with the analysis itself.

**Pull request merged**
