### PR TITLE
Create index for layers.parent_id #3961

### PR DESCRIPTION
**Pull request by rafatower**
@juanignaciosl @zenitraM please review

### CODE REVIEW

**Comment by zenitraM** [comment]
:+1:

**Comment by juanignaciosl** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4170/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4171/))

**Pull request merged**
