### PR TITLE
ArcGIS connector: Stop skipping ids on failure

### PR DESCRIPTION
**Pull request by Algunenano**

### CODE REVIEW

**Comment by Algunenano** [comment]
retest this, please

**Comment by Algunenano** [comment]
retest this, please

**Comment by alrocar** [comment]
retest this please

**Comment by rafatower** [comment]
retest this, please

**Comment by Algunenano** [comment]
> (taking a look at the other tests to see if we ever stabilize them)

Wasn't everything green? Keep in mind that the `Backend` task has dissapear and now there are 2 separate ones, backend-pg10 and backend-pg11, so `Backend` won't be green ever in this PR.

**Comment by rafatower** [comment]
retest this, please

**Pull request merged**
