### PR TITLE
Improved pagination for new dashboard

### LINKED ISSUE #2413: Fix current pagination in new dashboard
It should work in the same way that github does
screen shot 2015-02-20 at 17 53 50

show [X-n,...,X-2,X-1,X,X+1,X+2,...,X+n]

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2413

- Added the "edge" (only 1 as it was defined in the issue) if there are more pages than can be visible, just like how Github's own pagination works.
- Also update the pagination model immediately on click, to avoid the re-render delay until a response returns.

screen shot 2015-02-26 at 16 29 13
screen shot 2015-02-26 at 16 29 25
screen shot 2015-02-26 at 16 29 34
screen shot 2015-02-26 at 16 29 59
screen shot 2015-02-26 at 16 30 10

### CODE REVIEW

**Comment by viddo** [comment]
ping @xavijam code review
@saleiva you never answered my question in the issue, you want the "previous" and "next" links on the edges as well? :)

**Comment by xavijam** [comment]
First and last items don't have round corners and they "hide" grey border
screen shot 2015-02-26 at 17 07 26
.

**Comment by viddo** [comment]
Ouch, good catch. I'll look into that one

**Comment by viddo** [comment]
Fixed --> screen shot 2015-02-26 at 17 13 46

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1966/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1971/))

**Comment by viddo** [comment]
Apart from that detail, any more feedback or OK to go?

**Comment by xavijam** [comment]
Reviewing :)

**Comment by xavijam** [comment]
:gb:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1985/))

**Pull request merged**
