### PR TITLE
Updated deep-insights.js dependency

### PR DESCRIPTION
**Pull request by xavijam**
Updating deep-insights code fixing a problem we have discovered with FullStory and TrackJs.
cc @nobuti

### CODE REVIEW

**Comment by xavijam** [comment]
Taking into account, changes in `carto` dependency are already approved by @rochoa in https://github.com/CartoDB/cartodb/pull/11721.

**Comment by xavijam** [comment]
Frontend tests passed

**Comment by nobuti** [comment]
screen shot 2017-03-10 at 09 20 09

**Comment by xavijam** [comment]
YEAHHH! 💋

**Pull request merged**
