### PR TITLE
Render raw body from response fixes #3779

### LINKED ISSUE #3779: ActionView::Template::Error: undefined local variable or method content for Class
https://rollbar.com/vizzuality/CartoDB/items/7023/?item_page=0&#instances

```
ActionView::Template::Error: undefined local variable or method `content' for #<#<Class:0x000000090ed608>:0x00000009be6eb0>
1
File "inline template", line 210 in _inline_template__181012493303021673_81737000
... 30 non-project frames
32
File "/home/ubuntu/www/production.cartodb.com/releases/20150527082129/app/controllers/admin/visualizations_controller.rb", line 373 in block (2 levels) in embed_map
... 2 non-project frames
35
File "/home/ubuntu/www/production.cartodb.com/releases/20150527082129/app/controllers/admin/visualizations_controller.rb", line 372 in embed_map
... 6 non-project frames
42
File "/home/ubuntu/www/production.cartodb.com/releases/20150527082129/app/controllers/application_controller.rb", line 54 in wrap_in_profiler
... 67 non-project frames
```

Doesn't look urgent, because it only happens to one user, one viz, but it's strange enough as for taking a look.

@rafatower @iriberri

### PR DESCRIPTION
**Pull request by rafatower**
See http://guides.rubyonrails.org/layouts_and_rendering.html#rendering-raw-body

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3938/))

**Comment by rafatower** [comment]
retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3941/))

**Comment by rafatower** [comment]
Correct link to Rails 3 docs: http://guides.rubyonrails.org/v3.2.13/layouts_and_rendering.html#using-render-with-inline

Note that if I do:
```
format.html { render this_option_does_not_exist: foo_bar }
```
rails will don't care and will try to use the default layout/template and even fail silently.

Also note it uses `html_safe` that does nothing but marks the string as "safe" (meaning it does stuff if it is not marked as such). This is ok since the body comes from a previous successful response.

http://apidock.com/rails/String/html_safe

@juanignaciosl or @Kartones please review

**Comment by Kartones** [comment]
:+1:

**Comment by juanignaciosl** [comment]
:+1: from me, but I'm adding @viddo here, since he already fought against this and might add something helpful.

**Comment by viddo** [comment]
Already talked in person, :+1: for me too. but just for the sake making it a little easier for the next developer encountering this, perhaps it's worth adding an inline comment explaining why `.safe_html` is used in this context? The same explanation as you gave above should suffice.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3946/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3947/))

**Pull request merged**
