### PR TITLE
Fix ON/OFF switch jump in new merge datasets modal

### LINKED ISSUE #4169: Fix privacy link in options menu
Still opens old privacy modal even though the new-modals feature flag is activated
screen shot 2015-06-23 at 14 27 08

### LINKED ISSUE #4215: ON/OFF switch jump
Reproduce:
Switch off the *merge all columns toggle* and then switch on the individual toggles:

untitled

### PR DESCRIPTION
**Pull request by viddo**
Fixes #4215 

also fixed #4169 while at it

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4629/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4630/))

**Comment by viddo** [comment]
@xavijam :eyes:

**Comment by viddo** [comment]
:point_up: :eyes: @javierarce

**Comment by javierarce** [comment]
:+1:

**Pull request merged**
