### PR TITLE
Creating a map from a dataset view does not refresh the UI

### LINKED ISSUE #3825: Creating a visualization from a dataset view doesn't refresh the UI
only does it after refreshing the page. 
Important to fix @javisantana  @Kartones @juanignaciosl

### PR DESCRIPTION
**Pull request by xavijam**
- [x] Fixing 'share button' text when user is in dataset and map views
  - When user is viewing a dataset -> **VISUALIZE**
  - When a user is viewing a map -> **PUBLISH**
- [x] Review process from dataset to map.

cc @saleiva @viddo 
Fixes #3825

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4016/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4020/))

**Comment by xavijam** [comment]
After checking the creation of a new map from an already created dataset, it is working properly (checked in local, staging and current production) but sometimes you can't distinguish if the change has happened because the name of the new map contains the name of the dataset and the share button text doesn't change. There are several things we could check:

- Table name will be the same as the dataset adding a '1' at the end, in my opinion should have a 'map' word.
- The privacy always turns to LINK, if the dataset has the same, no changes in the UI.
- Map canvas: if you are in the map view, and create the map from that section, you will notice the grey space around the map.

Example:
dataset-to-map

Good thing is we will gain another difference, share button text will change depending the context, dataset or map.

**Comment by xavijam** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4024/))

**Comment by viddo** [comment]
Current changes look OK.

re: your last observation, I don't think it makes any sense to check a UI component's state to decide another UI's state… why aren't those states derived from a model? E.g. `cdb.admin.Visualization` such as `vis.get('type') === 'table'`, or whatever model is most suitable?

**Comment by viddo** [comment]
Nevermind my last comment, I misunderstood the _There are several things we could check_ as we needed to observe some UI state to show another thing…

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4029/))

**Pull request merged**
