### PR TITLE
public pages: update navigation and footer

### PR DESCRIPTION
**Pull request by matallo**
CR @javierarce 

screen shot 2016-04-07 at 11 52 24
screen shot 2016-04-07 at 11 54 13
screen shot 2016-04-07 at 11 54 37
screen shot 2016-04-07 at 11 55 30
screen shot 2016-04-07 at 16 24 01
screen shot 2016-04-07 at 16 24 14

/cc @saleiva @carlostallon

### CODE REVIEW

**Comment by carlostallon** [comment]
<3

**Comment by javierarce** [comment]
👍  Looks neat, but have a look to the hound warnings.

**Comment by matallo** [comment]
retest this, please

**Comment by jvillarf** [comment]
Hey guys, we were testing a new Jenkins Slave and we had to cancel your PR testing (#7077). So sorry about the inconveniences (you'll probably have to launch tests again)

**Pull request merged**
