### PR TITLE
multi_import sequel method usage fixes #3228

### LINKED ISSUE #3228: Fix insert query escaping at explore api

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones , @rafatower CR this, please. Take a look at `multi_insert` sequel method, I didn't know about it and it's perfect in this case.

@lbosque take a look as well, when I get the :+1: I can deploy and run if you want.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3069/))

**Comment by Kartones** [comment]
:+1:  Loving it

**Comment by rafatower** [comment]
:+1:

**Comment by lbosque** [comment]
+1

**Pull request merged**
