### PR TITLE
Remove tangram

### PR DESCRIPTION
**Pull request by dv343**
Remove tangram support by updating cartodb.js

Fix https://github.com/CartoDB/cartodb/issues/13461

### CODE REVIEW

**Comment by matallo** [comment]
yass, taking a look now

**Comment by dv343** [comment]
The dependency is being removed because the new carto.js version doesn't need it, only cartodb.js was using it.

**Comment by rubenmoya** [comment]
Hi! Sorry to jump in (and jump in late), there are some things related to `tangram` in our `webpack` config: https://github.com/CartoDB/cartodb/blob/master/webpack.dev.config.js#L122 should we keep that if we're removing tangram?

**Comment by matallo** [comment]
not at all! that's the kind of thing I was trying to spot, let's do it in this PR

**Comment by dv343** [comment]
Yes, this is an incomplete PR. This only uses a patched carto.js that doesn't use vector, but it doesn't clean the code: not in Builder, nor in backend, nor in the DB.

**Pull request merged**
