### PR TITLE
[NO MERGE] 3958 geocoding param force all rows

### PR DESCRIPTION
**Pull request by rafatower**
Someone from @CartoDB/backend please review

This is for phase 1 of #3958

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4867/))

**Comment by rafatower** [comment]
retest this, please

**Comment by Kartones** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4869/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4910/))

**Comment by rafatower** [comment]
Superseded by https://github.com/CartoDB/cartodb/pull/4427

**Pull request closed without merging**
