### PR TITLE
Filter columns of type date in style by value component

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes https://github.com/CartoDB/cartodb/issues/7873.

### CODE REVIEW

**Comment by matallo** [comment]
specs!

**Comment by alonsogarciapablo** [comment]
Thanks @matallo. Well spotted! I will try to add some basic tests.

About the new behaviour, this is how it looks after filtering out columns of type "date".

screen shot 2017-11-28 at 12 06 24

@CartoDB/design are you cool with this? Do you think that `No column results found with 'postedtime'` message might be a bit confusing? Thanks!

**Comment by arianaescobar** [comment]
I do think it might be. I would say something more along the lines of "The usage of date columns to Style by Value is not permitted. Please select a different column.", or something like that. 

@csobier Any thoughts on how to simplify that sentence or the idea?

**Comment by alonsogarciapablo** [comment]
Right now the same message is used when a column is not present in the dataset and when it has been filtered out (eg: `the_geom` and `the_geom_webmercator` and now any date type column).

**Comment by arianaescobar** [comment]
We could make it more general and say "That type of column is not supported when styling by value." but I wouldn't use "No column results found with 'x'" because that's not really the case. They do have a column with that name, and we did find it, we're just not showing it because they can't use it there.

**Comment by alonsogarciapablo** [comment]
From what I am seeing we're (re)using a component that allows choosing a column from a given set of columns. The error message is also defined by this component. Example of a different use of this same component:

screen shot 2017-11-28 at 12 58 30

👆 Only `agg_value` is displayed. Search will only search in `agg_value`, otherwise 👇 

screen shot 2017-11-28 at 12 58 39

**Comment by arianaescobar** [comment]
If you ask me, we should change that...

**Comment by alonsogarciapablo** [comment]
We can change this but we will need to think how to make it work for each different use case. It is quite a beefy change and I think it should be prioritised and perhaps addressed by a regular Builder member. Adding @ramiroaznar to the loop. Thanks for your input @arianaescobar!

**Comment by arianaescobar** [comment]
Happy to! Thanks for asking!

**Comment by csobier** [comment]
Is this specific to date columns only? "Date values are not available when styling by value". 

If that component should change, are we able to modify the type of column in the message? (number, date, string, etc) or should it be generic for all uses? If so, then I agree with Ariana- any of the following would be ok:
- "That type of column is not supported when styling by value"
- "This data type is not applicable when styling by value"
- "No compatible values are available when styling by value"

**Comment by ramiroaznar** [comment]
IMHO @arianaescobar's logic is right. But let's fix this issue. And if users complain or Design thinks it is a onboarding priority, let's open a new ticket. 

:bandera: LGTM

**Comment by arianaescobar** [comment]
But this **is** part of the issue, though. When we're excluding a data type from the feature, we should explain why. I understand if you prefer opening another ticket but we should definitely do it and not wait for a complaint.

**Comment by ramiroaznar** [comment]
As @alonsogarciapablo pointed out, this component is reused in other BUILDER parts, such as analysis:

image

So if we decide to change the message, it should be pretty generic and all @csobier suggestions are invalid.

**Comment by alonsogarciapablo** [comment]
This is the template that we use to generate the message for every component that uses a searchable list:

```
    "custom-list": {
      "placeholder": "Search by %{typeLabel}",
      "no-items": "There are no %{typeLabel} items",
      "no-results": "No %{typeLabel} results found with '%{query}'",
      "add-custom-result": "Add custom value"
    }

```

In the case of a column selector, we set `typeLabel` to `column` and that is why the error says `No column results found with 'postedtime'`.

**Comment by arianaescobar** [comment]
@ramiroaznar Not necessarily because there could be the case where the user searches for a column that doesn't exist. In that case, that message is valid. 

We're talking about filtering out columns because they can't be used for a certain feature. In that case, we could use a generic message like "That type of column is not supported in this feature".

**Comment by ramiroaznar** [comment]
Roger that! :+1:

**Comment by alonsogarciapablo** [comment]
The thing is that the component is currently not aware of all columns (only the filtered ones) so it is not possible (as it is right now) to check if what the user typed is indeed a non supported column and display a more specific error message in that case.

**Comment by arianaescobar** [comment]
That would be enough, right? 

Is it a filtered column? -> Show unsupported message
else -> let the user select the column (if it exists, of course)

**Comment by alonsogarciapablo** [comment]
That would be enough but we cannot do that right now.

Think of the component as a list where you specify a set of items that you want the users to be able to select and a search box that will only search in that set of items. The component has no idea about other items (eg: filtered columns).

**Comment by alonsogarciapablo** [comment]
Example:

image

👆  eg: We are explicitly displaying only `agg_value`, so the list of columns doesnt know anything about the rest of the columns.

**Comment by alonsogarciapablo** [comment]
What I am trying to explain is that the component that displays the list of columns and allows users to search that list is a generic component. It only knows about a list of generic searchable items and **knows nothing about columns, types of columns, etc.**

**Comment by arianaescobar** [comment]
I feel like my brain is exploding 😛 

In that case, merge it as you have it now. BUT, that component is making designers unhappy and killing kittens all over the world. We should invest some time in improving it.

**Comment by alonsogarciapablo** [comment]
@arianaescobar Would we make designers happy (and save some kittens) if we merge this now and open an issue describing this problem so that we come back to it at some point?

**Comment by arianaescobar** [comment]
@alonsogarciapablo less unhappy, for sure haha

**Comment by alonsogarciapablo** [comment]
Here is the issue for future reference: https://github.com/CartoDB/cartodb/issues/13142

**Comment by alonsogarciapablo** [comment]
🚀

**Pull request merged**
