### PR TITLE
Disable geometry edition for layers with aggregated styles

### LINKED ISSUE #11714: geometry edition available on aggregated styles
### Context
With an aggregated style applied, you can click on one of the grid cells and the geometry edition icon will appear. 

It will also let you edit properties from the underlying points layer, but the feature selected is totally inaccurate
 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a point's map and use an aggregated style visualization (Import [this .carto](https://github.com/CartoDB/cartodb/files/824860/geometry.edition.on.agg.styles.on.2017-03-07.at.14.12.28.carto.zip) to have it directly) 

2. click on a grid cell the geometry edition button should appear
3. click on the geometry edition button, the left panel will update with info from an (apparently) random geometry

### Current Result
geometry edition is available for aggregated styles

screen shot 2017-03-07 at 14 59 32

### Expected result
aggregated styles shouldn't allow geometry edition

### .carto file

[geometry edition on agg styles (on 2017-03-07 at 14.12.28).carto.zip](https://github.com/CartoDB/cartodb/files/824860/geometry.edition.on.agg.styles.on.2017-03-07.at.14.12.28.carto.zip)

### PR DESCRIPTION
**Pull request by rjimenezda**
Fix #11714 

Edit geometry button is now disabled for layers with aggregated styles. Copy is mine, so @brittanymicek would appreciate some input 🙇 

screen shot 2017-06-07 at 17 39 11

### CODE REVIEW

**Comment by brittanymicek** [comment]
@rjimenezda Only a minor change ;)
"Feature editing is disabled for layers with aggregated styles. To edit data, export this layer and import it as a new layer."

Re: to the last sentence - I'm concerned about the clarity of what we are asking. The confusion is around the "it as a". The "it" refers to the exported layer. Thus saying, export a layer and then re-import that same layer as a new layer. Sorry, I'm confused! Thanks!

Are we saying: 
- To edit data I will need to export the (current layer? only the layer with aggregated styles?) AND then edit that same layer, AND then re-import it as a new layer?
OR
- To edit data, I need to export the layer with aggregated styles and then import a COMPLETELY new layer with NO aggregated styles?

**Comment by rjimenezda** [comment]
@brittanymicek thanks a lot!

As far as I've used the app, the second one. You get a new layer without the aggregated styles, but with all the available points.

**Comment by rubenmoya** [comment]
Retest this please

**Comment by rubenmoya** [comment]
🚢 IT

**Comment by rubenmoya** [comment]
In production 🚀

**Pull request merged**
