### PR TITLE
Remove naing component from category widget form schema model

### PR DESCRIPTION
**Pull request by xavijam**
:trollface: ing me.

screen shot 2016-05-24 at 11 14 08

cc @piensaenpixel.

### CODE REVIEW

**Comment by xavijam** [comment]
@jvillarf failing on premise tests :S, should I be worried?

**Comment by jvillarf** [comment]
Hey,

it had an issue downloading PhantomJS package... Honestly, i don't know why. You might launch the tests again, if you consider this is necessary. 

Javi.

**Comment by viddo** [comment]
@jvillarf I think that's a known issue, it happens from time to time (rarely, but still) on the travis CI test runs too

**Comment by jvillarf** [comment]
Oh, ok @viddo . Thanks for the heads up :)

**Pull request merged**
