### PR TITLE
Prevents empty tags from being created and rendered

### LINKED ISSUE #3582: Adding table tags from the dashboard includes commas in final tag
Steps to reproduce

1. Go to your dashboard, Datasets
2. Find a table that doesn't have any tags
3. Add the tag, "test," with the comma
4. See that the comma remains in the tag.

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #3582.

@viddo what do you think?

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3786/))

**Comment by viddo** [comment]
I'm thinking, _why are there empty tags to begin with_? :) 

Rather than just fixing it for this specific place, perhaps the data (backend) model should not return empty result to begin with (if they come from there?)? Or if it's a strict client-side issue, wouldn't a better place be to make sure the model to filter out non-valid (e.g. empty) values on set/parse?

**Comment by viddo** [comment]
just read referenced issue (sorry, missed it), so if I understand it correctly it's the latter case. So I'd say the cleansing would be better suitable where the tags are set (i.e. on the model) rather than the (editable) view.

**Comment by alonsogarciapablo** [comment]
Yes, the problem was that we were actually sending empty tags to the backend and it was actually creating and returning them. This PR prevents that. We could open a separate issue to prevent this on the backend side...

**Comment by viddo** [comment]
IMHO, I think it makes more sense to fix the root issue than covering it up (i.e. fix it on the backend).

**Comment by alonsogarciapablo** [comment]
@viddo so your proposal would be to leave the frontend as is and:

1. Prevent empty tags from being created by the backend.
2. Do not return existing empty tags from the backend.

I'm okay with implementing the backend part (to prevent this from happening in the future) but I also think we shouldn't send empty tags to the backend.

**Comment by viddo** [comment]
Agree :)

**Comment by rafatower** [comment]
cc/ @Kartones @juanignaciosl

**Comment by Kartones** [comment]
Indeed, we should clean empty tags and disallow saving them on the backend

**Comment by alonsogarciapablo** [comment]
I will implement the backend part as part of this pull request.

**Comment by alonsogarciapablo** [comment]
@Kartones: [this commit](https://github.com/CartoDB/cartodb/commit/ea43b22b04389f893c9a6c08f7ca57a0c82f38eb) implements the backend part. Please take a look. I'm not very familiar with the backend so perhaps there's a better way to do it. Also, is this something that will be affected by the refactoring? Thanks!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3797/))

**Comment by Kartones** [comment]
Refactor is not affected because we're still with GET/reads logic.

Change is :+1:  once you fix the specs :P

**Comment by alonsogarciapablo** [comment]
Ups! :astonished:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3798/))

**Comment by alonsogarciapablo** [comment]
@Kartones I added the same behaviour to `Carto::Visualization`. Please check out [this commit](https://github.com/CartoDB/cartodb/commit/4d5ea0846369e28d2248ef2c91b2997ee68c541c).

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3804/))

**Comment by Kartones** [comment]
nice!

**Comment by alonsogarciapablo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3809/))

**Comment by viddo** [comment]
:ok_hand:

**Pull request merged**
