### PR TITLE
Sanitize error details

### PR DESCRIPTION
**Pull request by viddo**
image

cc @javierarce

### CODE REVIEW

**Comment by javierarce** [comment]
:+1: :boom:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5438/))

**Comment by viddo** [comment]
thx! :shipit:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5446/))

**Pull request merged**
