### PR TITLE
Parameter text for Filter by Column Value Analysis

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes https://github.com/CartoDB/design/issues/1125.

cc: @makella

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
Tried this out in staging and it's looking good.

screen shot 2018-03-05 at 13 37 06

The only question I have is if this might affect existing analyses using "Is greater or equal than" and "Is less or equal than".

**Comment by ivanmalagon** [comment]
Let me check what you point about existing analyses.

**Comment by ivanmalagon** [comment]
Existing analyses still works even if that string is changed. The form renders properly as well.

**Comment by alonsogarciapablo** [comment]
Thanks @ivanmalagon!

**Comment by alonsogarciapablo** [comment]
🚀 

cc: @makella ❤️

**Comment by makella** [comment]
❤️ ❤️ ❤️

thanks @ivanmalagon and @alonsogarciapablo !!

**Pull request merged**
