### PR TITLE
import process fails with .xlsx files

### LINKED ISSUE #5939: import process fails with .xlsx files
When users import .xlsx files to CartoDB, the import process fails. The error log shows the next message:
```
Errored importing data from /tmp/imports/20151014-20847-1x5jkx3/29.xls:\nfalse: NoMethodError: undefined method `force_normalize' for #<Hash:0x000000058e2ee8>
true: ----------------------------------------------------
false: [\"/home/ubuntu/www/production.cartodb.com/releases/20151014090018/services/importer/lib/importer/excel2csv.rb:51:in `run'\", 
\"/home/ubuntu/www/production.cartodb.com/releases/20151014090018/services/importer/lib/importer/loader.rb:124:in `block (2 levels) in normalize'\", 
\"/home/ubuntu/www/production.cartodb.com/releases/20151014090018/lib/cartodb/stats/aggregator.rb:45:in `block in timing'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'\"

`````
If you transform the .xlsx file into .csv it import it correctly to the account.

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #5939 

Broken this morning with one of my releases.

### CODE REVIEW

**Comment by Kartones** [comment]
@rafatower @ethervoid Any of you will do for the CR, and if you feel is important just push it, I'm deploying to staging right now to test (I'm missing some dependency in local to import XLS) but was just a missing (empty) parameter on the calls, if you check `Excel2Csv` parent class it has 5 params, not 4.

**Comment by Kartones** [comment]
Confirmed with staging test, the fix works, so feel free to push it live when you CR it if you don't want to wait until tomorrow.

**Comment by iriberri** [comment]
It would be great to push it as soon as checks and reviews pass, as this is becoming a pretty common error today. >10 issues in Support.

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
