### PR TITLE
Switch user quota trigger permission to the organization role

### LINKED ISSUE #11281: Fix for _CDB_UserQuotaInBytes public for existing orgs
The fix #10987 fixes future users, but existing organizations users probably need it as well.

In addition, consider reducing `public` to `CDB_Organization_Member_Group_Role_Member_Name`, it might be enough (although @javitonino pointed that code is using `public` in other similar cases).

On close, onpremise team should be pinged, so they run it on upgrades.

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #11281 

Please wait for 🍏  before CR.

Changes the permissions of the quota check to give it only to the organization role or the user.

To trigger the update for all existing user, we can use the existing rake: `cartodb:db:reset_trigger_check_quota`

---
**Aceptance**
Like https://github.com/CartoDB/cartodb/pull/10987
- Needs acceptance in onpremises, SaaS and dev, creating an organization with owner and attaching an existing user to an organization. Also need to test non-org users.
 - You should be able to update shared datasets in rw mode. You should create and share the dataset from the owner, and try to edit it from a subuser.
 - You can also test using the SQL api directly, and ensure nothing is broken for public visualizations, etc.

---
**Deploy**
Implies running the rake task over all clouds.

### CODE REVIEW

**Comment by javitonino** [comment]
I think it is necessary. By default, postgresql gives public access to the functions. When we initialize the database, we revoke this permission from all existing functions in the database.

However, as this function is added later, its permissions are not revoked by the previous tasks. So I decided to ensure the permissions for this are correct after creation. I considered reordering the creation code so this function is created before revoking permissions, but as this function can be called later (on quota updates) it doesn't work correctly.

**Comment by juanignaciosl** [comment]
Oh, I forgot that it was public by default, thanks for the explanation. 👍 , but I have one more doubt that should be checked in acceptance: as there are some legitime usages of public (SQL API without API Key), please check that this doesn't break normal operation (an unexpected quota check would fail).

**Comment by MariaCheca** [comment]
Made acceptance in staging and it looks ok. Also, I think it could be great to invest more time testing the SQL API, as after talking with @javitonino it could be the most vulnerable point. On-premises is pending for acceptance.

**Comment by matallo** [comment]
this specific acceptance being repeated twice, can't we create an automated test script, and/or a template similar to the smokes that we can run each time?

I'm doing this manually now, but if we encounter this again I'd go for automation

**Comment by gfiorav** [comment]
SaaS acceptance is 🍏 cc/ @matallo 

I have noticed a considerable delay on doing queries to the sql api after running the task. Not sure if it can be related cc/ @javitonino

**Comment by matallo** [comment]
I didn't found any delay in local, tho

**Comment by javitonino** [comment]
I cannot think of anything in running the task that could make the SQL API slow, it's probably just a glitch.

**Comment by matallo** [comment]
acceptance passing in onprem, also updated the README.md https://github.com/CartoDB/onpremises/pull/216

**Pull request merged**
