### PR TITLE
[DON'T merge] Upgrade Sequel gem

### PR DESCRIPTION
**Pull request by rafatower**

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4447/))

**Comment by rafatower** [comment]
retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4449/))

**Comment by rafatower** [comment]
tried several things but not an easy option, abandoning this branch

**Pull request closed without merging**
