### PR TITLE
Added location field to user

### LINKED ISSUE #5298: Add location field for the users
The new user profile pages include a new field to let users indicate their location.

screen shot 2015-08-31 at 10 54 33

### PR DESCRIPTION
**Pull request by ethervoid**
New location field for user and organizations

Closes #5298

### CODE REVIEW

**Comment by ethervoid** [comment]
Please @juanignaciosl CR this please

**Comment by juanignaciosl** [comment]
LGTM :+1:

**Comment by saleiva** [comment]
Check with @MariaCheca that we have a proper place to add this on the settings page so it can be filled.

**Comment by ethervoid** [comment]
Ok ,there is a issue in central to add the field to the view. We can add to this PR and merge all at once

**Comment by saleiva** [comment]
No problem if it's under control.

**Comment by ethervoid** [comment]
Merged in branch `5296-explore-user-feed`

**Comment by ethervoid** [comment]
Nevermind @saleiva its already there

captura de pantalla 2015-09-15 15 27 41

**Pull request closed without merging**
