### PR TITLE
Flush importer log when process starts + Bugfix

### LINKED ISSUE #4472: Flush importer log when process starts
At the point when we know the folder the import is going to run, etc., so debugging is possible.

Branch `4472-sync-logs-bugfix-and-improvement`

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #4472

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5094/))

**Comment by Kartones** [comment]
@ethervoid CR and see some dragons :D

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5098/))

**Comment by ethervoid** [comment]
LGTM :+1:

**Pull request merged**
