### PR TITLE
3560 domainless root redirection

### PR DESCRIPTION
**Pull request by rafatower**
@Kartones please review. Mi recommendation is to see it side-by-side (split).

The domainfull part is functionally equivalent, though I removed the double negations `if !obj.nil?` and merged the final else "default" case with a preceding one.

The domainless part takes advantage of the fact that `current_viewer` is taken from the session.

cc/ @javisantana

### CODE REVIEW

**Comment by Kartones** [comment]
+1 more legible now

**Comment by rafatower** [comment]
retest this please

**Comment by rafatower** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3555/))

**Pull request merged**
