### PR TITLE
For #3727, add some lesser-known SQL commands

### PR DESCRIPTION
**Pull request by pramsey**
to those allowed in the Editor

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3814/))

**Comment by javisantana** [comment]
would be nice to add some tests over here https://github.com/CartoDB/cartodb/blob/master/lib/assets/test/spec/cartodb/models/table.spec.js#L276

**Comment by pramsey** [comment]
This is why I was afraid to touch this: even in the original form, the code didn't adhere to the implied contract. For example, 'truncate' was in 'alterTable' instead of 'alterTableData' (it doesn't change table structure, it just removes rows); 'vacuum' was in 'alterTable' (it doesn't change table structure *or* data). All the commands I want to add ('reindex', 'grant', 'revoke') shouldn't be in either of these maps, as they alter neither structure nor data. I feel like I'm meddling in the wrong place here.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3821/))

**Comment by javisantana** [comment]
That split does not make any sense anymore, the only thing we need to know is if the sql query will change something or not no matter if it's the table data or other stuff

**Comment by pramsey** [comment]
Hokay, what should the comments say: probably you know more about what these things actually do than what the comments say they are supposed do.

* alterTable says "return true if the sql query alters table schema in some way"
* alterTableData says "return true if the sql query alters table data"

What should 'create index', which alters neither the schema nor the data return? Or 'reindex' which doesn't even add any new objects to the system? I see that 'select', in the tests, always returns false, which fits with the contract described in the comments.

**Comment by saleiva** [comment]
bump!

**Comment by javisantana** [comment]
sounds good

**Comment by saleiva** [comment]
bump!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4283/))

**Comment by pramsey** [comment]
OK, @javisantana this is returning the code to the old behaviours (select is false, everything else is true, with a special category of true for SQL that actually changes data), adding the strange SQL, and tests. If it seems right, mash the green button for me.

**Comment by saleiva** [comment]
bump!

**Pull request merged**
