### PR TITLE
compare_metadata.rb overlaps runs

### LINKED ISSUE #2565: compare_metadata.rb overlaps runs
If `script/compare_metadata.rb` takes long to execute, multiple runs might happen on the same batch server.

Make the script smarter so upon run detects if already running, and if so exits inmediately.

/cc @zenitraM

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #2565

### CODE REVIEW

**Comment by Kartones** [comment]
@lbosque CR please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2404/))

**Comment by Kartones** [comment]
@zenitraM CR redirected to you by orders of @lbosque

**Comment by zenitraM** [comment]
:+1:

**Pull request merged**
