### PR TITLE
Fix copy on delete items dialog

### LINKED ISSUE #2385: Remove name of maps
When you want lock some maps appear the name of the maps
image

Unify like this one (delete some maps)
image

### LINKED ISSUE #2392: Incorrect text on delete map modal
screen shot 2015-02-20 at 13 06 02

Maps cannot be exported, What about "Deleted maps cannot be recovered. Be sure before proceding"

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2392 

screen shot 2015-02-20 at 17 00 49

Fixes #2385 

screen shot 2015-02-20 at 17 14 32
screen shot 2015-02-20 at 17 15 02

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1817/))

**Comment by viddo** [comment]
cc @saleiva

**Comment by viddo** [comment]
cc @piensaenpixel

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1819/))

**Comment by viddo** [comment]
FYI @xavijam

**Pull request merged**
