### PR TITLE
Includes user full name in auth user response

### LINKED ISSUE #3335: Dropdown in public pages shows username instead of name

### PR DESCRIPTION
**Pull request by fdansv**
Fixes #3335 

Includes the full name of the viewing user in the response from the backend, so that it's rendered in the dropdown instead of the username.

Also my first PR in Ruby!

@Kartones @javisantana

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3779/))

**Comment by Kartones** [comment]
`user.name` is an optional field, I'd use a ternary if to check for existance and if not leave `user.username`

**Comment by fdansv** [comment]
Yep, changed that to use the function in the user object.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3781/))

**Comment by Kartones** [comment]
sadly, Ruby standard says no parenthesis are to be put if the method has no parameters, so to keep following it please remove them :grin: 

Other than that, :+1:

**Comment by fdansv** [comment]
Done! Merging ASATP

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3783/))

**Pull request merged**
