### PR TITLE
Add missing new modals

### LINKED ISSUE #4683: Replace old missed modals with new ones
While working on replacing what I thought was the last modals (#4682) I found a few others that all of us missed (so can't be commonly used). They need to be migrated though to be able to remove the old code planned for next/upcoming milestone:

**deletion:**
- [x] confirm delete slide (odyssey) in [table/slides/panel.js#L301-L313](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/slides/panel.js#L301-L313)
screen shot 2015-07-24 at 15 40 18

**warnings:**
- [x] show Gmaps deprecation in [table/mapview.js#L356-L369](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/mapview.js#L356-L369)
screen shot 2015-07-24 at 15 35 18

- [x] confirm edit geom in [table/geom_editor.js#L167-L179](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/geom_editor.js#L167-L179)
screen shot 2015-07-24 at 15 39 03

### PR DESCRIPTION
**Pull request by viddo**
Fixes #4683 

screen shot 2015-07-24 at 16 10 07
screen shot 2015-07-24 at 16 41 14
screen shot 2015-07-24 at 16 44 20

@xavijam please code review
@josecruz @saleiva please review visuals/copy

### CODE REVIEW

**Comment by xavijam** [comment]
Not much to say about code :es:, about the style, i feel the description is the last two dialogs are too long.

**Comment by viddo** [comment]
Yeah, could be, but they're the same texts as on the old ones :sob: 
Any suggestions for more brief texts that still convey the same info?

**Comment by xavijam** [comment]
Or at least, make those elements shorter.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5360/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5365/))

**Comment by josecruz** [comment]
@saleiva Would this one need a bit of love?
adf

**Comment by saleiva** [comment]
Create an issue, but don't block this because of that. Too minor

**Comment by viddo** [comment]
So that's a "good to go"?

**Comment by josecruz** [comment]
Yup for me:+1:

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5420/))

**Pull request merged**
