### PR TITLE
Add option to force-all-rows on already georeferenced dataset

### LINKED ISSUE #3958: Improve 2nd time georeferenciation when some rows doesn't get georef correctly
edit: TBD, after discussion below and in-person, /@viddo

- Backend
  - [x] update geocodings to accept a boolean param (`force_all_rows`) to redo geocodings for all rows
  - [x] update `/table` API to accept the `force_all_rows` param on PUT (when `latitude_column` and `longitude_column` are present I guess) - NOT NEEDED
  - [x] change to geocode all null or false (as opposed to just null as it is done right now)
  - [x] update `/geocodings/estimation` endpoint 
    - to take into account the change for null/false values above
    - to accept `force_all_rows` param, since it will affect estimated cost
- Frontend:
  - [x] add checkbox in footer of georeference modal, to toggle `force_all_rows` param (+ the regular state handling etc.)
  - [x] send `force_all_rows` param to `/geocoding/estimation` API to get accurate estimation cost/rows
  - [x] refactor [`table.geocodeLatAndLng `](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/table.js#L667-L693) to send `force_all_rows` param

---

Screenshot for the UI change:
2nd try

### PR DESCRIPTION
**Pull request by viddo**
Fixes #3958 

Implements the `force_all_rows` flag to be set, primary for geocoding itself, but also for estimating costs for the street addr. tab. 

@xavijam please review
cc @saleiva @rafatower since involved

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5016/))

**Comment by viddo** [comment]
deployed on ded05

**Comment by viddo** [comment]
hey @alonsogarciapablo @javierarce could someone of you do the code review since @xavijam won't have time today?

**Comment by xavijam** [comment]
I'll finally do it, because these two people are in the same position, so I'll take care of it.

**Comment by xavijam** [comment]
There are several messages in the geocoding result dialog which says: "Check your georef_status column and change..."  we should review those texts because it changes the behaviour of the georeference. cc @saleiva

**Comment by saleiva** [comment]
yep, we should update those texts to talk about the new checkbox :)

**Comment by viddo** [comment]
@josecruz, since you already planned to review the text as was pointed out in [georef fixes #4446](https://github.com/CartoDB/cartodb/issues/4446) and [missing quota #4324](https://github.com/CartoDB/cartodb/issues/4324), can you please take this into account?

**Comment by viddo** [comment]
deployed on ded04 instead

**Comment by xavijam** [comment]
screen shot 2015-07-16 at 12 19 44

Bottom gradient hides my scrollbar.

**Comment by xavijam** [comment]
I like the idea of having this option for geocoding :+1:
:es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5035/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5041/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5047/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5055/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5057/))

**Comment by viddo** [comment]
@xavijam found a bug, but it's not related to these changed but must have been before, so created a separate issue to tackle it later --> #4503 4503

**Comment by viddo** [comment]
Also fixed some issues that @rafatower found. Unless you have some more feedback I'll go ahead and merge

**Pull request merged**
