### PR TITLE
Move GET API requests api/v1/users/:user_id/layers

### LINKED ISSUE #3535: Move GET API requests api/v1/users/:user_id/layers
Move calls to `/carto/api/` controllers, setup shared specs, etc. Same as Table and Visualization endpoints.

Branch: `3535-new-users-layers-endpoints`
User flag: `active_record_layers_endpoint`

### PR DESCRIPTION
**Pull request by Kartones**
Closes #3535

Feat. flag is `active_record_layers_endpoint`

Won't be released until @xavijam is finished with some FE changes he needs to do.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3551/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3556/))

**Comment by Kartones** [comment]
@rafatower CR please

**Comment by rafatower** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3566/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3584/))

**Pull request merged**
