### PR TITLE
2448 add ruby profiler [don't merge yet]

### PR DESCRIPTION
**Pull request by rafatower**
@Kartones @zenitraM please review

Quick notes:
- By default it will do nothing. Performance-wise I don't know any possible improvement.
- To use it, you need to have a feature flag `profiler` enabled and add a param `profile_request=true`.
- It will leave the traces under `$RAILS_ROOT/tmp/performance`

I'd like to push this quickly to staging and see how it works without the `profile_request` (very quick smoke) and start checking some stuff in production.

PS: I'll gladly pay 1 euro for that gem :dancer:

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1879/))

**Comment by Kartones** [comment]
the problem is that `profile_request=true` param will mean all ajax calls won't be profiled :/

Why not only the feature flag?

**Comment by rafatower** [comment]
It is meant to profile particular requests, not everything as a whole. The profiling process is pretty heavy. You can always replay a call from the browser adding that param if that's what you want.

**Comment by zenitraM** [comment]
:+1:

**Comment by Kartones** [comment]
+1

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1902/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1981/))

**Pull request merged**
