### PR TITLE
fixes enabling google maps with empty key

### PR DESCRIPTION
**Pull request by javisantana**

### CODE REVIEW

**Comment by xavijam** [comment]
:jp:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3524/))

**Comment by lbosque** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3525/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3731/))

**Pull request closed without merging**
