### PR TITLE
Make the label checkable.

### LINKED ISSUE #11535: Clicking the label on a checkbox should activate/deactivate it
### Context
We've seen lots of user clicking on labels for activating/deactivating checkboxes lately. Although it's not a blocker (they end up clicking on the checkbox) it generates some friction.

### Expected result
Clicking on checkboxes should act like clicking on the checkbox itself.

cc/ @noguerol

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #11535.

### CODE REVIEW

**Comment by rubenmoya** [comment]
Looks good to me!

**Comment by rubenmoya** [comment]
There is a case where is not working:

checkbox_data

Also, it would nice to add it to radio buttons also, what do you think?

radio_buttons

**Comment by nobuti** [comment]
Deal!

El 2 jun. 2017 13:07, "Rubén Moya" <notifications@github.com> escribió:

There is a case where is not working:

[image: checkbox_data]
<https://cloud.githubusercontent.com/assets/905225/26723327/56ac07a4-4794-11e7-8c41-4870ce1fb201.gif>

Also, it would nice to add it to radio buttons also, what do you think?

[image: radio_buttons]
<https://cloud.githubusercontent.com/assets/905225/26723336/678f3e9c-4794-11e7-8f7f-93b199bd7a13.gif>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CartoDB/cartodb/pull/12261#issuecomment-305757523>, or mute
the thread

**Comment by rubenmoya** [comment]
We forgot about map options:

checkbox_settings

**Comment by rubenmoya** [comment]
I added the functionality it to the map settings panel, what do you think @nobuti?

checkbox_settings_2

**Comment by nobuti** [comment]
:kiss:

**Comment by rubenmoya** [comment]
In production 🚀

**Comment by nobuti** [comment]
\o/

**Pull request merged**
