### PR TITLE
Import geocoding finished email

### LINKED ISSUE #8933: Review geocoding finished email
Part of #8889.

screen shot 2016-07-18 at 11 33 43

cc @urbanphes

### PR DESCRIPTION
**Pull request by MariaCheca**
Closes #8933

screen shot 2016-08-08 at 14 43 04
screen shot 2016-08-08 at 14 44 31

 CR @matallo

### CODE REVIEW

**Comment by matallo** [comment]
out of curiosity, why the change in the literal? apart from that 👍

**Comment by MariaCheca** [comment]
I was just following the design files texts, but I can revert that change if you think that's better :)

**Comment by matallo** [comment]
it was just curiosity, whatever design thinks is best!

**Comment by MariaCheca** [comment]
✨

**Pull request merged**
