### PR TITLE
11426 UI fixes for georeference

### PR DESCRIPTION
**Pull request by ivanmalagon**
Implements #11426 

#### Acceptance

1. Check that every copy change in https://github.com/CartoDB/cartodb/issues/11426 is present.

2. Instead of changing the look & feel of the required notification, we've fixed the problem of the validation getting triggered when changing georeference type. (check GIF below)

3. Check also that `suggest` and `merge from` dropdowns work as always. `suggest` dropdowns appears in _geometry edition_ and `merge from` in _predict trends_ analysis. Just check that every dropdown in those places work. These two components share a template that has been modified in this PR, hence this check.

georeference

### CODE REVIEW

**Comment by matallo** [comment]
When doing CR I like to setup the branch locally so I can better follow/understand the code. I hope you don't mind, but I just found the placeholder is missing in the template, for the first Georeference analysis I tried.

screen shot 2017-02-17 at 10 47 27

**Comment by matallo** [comment]
I don't usually do consecutive CR and acceptance but ...

I found the text is not right in **Admin. Regions**

- "Select a admin. region column", the text says "Select a region column"

screen shot 2017-02-20 at 09 27 16

**Comment by matallo** [comment]
Actually I'd better say "Select an admin. region column"

**Comment by matallo** [comment]
Some minor literal details that maybe have already been discussed out of the PR, feel free to move on to deploy but state those changes somewhere in the issue or the PR

**Comment by nobuti** [comment]
Works like a charm ✨

**Comment by nobuti** [comment]
Waiting green and 🚀

**Comment by nobuti** [comment]
Frontend passing, vamos.

**Pull request merged**
