### PR TITLE
Adds new error image. Replaces card placeholder

### PR DESCRIPTION
**Pull request by javierarce**
This branch:

- Adds a new error placeholder (already approved by @CartoDB/design; see image below).
- Merges branch `224-preview-remove-table`.

mapcard_error

### CODE REVIEW

**Comment by javierarce** [comment]
@CartoDB/frontend: could you review this, please?

**Comment by viddo** [comment]
Looks legit :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1608/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1609/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1612/))

**Pull request merged**
