### PR TITLE
Fix dataset list header in homepage

### PR DESCRIPTION
**Pull request by csubira**
Due to latest changes in dashboard dataset list sticky header position needs to be fixed in homepage:

datasetlistheader

### CODE REVIEW

**Comment by csubira** [comment]
Ready to be reviewed @CartoDB/rt-managers

**Comment by alejandraarri** [comment]
I added two variables `$header__height` and `$subheader__height`, because they have the same height but they don't necessarily need to. There are other `64px` left that are not really `$header__height` and they refer to the margin between the header and the title of the page.

**Comment by alejandraarri** [comment]
Retest this please

**Comment by jesusbotella** [comment]
I've tested all functionality and it works flawlessly :) (with and without notification in the header)

**Pull request merged**
