### PR TITLE
Support RAR files for imports

### LINKED ISSUE #2366: support rar files
cc @juanignaciosl @Kartones 

Right now, we're showing: 
image

### PR DESCRIPTION
**Pull request by jgoizueta**
Fixes #2366

### CODE REVIEW

**Comment by ethervoid** [comment]
Fix hound's warnings, test in staging and ship it

**Comment by jgoizueta** [comment]
There's a conflict here between what hound likes and my interpretation of: https://github.com/Vizzuality/ruby-style-guide (look for "# good - it's apparent what's going on" in the guide).

who wins?

**Comment by ethervoid** [comment]
You have a lot of experience with Ruby so your opinion prevails

**Comment by jgoizueta** [comment]
OK, after some discussion with @juanignaciosl I've decided to be friends with that dog

**Pull request merged**
