### PR TITLE
Update cartodb.js dependency.

### LINKED ISSUE #10182: Legends not working with negative values
Legends in the Builder do not work with negative values. I loaded a dataset of values that has negative and positive values in the range. The choropleth band renders fine, however, the average line falls to the left of the choropleth bar outside of the bar itself since the average is a negative value.

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #10182.

cc @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
DALE NENO!

**Comment by xavijam** [comment]
Hey, wait, it brings several changes in torque and other packages.

**Comment by nobuti** [comment]
I don't know where the others come from, it supposed it only has to update cartodb.js. Maybe @donflopez can throw some light for the torque thing. About the rest of the changes, I think we are safe, it only changes the resolve attribute, pretty sure it's the npm version.

**Comment by donflopez** [comment]
Torque has this new [PR](https://github.com/CartoDB/torque/pull/266). I need to try it in staging, but the changes are for a feature that we are not using.

**Comment by nobuti** [comment]
@donflopez so do I need to freeze this PR? are we safe merging it?

**Comment by donflopez** [comment]
It seems to work without any problem @nobuti!

Thanks 🙂

**Comment by xavijam** [comment]
:+1:, if you are sure @donflopez, let's go! 🚢 🇮🇹 .

**Comment by nobuti** [comment]
This will be shipped as part of https://github.com/CartoDB/cartodb/pull/10198

**Pull request closed without merging**
