### PR TITLE
Place overwrite option at the end of ogr2ogr command line

### LINKED ISSUE #7297: ogr2ogr2.1 ignores overwrite option
When the `-overwrite` option is added for ogr2ogr retries it is ignored. But it works if we place it at the end of the command line.

Happens with ogr2ogr2.1 and not with ogr2ogr2.

### PR DESCRIPTION
**Pull request by jgoizueta**
fixes #7297

### CODE REVIEW

**Comment by iriberri** [comment]
I'm gonna do some tests, but I :+1: with this change. Please don't forget to squash the commits whenever this is merged, as some of them were tests and could provoke confusions if someone checks the history of the file in the future. :-)

**Comment by rafatower** [comment]
Fine by me as long as the testing goes ok

**Comment by iriberri** [comment]
My local tests are being successful. Adding the overwrite at the final of the string is respecting the update option with the prelude and closure statements. :+1: I'll try to reproduce a real scenario in staging as soon as I get a problematic file and after that we should be good to go.

**Comment by iriberri** [comment]
It's working! :-) @jgoizueta is gonna remove the testing commits of the branch and we can merge afterwards.

**Comment by iriberri** [comment]
FTR: No occurrences in Rollbar staging.

**Pull request merged**
