### PR TITLE
Fixes an issue that prevented running an analysis after an error

### LINKED ISSUE #10280: Unable to apply/run analysis after error
## STR

1. Create a map with a points dataset.

1. Add analysis: Calculate clusters of points.

1. Apply.
screen shot 2016-10-20 at 15 55 19

1. The analysis fails due to a statement timeout limit.

## Current result

1. There is no error message associated with the failed status.

1. It is no longer possible to apply the analysis with other parameters.

1. After reloading the builder, the message failed status message appears.

1. However, it's still not possible to apply an analysis with different parameters.

## Expected result

1. I would like to see the failed status error message without reloading.
1. I would like to apply the analysis with different parameters, with and without reloading the builder.

cc @javisantana @xavijam

### PR DESCRIPTION
**Pull request by javierarce**
Closes #10280

This PR fixes one of the reported errors: 
> I would like to apply the analysis with different parameters, with and without reloading the builder.
> I would like to see the failed status error message without reloading.

Please, read this thread to understand the reason of the second issue and the solution to fix it.

### CODE REVIEW

**Comment by javierarce** [comment]
@xavijam, @javisantana: any idea how to obtain a timeout error applying an analysis?

**Comment by javisantana** [comment]
do `SELECT cartodb.CDB_Conf_SetConf('analysis_quota_factor', '0');` as postgres user in the database (don't do that in production)

then  `SELECT cartodb.CDB_Conf_SetConf('analysis_quota_factor', '2');` to go back to normal

**Comment by javierarce** [comment]
@javisantana: cool. Thanks!

**Comment by javierarce** [comment]
Ok, just learned that the backend returns the error in the key `error_message` 

screen_shot_2016-10-25_at_09_38_13

… and we are printing the error that comes in the [error property of the analysis node](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/analysis-notifications.js#L90).

**Comment by xavijam** [comment]
:(, when did we change that? cc @dgaubert and @alonsogarciapablo.

**Comment by dgaubert** [comment]
I think, it was: https://github.com/CartoDB/Windshaft-cartodb/commit/d0980a2872ddaa86a7ceecddd3faf35b633b12e4

**Comment by javierarce** [comment]
Ok, where should we fix that?

In the frontend we could account for that and simply do:
```
if ((error && error.message) || analysisNode.get('error_message')) {
   message += ': ' + ((error && error.message) || analysisNode.get('error_message'));
}
```

**Comment by javierarce** [comment]
Ok, I'll fix it with the solution I just described. Let me know if you prefer other solution.

**Comment by xavijam** [comment]
Ok, fine by me @javierarce 🤗

**Comment by xavijam** [comment]
Nice! :es:

**Pull request merged**
