### PR TITLE
#4001 bugfixed

### LINKED ISSUE #4001: 404 error when accessing to a shared table
**Steps**

From a new brand organisation, with two new users (A -the owner-, and B):

* Create a new table in user B. Add some rows randomly. Share it with read permissions to user A
* Log into user A, go to the datasets dashboard and try to access the table

**Result**
The table shows fine and you're able to edit it:

image

The following error appears:

*GET https://orgtestded02.cartodb-staging.com/u/userorgtestded02/api/v1_1/tables/untitled_table 404 (Not Found)J.support.ajax.J.ajaxTransport.send @ cartodb.uncompressed.js:27J.extend.ajax @ cartodb.uncompressed.js:27a.sync @ cartodb.uncompressed.js:1872Backbone.sync @ app.js:85f.extend.fetch @ cartodb.uncompressed.js:857cdb.decorators.elder.b @ cartodb.uncompressed.js:25856cdb.decorators.elder.e.elder @ cartodb.uncompressed.js:25873cdb.core.Model.Backbone.Model.extend.fetch @ cartodb.uncompressed.js:26400cdb.decorators.elder.b @ cartodb.uncompressed.js:25856cdb.decorators.elder.e.elder @ cartodb.uncompressed.js:25873cdb.decorators.elder.b @ cartodb.uncompressed.js:25859cdb.decorators.elder.e.elder @ cartodb.uncompressed.js:25873cdb.admin.CartoDBTableMetadata.cdb.ui.common.TableProperties.extend.fetch @ table.js:561(anonymous function) @ cartodb_layer.js:44a.Events.trigger @ cartodb.uncompressed.js:676f.extend.change @ cartodb.uncompressed.js:986f.extend.set @ cartodb.uncompressed.js:827f.extend.fetch.b.success @ cartodb.uncompressed.js:853J.Callbacks.l @ cartodb.uncompressed.js:25J.Callbacks.m.fireWith @ cartodb.uncompressed.js:25d @ cartodb.uncompressed.js:27J.support.ajax.J.ajaxTransport.send.d @ cartodb.uncompressed.js:27*

*userorgtest4ded02.untitled_table:1 Uncaught SyntaxError: Unexpected end of input*

Failing request in detail:

*Request URL:https://orgtestded02.cartodb-staging.com/u/userorgtestded02/api/v1_1/tables/untitled_table
Request Method:GET
Status Code:404 Not Found*

**More info**
@juanignaciosl has deactivated the flag `active_record_layers_endpoint` which seemed to be the issue.

cc @Kartones

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #4001

### CODE REVIEW

**Comment by Kartones** [comment]
@juanignaciosl CR please

It's a one-liner, old code wasn't migrated equally and the Layer Presenter uses this and if always has double quotes will fail the requests (before retrying without double quotes).

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4472/))

**Comment by juanignaciosl** [comment]
Couldn't we fix it outside? I don't like that method behaviour depends on value :-\

**Comment by Kartones** [comment]
I've filled a frontend bug because if the username has a dash it will still fail (but table name is ok to have them, and for SQL API, etc. should stay).

But what I did is just replicate the old behaviour of User model, only escaping when needed, as else there is no way to solve it except propagating a "force quotes" parameter that will only be false at a single point in the code... And I'd rather wait for the proper fix/support in the FE and then remove the logic inside.

It always returns a string containing "the same", is only the specific format what changes a bit, while I agree presentation differs I didn't see it as such an issue as changing all the code that uses the method, dunno...

**Comment by juanignaciosl** [comment]
Ook, :+1:

**Pull request merged**
