### PR TITLE
Split size/color component [WIP]

### PR DESCRIPTION
**Pull request by elenatorro**
Project https://github.com/CartoDB/product/issues/54

Issues:
* Fill styling size/color https://github.com/CartoDB/cartodb/issues/13905
* Stroke styling size/color https://github.com/CartoDB/cartodb/issues/13906
* Label styling (fill & halo) size/color https://github.com/CartoDB/cartodb/issues/13907

# Acceptance

This split affects the Style form. A detailed revision is needed in this part of Builder, to check that styling layers is working as expected. This should include at least:

## Previous map
- Load several existing maps to check they are ok (style is kept, form reflects the correct values, there are no error messages, and CartoCSS panel is working).

## New map / Simple
- Create a new map using 3 kinds of layers: point, line and polygon.
- Style them using basic options: fixed / solid value for size and color, modifying fill and also stroke properties.
- Duplicate the layers and now use more advanced styles ('by value options', for size & color)
- Check styles are preserved after editing them (e.g. go to dashboard and re-enter style form).
- Style point layer by image. Change the color of the icons.

## New maps / Aggregations
- Take the point layer and style it using aggregation modes (Squares, Hexabins...)
- For each aggregation type, modify available properties, specially size & color options 

## Labels
- Use labels on one of the layers, modifying its properties, specially size, color, halo size and halo color.

### CODE REVIEW

**Comment by VictorVelarde** [comment]
retest this please

**Comment by ramiroaznar** [comment]
Using Google Chrome Versión 61.0.3163.100 (Build oficial) (64 bits), I found the following issues:

* Hover popups are kept after getting out of the element:

hoverpopup

* It would be great if we can explain why we are "styling" by `cartodb_id`. The user should know that we are aggregating by pixel and counting unique `cartodb_id`s...

image

* @makella correct me if I am wrong, but it is possible to style by value using custom markers? I think now it can be done in BUILDER...

custom-img

**Comment by ivanmalagon** [comment]
@ramiroaznar It's possible if it's a string, like in neighbourhoods.

image

**Comment by makella** [comment]
@ramiroaznar good catches! 

In terms of markers for categories, I had mentioned that in the initial design thread (https://github.com/CartoDB/design/issues/1082#issuecomment-358721594). I think we decided to just go with the general. You can't do markers with sequential so it isn't a global kind of rule.

@tea-cat will be redoing some screenshots for impacted Guides today so I'll ask her to report any other things like this through that process as well.

**Comment by VictorVelarde** [comment]
Issues detected by @ramiroaznar:
- [ ] "sticky" popups
- [ ] tip for aggregation (count cartodb_id per unit)
- [ ] missing option "style by value using custom markers"

**Comment by alonsogarciapablo** [comment]
Great feedback @ramiroaznar!

> It would be great if we can explain why we are "styling" by cartodb_id. The user should know that we are aggregating by pixel and counting unique cartodb_ids...

How would you show that @ramiroaznar? That's a generic list of columns, so it's a bit tricky to display something for the `cartodb_id` column only.

**Comment by alonsogarciapablo** [comment]
Tooltips work perfectly fine for me (Google Chrome Version 66.0.3359.181).

**Comment by ramiroaznar** [comment]
I am still having _sticky_ popups. Deleting the cache and using an incognito session does not solve the issue.

**Comment by VictorVelarde** [comment]
@ramiroaznar can you test with another browser? (or update chrome to latest version, if that is not a problem for you)

**Comment by ramiroaznar** [comment]
Working fine in Firefox in 60.0.1 (64-bit).

**Comment by VictorVelarde** [comment]
Thx @zingbot! 
It seems that tooltip has been there for a while... We'll fix it!

**Comment by alonsogarciapablo** [comment]
💪💪💪

**Comment by VictorVelarde** [comment]
Summing up:
Issues detected by @ramiroaznar and @zingbot 
- [ ] "sticky" tooltips --> unable to reproduce
- [x] missing option "style by value using custom markers" --> fixed (not deployed yet)
- [ ] tip for aggregation (count cartodb_id per unit) --> ?
- [x] wrong tooltip for label column  --> fixed (not deployed yet)

**Comment by VictorVelarde** [comment]
Hi @ramiroaznar and @alonsogarciapablo 

What do you think of something like this?

heatmap_tooltip



This tooltip could be displayed in both heatmap aggregation modes: "Heatmap" and "Animated / Heatmap"

**Comment by ramiroaznar** [comment]
@VictorVelarde for the third issue, I will summon someone @arianaescobar and @makella

**Comment by ramiroaznar** [comment]
LGTM. Also, @jsanz can give you feedback on this one.

**Comment by arianaescobar** [comment]
To me, `based on counting the number of "cartodb_id" records per pixel` is way too much information for that. And it doesn't add too much value for the user. If we start adding tooltips explaining how we do each thing, Builder would implode haha. 

I would just leave it at "Change the heatmap's color scheme". 

But yeah, wait for @makella's feedback too :) 
Thanks for asking @ramiroaznar

**Comment by alonsogarciapablo** [comment]
@VictorVelarde Is there a tooltip now? What does the it say?

**Comment by alonsogarciapablo** [comment]
Ok, it currently says "Change the point color":

screen shot 2018-06-14 at 12 38 29

**Comment by VictorVelarde** [comment]
There are currently 2 tooltips:
* Animated / Heatmap >> "Change the point color"
* Heatmap: >> "Change the heatmap color"

As @makella needs an updated version at staging for the guides (with other issues fixed, such as missing markers for categories), we're gonna deploy an updated version, and we'll use ari's copy for both cases: _"Change the heatmap's color scheme"_. That could be changed in the future, of course.

**Comment by VictorVelarde** [comment]
Summing up:
Issues detected by @ramiroaznar and @zingbot
- [ ] "sticky" tooltips --> unable to reproduce
- [x] missing option "style by value using custom markers" --> fixed & deployed to new staging
- [x] tooltip for aggregation heatmap --> fixed & deployed to new staging
- [x] wrong tooltip for label column  --> fixed & deployed to new staging

**Comment by ramiroaznar** [comment]
LGTM. Amazing job @VictorVelarde & @elenatorro. :heart:

**Comment by ztephm** [comment]
This looks so great!! You will make our clients happy @VictorVelarde @elenatorro :) There are two small things I noticed:

1. If you only use 2 buckets for point size the lowest one doesn't show in the size Legend, but if you use 3 buckets it does

    **STR**
    1. In Point Size section select By Value & choose a column
    2. Set the number of buckets to 3
    3. Click on the layer's Legend tab > Click Size tab > select Bubble Legend
    4. Go back to the Style tab and change the number of buckets to 2

    3 buckets:
    screen shot 2018-06-14 at 4 16 28 pm


    2 buckets:
    screen shot 2018-06-14 at 4 16 54 pm



2. Alpha values can display differently in custom color palette interface when really they are the same

    **STR**
    1. In Point Color section select By Value & select a color palette
    2. Click Custom Color Set
    3. Use the slider to make opacity lower
  
    The alpha number changes correctly in the field next to the slider, but the grayed-out alpha value in the field under the color picker stays at `1`. It should be the same value as in the top field, no?

    screen shot 2018-06-14 at 3 54 54 pm

    Leaving it up to the design experts tho definitely, maybe b/c bottom field is grayed-out/inactive it doesn't need to show same value.

Here's a map showing both issues:
[Untitled Map copy (on 2018-06-14 at 19.47.22).carto.zip](https://github.com/CartoDB/cartodb/files/2103831/Untitled.Map.copy.on.2018-06-14.at.19.47.22.carto.zip)

**Comment by arianaescobar** [comment]
@ztephm you are right on both things, they shouldn't behave like that.
@VictorVelarde let me know if I can help you out in any of that.

**Comment by ivanmalagon** [comment]
Regarding those two issues:

1.- Bubble bug is related with legends. Nothing to do with this PR. It's already happening in production. I've created a separated issue to tackle it in the RT. [Bubble legends with 2 buckets are wrongly rendered ](https://github.com/CartoDB/cartodb/issues/14075)

2.- In this case, the alpha value is set at a ramp level. I mean, when you modify the alpha value to 0.3 it gets modified to all the palette, not to the particular color that is shown below. I don't know if this makes a difference @arianaescobar 

Thanks for the feedback!

**Comment by ramiroaznar** [comment]
1-Moving it to RT kanban.
2-Yes, the alpha thing is something spotted a long time ago. AFAIK we did not implement it in the UI because it cannot be translated as an argument inside a Turbo CARTO ramp.

**Comment by alonsogarciapablo** [comment]
Thanks for the feedback @ztephm. It looks like both issues are currently happening in production.

I would say this is ready to 🚀 as soon as the guides and in-product notification are ready.

**Comment by makella** [comment]
@arianaescobar @VictorVelarde agree that this is too descriptive 
> To me, based on counting the number of "cartodb_id" records per pixel is way too much information for that. And it doesn't add too much value for the user. If we start adding tooltips explaining how we do each thing, Builder would implode haha.

And this looks like a good alternative
> I would just leave it at "Change the heatmap's color scheme".

**Comment by tea-cat** [comment]
One issue with the staging account I am working in is the lack of access to analysis tools offered exclusively to Enterprise Accounts. 

**The Following Guides require Enterprise Access:** 
1.DATA/SQL Guides< Connecting Twitter Data
2. ANALYSIS Guide<Enrich from Data Observatory 

Any way I can get access to these tools for staging? 
Thanks!

**Comment by ztephm** [comment]
FWIW the Twitter Connector is deprecated for now: [https://github.com/CartoDB/support/issues/1589](https://github.com/CartoDB/support/issues/1589)

**Comment by tea-cat** [comment]
**An additional problem**: I reached the quota on my account and can no longer connect to more datasets without an upgrade. I have deleted older datasets, but can't seem to free enough space to any add new datasets. If I could please request some assistance with this issue, I would greatly appreciate it. 

**Revamp Update:** I have completed all of the screenshots with the exception of:

- The 2 that require an enterprise account. 

- Convert Text into City and Admin Region Geometries 

- Sync Real-time Data 

- Understanding Map Layers in Builder (gifs) 

Once I can add more datasets to the staging account I can complete the last of the guides.  In the meantime, I will be work on updating the terminology.

**Comment by tea-cat** [comment]
Thanks @ztephm ! 

I won't worry about the Twitter Connect Guide for now.

**Comment by ivanmalagon** [comment]
Just upgraded the user in the latest staging with more quota and Enrich with D.O enabled @tea-cat 

I'm taking a look on the Admin regions issue as well.

**Comment by ramiroaznar** [comment]
@ivanmalagon I am sure the Adm. Region issue is because it is hitting our platform limits. Something I have discussed already with @alonsogarciapablo.

**Comment by ivanmalagon** [comment]
Yes, checked in local and staging cloud. Admin regions aggregation doesn't work on staging.
We have two options here:
1.- Fake the guide screenshots.
2.- Wait until this in production and the update only that guide.

I'd go for 2.

**Comment by ramiroaznar** [comment]
Yes, I vote for 2 too.

**Comment by tea-cat** [comment]
Thank you so much @ivanmalagon!

**Comment by ramiroaznar** [comment]
@zingbot I would not remove the feature (people use it because they complain about the platform limits errors, don't know how many though...). I think we can improve the performance of the query. Don't know if possible, but returning all country/admin. regions geometries is useless...

**Comment by alonsogarciapablo** [comment]
I found an issue while updating [this guide](https://carto.com/learn/guides/publish-share/describing-data-with-legends/).

Right now, users can change the color of a line (eg: SF Streets) "By value":

screen shot 2018-06-19 at 13 44 24

With the new changes, there's no "By value" option for Stroke Color:

screen shot 2018-06-19 at 13 39 55

**Comment by ivanmalagon** [comment]
Taking a look on that issuee, @alonsogarciapablo

**Comment by ramiroaznar** [comment]
Don't bother with that one. Right now it cannot be implemented in BUILDER:

image

*But I cannot find the discussion about taking out this component.

**Comment by ivanmalagon** [comment]
What do you refer to, @ramiroaznar ? In BUILDER I can select the color by value with lines.

image

**Comment by ramiroaznar** [comment]
`line-color`, as you have shown, support expressions such as TurboCARTO ramps, but `marker-line-color` does not.

**Comment by ramiroaznar** [comment]
First, [you will need to add it in ENGINE (`"expresion": true`)](https://github.com/CartoDB/carto/blob/master/lib/carto/torque-reference.js#L606) and then in BUILDER. So too much work in my opinion...

**Comment by ramiroaznar** [comment]
So after talking with @alonsogarciapablo, I was wrong. We need to fix the `line-color` feature in lines geometry layers.

**Comment by makella** [comment]
wait, are we enabling marker line color by value? if so, we need the same for polygon lines! and we should have a party if we are doing this!!

**Comment by ramiroaznar** [comment]
@makella no we aren't, sorry for the noise. We are going to use the UI with `marker-width`, `marker-fill`, `line-color` and `line-color` (just in lines), and `polygon-fill`.

**Pull request merged**
