### PR TITLE
9509 mapcard preview authtokens

### LINKED ISSUE #9509: Use auth tokens to get preview images in dashboard
So it works for private visualizations.

### PR DESCRIPTION
**Pull request by javitonino**
Closes #9509 

Pases auth_token to the dashboard visualization list in order to be able to show preview for shared/protected visualizations.

### CODE REVIEW

**Comment by xavijam** [comment]
Frontend part 👍

**Comment by javitonino** [comment]
Not even had to ask for the CR :laughing: Fixing backend tests before backend CR.

**Comment by xavijam** [comment]
@guido, @javitonino says that it is your call :joy:.

**Comment by xavijam** [comment]
Don't forget to bump package version in master branch when it is merged.

**Comment by gfiorav** [comment]
do it!

**Pull request merged**
