### PR TITLE
Do not overwrite CartoDB::Cartodb module #4503

### PR DESCRIPTION
**Pull request by rafatower**
Related to https://github.com/CartoDB/cartodb/pull/4575#discussion_r35297301

@Kartones @juanignaciosl mini test code review

### CODE REVIEW

**Comment by Kartones** [comment]
Ohh, thanks!

**Comment by Kartones** [comment]
:+1:

**Comment by rafatower** [comment]
retest this, please

**Comment by juanignaciosl** [comment]
Good to know, :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5273/))

**Pull request merged**
