### PR TITLE
query_wrapper -> sql_wrap for named maps closes #7344

### LINKED ISSUE #7344: save query_wrapper in named maps
We added a new attribute to layers in maps api => https://github.com/CartoDB/Windshaft-cartodb/pull/441

basically we need to send `sql_wrap` attribute from layer definitions to the named map created.

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #7344.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
@gfiorav CR this, please.

**Comment by gfiorav** [comment]
📦 it!

**Comment by juanignaciosl** [comment]
Yes, it has "for named maps", it's indeed for that :-) It makes density maps work with named maps.

**Comment by gfiorav** [comment]
🌴

**Pull request merged**
