### PR TITLE
Cached responses [do not merge]

### PR DESCRIPTION
**Pull request by javisantana**
in order to improve the dashboard speed I added this cached sync. What it does is to store the data in local storage using it the next time you fetch it. It always fetch it but you get results faster.

I also prepared it to invalidate the cache when needed based on the namespace you give when create the sync method. It's the same system that subrogate keys use

In this case I'm using it i the visualization list in order to improve the dashboard and the table list speed

cc @CartoDB/frontend 

This PR is to discuss this and find problems, before reviewing it, please read https://github.com/teambox/backbone.memoized_sync/blob/master/backbone.memoized_sync.js

### CODE REVIEW

**Comment by viddo** [comment]
sounds good to me

The only things I can think of is that @xavijam [added a wrapper for localStorage](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_common/local_storage.js) for the new dashboard (due to some browser issues I think?), perhaps we need to use the same here?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1939/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1938/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1948/))

**Pull request merged**
