### PR TITLE
Adds loader for categories list

### PR DESCRIPTION
**Pull request by javierarce**
animation

CR: @xavijam 
CR: @piensaenpixel

### CODE REVIEW

**Comment by xavijam** [comment]
What about the error state? 👼

**Comment by javierarce** [comment]
I'll handle that in another issue :)

**Comment by xavijam** [comment]
BTW, @piensaenpixel was changing loaders. Please @piensaenpixel, take it into account when you replace them 💋 .

**Comment by xavijam** [comment]
🚢 🇮🇹

**Comment by piensaenpixel** [comment]
update loader (with new cartoassets) and center

image

**Pull request merged**
