### PR TITLE
6581 fix layer and map factories load errors

### LINKED ISSUE #6581: Fix Layer and Map factories LoadErrors
Depending on the first request Rails triggers errors with some classes such as `MapFactory` and `LayerFactory` ( `LoadError Expected layer_factory.rb to define LayerFactory error`)

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #6581. @gfiorav , CR this, please.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by gfiorav** [comment]
As soon as that CI passes it's :+1: for me

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
@gfiorav , CR this again, please.

I've been fighting against the tests for two days but I give in: no matter what I attempt, some tests will try to  resolve `Factories` module under `CartoDB`. I think that the problem is related to having another `Factories` module for test factories under `CartoDB`, and [spec_helper including `CartoDB::Factories`](https://github.com/CartoDB/cartodb/blob/master/spec/spec_helper.rb#L48).

All that said, I've finally renamed production factories module to `ModelFactories` to avoid name clashing. Corollary: specs factories are under `Factories` and production factories are under `ModelFactories`, which is confortable and makes sense (a little of _hacer de vicio virtud_ here, I know).

**Comment by gfiorav** [comment]
:+1:

**Pull request merged**
