### PR TITLE
Wrong root url fixes CartoDB/cartodb-platform#1203

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones CR this, please.This fixes CartoDB/cartodb-platform#1203

### CODE REVIEW

**Comment by Kartones** [comment]
Uops, might not be so easy, seems some tests fail by not redirecting properly :(

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
@Kartones CR this, please. Currently deployed in ded02.

**Comment by Kartones** [comment]
:+1:

**Pull request merged**
