### PR TITLE
Fixed import dataset and basemaps modal texts and footer elements

### LINKED ISSUE #8987: Import dataset modal styles in editor
screen shot 2016-07-19 at 16 37 16
Should be:
screen shot 2016-07-19 at 16 37 59

screen shot 2016-07-19 at 16 39 20

### PR DESCRIPTION
**Pull request by MariaCheca**
Fixes #8987 

screen shot 2016-07-19 at 18 06 17
screen shot 2016-07-19 at 18 04 34

CR @matallo

### CODE REVIEW

**Comment by xavijam** [comment]
@matallo, take a look and if you feel confident merge it too pretty please 🙏 , @MariaCheca doesn't work today.

**Comment by MariaCheca** [comment]
_ping_ @matallo review it please

**Comment by matallo** [comment]
taking a look now

**Comment by matallo** [comment]
LGTM!

**Comment by MariaCheca** [comment]
✨

**Pull request merged**
