### PR TITLE
Handle no geometries scenario upon map bounds recalculation

### LINKED ISSUE #4616: Map created from file without geometries gets centered in Null Island
**Steps:**

* Import [this CSV](https://gist.githubusercontent.com/iriberri/40b63cbc775f805b5eaf/raw/206bb50496cb439f4a6eee7e218c971730a9942f/examplessssssss.csv)

Resulting map in the Editor:

image

Viz.json info (https://vmg.cartodb.com/viz/3f9726e6-305a-11e5-966b-0e5e07bb5d8a/map):

````
[
[
0,
0
],
[
0,
0
]
],
center: "[30, 0]",
zoom: 3,
````

After refreshing the page, the map is always being shown near Null Island and zoom 18.

cc @javisantana

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #4616

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5456/))

**Comment by Kartones** [comment]
@javisantana CR please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5459/))

**Comment by javisantana** [comment]
:es:

**Pull request merged**
