### PR TITLE
fix modal

### PR DESCRIPTION
**Pull request by piensaenpixel**
@javierarce could you take a look?

### CODE REVIEW

**Comment by javierarce** [comment]
On Safari the main analysis view works fine, but the info view shows a blank page :(

**Comment by piensaenpixel** [comment]
@javierarce  i think is fixed, could you take a look? also we should review all the modals :(

**Comment by javierarce** [comment]
👍  🎏

**Comment by javierarce** [comment]
Ok, last changes fixes the issue and doesn't have side effects in other modals (tested in safari, firefox, chrome and ie11). Good to go!

**Comment by piensaenpixel** [comment]
I cant't believe :)

**Pull request merged**
