### PR TITLE
Reduce the number of datasets to 9

### LINKED ISSUE #5640: Reduce the number of datasets shown in the public dataset page
In this view https://user.cartodb.com/datasets we are showing 20 elements per page. That's too many, we should only show 9 per page.

@ethervoid: can you reduce the number? After you're done I'll add the blank cards to fill the empty spaces.

### PR DESCRIPTION
**Pull request by ethervoid**
Closes #5640 

Reduces the number of datasets returned by page

### CODE REVIEW

**Comment by ethervoid** [comment]
Please @Kartones CR this :)

**Comment by Kartones** [comment]
:+1:

**Comment by javierarce** [comment]
@xavijam: can you review the front-end part? https://github.com/CartoDB/cartodb/commit/617c35f2d955688148c3a35612f725b37ce44a64

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
