### PR TITLE
fixes #2536, update table as vmg set type = 'cabron'

### LINKED ISSUE #2536: UPDATE tablename AS alias gives syntax error in the Editor
image

**GET https://vmg.cartodb.com/api/v2/sql?q=select%20*%20from%20(update%20untitled…)%20__wrapped%20limit%200&api_key=APIKEY 400 (Bad Request)**

https://vmg.cartodb.com/api/v2/sql?q=select%20*%20from%20(update%20untitled_table_9%20as%20o%20set%20name%20%3D%20%27pepe%27)%20__wrapped%20limit%200&api_key=APIKEY

````
ERROR:  syntax error at or near "as"
````

But, directly without the wrapped query it works:

https://vmg.cartodb.com/api/v2/sql?q=update%20untitled_table_9%20as%20a%20set%20name%20%3D%20%27pepe%27&api_key=APIKEY

````
{
rows: [ ],
time: 0.072,
fields: { },
total_rows: 1
}
````

From Support:

```
We're using a query to automatically update the table at a regular interval,
 but the query has suddenly stopped working. 
CartoDB no longer seems to accept queries like:

UPDATE tablename AS o SET name = o.name

The syntax is clearly valid according to the PostgreSQL documentation
 (http://www.postgresql.org/docs/9.1/static/sql-update.html), 
works fine on a local server and has worked on CartoDB in the past.
````

SB/4638032

cc @rochoa @javisantana @xavijam

### PR DESCRIPTION
**Pull request by javisantana**
@vmg review it please 

CR @viddo

### CODE REVIEW

**Comment by viddo** [comment]
Looks legit :shipit:

**Comment by iriberri** [comment]
If this is something related with the vmg CartoDB account, is not his, it's one of my multiple testing accounts :smile:

**Comment by javisantana** [comment]
XDDDDDD epic fail, sorry @vmg

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2090/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2091/))

**Pull request merged**
