### PR TITLE
Adds a layer with labels to new tables if default basemap has labels on top

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
For new maps, [we copy the base layers of the first selected map](https://github.com/CartoDB/cartodb/blob/master/app/models/visualization/table_blender.rb#L16).
cc// @Kartones

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4754/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4756/))

**Comment by Kartones** [comment]
:+1:

**Comment by alonsogarciapablo** [comment]
Fixes #4287

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4766/))

**Pull request merged**
