### PR TITLE
[Dashboard] Show zero when remaining quota is negative

### PR DESCRIPTION
**Pull request by csubira**
#14565

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
💪

**Comment by alonsogarciapablo** [comment]
I'm still not seeing this in production. Do we need to re-deploy? Bump the version of the assets perhaps? Thank you!

**Comment by jesusbotella** [comment]
We didn't deploy that yet, but feel free to do it if you want :)
You only need to run `npm run bump` after checking out master branch and pulling changes from origin. And right after that, launch the deploy on Jenkins.

**Comment by alonsogarciapablo** [comment]
No worries. I will wait 😂

**Pull request merged**
