### PR TITLE
Do not store session for api_key auth #3207

### PR DESCRIPTION
**Pull request by rafatower**
@juanignaciosl @Kartones @javisantana mini-review please

### CODE REVIEW

**Comment by Kartones** [comment]
Nice! :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3029/))

**Comment by juanignaciosl** [comment]
Great :+1:

**Comment by rafatower** [comment]
There's an issue with `ApplicationController#current_viewer` that relies on warden storing stuff in the session context. I'm gonna look for a solution for that.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3038/))

**Comment by rafatower** [comment]
@Kartones can you please review the `current_viewer` stuff?

**Comment by Kartones** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3051/))

**Pull request merged**
