### PR TITLE
#6306 soft_geocoding_limit false by default

### LINKED ISSUE #6303: Wrong query output at CartoDB editor
I'm getting a different output when running the following query from editor and API:

```
SELECT a.name,a.surname,a.email,a.cartodb_id,b.profile_id
FROM "finanzasdf-admin".alasarr_users a
INNER JOIN "finanzasdf-admin".alasarr_users_profiles b ON b.user_id=a.cartodb_id
where a.email='alberto@geographica.gs'
```

API returns two records (right) and editor returns one (wrong).

API query:

```
https://finanzasdf-admin.cartodb.com/api/v2/sql?api_key=XXXX&q=SELECT a.name,a.surname,a.email,a.cartodb_id,b.profile_id FROM alasarr_users a INNER JOIN alasarr_users_profiles b ON b.user_id=a.cartodb_id where a.email='alberto@geographica.gs'
```

API output (total_rows=2):

```
{"rows":[{"name":"Alberto","surname":"Asuero","email":"alberto@geographica.gs","cartodb_id":2,"profile_id":2},{"name":"Alberto","surname":"Asuero","email":"alberto@geographica.gs","cartodb_id":2,"profile_id":3}],"time":0.001,"fields":{"name":{"type":"string"},"surname":{"type":"string"},"email":{"type":"string"},"cartodb_id":{"type":"number"},"profile_id":{"type":"number"}},"total_rows":2}
```

Editor (total_rows=1):

captura de pantalla 2015-12-22 a las 8 18 30

### LINKED ISSUE #6306: Change soft_geocoding_limit default value to false in the enterprise user API
It is right now true by default but it should be false.
http://docs.cartodb.com/cartodb-enterprise/enterprise-api/#arguments

cc @rafatower

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #6306.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
@rafatower CR this, please.

**Comment by juanignaciosl** [comment]
@jgoizueta CR this, please.

**Comment by jgoizueta** [comment]
Looks fine.

While we're at it I would change the `correctly creates a user` test to set `soft_geocoding_limit` to true, or even add a new creation test so we have one with true and another with false to cover all creation cases (false, true, default). This may be overkill, though :stuck_out_tongue:

**Comment by juanignaciosl** [comment]
@jgoizueta thanks! I'm afraid I won't take your suggestion this time because it's not needed for this and I have TONS of fronts right now, I need to make progress :(

**Pull request merged**
