### PR TITLE
Support ordering visualizations by :name and specifying an :order_direction (approach 2)

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Second option of https://github.com/CartoDB/cartodb/issues/14316#issuecomment-434760170.

Haven't really tested it but wanted to get your thoughts @javitonino before I put more work into it.

### CODE REVIEW

**Comment by javitonino** [comment]
LGTM. Only thing missing is that because the `page_per_page_order_params` method return type changed, we will have to review all callers to that function and have then handle the extra returned element.

It's fine if we just ignore it, but at least put a `_` to say we expect a 4th return parameter and we decided to ignore it. I know this is entirely optional (ruby will eat the extra returned values without error) but I prefer that we are explicit so it's easier to update this in the feature.

To be clear, just do a global search + replace:
`page, per_page, order = page_per_page_order_params(VALID_ORDER_PARAMS)`
to
`page, per_page, order, _order_direction = page_per_page_order_params(VALID_ORDER_PARAMS)`

and that should be enough. Properly handling that in all other controllers would be a great extra, but out of scope.

**Comment by alonsogarciapablo** [comment]
Good point @javitonino. I just changed it.

**Comment by javitonino** [comment]
Hey!

This should not have been merged!

It has no CR of the latest changes. No Acceptance. And the checks are :red_circle: (missing NEWS).

As I said on the other ticket, we do CR + Acceptance after each change, small as it may be.

**Comment by javitonino** [comment]
Since it has not been deployed yet, please revert this PR and create a new one (identical to this) and submit it for review :pray:

**Comment by javitonino** [comment]
Oops, it got merged into the other PR :see_no_evil:

**Pull request merged**
