### PR TITLE
Form field error

### PR DESCRIPTION
**Pull request by xavijam**
Basically, represented correctly the error state for generic form elements in the new editor.

screen shot 2016-04-18 at 18 20 15

Also:
- Updated master with analysis.
- Conflicts solved.

CR: @javierarce 
cc @piensaenpixel

### CODE REVIEW

**Comment by javierarce** [comment]
Besides the hound warnings, this is 🔝  for me.

**Comment by xavijam** [comment]
Hound warnings fixed in the last commit ;).

**Comment by javierarce** [comment]
Haha, I think I commented in a window that wasn't up-to-date 😅

**Comment by piensaenpixel** [comment]
👍

**Pull request merged**
