### PR TITLE
Disable soft geocoding for users without block price set

### LINKED ISSUE #10507: Geocoding fails if no geocoding block price is assigned
app/models/geocoding.rb#price:

```ruby
211   def price
212     return 0 unless used_credits.to_i > 0
213     (user.geocoding_block_price * used_credits) / ::User::GEOCODING_BLOCK_SIZE.to_f
214   end # price
```

It fails if `geocoding_block_price` is null (open source users, for example).

cc @CartoDB/dataservices

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #10507

### CODE REVIEW

**Comment by javitonino** [comment]
@rafatower Can you take a quick look? This is a just-in-case fix, but I don't think it will actually be needed. I just added it as a precaution against free geocoding.

I am also fixing the affected users (manually since there are very few).

**Comment by rafatower** [comment]
:+1:

Quick question: did you check that fresh users get a block price?

**Comment by rafatower** [comment]
Out of the scope of the review but to take into account: the `soft_limit` attribute is used beyond rails app, so I'd advocate against putting logic in such checks cc/ @juanignaciosl

**Comment by javitonino** [comment]
There were some users getting null block prices (from the price plans). I have fixed the price plans to avoid it.

Also, if the check is being used elsewhere, what if we remove this check and we put a validation in central that disallows setting soft geocoding limit with nil block prices? This way we ensure users are not created with invalid combinations of parameters, no check needed. I'd also pursue making these kind of attributes NOT NULL in the database, to avoid this kind of issue.

**Comment by javitonino** [comment]
Ok, trashing this then, and moving the check to central. Thanks!

**Pull request closed without merging**
