### PR TITLE
Disabling 'export image' functionality if provider is google maps

### PR DESCRIPTION
**Pull request by xavijam**
Basically it will check the map provider and if it is GMaps, 'image export' option won't be available.

export-image-leaflet-no-gmaps

Fixes https://github.com/CartoDB/cartodb-management/issues/3818
cc @javisantana @jatorre @saleiva

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3991/))

**Comment by xavijam** [comment]
@viddo could you check it? CTO remains busy :).

**Comment by viddo** [comment]
Looks OK, but why not keep the provider details internally in the map model? I.e. provide some `canExport` method that internally do that `provider.toLowerCase().indexOf("googlemaps") === -1` check?

**Comment by xavijam** [comment]
better @viddo?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4007/))

**Comment by viddo** [comment]
:+1:

**Pull request merged**
