### PR TITLE
Private vizjson fixes

### PR DESCRIPTION
**Pull request by javierarce**
As a temporary measure, we now add the API key of the user to make the vizjson request for PRIVATE or PASSWORD visualizations.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1809/))

**Comment by javisantana** [comment]
why is that? cc @Kartones

**Comment by Kartones** [comment]
To try to allow grabbing private vizjsons without forcibly specifying api_key. but this change doesn't works so I'm reverting it.

It seems is something about Unicorn, but before lowering security I'd rather leave it "failing" if the action doesn't improves the situation.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1810/))

**Comment by Kartones** [comment]
Research so far:

- Local Thin server works fine. If there's a user session Rails and Warden work as expected and normal application-level authorization is performed and if correct private viz.json is served.
- Pre-production and Production servers use Unicorn. At both same issue happens. A 403 is returned as if there were no sessions.
  - [x] Both requests are done from https
  - [x] Correct no caching headers are present on private viz (also 403 returns `Cache-Control:no-cache` and a `X-Cache: MISS`)
  - [x] Server session exists / user is logged in
  - [x] get_authenticated_users at for example public profile page returns session correcty
  - [x] Correct or at least same _cartodb_session cookie data is sent in both scenarios.
  - [x] If specifying an api_key authorization is performed and private viz.json is served.

**Comment by javierarce** [comment]
@CartoDB/frontend: can you review this, please?

**Comment by javierarce** [comment]
@CartoDB/frontend: can you review this, please? (see the description of the PR)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1812/))

**Comment by javisantana** [comment]
but, are we fixing a deployment problem or a real app auth problem?

**Comment by Kartones** [comment]
Real app auth problem/different auth behaviour.

**Comment by Kartones** [comment]
Moving my auth issues to a ticket to push @javierarce fixes so the dashboard works

**Pull request merged**
