### PR TITLE
Add format option to the premium data library

### LINKED ISSUE #14216: Add format option to `load_in_data_library`
### Context

See CartoDB/bigmetadata/issues/540. We should add an option to choose the format, which should default to GPKG.

cc @javitonino

### PR DESCRIPTION
**Pull request by ethervoid**
Closes #14216

### CODE REVIEW

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by ethervoid** [comment]
@ramiroaznar who is going to do the acceptance of this?

**Comment by juanignaciosl** [comment]
Acceptance ok :+1:

**Pull request merged**
