### PR TITLE
Recover deleted route and index function for api/v1/synchronizations/

### PR DESCRIPTION
**Pull request by iriberri**
This was removed at: https://github.com/CartoDB/cartodb/commit/6238fbaac2b3e4f3d64c1a3855c144ab195cd8bf

Fixes https://github.com/CartoDB/cartodb/issues/6313

### CODE REVIEW

**Comment by rafatower** [comment]
ok

were there any related tests?

**Comment by iriberri** [comment]
Nope. Gonna add one here: https://github.com/CartoDB/cartodb/blob/master/spec/requests/api/synchronizations_spec.rb

**Comment by iriberri** [comment]
@rafatower now there is one that will shout if the route is eventually discarded again.

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
