### PR TITLE
Fix missing meta on privacy update

### LINKED ISSUE #5667: Privacy change causes dataset to not show meta indicators in listing
dataset-properties

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #5667

The problem was that the JSON return was not done properly and nested info about synchronisation was lost. Now it should be fine.

This uses the new presenter (returns one thing or another depend on who is asking) but has to "convert" from member to viz, which might not be the best thing.

When CI pases I'll call for a CR.

P.D.: Although not in the scope of the ticket I corrected the return of create as well, as it had the same flaw.

cc/ @xavijam

### CODE REVIEW

**Comment by gfiorav** [comment]
Hey, @juanignaciosl, could you have a look?

**Comment by juanignaciosl** [comment]
Uhm. Maybe this fix works, but the approach feels wrong. That controller, `app/controllers/api/json/visualizations_controller.rb` is an "old" controller, so it should use `CartoDB::Visualization::Member`, not `Carto::Visualization`. In general "old" code (code not using ActiveRecord) should not depend to new. There're several reasons for that, from technical (avoid circular dependencies) to "procedural": we decided not to refactor old code but rewrite and delete.

I'd try to fix the old one first. If fixing it easy enough, I'd go for it.

**Comment by gfiorav** [comment]
@juanignaciosl So you propose writing a different presenter to support the old model?

**Comment by juanignaciosl** [comment]
Not really. Presenters were mostly introduced for the new models to avoid presentation logic inside the models code, I think there were no presenters before (at least there were not "mandatory").

I don't know as much as you do about this problem, but taking a look at the (wrong) JSON there's a `null` `synchronization` attribute, so it looks like sync is there but it`s not loaded. I'd first review the code, maybe you can fix the issue just loading the synchronization.

**Comment by gfiorav** [comment]
@juanignaciosl Synchro is not null.

The `render_jsonp` is just not rendering it (I guess it has to do with it being nested).

**Comment by juanignaciosl** [comment]
screen shot 2016-01-14 at 11 32 30

^ it is, isn't it?

**Comment by gfiorav** [comment]
It is in the JSON, but just before entering `render_jsonp` it's not, that's what I meant.

**Comment by juanignaciosl** [comment]
Ah, sorry :sweat_smile: 

Could you look into the code to check why `render_json`` renders `permission` but not `synchronization`?

**Comment by gfiorav** [comment]
Hi @juanignaciosl , take a look now please!

**Comment by juanignaciosl** [comment]
<3 :+1: Nice catch! I hope you enjoyed mining down the old models :-)

**Comment by gfiorav** [comment]
:heart: :kiss: thanks @juanignaciosl 

Yes I enjoyed :laughing: :gun:

**Pull request merged**
