### PR TITLE
org. notifications: mark as read header component [WIP]

### PR DESCRIPTION
**Pull request by matallo**
re: https://github.com/CartoDB/cartodb/issues/11807

to be merged after https://github.com/CartoDB/cartodb/pull/11779

this is specially tricky as the `@organizations_notification` object has to be included in every controller, as well as the `organizations_notification` variable in every view where organization notifications will be shown in the header component

**acceptance**

- New dashboard and new public dashboard should not appear anymore
- check after creating a new notification it appears in the header component (see attached) and it gets dismissed as the component is closed

screen shot 2017-03-24 at 13 07 48
screen shot 2017-03-24 at 13 08 11

- these should not affect current notifications for quotas and such, which still work with localStorage
- the components works on every page the private header is

### CODE REVIEW

**Comment by xavijam** [comment]
One thing, remember to add the scroll (I'd not add a custom one unless we have one view ready for that) in the notifications list 💋 .

**Comment by nobuti** [comment]
@matallo is this still WIP or may I do the CR?

**Comment by matallo** [comment]
oh sorry, still WIP until I double check every place where this component appears

**Comment by matallo** [comment]
just added the loaders, as told https://github.com/CartoDB/cartodb/pull/11842/commits/817d2fef45913baebe546e8086317cc527ecc75a I think it needs some backend 👀  

I couldn't make the mobile apps view to work `/your_apps/mobile`, so I'll probably ping you

**Comment by matallo** [comment]
moved the organization notifications loader to a helper, and added it to the mobile apps

/cc @javitonino

**Comment by xavijam** [comment]
Two things I noticed reviewed shortly this PR:

- In Safari the notifications dropdown was not appearing.
- We should check if table quota notification appears when the user reaches his/her limits*.

*When user is close or has passed his/her table quota limit, a notification should appear saying that, and offering an update if possible (for organization users or on-premise users should not offering anything).

**Comment by nobuti** [comment]
It works fine, but I could reproduce the safari issue

screen shot 2017-03-30 at 12 51 42

I think we could fix it applying `flex-basis: auto` to the scroll view inside the dropdown, due the container has no height applied.

About your comment @xavijam, the issue description mentions the quota notifications is not working yet through this, not sure if I'm missing something.

**Comment by xavijam** [comment]
It should work, if it is not working we should get back to development and add it again.

**Comment by nobuti** [comment]
screen shot 2017-03-30 at 14 57 09 
🌟

**Comment by xavijam** [comment]
VAMOS!, not sure if that icon is the correct one but VAMOS! :D. Great @matallo!

**Comment by xavijam** [comment]
If we consider that CR and acceptance is ok, please, deploy it in any staging and warn @noguerol in order to pass their acceptance, pretty please.

**Comment by nobuti** [comment]
Fixed the icon and the safari's issue with the dropdown. All yours @noguerol, it's in ded05.

**Comment by xavijam** [comment]
💃  🚀  🌟

**Comment by xavijam** [comment]
Hey, we missed the `NEWs.md` 🔢 .

**Comment by urbanphes** [comment]
Some things:
- Only appears the notification icon on the 9 first notifications. (I tested with 20 notifications)

- Change the notifications icon orange color to green, the same that the circle. (#73C86B) In this way we relationship it both.
captura de pantalla 2017-04-04 a las 18 03 22

- When the notifications have been consumed, the next notification "There are no notifications :)" appears with a weird align. This should be aligned to the left side, without icon.
captura de pantalla 2017-04-04 a las 18 04 30

- The scroll bar should appear to 6px from the right side, in this way is easier to click over this.
captura de pantalla 2017-04-04 a las 18 44 52

**Comment by noguerol** [comment]
Out of @urbanphes comments, i've not been able to reproduce the only 9 icons bug. Additionally to that there is one fix and to nice changes we could add for acceptance:

1. Radio button has a weird inside misalignment

captura de pantalla 2017-04-05 a las 17 57 13

captura de pantalla 2017-04-05 a las 17 57 09

2. When resending notification and the notification input text box is out of the viewport, center it
captura de pantalla 2017-04-06 a las 11 30 06

3. Open notification links in a new tab, as they will normally pointing outside Builder.

captura de pantalla 2017-04-06 a las 11 33 09

**Comment by ivanmalagon** [comment]
Latest fixes:

- Dropdown
    - Icons now are same green as bubble.
    - Scroll bar now with proper padding.
    - Shadows have been wiped out (by petition of @urbanphes )

scroll fixed

- When no notifications left, text aligned to left (no pun intended).

image

- When clicking `resend` the page gets scrolled to top.

scrollto

**Comment by ivanmalagon** [comment]
Deployed in DED01. Ready for @noguerol to validate the last fixes.

**Comment by javitonino** [comment]
cc @csobier, so she's notified when this is ready.

**Comment by xavijam** [comment]
Approved by @noguerol, deploying!

**Comment by matallo** [comment]
BOOM

**Pull request merged**
