### PR TITLE
Reduced default opacity of poligon-stroke to 0.5

### LINKED ISSUE #2810: Reduce polygon stroke opacity to <1
Right now, if you load a ton of small polygons they

a) End up on the light basemap
b) Have 1px polygon stroke that is white and full opaque

So you end up not being able to see anything on the map unless you know the trick.

I'd say something like 0.5-0.8 could fix it, but worth experimenting

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #2810.

@xavijam @saleiva PTAL! Thx!

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3258/))

**Comment by xavijam** [comment]
:+1:

**Comment by saleiva** [comment]
+1

**Comment by saleiva** [comment]
It was de default-width which needed to be reduced to 0.5. My fault, Bad review :(

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3273/))

**Pull request merged**
