### PR TITLE
Added read permission tag in dataset view header

### LINKED ISSUE #9982: Add r/w permission label in dataset view
This element is present in the designs but hasn't been implemented yet.

screen shot 2016-10-03 at 16 16 17

cc @xavijam

### PR DESCRIPTION
**Pull request by MariaCheca**
Fixes #9982 

screen shot 2016-10-13 at 13 34 23

CR @xavijam

### CODE REVIEW

**Comment by MariaCheca** [comment]
So should I add some tests or not?

**Comment by xavijam** [comment]
YEP!

**Comment by MariaCheca** [comment]
GREAT 👍

**Comment by xavijam** [comment]
Merge master in order to make our tests run

**Pull request merged**
