### PR TITLE
Dont geocode short or just number strings

### PR DESCRIPTION
**Pull request by rafatower**
@Kartones can you please review?

Some notes:
- i know it lacks tests but I don't know yet how much of the code I will change and therefore it's hard for me to write tests in an effective way.
- commit messages can let you follow my thinking process maybe better than just the diff
- I'm focused on fixing stuff and getting a good idea of maintainability problems.
- I'm trying to capture some design decisions in comments, not the best option IMO but better than struggling with legacy code as it is.
- Feel free to add anyone if you think it is worthy for sharing points of view.
- After releasing this I'll clean up the cache with sth like `DELETE FROM cache where WHERE length(searchText) > 3 AND searchText !~ '^[\d]*$`

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4484/))

**Comment by Kartones** [comment]
uhm:
`After releasing this I'll clean up the cache with sth like DELETE FROM cache where WHERE length(searchText) > 3 AND searchText !~ '^[\d]*$`

Then please check that query XD or you will delete all cache items *bigger* than 3 :P better use this one:
`DELETE FROM cache where WHERE length(searchText) < 3 AND searchText !~ '^[\d]*$`

**Comment by rafatower** [comment]
you're (almost) right :smile: 
```
DELETE FROM cache WHERE length(searchText) < 3 OR searchText ~ '^[\d]*$
```

**Comment by Kartones** [comment]
:trollface: you say "smaller than" so `<` but yes, just trolling, just pointing that the comparator was wrong

**Comment by Kartones** [comment]
+1 to the changes, better and easier to read by haing pure SQL for the future migration to AR, so good job!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4495/))

**Pull request merged**
