### PR TITLE
Sort category names alphabetically in legends

### LINKED ISSUE #2808: alphabetically ordered legend items
Could items in a legend automatically be ordered alphabetically/numerically instead of being unordered?

screen shot 2015-03-17 at 10 05 25

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #2808.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3044/))

**Comment by alonsogarciapablo** [comment]
@javisantana, this seems to get the job done. :+1: 

Another option would be to sort the categories [here](https://github.com/CartoDB/cartodb/blob/2808-order-legend-items/lib/assets/javascripts/cartodb/models/carto/category.js#L82).

**Comment by javisantana** [comment]
i love when things work by chance :es:

as a side comment, all those functions that we have to get analytics from a table should be in cartodb.js/src/api/sql.js

The reason is that a lot of times the user want to get stats from the table and they need to do their own queries so having:

```
var sql = cartodb.SQL({ username: 'rambo' });
sql.categoriesForColumn(...., function() {
});
```

But there is another reason to do that. Postgres has its own statistics for columns in tables, so for example we could have a "fast" path for this using pg_stats which collections information for  columns:

```sql
# select chr((65 + round(random() * 25))::integer) as ch into table_test from generate_series(1, 100000);
SELECT 100000
# select most_common_vals, most_common_freqs from pg_stats where tablename = 'table_test';
                   most_common_vals                    |                                                                                                                     most_common_freqs
-------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 {X,L,S,Y,P,J,O,F,T,D,N,Q,K,B,W,E,C,U,G,H,M,I,R,V,Z,A} | {0.0433333,0.0414667,0.0410667,0.0409667,0.0408,0.0405667,0.0405667,0.0404667,0.0404667,0.0403333,0.0402333,0.0402333,0.0401667,0.0396667,0.0396667,0.0396333,0.0393333,0.0391667,0.0391333,0.0388667,0.0387667,0.0387333,0.0383,0.0380667,0.0203,0.0197}
```

cc @CartoDB/frontend

**Comment by viddo** [comment]
Thx for the info! Although, I'm thinking, apart from informing us in-context here, shouldn't this be documented somewhere?

**Comment by xavijam** [comment]
Agree with @viddo.

**Comment by xavijam** [comment]
In any case :+1:

**Comment by javisantana** [comment]
@viddo what do you mean with documented?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3053/))

**Comment by viddo** [comment]
> ..., all those functions that we have to get analytics from a table should be in cartodb.js/src/api/sql.js

I interpret this as there are functions that should be located in the sql.js there are currently located elsewhere (where they shouldn't be). But how would should we know? After reading this issue we will have it in the back of our heads (at best), but what about new people joining the project in the future? 

So, what I mean with _documented_ is that this decision/convention/guideline should be written down and explained (like above), e.g. in the wiki or a versioned `doc/` dir.

**Comment by alonsogarciapablo** [comment]
@javisantana PTAL at [this final commit](https://github.com/CartoDB/cartodb/pull/3218/files).

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3064/))

**Comment by javisantana** [comment]
:es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3066/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3068/))

**Comment by ohasselblad** [comment]
thanks for the sorting, you guys are superstars

**Pull request merged**
