### PR TITLE
utf-8 encoding at filename* header

### LINKED ISSUE #10701: Problem downloading a .carto with asian characters
@CartoDB/builder-backend

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #10701.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
@javitonino , @gfiorav , could you please CR this? Pinging both because both of you were involved in the original issue.

**Comment by javitonino** [comment]
Patch looks reasonable. Have you deployed it somewhere so we can test (with different browsers)?

**Comment by juanignaciosl** [comment]
@javitonino ded06. I must admit that I've only tested it with Chrome so far. AFAIK, clients that don't support `filename*` will use `filename`, which is now safe (maybe ugly, but safe), as the encoding prevents from crashing.

**Comment by juanignaciosl** [comment]
@javitonino tested in Safari and Firefox as well.

**Comment by javitonino** [comment]
Tested with firefox/chrome in linux and it works like a charm :clap: 

This is a :shipit: for me.

**Comment by juanignaciosl** [comment]
Waiting for @gfiorav point of view. Thanks!

**Comment by juanignaciosl** [comment]
@gfiorav not at all! Please try it at ded06 :-) . Browsers that support it (it looks like all of them do) will use the `filename*` value, which is the url encoded version of the original name. It must be url encoded to be safe, but the browser downloads the original filename (I've tried chinese characters). If any client doesn't support that field, it will use `filename`, which will have replaced characters. This is needed for the `POST` to work, but it will only be used as a fallback in those cases where the client doesn't know about `filename*`.

**Comment by gfiorav** [comment]
Super 🌴 then!

P.S.: Did you buy a Chinese keyboard for this? 😛

**Comment by juanignaciosl** [comment]
Amazon Prime is super fast :-)

**Pull request merged**
