### PR TITLE
Update non-org users in central

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones CR this fix for #2894, please.

### CODE REVIEW

**Comment by Kartones** [comment]
:+1:   wow, so data was not being sync/updated box->central ?

**Comment by juanignaciosl** [comment]
Nop. When user controller was adapted to work with the new account page it was not done. Probably `@user.update_in_central` misled, since you had to go inside the method to see only org users were updated.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2530/))

**Comment by Kartones** [comment]
ohh right, because in the past all user profile stuff was at central. Thanks for the info!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2657/))

**Comment by matallo** [comment]
:sparkles: deploying tomorrow first thing

**Pull request merged**
