### PR TITLE
SQL file should return an unsupported file exception

### LINKED ISSUE #7204: SQL files are being admitted but crash to import
````
NoMethodError: undefined method `call' for CartoDB::Importer2::Loader:Class
````

with unknown 99999.

````
[\"/services/importer/lib/importer/runner.rb:117:in `find'\",
 \"/services/importer/lib/importer/runner.rb:117:in `loader_for'\", 
\"/services/importer/lib/importer/runner.rb:157:in `import'\", 
\"/services/importer/lib/importer/runner.rb:344:in `execute_import'\", 
\"/services/importer/lib/importer/runner.rb:273:in `block (3 levels) in single_resource_import'\",
`````

### PR DESCRIPTION
**Pull request by ethervoid**
Closes #7204 

@iriberri CR this

### CODE REVIEW

**Comment by iriberri** [comment]
I'm seeing that there are more mentions to the SQL format all over the project, e.g:

(Frontend) https://github.com/CartoDB/cartodb/blob/744a01eadb078119cdca78987375cb7f3fc8f097/lib/assets/javascripts/cartodb3/config/upload-config.js

(Backend) https://github.com/CartoDB/cartodb/blob/bb7fe3a0145af6009c2fe657263315675b38c68e/services/importer/lib/importer/unp.rb#L19

It could be a good idea to ping somebody in frontend to make sure we're being consistent and not leaving the format spread around the project :)

**Comment by ethervoid** [comment]
We're removing all related to SQL extension in the importer but @iriberri spotted [this](https://github.com/CartoDB/cartodb/blob/744a01eadb078119cdca78987375cb7f3fc8f097/lib/assets/javascripts/cartodb3/config/upload-config.js) in the fronted. Is save to remove it? Any other occurrences? // @CartoDB/frontend

**Comment by xavijam** [comment]
No problem to remove it. Could you remove from `lib/assets/javascripts/cartodb3/config/upload-config.js` too? Please

**Comment by ethervoid** [comment]
Sure, do we have to update the package.json for this right?

**Comment by xavijam** [comment]
Yes

**Pull request merged**
