### PR TITLE
Adds copy & paste functionality for overlays

### PR DESCRIPTION
**Pull request by javierarce**
Adds copy & paste functionality for overlays (text, annotations and images).

capture
capture2

### CODE REVIEW

**Comment by javierarce** [comment]
@xavijam: can you review this, please?

**Comment by xavijam** [comment]
@viddo, could you take care of it pretty please?

**Comment by viddo** [comment]
sure, but you owe me some :chocolate_bar:

**Comment by xavijam** [comment]
@Cartofante, please remind me tomorrow to buy some chocolate to @viddo.

**Comment by viddo** [comment]
Looks legit :+1:

**Pull request merged**
