### PR TITLE
Switch vacuum full by vacuum analyze from table.optimize

### LINKED ISSUE #7239: Remove vacuum full from imports

### PR DESCRIPTION
**Pull request by iriberri**
Closes #7239

In the past, the import process was highly manipulating the target tables: creating, renaming and dropping columns (for example, in the QueryBatcher). In that scenario, having a vacuum full running for each import might make sense to clean the table.

This `table.optimize` function is called from `app/models/data_import.rb` in `migrate_existing` and `app/models/table_registrar.rb` in `register`. 

Performing a vacuum full on a table which has been newly created and has not suffered those manipulations has a cost in the import time, so we are substituting it by a simpler "VACUUM ANALYZE" which will update the stats (might be important for calculating bounds when the geometries have changed, e.g. in geo-guessing).

### CODE REVIEW

**Comment by iriberri** [comment]
retest this, please

**Comment by iriberri** [comment]
@rafatower could you check? Please, ignore the build which seems pending on the PR.

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by rafatower** [comment]
:+1:

**Comment by rafatower** [comment]
With a new benchmark I'd close the speed ups for this sprint and focus on the arch stuff (you know, fdw's, augmentation and all that)

**Comment by iriberri** [comment]
:+1:

**Pull request merged**
