### PR TITLE
Some text improvements in the new publish map modal window

### PR DESCRIPTION
**Pull request by javierarce**
See my proposal in the original ticket: https://github.com/CartoDB/cartodb/issues/3525

### CODE REVIEW

**Comment by javierarce** [comment]
@viddo & @saleiva: can you review this, please?

**Comment by saleiva** [comment]
+1

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3504/))

**Comment by viddo** [comment]
:sparkles: :shipit:

**Comment by javierarce** [comment]
retest this please

**Comment by javierarce** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3516/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3517/))

**Pull request merged**
