### PR TITLE
Remove SCSS lint in Hound config

### PR DESCRIPTION
**Pull request by jesusbotella**
Hound was linting our styles with SASSLint which had a default configuration that made inconsistencies in our styles. So I disabled it and leave the linting in the `npm run ci` passed in Travis and Jenkins.

### CODE REVIEW

**Comment by ivanmalagon** [comment]
LGTM but what's the error above with `stylelint`?

**Comment by jesusbotella** [comment]
The error was caused by Hound itself when I tried to use the same configuration that we're using in our local linters. Seems like `stylelint-config-property-sort-order-smacss` is not supported in Hound.

**Comment by IagoLast** [comment]
:iago :fuu +1

**Comment by ivanmalagon** [comment]
I've made a couple of changes:
- the grunt `lint` task now runs `npm run lint`. Before, it ran only eslint for the js. Now, it runs the npm script that pass both js & css. This way we can simplify the CI recipe that has an additional step for css.
- I moved `lint` to the first step of the `test` grunt task. If `lint` fails, it exits so we don't have to pass the tests.

**Comment by ivanmalagon** [comment]
Any reviewer for my last changes?

**Pull request closed without merging**
