### PR TITLE
Fixed negative workflow count

### LINKED ISSUE #9841: Avoid negative workflow count
If layer nodes are 0 (that happens when a layer source is another layer's analysis) avoid showing this -1.

screen shot 2016-09-21 at 16 16 40

### PR DESCRIPTION
**Pull request by MariaCheca**
**Opened a new PR as the first one's tests were not responding well.**
Fixes #9841 

In case the value returned is 0, return it without the -1 operation to exclude from the result the layer source.

CR @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
I miss the tests :)

**Comment by MariaCheca** [comment]
ping @xavijam

**Comment by xavijam** [comment]
Hey but there is no test checking the problem, just a minor change about the count. I'd do an explicit one showing the case.

**Comment by xavijam** [comment]
Ping! :)

**Comment by MariaCheca** [comment]
Working on it!

**Comment by MariaCheca** [comment]
retest this please

**Comment by xavijam** [comment]
Hound is a bit crazy today @MariaCheca, I feel you can merge without fear.

**Comment by MariaCheca** [comment]
WOHO!

**Pull request merged**
