### PR TITLE
infowindow: loading states

### PR DESCRIPTION
**Pull request by matallo**
bitmap

wip, added stateless, need to add loading

### CODE REVIEW

**Comment by matallo** [comment]
retest this, please

**Comment by xavijam** [comment]
are we still working on this?

**Comment by matallo** [comment]
it was on hold for the bottom views, now they've been added I can carry on

**Comment by xavijam** [comment]
We have conflicts :S.

**Comment by xavijam** [comment]
:+1: 🚢 :it:

**Pull request merged**
