### PR TITLE
Co549 fix ldap connection

### PR DESCRIPTION
**Pull request by juanignaciosl**
Master merge of #7165 changes.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by juanignaciosl** [comment]
@danicarrion This is the (other) branch where you can commit the final patch. Great work BTW! 💪

**Comment by danicarrion** [comment]
please review, my ruby skills are quite limited. also, I guess part of the existing code on that file can be removed / updated based on the changes I made. is it worth checking?

**Pull request merged**
