### PR TITLE
Adding link to the avatar img if loged in - fixes #2887

### LINKED ISSUE #2887: If loged in, big avatar should go to the dashboard on the public page

### PR DESCRIPTION
**Pull request by saleiva**

### CODE REVIEW

**Comment by saleiva** [comment]
@viddo please CR!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2511/))

**Comment by viddo** [comment]
:+1:

**Comment by saleiva** [comment]
:cn:

**Pull request merged**
