### PR TITLE
Fixes unwanted spaces on map cards on public pages

### LINKED ISSUE #3576: Tags in public map cards are rendered with a blank space before the comma
screen shot 2015-05-08 at 16 11 50

### PR DESCRIPTION
**Pull request by viddo**
Fixes #3576 
screen shot 2015-05-12 at 16 02 06

The problem is that the helper formatter yields the back to the template, but if the yields contains additional spaces they are included. The object in the helper is a `OutputBuffer` and not a string so don't can't trim inside the formatter method either, other ideas to fix this?

### CODE REVIEW

**Comment by viddo** [comment]
@alonsogarciapablo ping :)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3630/))

**Comment by juanignaciosl** [comment]
@Kartones , @rafatower , take a look at my last commit eb36d7b . It patches #3611, but problem remains at ActiveRecord level.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3632/))

**Comment by alonsogarciapablo** [comment]
LGTM!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3636/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3637/))

**Comment by juanignaciosl** [comment]
For later reference: changing the order of ActiveRecord load broke tag load. 4c417c8 fixes it.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3638/))

**Comment by rafatower** [comment]
Sorry for the late review. LGTM. Don't hesitate to poke me on slack if you need it.

AR surprises

**Pull request merged**
