### PR TITLE
Fix connect to third party services flexbox

### LINKED ISSUE #5471: Fix flexbox in third party connections inputs
When user is connected to a service, the "disconnect" link should be inline with the input.

screen shot 2015-09-10 at 16 55 03

### PR DESCRIPTION
**Pull request by MariaCheca**
Fixes #5471 

screen shot 2015-09-10 at 17 36 32

CR @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
An image in the description would be nice

**Comment by xavijam** [comment]
Also, what is the staging server to test this thing :dancer: ?

**Comment by xavijam** [comment]
When there is an error appears like:

screen shot 2015-09-10 at 17 41 49

**Comment by MariaCheca** [comment]
All problems fixed! :sparkles:

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
