### PR TITLE
10962 drop html type support

### LINKED ISSUE #10962: Drop html type support for legends
We need to stop accepting `html` types in the backend for legends. All migrations are performed to custom now and all existing html have been migrated (except 3 duplicated legends in 1 layer in prod, not worth it).

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #10962 by dropping support for html legends.

HTML legends are no longer used, instead we use `custom` type with an `html` field.

### CODE REVIEW

**Comment by xavijam** [comment]
Acceptance needed?

**Comment by xavijam** [comment]
Although we need to merge with master.

**Comment by javitonino** [comment]
Merged master and fixed some tests. I'd say we skip acceptance on this one (there is no way to really test it at acceptance level). I vote for deploy as soon as some backend tests are 🍏

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
