### PR TITLE
Disable SQL+CartoCSS UI

### PR DESCRIPTION
**Pull request by viddo**
solves #5989, at least as long it's agreed that using the feature flags-feature is the way to go.

screen shot 2015-10-22 at 18 39 47

@xavijam can you review please?
cc @mbforr

### CODE REVIEW

**Comment by xavijam** [comment]
For me perfect :+1: !

**Comment by mbforr** [comment]
Same here - fantastic!

On Fri, Oct 23, 2015 at 4:31 AM, Javier Álvarez Medina <
notifications@github.com> wrote:

> For me perfect [image: :+1:] !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/5992#issuecomment-150511542>.
>



-- 
*Matt Forrest*
Account Manager

*CartoDB*
201 Moore St, Brooklyn, NY, 11206, USA
T: (612) 325-8470 Skype: mbforr
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by viddo** [comment]
@mbforr considering we avoid releases on Fridays it will be merged/deployed on Monday morning, just so you know :)

**Comment by mbforr** [comment]
Yeah perfect. Same process as last time :)

On Fri, Oct 23, 2015 at 9:50 AM, Nicklas Gummesson <notifications@github.com
> wrote:

> @mbforr <https://github.com/mbforr> considering we avoid releases on
> Fridays it will be merged/deployed on Monday morning, just so you know :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/5992#issuecomment-150578353>.
>



-- 
*Matt Forrest*
Account Manager

*CartoDB*
201 Moore St, Brooklyn, NY, 11206, USA
T: (612) 325-8470 Skype: mbforr
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Pull request merged**
