### PR TITLE
Fixes for on-premises version

### LINKED ISSUE #10883: Public Table View style is broken
image

#SMOKE_PD06

### LINKED ISSUE #10884: Feedback modal should not be available for on-premises
screen shot 2016-11-29 at 17 55 40

### PR DESCRIPTION
**Pull request by xavijam**
Fixes #10884.
Fixes #10883.

CR: @MariaCheca

### CODE REVIEW

**Comment by MariaCheca** [comment]
The push tests on Travis are failling, I've restarted them a couple of times but the result is the same. @xavijam please check if there's something wrong 🤗

**Comment by xavijam** [comment]
Sorry, I didn't merge master to that branch, test should pass now. 💋

**Comment by xavijam** [comment]
Here they are, not much to do 💋 .

**Comment by MariaCheca** [comment]
🇦🇹

**Pull request merged**
