### PR TITLE
4166 promote refactored vis endpoint

### LINKED ISSUE #4166: Promote refactored visualizations endpoints to default ones
- Includes both visualizations controller and overlays controller, because the later depends on the former.

- [x] Delete `X_1` paths and reroute original ones to the new controller
- [x] Delete old controller actions served by new controller
- [x] Remove `active_record_vis_endpoint` feature flag & related code (including JS "url patching")
- [x] Stabilize specs

Branch: `4166-promote-refactored-vis-endpoint`

### PR DESCRIPTION
**Pull request by Kartones**
Closes #4166 

Pending build results to stabilize specs

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4517/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4520/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4524/))

**Comment by Kartones** [comment]
@juanignaciosl CR please

**Comment by juanignaciosl** [comment]
Wow, a lot of :fire: here! LGTM

**Pull request merged**
