### PR TITLE
Position map overlays properly when there is a SQL header banner

### LINKED ISSUE #2683: "create table from query or clear view" banner covers zoom overlay and search box
For all maps that were done in our workshop today, we've seen situations like this:

screen shot 2015-03-09 at 14 48 39

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2683 

reposion-overlays

When map overlays was split out from mapview at least one variable (this.headerMessageIsVisible) wasn’t migrated with the rest, so the check to re-position overlays could not have been working since then. Also, the search overlay position calls were not correct either.

Anyway, this is the "quick fix". Adding tests for this was extremely hard (there didn't exist none), so finally skipped it since I don't think it's worth it right now. The code related to these parts are extremely and overly complicated (especially since most of it could be replaced with some proper CSS). Having in mind that we inevitably will touch this again when doing the redesign of the editor I propose to deal with it then instead.

### CODE REVIEW

**Comment by viddo** [comment]
@javierarce code review please 
cc @ohasselblad @saleiva see the animated gif for new (position) behavior of the overlays.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2333/))

**Comment by javisantana** [comment]
> The code related to these parts are extremely and overly complicated

:tmcw:

**Comment by saleiva** [comment]
:+1:

**Comment by viddo** [comment]
@javisantana relatively speaking ofc :kiss:

**Comment by javierarce** [comment]
:+1:  

I would only change:

`setHeaderMessageIsVisibility` with `setHeaderMessageIsVisible`

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2334/))

**Comment by viddo** [comment]
@javierarce agree, done

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2341/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2340/))

**Comment by ohasselblad** [comment]
looks beautiful to me :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2375/))

**Pull request merged**
