### PR TITLE
4943 enable account token link can trigger ensure account has been activated error

### LINKED ISSUE #4943: enable_account_token link can trigger ensure_account_has_been_activated error
@gfiorav has reproduced this error with the following steps:

1. Sign up a new organization user.
2. Activate his account with the email link.
3. Delete his account from account page.
4. Sign up again with the same username and email.
5. Try to activate his account with the email link. It will display the following error message:

4d7409f2-3c3d-11e5-9b2a-fdbbc2aa8017

This is the trace:

```
Started GET "/u/guido-2/enable_account_token/c098649190ea96d12ee4d5820c0b383327146c87" for 83.35.159.104 at 2015-08-07 11:33:22 +0000
Processing by AccountTokensController#enable as HTML
  Parameters: {"user_domain"=>"guido-2", "id"=>"c098649190ea96d12ee4d5820c0b383327146c87"}
Redirected to https://guido-2.cartodb-staging.com/account_token_authentication_error
Filter chain halted as :ensure_account_has_been_activated rendered or redirected
```

Nevertheless a following request (from a different computer) worked as expected:

```
Started GET "/u/guido-2/enable_account_token/c098649190ea96d12ee4d5820c0b383327146c87" for 52.0.190.149 at 2015-08-07 11:34:54 +0000
Processing by AccountTokensController#enable as */*
  Parameters: {"user_domain"=>"guido-2", "id"=>"c098649190ea96d12ee4d5820c0b383327146c87"}
  Rendered signup/account_enabled.html.erb within layouts/frontend (0.9ms)
  Rendered shared/_analytics.html.erb (0.1ms)
  Rendered shared/_trackjs.html.erb (0.1ms)
```

It _might_ be because of session remembering.

Also, now we're returning an standard 404 error message when the token has already been validated. It'd be nicer returning an "already validated account" message.

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #4943. @Kartones CR this, please.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5675/))

**Comment by Kartones** [comment]
:+1:

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5691/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5693/))

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5698/))

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5700/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5701/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5702/))

**Pull request merged**
