### PR TITLE
Add analysis checker within analyses data entry point

### PR DESCRIPTION
**Pull request by xavijam**
This should be the way to check if an analysis should be visible or not. And we have move all the parameters related with analysis to the same point, the 'data/analyses' file. There we will have all the info we need to start working with any analysis in any place, form, add-analysis modal, onboarding, animations,...

Also, due to the fact that we have several forms where we use more than one analysis, we have added some checkers in:

**Area-of-influence**: time option shouldn't be enabled if there is no routing provider.
**Geocoding**: only lat-lon option should be available when there is no geocoder provider.

screen shot 2016-11-23 at 16 43 47

screen shot 2016-11-24 at 11 29 54

CR: @javierarce (when tests turns into green).
Also, I'll need help in order to test at length those changes.
@javierarce and @piensaenpixel can I count with you? 🙏  (maybe?).

Fixes https://github.com/CartoDB/cartodb/issues/10771.
cc @rporres @javisantana @santisaez @saleiva

### CODE REVIEW

**Comment by xavijam** [comment]
So adding @CartoDB/dataservices team in order to check if we are validating "available" analyses properly. Also, those analyses we are checking are:

- data-observatory-measure: by custom install flag.
- georeference-city: by custom install flag.
- georeference-ip-address: by custom install flag.
- georeference-country: by custom install flag.
- georeference-postal-code: by custom install flag.
- georeference-street-address: by `geocoder_provider`.
- georeference-admin-region: by custom install flag.
- routing-sequential: by `routing_provider`.
- routing-to-layer-all-to-all: by `routing_provider`.
- routing-to-single-point: by `routing_provider`.
- trade-area: by `isolines_provider`.

**Comment by jgoizueta** [comment]
These cases that rely on service providers:

* georeference-street-address: by geocoder_provider.
* trade-area: by isolines_provider.
* routing-sequential: by routing_provider.
* routing-to-layer-all-to-all: by routing_provider.
* routing-to-single-point: by routing_provider.

The problem is that now we can have default providers so. Using the quota has a similar problem because internal services can be used without a quota.

We should probably remove those defaults, at least for quota have non zero quotas for all usable services, but right now we better use another way of disabling services. A (hardcoded) configuration flag could be added for on-premises/saas/...

@ethervoid @rafatower will have a more informed opinion, please comment on this

**Comment by ethervoid** [comment]
This config should be enough, what do you think @xavijam ?

captura de pantalla 2016-11-25 13 03 32

**Comment by xavijam** [comment]
That's ❤️

**Comment by ethervoid** [comment]
Deployed. Merge master and enjoy :)

**Comment by xavijam** [comment]
I'm deploying changes in ded02. So we should check that:

- Available analyses appear, those not available should not appear.
- Analyses animations appear in the proper analysis and work correctly in the add-analysis-modal.
- Onboarding messages appear correctly after an analysis is applied.

cc @javierarce @piensaenpixel

**Comment by xavijam** [comment]
Ooooooook, deployed again in ded02 after some small problems :).

**Comment by xavijam** [comment]
Merging when green.

**Comment by xavijam** [comment]
Thanks @javierarce for your help.

**Pull request merged**
