### PR TITLE
Enabling asset spec to run in parallel

### PR DESCRIPTION
**Pull request by jesusvazquez**

### CODE REVIEW

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
In this PR I'm also removing the Makefile.parallel dependency. As soon as it pass the tests in both CI's I think we can merge it into master.

cc\ @juanignaciosl @Kartones

**Comment by Kartones** [comment]
Although my knowledge of `sed` is null :+1: for the spec changes!

**Pull request merged**
