### PR TITLE
Removed compatibility with Builder modal in Editor

### LINKED ISSUE #9731: Remove the compatibility dialog that appears in the Editor
Although we display a "WAIT! This map contains new Builder features that are not supported in the Editor” warning opening a map “backwards”, there’s a `POST` to map endpoint that might break something.

Probably that POST should be avoided.

cc @xavijam @gfiorav @javitonino

### PR DESCRIPTION
**Pull request by MariaCheca**
Closes #9731

CR @xavijam

### CODE REVIEW

**Comment by javitonino** [comment]
This is the original PR https://github.com/CartoDB/cartodb/pull/8378 where this was added. Thought it might be useful to see if you removed everything (I haven't checked).

**Comment by MariaCheca** [comment]
Thanks @javitonino! Looks like everything's ok, but I have a question about this property in the visulization presenter: https://github.com/CartoDB/cartodb/pull/8378/files#diff-4e78c66404e37424037aa177c4dba87bR67 Should it be removed or not?

**Comment by javitonino** [comment]
I'd go for the removal of everything if it's not being used elsewhere (which I think it's not). If it is not being used anywhere else in the frontend, feel free to remove the attribute from the presenter and the model. Out with the junk!

**Comment by xavijam** [comment]
We can't remove the dialog, we have to change the message, that's all. Should we close this one then?

**Pull request closed without merging**
