### PR TITLE
improve email template

### PR DESCRIPTION
**Pull request by matallo**
close https://github.com/CartoDB/cartodb-central/issues/487

screen shot 2015-06-24 at 18 03 59
screen shot 2015-06-24 at 18 05 34
screen shot 2015-06-24 at 17 55 28
screen shot 2015-06-24 at 17 56 14
screen shot 2015-06-24 at 17 57 25
screen shot 2015-06-24 at 17 58 14

CR @juanignaciosl, btw I couldn't manage the `new_organization_user` to work, as you have been involved recently in this, can you help me a bit?

please review @CartoDB/design, tested in desktop android gmail and iphone mail

### CODE REVIEW

**Comment by carlostallon** [comment]
Looking good to me

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4555/))

**Comment by saleiva** [comment]
Ooooh, but we lost the color coding :(
I'd add a bit more of padding since lines are too width for me. Also the error module is a bit weird, either we make it 100% width or we give more margin to it.

**Comment by matallo** [comment]
sure, summoning layout and spacing guys here @carlostallon @josecruz

**Comment by carlostallon** [comment]
- Works better with fixed width.
- a little bit more of padding could work better
- I will make the buttons with rounded corners if possible
- As it's to much text i will align to left, also the button


2015-06-25 16:11 GMT+02:00 Carlos Matallín <notifications@github.com>:

> sure, summoning layout and spacing guys here @carlostallon
> <https://github.com/carlostallon> @josecruz <https://github.com/josecruz>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/4190#issuecomment-115271349>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by matallo** [comment]
- can't make rounded corners because in mobile it breaks, prefer to leave it like this (already discussed with @piensaenpixel)
- what do you mean by fixed with?
- ok to left align
- "a little bit more of padding" I was expecting more a sketch mockup I could replicate

also, take into account the mobile layout

screen shot 2015-06-25 at 17 30 50

if you need me to send some test just ping me

**Comment by matallo** [comment]
ping @carlostallon

**Comment by saleiva** [comment]
I'd assign this to @piensaenpixel

**Comment by piensaenpixel** [comment]
Take a look

emails-templates

https://www.dropbox.com/s/z7ffbaqlvyt0kaj/emails-templates.sketch?dl=0

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4643/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4644/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4647/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4648/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4649/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4650/))

**Comment by matallo** [comment]
screen shot 2015-07-01 at 10 49 35
screen shot 2015-07-01 at 10 57 13
screen shot 2015-07-01 at 10 57 59
screen shot 2015-07-01 at 10 59 58
screen shot 2015-06-30 at 20 54 13
screen shot 2015-07-01 at 11 05 22
screen shot 2015-07-01 at 12 37 07
screen shot 2015-07-01 at 12 39 34
screen shot 2015-07-01 at 12 41 55

/cc @piensaenpixel @juanignaciosl (maybe you want to try activate link version)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4661/))

**Comment by matallo** [comment]
bump

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4689/))

**Pull request merged**
