### PR TITLE
Fixes alignment of the number inside the zoom info overlay

### PR DESCRIPTION
**Pull request by javierarce**
screen shot 2015-05-07 at 11 31 16
screen shot 2015-05-07 at 11 31 37

Original issue: #3550

### CODE REVIEW

**Comment by javierarce** [comment]
@xavijam & @piensaenpixel: please have a :eyes:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3531/))

**Comment by xavijam** [comment]
Checked in several browsers?

**Comment by javierarce** [comment]
Yep: Mac: Chrome / Safari / Firefox. PC: IE / Firefox

**Comment by xavijam** [comment]
:+1: ok!

**Pull request merged**
