### PR TITLE
Remove tmp & unused files

### LINKED ISSUE #2249: temporary files in repository ?
Having a disk space issue I went around looking for things to drop and to my surprise cartodb repo was one of the biggest source trees I had around. The biggest directory was the "public" one. I got rid of it and then checked with "git status" what was in the sources.

Suspiciously a lot of files under a "tmp" dir were, an extract:
```
        deleted:    public/tmp/sass-cache/6e853547434e9892c87813cf8e3d9d1284d71266/_inline-block.scssc
        deleted:    public/tmp/sass-cache/6e853547434e9892c87813cf8e3d9d1284d71266/_opacity.scssc
        deleted:    public/tmp/sass-cache/6e853547434e9892c87813cf8e3d9d1284d71266/_shared.scssc
        deleted:    public/tmp/sass-cache/6e853547434e9892c87813cf8e3d9d1284d71266/_text-shadow.scssc
```

Do those files really belong there ?

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2249 

Removed cache files `public/tmp` from repo

Also while at it I saw more things that could be cleaned up:
- Move SASS cache dir out of `app/assets/stylesheets/` → `tmp/sass`
- Moved sessions files `app/assets/javascripts/` → `lib/assets/javascripts/cartodb/sessions/` (already defined as a normal JS bundle), to have all JS source code in the same place
- Removed unused JS assets (`app/assets/javascripts/`), that was bundled by sprockets (now done through grunt)
- Removed unused test runner (`scripts/run_js_tests`), and its related files

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1762/))

**Comment by viddo** [comment]
@CartoDB/frontend please code review, I've verified working fine locally, let me know if something was removed/changed wrongly

**Comment by javierarce** [comment]
It looks fine to me, but I would push it to staging to test it there too.

**Comment by viddo** [comment]
will do!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1764/))

**Comment by viddo** [comment]
deployed on `ded02`, both clinker, build and  deploy have worked fine. have tested login (related to sessions bundle change) and generally browser around tables/vis and no problems so far. Is there anything else that I should test in particular?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1802/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1814/))

**Comment by viddo** [comment]
Tested on ded01 today again and no weird behaviour. 
Unless someone has any more feedback, I'll release it on Mon 23th, to avoid "Friday hickups".

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1869/))

**Pull request merged**
