### PR TITLE
change loaders

### PR DESCRIPTION
**Pull request by piensaenpixel**
@xavijam could you take a look? only change the new markup with the cartoassets

### CODE REVIEW

**Comment by xavijam** [comment]
Aren't there any other places where we use the "old" loader?

**Comment by piensaenpixel** [comment]
i only found this one :(

**Comment by xavijam** [comment]
Ok, update npm-shrinkwrap with `npm run update-...`, change loader in https://github.com/CartoDB/cartodb/pull/7700 and ready to go!

**Comment by xavijam** [comment]
@jvillarf failing on-premise tests, should we be worried?

**Comment by jvillarf** [comment]
@xavijam it has failed while trying to download npm files from github... I've checked it and github is using an extra IP range that wasn't included in our firewall. I've already included it. 

Thanks a lot for reporting!

**Comment by xavijam** [comment]
Go ahead!

**Pull request merged**
