### PR TITLE
Remove data library section

### PR DESCRIPTION
**Pull request by neokore**
Related to https://app.clubhouse.io/cartoteam/story/108441/redirect-data-library-to-spatial-data-catalog
- [x] Redirection
- [ ] Removal

### CODE REVIEW

**Comment by VictorVelarde** [comment]
I'm gonna rebase master and make a new deployment to staging

**Comment by VictorVelarde** [comment]
Staging at https://rm-data-library-gallery.carto-staging.com

**Comment by VictorVelarde** [comment]
This is a removal of a page we are already not displaying, the 'good old' data library. Most of the removal is frontend, but some ruby is also deleted.

**Review by VictorVelarde — APPROVED** [review]
LGTM to me. Let's have also a quick review of the removal from backend before deploying

**Review by thedae — APPROVED** [review]
LGTM!

**Pull request merged**
