### PR TITLE
Fixed mobile apps form app_type input if it can't be changed

### LINKED ISSUE #9376: Sending app_type to controller if it can't be changed fails in mobile apps form
That's it.

cc @javitonino @csobier

### PR DESCRIPTION
**Pull request by MariaCheca**
Fixes #9376

Set the input to `disabled` in case it cannot be changed, so it won't be sent to the controller.

CR @javitonino

### CODE REVIEW

**Comment by javitonino** [comment]
Does this change the form appearance?

Also, now that we are at it, better to also do it for platform.

**Comment by MariaCheca** [comment]
The form design remains as it was. And it's not necessary change it for platform, as it has already logic to set it as disabled in those cases.

**Comment by javitonino** [comment]
:+1:, ship it then!

**Comment by MariaCheca** [comment]
✨

**Pull request merged**
