### PR TITLE
Removing hardcoded private_maps_enabled check closes CartoDB/cartodb-central#627

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes CartoDB/cartodb-central#627. @Kartones @iriberri CR this, please.

### CODE REVIEW

**Comment by Kartones** [comment]
:+1:

**Comment by juanignaciosl** [comment]
Uhm, this has failed because of an explicit test. @rafatower , you added that at a9f501b43, could you CR this as well? If you agree I'll change tests as well. I've checked private maps and datasets price plans configuration match pricing page.

**Comment by rafatower** [comment]
I'm ok with the changes but you understand that a code review cannot guarantee the "expected behavior" in this case :-)

**Comment by juanignaciosl** [comment]
Sure :-) I've checked plan data vs. that code as your comment suggested, It Should Work™

**Pull request merged**
