### PR TITLE
Allows to specify a custom value in the select views

### LINKED ISSUE #8759: Custom value is missing from the dropdown and needed for example in geocoding analysis
screen shot 2016-07-11 at 17 40 36

### PR DESCRIPTION
**Pull request by javierarce**
See description of the ticket #8759

animation

Here's how to use it:

```js
      country: {
        type: 'Select',
        options: this._columnOptions.filterByType('string'),
        title: _t('editor.layers.analysis-form.country'),
        help: _t('editor.layers.analysis-form.country-help'),
        validators: this._getFieldValidator('country'),
        editorAttrs: {
          showSearch: true,
          allowFreeTextInput: true
        }
      },
```

CR: @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
If we show the "value" added before, I would display it with something especial like `"Italy"`, what do you think?

**Comment by saleiva** [comment]
I'd just Add quotes " ". so we keep readability

**Comment by saleiva** [comment]
BTW @javierarce this looks so goodo

**Comment by xavijam** [comment]
:es:, just the quotes thing.

**Comment by javierarce** [comment]
Like this, right?

screen shot 2016-07-12 at 17 45 20

**Comment by xavijam** [comment]
Yeah!

**Pull request merged**
