### PR TITLE
Updates texts for the instagram connector

### PR DESCRIPTION
**Pull request by javierarce**
Updates texts for the instagram connector based on the service_name.

Proposed text changes: https://github.com/CartoDB/cartodb/issues/3258

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3114/))

**Comment by javierarce** [comment]
@viddo: can you have a look, please?

**Comment by viddo** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3120/))

**Pull request merged**
