### PR TITLE
Redirect to login if there is an error

### LINKED ISSUE #13277: Redirect to login if the user is not logged in static pages
Static pages where the user has to be logged in must handle redirection to the login page, otherwise static pages will fail when serving them through Nginx.

### PR DESCRIPTION
**Pull request by elenatorro**
This PR fixes #13277.

It is necessary to redirect the user to the login page if there is an error, otherwise it won't work in static pages served by Nginx (https://github.com/CartoDB/cartodb-platform/issues/3798).

### CODE REVIEW

**Comment by nobuti** [comment]
This won't work with password protected maps. In that scenario, we wait for the error in order to show the password form.

**Comment by elenatorro** [comment]
retest this please

**Comment by juanignaciosl** [comment]
^ the GitHub notifier failed because of the downtime, but backend tests passed.

**Comment by nobuti** [comment]
Working fine with the default platform branch. Next, I'll test it with nginx changes.

**Comment by nobuti** [comment]
The only thing I found is not related with the code related with this PR. Trying to login from the superadmin returns a nginx error. Other than that it works 💅 .

**Comment by nobuti** [comment]
🚀

**Pull request merged**
