### PR TITLE
Filters

### LINKED ISSUE #12386: Get back the special measurements dropdown with the possibility of filter by category
It was initially created [here](https://github.com/CartoDB/cartodb/issues/11618), and then changed again to a normal dropdown filtered in the client. So, finally, we have decided to get back to the first solution and use "backend filtering" using DO queries. That means we will need help in order to create the "search-as-you-type" functionality with backend requests. cc @CartoDB/builder-backend 

screen shot 2017-02-23 at 10 25 01

- Step 1 (measurament):
screen shot 2017-02-23 at 10 25 29

- Step 2 (segment):
screen shot 2017-02-23 at 10 25 33

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #12386 #12388.

### CODE REVIEW

**Comment by nobuti** [comment]
Implementation of https://github.com/CartoDB/cartodb-management/issues/4967#issuecomment-311906816 is still pending.

**Comment by xavijam** [comment]
There is a small problem, GIF:

bug-filters

**Comment by xavijam** [comment]
Also, this is a question, I feel, for @ethervoid. After selecting two filters, the results list is empty, but selecting only one the results appear correctly.

filters-back

**Comment by nobuti** [comment]
Back to development :female_detective:

**Comment by kevin-reilly** [comment]
When I change the Boundary level on my map, the screen "jumps."

jumping

**Comment by nobuti** [comment]
@kevin-reilly that's an issue with the scroll component we are using.
@xavijam both issues are fixed. 🚀  to ruis.

**Pull request merged**
