### PR TITLE
10767 move preview layers into view

### LINKED ISSUE #10767: Move `preview_layers` into `view` for named map templates
Docs were wrong and I followed them blindly!

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #10767

Please CR @juanignaciosl

### CODE REVIEW

**Comment by gfiorav** [comment]
The old mechanism (wrapping queries via placeholders) still works and is still in place both here and in the Maps API, that's why it worked and slipped under the radar 🙈

**Comment by gfiorav** [comment]
Hey @juanignaciosl, back in the day I didn't send layer ids in the template since it was an optional param according to [the specification](https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.5.0.md) (and still is). It turns out that it's mandatory if you `preview_layers` visibility to work, as it matches layer for visibility via index or id.

Could you have a look? 


DISCLAIMER: I've added a `options` variable because the inline was 120+ characters long 😛

**Comment by gfiorav** [comment]
@juanignaciosl I haven't touched `dataviews` at all. Do you fear that the Maps API is doing something funky with layer ids in options? I'll check for sure, but I sense some knowledge I'd like to have in that suggestion 😛

**Comment by juanignaciosl** [comment]
Yes, sorry about not explaining myself. In the past I've seen using it to match layers and widgets. I'm 99% sure that it will work, but it deserves a simple test.

**Comment by gfiorav** [comment]
Just to be clear: you use the named map template to match layers to widgets?

**Comment by juanignaciosl** [comment]
I'm almost sure that it's not used. I just suggested a simple test, not a big deal. I'm sorry if it's been misleading.

**Comment by gfiorav** [comment]
Forgot to update the tests, btw!

**Pull request merged**
