### PR TITLE
sessions: better google button

### PR DESCRIPTION
**Pull request by matallo**
as I removed the old view the google button was still with the old style

from
screen shot 2015-07-01 at 15 47 18

to
screen shot 2015-07-01 at 15 47 57

CR @juanignaciosl

### CODE REVIEW

**Comment by juanignaciosl** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4665/))

**Comment by matallo** [comment]
retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4668/))

**Pull request merged**
