### PR TITLE
Trending maps report email redesign

### LINKED ISSUE #9384: Trending maps report email body missing
screen shot 2016-08-10 at 10 24 12

### PR DESCRIPTION
**Pull request by MariaCheca**
Closes #9384

screen shot 2016-08-10 at 10 56 30

CR @matallo cc @xavijam

### CODE REVIEW

**Comment by matallo** [comment]
suggestion, what about adding the twitter card? (a la "your map is trending")

**Comment by MariaCheca** [comment]
What do you think, @xavijam? Do we include an static picture of the map to complete the info?

**Comment by xavijam** [comment]
I feel it is a bit crazy, because it could contain 50 images. Imagine my pending mobile data network after opening this kind of email 😱 .

**Comment by xavijam** [comment]
:+1:

**Comment by MariaCheca** [comment]
Hum, maybe you're right, so better keep it as it is :)

**Comment by matallo** [comment]
go on

**Comment by MariaCheca** [comment]
✨

**Pull request merged**
