### PR TITLE
404: content edits

### PR DESCRIPTION
**Pull request by matallo**
changes the literal in the title meta according to the title in the page

> WE ARE SORRY BUT IT SEEMS THE PAGE YOU'RE LOOKING FOR DOESN'T EXIST

/cc @CartoDB/frontend @zenitraM

### CODE REVIEW

**Comment by javierarce** [comment]
This PR just contains 1 deletion. Is it right?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2007/))

**Comment by matallo** [comment]
@javierarce indeed, as it is a minified version of the page 1 addition, 1 deletion :(

**Comment by javierarce** [comment]
Ok, well, it's a bit difficult to review, but I see that there's the string "We are sorry but it seems the page you're looking for doesn't exist" in there, so for me :+1:

**Comment by Kartones** [comment]
+1

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2017/))

**Pull request merged**
