### PR TITLE
Updated dependencies.

### PR DESCRIPTION
**Pull request by nobuti**
This PR implements #11838.

It updates cartodb.js to bring https://github.com/CartoDB/cartodb.js/pull/1623

### CODE REVIEW

**Comment by matallo** [comment]
not really sure if this is related but the widget won't activate until you interact with the map, i.e. click zoom controls

once the map works normally, if you enable autostyle from editor view, when disabling in the embed it would still keep the autostyle style, you have to check and uncheck again

autostyle

if you reload in the layers list with autostyle enabled, there seems to be an error

pageshot of untitled map 2 carto 2017-04-02-1134 57
 
I made sure I did a clean `npm install`

**Comment by nobuti** [comment]
About the first point, there is an open issue already to fix it.
I think the layer list issue is not linked with the changes deployed here, they only related with the named_map template, but I'll check it out.

**Comment by matallo** [comment]
I'm still experiencing the same issues with "matatagoog02" user in staging :(

even worse, having the autostyling ON on the first load the tiles loaded are not styled, this works once you interact with the map though

**Comment by xavijam** [comment]
Take into account also this issue in CartoDB.js https://github.com/CartoDB/cartodb.js/issues/1610.

**Comment by matallo** [comment]
oh, if both the initialization and check/uncheck are known and reported issues, then it'd be good to go

**Comment by xavijam** [comment]
I feel it is related with the issue described above (almost 100% sure).

**Comment by nobuti** [comment]
I'm looking into the check/uncheck thing.

**Comment by nobuti** [comment]
As far I can see, when the dataview fails requesting data, deep-insights fails generating the styles for the autostyle, because the dataview has no data:

```
marker-fill: ramp([type_store], (), ());  
```
screen shot 2017-04-18 at 15 38 57

But even the request to the maps api fails, the style is set into the `initialState` attribute, so if the user disable widget's autostyle, then it tries to set this attribute again, without success. 

Not sure if we could check the styles validity before use them @xavijam.

**Comment by xavijam** [comment]
Yeah, I understand. This is a different problem than the thing we want to solve. I'd open a ticket in deep-insights with this problem.

**Comment by xavijam** [comment]
Already talked with @nobuti, it is a problem we have already @matallo. If happens in the embed and in builder. If you move the map to the place where there is data, everything will work as expected.

**Comment by nobuti** [comment]
Both issues should be fixed in DI. Heading ded03.

**Comment by nobuti** [comment]
User `nobuti-ded03` just in case.

**Comment by ivanmalagon** [comment]
Acceptance passed.

- The check / uncheck issue in embed view doesn't happen anymore.

- The error while reloading the Builder view doesn't happen anymore.

- Still having issues with widgets not being initialised until we interact with the map. So a layer with autostyle doesn't show the proper colors until we move / zoom the map. Then, the interaction behaves as expected. This is going to be tackled at [https://github.com/CartoDB/cartodb.js/issues/1610](https://github.com/CartoDB/cartodb.js/issues/1610)

**Comment by ivanmalagon** [comment]
Deployed to production.

**Pull request merged**
