### PR TITLE
Fixes connect with lines animation description

### LINKED ISSUE #10354: Connect with lines text is a placeholder now
When looking at the analysis details it shows 
'analyses-onboarding.line-to-single-point.description'

### PR DESCRIPTION
**Pull request by javierarce**
Fixes #10354

screen shot 2016-11-04 at 10 33 04

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam

**Comment by xavijam** [comment]
Could you add the animation in the description?

**Comment by javierarce** [comment]
👌

**Comment by xavijam** [comment]
😂  that's not a gif! but it is ok 💋  🇪🇸

**Comment by javierarce** [comment]
Why do you want a gif?

**Comment by xavijam** [comment]
Jur, sorry, I don't know why I expected a change in the animation. :(, sorry.

**Comment by javierarce** [comment]
It's ok! :)

**Pull request merged**
