### PR TITLE
Provide a meaningful error when import fails because of stament timeout

### LINKED ISSUE #1678: Provide a meaningful error when import fails because of stament timeout
When importing a raster or any other large file, if there is a problem with statement timeouts we say an unexpected problem had occurred, but we know what happened. We should provide a text saying:

"There is been a problem importing your file due to the time is been taking to process it. Please try again and contact us if the problem persist."

As discussed with @Kartones

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #1678, by checking statement timeout errors upon import (or table registering) and providing a new feedback message.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1456/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1457/))

**Comment by Kartones** [comment]
@rafatower CR please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1465/))

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
