### PR TITLE
Updated styles for Sync Interval Dialog

### LINKED ISSUE #12145: Dashboard "sync options" modal needs a facelift 💄 (old styles)
### Steps to Reproduce
1. Create a sync from any url (not from data library)
2. Go to the dashboard, dataset listing
3. Click on the sync icon (small circle to the top-right of the geometry type icon)

### Current Result

screenshot_20170517_155155

### Expected result
Something pretty 💖 

cc @xavijam

### PR DESCRIPTION
**Pull request by rjimenezda**
Fix #12145 

I had to change the radio buttons markdown a bit, and took the opportunity to make them accessible ( id / for ).

I also corrected a title color in the privacy settings dialog

Before:
screen shot 2017-06-06 at 12 45 13

After:
screen shot 2017-06-06 at 12 45 03

### CODE REVIEW

**Comment by rubenmoya** [comment]
So pretty! 💅 

Let's go to deploy!

**Comment by rubenmoya** [comment]
In production 🚀

**Comment by xavijam** [comment]
Hey guys, this is not the styles we have right now for that dialog.

screen shot 2017-06-08 at 11 31 02

Have you checked it with the sync options in the dataset/builder view?

**Comment by rjimenezda** [comment]
Oh, I assumed it was 'use correct typeface / radio buttons'. My bad.

**Comment by xavijam** [comment]
It is fine, don't worry. But yeah, we needed the new styles + the new "look&feel".

**Comment by rubenmoya** [comment]
My bad too, I just checked the typeface / radio buttons in acceptance.

**Pull request merged**
