### PR TITLE
Removes rendering binding so it doesn't get fired every time a map is removed

### PR DESCRIPTION
**Pull request by javierarce**
See original ticket to understand the problem: https://github.com/CartoDB/cartodb/issues/2921

This is what it seems to be happening: when several maps are removed on a batch in the new dashboard, the [render method]( https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_dashboard/list_view.js#L32) of the list view is called once per visualization. Maps that are going to be removed are rendered, but since the method that loads the vizjson to draw the preview is asynchronous, it can happen that we attempt to create a preview of a vizjson that doesn't exist anymore.

Since we are refreshing the collection when the removal of all the elements is finished, we don't need to bind the 'remove' event in the collection.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2746/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2760/))

**Comment by javierarce** [comment]
@viddo or @xavijam: can you review this fix, please?

**Comment by xavijam** [comment]
Don't we need a collection.fetch when operation is complete?
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_dashboard/filters_view.js#L200

**Comment by javierarce** [comment]
I'm not sure. We are doing this instead:  https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_dashboard/dialogs/delete_items_view.js#L35

**Comment by xavijam** [comment]
Yep, that is fine, but when dialog is closed and operation is completed, we need to "reload" the collection. "remove" bind did that, but we have (correctly) removed it preventing doing it as many times as items we wanted to delete.

**Comment by javierarce** [comment]
Ok, after a bit of research, I saw that we were already binding the remove event here: https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_dashboard/content_controller_view.js#L28

That lines calls the `_onDataChange` method that triggers a fetch of the collection:

https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_dashboard/content_controller_view.js#L253

**Comment by xavijam** [comment]
In that case, we have to remove that bind as well, if not will be fired as many times as items user deletes. And I'd make a collection.fetch() when delete items operation is completed in ```filters_view.js``` as I mentioned before.

**Comment by javierarce** [comment]
Ok!

**Comment by javierarce** [comment]
@xavijam: have a look to the changes, please.

**Comment by xavijam** [comment]
Smell so good :)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2775/))

**Pull request merged**
