### PR TITLE
Update aws s3 gem

### PR DESCRIPTION
**Pull request by juanignaciosl**
Needed for CartoDB/tech-ops/issues/463 (see [comment](https://github.com/CartoDB/tech-ops/issues/463#issuecomment-375763447)).

👁 this requires configuration change.

### CODE REVIEW

**Comment by amartinj** [comment]
🔴 DO NOT MERGE 🔴  until https://github.com/CartoDB/cartodb-platform/pull/4219 is deployed

**Comment by amartinj** [comment]
Acceptance: 💚 

I've tested both this PR and [the config one](CartoDB/cartodb-platform#4219) together in staging. It works just fine. Added assets, exports and imports.

**Comment by juanignaciosl** [comment]
CartoDB/cartodb-platform/pull/4219 has been merged. I will deploy after some last tests. cc @javitonino

**Comment by javitonino** [comment]
Have you tested both user assets (e.g: avatar/map marker) and organization assets(map markers configured in org settings page)?

**Comment by juanignaciosl** [comment]
I did. I'll do one last test of this when staging environment is ready with the updated configuration.

**Comment by juanignaciosl** [comment]
@javitonino tested again with a brand new image containing the required attribute. I'll deploy this tomorrow early morning, ok?

**Pull request merged**
