### PR TITLE
Update deep-insights dependency

### PR DESCRIPTION
**Pull request by ivanmalagon**
Related to https://github.com/CartoDB/cartodb/issues/12576

This PR implements applying the filter in time-series widgets (no animated) when loading the map.

**Acceptance**

1. In Builder, create a non animated time-series widget.
2. Filter it. Select a range.
3. Publish the map.
4. Check that if we refresh Builder, the filter is correctly loaded and applied.
5. Open the embed page and check that the filter is correctly loaded and applied.
6. Please, play with the range filter. Destroy the widget, create it again... try to break things.

### CODE REVIEW

**Comment by nobuti** [comment]
I found an issue. When filtering works like a charm, but if you clear the filter and reload the browser, the timeseries still is shown filtered. Also, if you change the zoom, the filter is invalidated properly. This doesn't happen with a simple map panning.

timeseries-filter-clear-reload

**Comment by nobuti** [comment]
Back to development.

**Comment by ivanmalagon** [comment]
While doing another thing, we've found the reason of why this was not implemented before.

The state of the map is not correctly set when dealing with time-series. Let me ellaborate:
- When you apply a filter, the maps get instantiated with a filter. You can see the query parameter in the request:
`filters:{"dataviews":{"1923c504-5bae-4b29-b98d-5459e65f1c56":{"min":1192.8,"max":2982}}}`
- Then, if you refresh, you can see in the global object `stateJSON` that is has info for the widget, with those `min` and `max` properties. That tells us that the widget has an initial state and apply the filter.
- Then you clean the filter. The maps gets correctly instantiated, there is no `filters` property in the request.
- But if you refresh the page, the `stateJSON` still has the `min` and `max` properties for the time-series widgets. IT SHOULD NOT HAVE THAT because we've instantiated the map with no filters.

I don't know who is responsible for this, if backend or maps API or us. But I'm sure that's the problem that you found.

**Comment by nobuti** [comment]
Fixed the issue in https://github.com/CartoDB/deep-insights.js/pull/571/commits/4899296aa520b107dabc8f0191a7c0b650c8f338

**Pull request merged**
