### PR TITLE
Force to generate https URLs for assets

### PR DESCRIPTION
**Pull request by javitonino**
Towards fixing #6904, but a cleanup rake will need to be run afterwards.

### CODE REVIEW

**Comment by javitonino** [comment]
Please CR @juanignaciosl. Cannot test in staging very well, as in staging it always generates https URLs anyway (maybe something in the bucket configuration). I testes that it doesn't break anything, but not if this actually does what it's supposed to do. It should according to the AWS source/docs.

**Comment by juanignaciosl** [comment]
LGTM. You might want to take a look at `DataRepository::Filesystem::S3::Backend` as well, which also uses that.

**Comment by javitonino** [comment]
I think that one is not in actual use (it is used internally by S3Uploader, but that doesn't appear to be called from anywhere in the code, barring some specs). I changed it anyway just in case, but creating an issue to check if this is actually dead code.

**Comment by juanignaciosl** [comment]
Meh, you could've merged yours before, it certainly looks like dead code. Nice, nevertheless :-)

**Pull request merged**
