### PR TITLE
[DONT MERGE] No longer create the schema_triggers extension

### PR DESCRIPTION
**Pull request by zenitraM**
This drops :bomb: the need for schema_triggers extension.

This will probably fail specs until https://github.com/CartoDB/cartodb-postgresql/pull/190 is merged, released and the config on the app changed to install that version.

cc @rafatower

### CODE REVIEW

**Comment by rafatower** [comment]
:+1:

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by Cartofante** [comment]
Sure!

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Comment by zenitraM** [comment]
retest this please

**Pull request merged**
