### PR TITLE
scrub Rollbar data

### PR DESCRIPTION
**Pull request by alrocar**
https://github.com/CartoDB/cartodb-central/issues/2244

Deployment [plan](https://github.com/CartoDB/cartodb-central/issues/2244#issuecomment-627472662)

### CODE REVIEW

**Comment by alrocar** [comment]
cc. @skgsergio

**Comment by alrocar** [comment]
Changing the approach to what @amiedes suggested [here](https://github.com/CartoDB/cartodb-central/pull/2797#pullrequestreview-410656386)

**Comment by amiedes** [comment]
Acceptance ✅ 

You can see the result in this Rollbar test: https://rollbar.com/carto/CartoDB/items/41439/occurrences/123358243588/

Just a comment: should we remove also `auth_token`, `enable_account_token`, `last_password_change_date`, `password_reset_sent_at`?

(feel free to merge it)

**Comment by alrocar** [comment]
> Just a comment: should we remove also auth_token, enable_account_token, last_password_change_date, password_reset_sent_at?

good catch, let me remove those before deploying.

I'm assigning the PR to me

**Pull request merged**
