### PR TITLE
Upgrade to google-client-api 0.28.4

### PR DESCRIPTION
**Pull request by ethervoid**
Related #14696 

We need to upgrade it because it fails with ruby 2.4.x

### CODE REVIEW

**Comment by ethervoid** [comment]
Don't be shy, ask for all changes needed. I've done it in a rush but that
is not excuse to have it cleaner or improved

**Comment by gonzaloriestra** [comment]
I've tested it in the dedicated instance you have created, but I couldn't import any file from 2 different Google accounts, while those files do work in production.

It says: `Unknown (99999). Sorry, something went wrong and we're not sure what. Try uploading your file again, or contact us and we'll try to help you quickly.`

https://rollbar.com/carto/CartoDB/items/8/

**Comment by gonzaloriestra** [comment]
Acceptance:

- [x] Drive, Box, Dropbox and ArcGIS connectors (connection, file listing, importing and revoke)
- [x] CSV, XLS, SHP and Zip file types with Drive
- [x] Listing of Drive account with more than 440 files (limited to that number)
- [x] Shared files in Drive
- [ ] Synchronizations
- [ ] Repeat the tests using ruby 2.2 to check backward compatibility

**Comment by ethervoid** [comment]
@gonzaloriestra I didn't answer properly to the test part. We can't have tests because this is a third party library use so we should test the integration but for that, we need to have an oauth app + authentication...and that is going to be open in the repository so...

**Comment by jgoizueta** [comment]
I've been testing this branch with Ruby 2.2 in a dedicated staging host.

Everything's fine, except we'll need to wait for an hour to see if the synchronization updates correctly.

- [x] Drive, Box, Dropbox and ArcGIS connectors (connection, file listing, importing and revoke)
- [x] CSV, XLS, SHP and Zip file types with Drive
- [x] Listing of Drive account with more than 440 files (limited to that number)
- [x] Shared files in Drive
- [x] Single and multilayer imports
- [ ] Synchronizations

**Comment by jgoizueta** [comment]
Synchronizations update correctly

**Pull request merged**
