### PR TITLE
Add a couple of indexes for layers

### PR DESCRIPTION
**Pull request by lbosque**
@rafatower please review

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1303/))

**Comment by rafatower** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1389/))

**Comment by rafatower** [comment]
I'm gonna test this in staging, merge and deploy to production as requested by santana

**Pull request merged**
