### PR TITLE
improved cache system to invalidate the local cache when a visualization...

### PR DESCRIPTION
**Pull request by javisantana**
... is added or removed (or changed)

also remove backbone instrumentation (not actually used)

The way it works:

- a model uses this.sync = cachedSync(SUBROGATE_KEY) (A)
- subrogateKey: [SUBROGATE_KEY] array is set in another model (B)
- model A is fetch, it's cached marked with SUBROGATE_KEY.
- when an instance of model B is created, removed or changed in the server all the objects cached with SUBROGATE_KEY are removed.

In cartodb case:

- visualizations are fetch using cachedSync and stored with subrogate key 'vis'
- visualization and table models have subrogateKey: 'vis' so everytime you change something the cache is invalidated

cc @viddo

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2998/))

**Comment by viddo** [comment]
:+1:

**Comment by viddo** [comment]
The only thing that got me really stuck was the word "subrogate", which I though was a typo first (instead of surrogate), but since it's a real word (hey I learned something new today) I guess it is used on purpose?

**Comment by javisantana** [comment]
it's a typo :dancer:

**Comment by viddo** [comment]
Aha, same goes for `invalidateSubgorateKeys` then, right?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3001/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3003/))

**Comment by javisantana** [comment]
cc @xavijam

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3054/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3057/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3063/))

**Pull request merged**
