### PR TITLE
Fixing problem when an auto-styled polygon layer adds a new analysis

### PR DESCRIPTION
**Pull request by xavijam**
Ticket: #11252.

**THINGS TO BE TESTED:**
First, steps to be done before:
- Create a map with a layer of each geometry (points, lines and polygons).
- Add a widget with auto-style for each layer.

I would try to make the thing fail with each type of geometry. So, in short:
- Add the layer.
- Create a widget with autostyle powers.
- Autostyle it.
- Add a new analysis, no matter the type.

Also, I'd test when user re-uses the autostyle styles, in order to check everything works as expected:
- Create a map with one layer (no matter which geometry).
- Add a widget with autostyle powers.
- Autostyle it.
- Go to the layer style.
- Change something in the style.
- Check that autostyle style now is removed.

Check that the autostyle state disappears and a non-desired legend appears in the map.

cc @nobuti

### CODE REVIEW

**Comment by xavijam** [comment]
Fixing them right now, thanks man.

**Comment by xavijam** [comment]
Tests passing 💋

**Comment by nobuti** [comment]
I found an error while testing with lines:

screen shot 2017-01-16 at 18 55 39

STR the error:
- Add a layer with lines.
- Add a category widget, and apply autostyle
- Add an analysis (in my case, a subsample)
- 💥

**Comment by xavijam** [comment]
Found, probably, the source of the problem, doing:

- Add a points layer.
- Add a histogram widget with autostyle powers.
- Go to style tab.
- Apply autostyle from the widget.
- Go to analysis tab.
- Apply an analysis.
- Thing fails.

**Comment by xavijam** [comment]
Deploying to ded03 again, seems like issues are gone, hopefully.

**Comment by xavijam** [comment]
Last problem reported (above ) was related to a problem with the object referencing.

**Comment by MariaCheca** [comment]
Acceptance passing 🌈

**Pull request merged**
