### PR TITLE
Pagination for new public dashboard maps/datasets

### LINKED ISSUE #2157: Pagination support for new public dashboard
screen shot 2015-02-10 at 12 17 45

Using same look&feel as on private dashboard

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2157 

- as [discussed in an earlier issue related to new public dashboard](https://github.com/CartoDB/cartodb/pull/2088#discussion_r24177229), use existing client-side code to render pagination to avoid duplicating the logic. only need minimal bootstrapping to set it up
- make the whole pagination item clickable (larger click surface)
- renamed `handle_a_href_on_click` => `navigate_through_router` to make its intention clearer

### CODE REVIEW

**Comment by viddo** [comment]
@xavijam Code review please, see comments in desc for some rationales related to the changes. Btw, append [`?w=0`](https://github.com/CartoDB/cartodb/pull/2164/files?w=0) to the URL not see unrelated whitespace changes

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1490/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1494/))

**Comment by xavijam** [comment]
When user requests a page that doesn't exist, text should change (go to the first page for example?) and paginator shouldn't appear.

screen shot 2015-02-10 at 16 20 57

**Comment by xavijam** [comment]
Commented, pages out of range, not a big issue (nice to have).

But :+1:

**Comment by viddo** [comment]
fixed the mentioned issues, figured it was better to have them done and over with while at it (see the last 3 commits)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1498/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1500/))

**Pull request merged**
