### PR TITLE
Embedded maps use embed.js instead of cdb.js

### LINKED ISSUE #3365: dont include editor code in embed
cdb.js should not be included in the embeds because it contains editor code, just create a new js

embed.js: [
    'vendor/assets/javascripts/cartodb.uncompressed.js',
    'vendor/assets/javascripts/cartodb.mod.torque.uncompressed.js',
    'vendor/assets/javascripts/cartodb.mod.odyssey.uncompressed.js',
    'lib/build/app_config.js'
]

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #3365.

@viddo, what do you think? Thanks!

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4214/))

**Comment by viddo** [comment]
Looks legit, from what I understand you basically split up app.js in two parts to not have to load it all for embeds, right?  

You should probably verify everything working on staging considering the changed files are used in a lot of places (editor, dashboard etc.) just in case, since we don't have integration/end-to-end testing just yet.

**Comment by javisantana** [comment]
do we need config.js in embeds?

**Comment by alonsogarciapablo** [comment]
@viddo: yes! that's exactly what this PR is about. I'm going to do some testing in staging.

@javisantana: we can probably get rid of it since it's "only" setting "assets_url" in cdb.config (which we don't use in embeds) and logging the version of cartodbui.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4222/))

**Comment by alonsogarciapablo** [comment]
I removed `config.js` from `embed.js`. I pushed to staging and everything seems to be working fine.

@rafatower I saw that we're caching embedded maps, so I guess this change will take some time (24 hours) to be working for every request. Is that correct? There's no rush for this so I don't think it's worth it invalidating the cache, but I wanted to have your input on this in case I'm missing something. Thanks!

**Comment by rafatower** [comment]
I'd increase the version of the embed keys so that you don't need to invalidate/wait 24h.

**Comment by alonsogarciapablo** [comment]
@rafatower Yes, that's what I was refering to. Is there already a convention for those numbers? Should I just bump it to version 2?

**Comment by rafatower** [comment]
Sorry, just bump it to '2' and that will settle the convention :)

**Comment by alonsogarciapablo** [comment]
[done!](https://github.com/CartoDB/cartodb/commit/a1a61ba9008aba365b1f8ed744f19ff394ebf021). Thanks!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4233/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4234/))

**Pull request merged**
