### PR TITLE
Ui fixes

### PR DESCRIPTION
**Pull request by piensaenpixel**
@xavijam could you take a look?

This PR Fix:
- Add Seconds in areas of influence analysis cc @saleiva 

- Missing active state in navigation
image
image

- line color cc @saleiva 
image

### CODE REVIEW

**Comment by xavijam** [comment]
Hey @piensaenpixel, check the line for sync tables when builder is dark.

**Comment by xavijam** [comment]
:es:

**Comment by piensaenpixel** [comment]
@xavijam when it's dark. It was ok :)

**Comment by saleiva** [comment]
🇯🇵

**Pull request merged**
