### PR TITLE
Upgrading cartodb PostgreSQL extension to 0.11.5

### PR DESCRIPTION
**Pull request by jgoizueta**
can someone @ethervoid @rafatower review this?

I'm preparing a new release of the cartodb extension because we missed @luisbosque 's changes

### CODE REVIEW

**Comment by ethervoid** [comment]
Looks good to me but I don't know exactly how this works so is better that @rafatower check this out

**Comment by jgoizueta** [comment]
retest this, please

**Comment by jgoizueta** [comment]
retest this, please

**Comment by rafatower** [comment]
There's something that worries me: the SHA5 hashes of the tags and the subrepo do not match:

https://github.com/CartoDB/cartodb-postgresql/releases

worth a review. Let me know if I can help

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
