### PR TITLE
Checking for config params fixing #2193

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones CR this, please.

@santisaez could you check those are the params you'd set? (see  app/controllers/admin/users_controller.rb `extra_*` methods).

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1805/))

**Comment by Kartones** [comment]
+1

PS: I want to build a small wrapper class to stop this madness of config handling and nulls and missing fields

**Comment by santisaez** [comment]
This is the default look, without setting `:geocoder` and `:datasource_search` keys in the config:

2382_default

`extra_geocodings_enabled()` is working as expected, if `geocoder` key is enabled the option appears:

2382_extras

But something is wrong with `extra_tweets_enabled()`, although the config keys are added it's not displaying the option, seems it's failing looking for config keys in the tree. 

This is the config for Twitter I'm currently using:

```ruby
  datasource_search:
    twitter_search:
      standard:
        auth_required:  true
        username:       'xxx'
        password:       'xxx'
        search_url:     'xxx'
        ratelimit_active:       true
        ratelimit_ttl:          4
        ratelimit_concurrency:  8
        ratelimit_wait_secs:    0.5
      customized_user_list: ['xxx']
      customized_orgs_list: ['xxx']
      entity_to_config_map: [ { twitter: 'twitter_conf'}, { xxx: 'xxx' } ]
      customized:
        twitter_conf:
          auth_required:  true
          username:       'xxx'
          password:       'xxx'
          search_url:     'xxx'
          ratelimit_active:       true
          ratelimit_ttl:          4
          ratelimit_concurrency:  8
          ratelimit_wait_secs:    0.5
        srogers_twitter_conf:
          auth_required:  true
          username:       'xxx'
          password:       'xxx'
          search_url:     'xxx'
          ratelimit_active:       true
          ratelimit_ttl:          4
          ratelimit_concurrency:  8
          ratelimit_wait_secs:    0.5
```

**Comment by juanignaciosl** [comment]
It works for me :-\

screen shot 2015-02-25 at 11 28 43

Twitter check checks not only for username key presence but also not empty value. For example, `username: ''` won't enable twitter. Could that be the problem?

**Comment by santisaez** [comment]
:+1: it's working!

Sorry it was an issue with a duplicated entry for `datasource_search` in my open-source deploy, it has been removed from the template to avoid more issues in the future ;-)

**Pull request merged**
