### PR TITLE
Publishing changes

### LINKED ISSUE #8528: First published and unpublished changes
1) When the map hasn't been published before the modal screen shows a message and the options to share are disabled.
image

<br><br>
2) When you have unpublished changes this text is shown next to the share button
image

cc/ @saleiva

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #8528.

share-publishing

I see one "problem". The pending changes are not persisted, right now they are tracked only in the current session, if the user reloads the browser, the pending changes get lost. I think that making a request with every change is too much, but...

cc @xavijam

### CODE REVIEW

**Comment by nobuti** [comment]
@saleiva @javisantana see my comment above

**Comment by xavijam** [comment]
Fine by me, but @saleiva and/or @javisantana I'd like some words from you.

**Comment by saleiva** [comment]
Open a ticket for after 7/7 and go with this. :)

**Comment by javisantana** [comment]
I'd use the typical pattern:

- save every X seconds if there are changes
- if the user is closing with pending changes tell him to wait or ask for confirmation

saving every single change is kind of killer but let see

Are we cancelling a previous request if is already working?

**Pull request merged**
