### PR TITLE
Fetching data in geocodeLatAndLng() and fixing test

### PR DESCRIPTION
**Pull request by Xatpy**
Ref. ticket [#2518](https://github.com/CartoDB/cartodb/issues/2518): **Geocoding by Lon/Lat doesn't refresh the table automatically**

The issue was that the table hadn't been fetched when it was georeferenced by Lon/Lat.

This PR also fixed that test (*should add lat and lon to the_geom if georeferenced by column*)

Demo-gif:
cdb_2518

### CODE REVIEW

**Comment by Xatpy** [comment]
Please, @viddo , could you check it?

**Comment by viddo** [comment]
:+1: don't forget to update NEWS and bump version

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2199/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2203/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2210/))

**Pull request merged**
