### PR TITLE
4223 detect report invalid imports without rows [NO MERGE]

### PR DESCRIPTION
**Pull request by ethervoid**
* [X] If an import finish but insert 0 rows because of encoding issues, return an error
* [X] Added metrics to measure how many `SHP` file we are importj g and what is the percent of error in every importation
* [X] Created a SHP helper
* [X] Added tests for SHP helper
* [X] Removed `SHAPE_ENCODING` from `ogr2ogr` because this parameter is used to recoding the SHP data

**This change fixes issue #4223**

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4918/))

**Comment by ethervoid** [comment]
This commit fixes issue #3266

**Comment by ethervoid** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4921/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4923/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4928/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4930/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4938/))

**Comment by ethervoid** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4939/))

**Comment by ethervoid** [comment]
I have to make a cleanup in this one

**Pull request closed without merging**
