### PR TITLE
Disable geocoding options (feature flags) and test

### PR DESCRIPTION
**Pull request by Xatpy**
This new branch and commit is related to this old [PR](https://github.com/CartoDB/cartodb/pull/1500/files?diff=split)
The reason is that there was a lot of conflicts because it was an old branch, so I decided to create a new one pulling from master.

it uses a [Feature Flag](https://github.com/Vizzuality/cartodb-management/wiki/Feature-Flags) called **georef_disabled**.

### CODE REVIEW

**Comment by Xatpy** [comment]
Please @javisantana , could you review it?

**Comment by Xatpy** [comment]
Clinker error, but in its log:
15:01:59 1512 specs in 78.063s.
15:01:59 >> 0 failures

**Comment by Xatpy** [comment]
retest this please

**Comment by xavijam** [comment]
subscribed!

**Comment by Xatpy** [comment]
retest this please

**Comment by javisantana** [comment]
:es:

**Pull request merged**
