### PR TITLE
4256 labels on top be

### PR DESCRIPTION
**Pull request by Kartones**
Closes #4323

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4739/))

**Comment by Kartones** [comment]
@alonsogarciapablo CR please. Except if some other related spec fails, it should be ready.

**Comment by Kartones** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4741/))

**Comment by alonsogarciapablo** [comment]
:+1:

**Pull request merged**
