### PR TITLE
Remove notifications feature flag

### PR DESCRIPTION
**Pull request by javitonino**
Part of #11947 

**Acceptance**
- [ ] Ensure that notifications work without the feature flag active:
  - [ ] Send a notification from org panel
  - [ ] Check that it is received by a user
  - [ ] Check that it can be marked as read (open/close the bell notification list)

**Deploy**
- Notify in https://github.com/CartoDB/docs/pull/1196, so the docs can be merged

### CODE REVIEW

**Comment by javitonino** [comment]
I did not find any instance of the feature flag in frontend. Maybe @matallo can tell us if he added such a check. Next time, let's use a less generic name than "notifications" for feature flags 🙏, it makes it easier to make sure you did not forget anything when removing it.

**Comment by matallo** [comment]
here's one occurence https://github.com/CartoDB/cartodb/blob/master/app/views/admin/shared/_org_subheader.html.erb#L26

**Comment by xavijam** [comment]
I feel there is no other place, so let's go! 💃

**Comment by javitonino** [comment]
Unblocking since the FF is unrestricted anyway (my previous reasoning was bogus).

**Pull request merged**
