### PR TITLE
Don't require password validation for SAML user deletion

### LINKED ISSUE #11240: Box deletion of SAML auto created users
### Context

Right now, if a user wants to delete her own account, she can't since the autogenerated password is never shown. I will now summarise the 2 approaches discussed to this problem:

1. A user shouldn't be able to delete her account. Only admin can do that from the appropriate panel. We substitute the "Delete my account" link with an explanatory message.
2. A user can delete her account without specifying a password (as it is with Google signings now).

@CartoDB/builder-backend

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #11240.

Acceptance:
- Try to delete a SAML account (by himself). It should work without prompting for password.
- Try to delete a Google login account (same).
- Try to delete a normal account. It should ask for password and fail with wrong password.

### CODE REVIEW

**Comment by javitonino** [comment]
I found two issues during acceptance that we may want to address during this PR.

1. After deleting a SAML account, the user is not logged out, so visiting any page in the dashboard will redirect to login, then to SAML IdP and then trigger account recreation. As a consequence, it is a quite easy to recreate an account after deleting it. I suggest adding a `cdb_logout` to the user deletion controller.
2. Not directly related to this PR. When deleting an account and failing to provide the correct password, the account page is rendered incorrectly. It should look like:

screenshot_20170116_134524

but it looks like:

screenshot_20170116_134508

Probably, there are some filter that load template variables that are not being ran.

What do you think @juanignaciosl? I think we should address 1 during this PR at least, and 2 if it's easy (otherwise we can open a new ticket for later, as it's minor). Leaving in acceptance until we decide.

**Comment by juanignaciosl** [comment]
1. [`Admin::UsersController#delete` already has a `cdb_logout`](https://github.com/CartoDB/cartodb/blob/4d9cde07597d0b08d0abff6043c0eb9ec5ffea02/app/controllers/admin/users_controller.rb#L123). The "redirect to login" behaviour is caused by the request to a private page that you explain. There's nothing else that we can do, IMHO. As auto creation must be there, it will happen as soon as the user tries to open any private page. That was my main concern about self user deletion in this context, indeed.
2. I'll address 2 while 1 is discussed 👍

**Comment by javitonino** [comment]
1. Took a look at it and saw that the issue is that `cdb_logout` doesn't logout from the IdP, so of course we don't fully logout (I thought it was handled by cdb_logout, but this makes sense). What about, if SAML is enabled, redirecting to the SAML logout instead. Something like:
```
cdb_logout
saml = Carto::SamlService.new(@user.organization)
if saml.enabled?
  return redirect_to(saml.sp_logout_request)
...
```

**Comment by juanignaciosl** [comment]
After a little internal debate, I'm testing to redirect to logout instead, so SAML is not leaked all over the application.

**Comment by MariaCheca** [comment]
CR 👍

**Comment by MariaCheca** [comment]
Acceptance passing 🇩🇰

**Pull request merged**
