### PR TITLE
Add sync modal to dashboard datasets listing

### LINKED ISSUE #4790: Clicking on the sync icon from the datasets view should open the sync table options modal
related with #4775

### PR DESCRIPTION
**Pull request by viddo**
Fixes #4790

Refactored sync view to take into account the table state is not always loaded (like on the dashboard view).

@javierarce pretty please review? cc @saleiva

### CODE REVIEW

**Comment by xavijam** [comment]
What happens when user changes sync interval? Item is re-rendered? Imagine if user removes sync state.

**Comment by javierarce** [comment]
:+1:  Sorry for the late review. LGTM.

**Comment by viddo** [comment]
@xavijam that is covered in https://github.com/CartoDB/cartodb/pull/5094/files#diff-d05ff59eadc68b7a7abcf0bd86047d5aR172, by refetching the (vis) model which re-renders the item

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
