### PR TITLE
Fix create-map map template icons being displaced

### PR DESCRIPTION
**Pull request by viddo**
Currently:
screen shot 2015-04-22 at 11 43 46

Fixes in Chrome + IE(10)
screen shot 2015-04-22 at 11 50 10
screen shot 2015-04-22 at 11 59 24

### CODE REVIEW

**Comment by viddo** [comment]
@xavijam

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
thanks

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3191/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3192/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3194/))

**Pull request merged**
