### PR TITLE
Organization seats limit reached email

### LINKED ISSUE #8936: Review organization seat limit reached email
screen shot 2016-07-18 at 12 00 19

Part of #8889.
cc @urbanphes

### PR DESCRIPTION
**Pull request by MariaCheca**
Closes #8936

screen shot 2016-08-08 at 17 15 47

CR @matallo

### CODE REVIEW

**Comment by matallo** [comment]
on emails I prefer break space than paragraphs but 👍

**Comment by MariaCheca** [comment]
OMG you just said that in the last email :____ Ok, I guess I could replace those `<p>` with `<br>` in another improvements PR for all emails redesigned.

**Comment by matallo** [comment]
haha, nothing to worry about, just personal preference after struggling with email markup

**Comment by MariaCheca** [comment]
That's why I would prefer to take your advise :P

**Comment by MariaCheca** [comment]
✨

**Pull request merged**
