### PR TITLE
Coverage for all tests

### PR DESCRIPTION
**Pull request by juanignaciosl**
Coverage for files not using spec_helper.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
@gfiorav CR this, please.

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by luisbosque** [comment]
retest this please

**Comment by gfiorav** [comment]
Ready to deliver :package:

**Pull request merged**
