### PR TITLE
🔥Period 🔥

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
This PR removes the period from this message:

Screenshot 2019-05-30 at 12 48 12

@kukukaka agree?

### CODE REVIEW

**Comment by kukukaka** [comment]
@vdiego ?

**Comment by vdiego** [comment]
not needed imo

**Comment by alonsogarciapablo** [comment]
Thank you both for your feedback on SUCH AN IMPORTANT THING! 😂

**Comment by vdiego** [comment]
These are tough choices :joy:

**Comment by alonsogarciapablo** [comment]
Retest this please

**Pull request merged**
