### PR TITLE
Start using CDB_TableMetadataTouch to upsert cdb_tablemetadata

### PR DESCRIPTION
**Pull request by rochoa**

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2015/))

**Comment by rochoa** [comment]
cc @javisantana @Kartones this is the long awaited "do not manipulate cdb_tablemetadata directly" patch. All users should be running 0.7.0 version of cartodb-postgresql by now so it's time to start using the touch method.

What do you think? :smile:

**Comment by Kartones** [comment]
for me is a YES, if something breaks we can always revert and would fail quickly so...

**Comment by javisantana** [comment]
:es: <3

**Pull request merged**
