### PR TITLE
Visualization stats endpoint

### LINKED ISSUE #3169: Move test suite describe 'GET /api/v1/viz/:id/stats'

### PR DESCRIPTION
**Pull request by juanignaciosl**
@rafatower CR, please. This closes #3169.

@javisantana [this](https://github.com/CartoDB/cartodb/compare/3169-describe_GET_api_v1_viz_id_stats?expand=1#diff-29edfe9aebf974e765602af4cddc7bedR23) is the only needed thing to enable the endpoint, isn't it?

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2986/))

**Comment by rafatower** [comment]
:+1:

**Comment by javisantana** [comment]
adding that is not going to work out of the box, you need to change stats model to support that

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2989/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3023/))

**Comment by rafatower** [comment]
In the end, is that endpoint used currently?

**Pull request merged**
