### PR TITLE
Changing the password of a password protected vis doesn't refresh the auth_tokens

### LINKED ISSUE #2969: Changing the password of a password protected vis doesn't refresh the auth_tokens
#### Steps to reproduce it

1. Create a password protected visualization.
2. Get the `auth_tokens` from the vizjson.
3. Change the password of the visualization.
4. Get the `auth_tokens` from the vizjson again.

#### Expected result

The `auth_tokens` should be different.

#### Actual result

The vizjson is not refreshed and the `auth_tokens` are the same.

--

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #2969

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3070/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3073/))

**Comment by Kartones** [comment]
@juanignaciosl CR please. Sorry for touching Vis backend but this is hurting us as cache doesn't gets invalidated and people think their Pass protected vis are broken

**Comment by juanignaciosl** [comment]
Ok, this change doesn't have to be propagated to new models yet.

**Pull request merged**
