### PR TITLE
Filter panel css

### PR DESCRIPTION
**Pull request by klibloomberg**
updated various css for changes in filter panel. 

@mbektas

### CODE REVIEW

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by mbektas** [comment]
@klibloomberg this is the wrong repo. You need to use https://github.com/bloomberg/cartodb

**Comment by mbektas** [comment]
@klibloomberg can you close this one?

**Comment by klibloomberg** [comment]
abandon PR

**Pull request closed without merging**
