### PR TITLE
Upgrade cartodb-postgresql extension version to 0.10.1

### PR DESCRIPTION
**Pull request by rafatower**
Quick review @rochoa . This includes these changes: https://github.com/CartoDB/cartodb-postgresql/commit/c2780773d25a4151d35cc922e8ed0a5c6d865b2c

thanks!

### CODE REVIEW

**Comment by rochoa** [comment]
:shipit:

**Comment by rafatower** [comment]
A bit dirty but I fixed the migration and updated `--force` the tag and this branch, see https://github.com/CartoDB/cartodb-postgresql/commit/0c14df5f89ad16f333284814c30969c1bc2525c0

I'll think of a test for this https://github.com/CartoDB/cartodb-postgresql/issues/94

**Comment by rafatower** [comment]
retest this please

**Comment by rafatower** [comment]
retest this please

**Pull request merged**
