### PR TITLE
Only send JS errors+stats in production [no merge]

### LINKED ISSUE #1892: Make sure mixpanel and trackJs works for dev/staging env
Related to #1890 we need a long-term solution for the problem with mixpanel and trackJs not being used for neither dev or staging environments, it has happened more than once that something (luckily not any important pages) fail due to these code paths are only reached in production.

Proposed solutions:
- Enable mixpanel and trackJs for staging at least, is possible to filter out dev/staging env data by some additional metadata?
- Unit test entry point, to cover cases of trackJs and Mixpanel are present.

Other ideas?

### PR DESCRIPTION
**Pull request by viddo**
Fixes #1892 

In addition to the minor code change:

**TrackJS:**
- Removed `trackAjaxFail: false` since trackJs lib yields a warning that property is not supported anyway
- Load trackJs on all environments (that has a token set in `app_config.yml`), but only send errors to trackJs if the config has `enabled` set to true, i.e.:
```haml
trackjs: 
  enabled: true
```

**For Mixpanel:**
- Always load mixpanel on all environments (that has a token set in `app_config.yml`)
- Per [Mixpanel's own proposal](https://mixpanel.com/help/questions/articles/can-i-exclude-myself-from-mixpanel-data) use a "dev/staging" token for non-production environments to not pollute statistics.

---

Will talk to devops about how to config changes for staging+production environments.

So, effectively we would catch errors at latest in staging, and for devs touching frontend should have the tokens in their dev env `app_config.yml` to catch errors even earlier.

**edit:** removed `Rails.env` usage to load TrackJS

### CODE REVIEW

**Comment by viddo** [comment]
@CartoDB/frontend sounds reasonable?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1319/))

**Comment by xavijam** [comment]
Sounds good dude :+1: :dancer:

**Comment by viddo** [comment]
@zenitraM @lbosque @santisaez do you have any objections or is there anything I might have overlooked? If everything is OK I would need help from you with the following two tasks:

1. set the production TrackJs token for staging's `app_config.yml`
2. create a ["dev token" for Mixpanel](https://mixpanel.com/help/questions/articles/can-i-exclude-myself-from-mixpanel-data) and set it for staging's `app_config.yml` (and pass the token to frontend@ mailing list so people

**Comment by javisantana** [comment]
for me it should send stats when we have config for that, doing things in function of rails env gave a lot of problems in the past

**Comment by javisantana** [comment]
please update news if needed and merge

**Comment by viddo** [comment]
Re: rails env that's totally reasonable :+1:, I'll make sure to fix it.

The reason why it have not been merged yet is because I need help from someone who has admin privileges to staging/production environments and mixpanel to do the necessary changes required by this PR (asked several occasions). I'll get back to this one as soon as I finished the other issues with higher priority related to the new dashboard.

Re: update NEWS, will do once this is ready to be merged.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1794/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1795/))

**Comment by viddo** [comment]
Based on feedback have done some additional changes. To be able to merge & release this branch I would need the following changes to `config/app_config.yml`:

For staging:
```
mixpanel:
   api_key: 'dev-api-key'
   api_secret: 'dev-api-secret'
   token: 'dev-token'
trackjs:
  customer: 'key-used-in-production'
  enabled: false
```

For production:
```haml
trackjs:
  enabled: true
```

Again, the "dev-*_" strings should be created through Mixpanel's dashboard. @matallo It have come to my attention that you might be able to help me with this?  ;)

For the config changes, can someone of Devops @santisaez @zenitraM @azamorano help me out tomorrow Fri to finish this off finally?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1796/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1807/))

**Pull request merged**
