### PR TITLE
Upgrade cartodb extension to v0.21.0

### PR DESCRIPTION
**Pull request by jgoizueta**
Update cartodb extension for some fixes

### CODE REVIEW

**Comment by jgoizueta** [comment]
uh, oh, why are the backend CI tests trying to delete a db named ""?

```
16:34:57 Creating user publicuser
16:34:57 Creating user tileuser
16:34:57 + sh runParallelTests.sh 12
16:34:57 rm: cannot remove 'parallel_tests': No such file or directory
16:34:57 # Speclist has been created
16:34:57 redis-server(17133): Operation not permitted
16:35:00 ERROR:  zero-length delimited identifier at or near """"
16:35:00 LINE 1: drop database ""
16:35:00                       ^
16:35:00 rm: cannot remove 'parallel_tests/users_databases_new.log': No such file or directory
16:35:00 ERROR:  zero-length delimited identifier at or near """"
16:35:00 LINE 1: drop database ""
16:35:00                       ^
16:35:00 rm: cannot remove 'parallel_tests/users_databases_new.log': No such file or directory
16:35:00 # Cleaner finished
16:35:00 rm: cannot remove 'config/database_*': No such file or directory
16:35:12 # Wrapper finished
```

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by jgoizueta** [comment]
Oh well, now the front tests fail too
```
09:05:34 Running "browserify:explore" (browserify) task
09:05:35 Warning: watch /home/ubuntu/workspace/CartoDB-PR-testing-frontend/package.json ENOSPC Use --force to continue.
```
No space on disk?

**Comment by jgoizueta** [comment]
Retest this, please.

**Comment by jgoizueta** [comment]
Retest this, please.

**Comment by skgsergio** [comment]
retest this please

**Comment by skgsergio** [comment]
Backend tests will fail due to PG10.

**Pull request merged**
