### PR TITLE
Hides header back arrow  

### PR DESCRIPTION
**Pull request by javierarce**
Original issue: #11138 

This ticket removes an arrow from the fill component form when styling by value:

screen shot 2017-02-17 at 09 54 15

With this change we'll prevent users to inadvertently go to the column list instead of going back to the list of categories.

### CODE REVIEW

**Comment by saleiva** [comment]
The idea was hiding the complete "row" so not only the arrow, but also the name of the column

**Comment by javierarce** [comment]
@saleiva maybe I'm missing something, but the original ticket says: "There should be only one back action to the list of categories." It's a bit ambiguous to me.

**Comment by javierarce** [comment]
@matallo I think in this case is not worth it.

**Comment by saleiva** [comment]
agree on that, I checked with the designs and yeah, the whole row should be removed. (sorry!)

**Comment by javierarce** [comment]
No problem!

**Pull request merged**
