### PR TITLE
Hiding 'Buy more seats"/"Upgrade your quota" if isn't SaaS

### PR DESCRIPTION
**Pull request by Xatpy**
Ticket [Ref.1957](https://github.com/CartoDB/cartodb/issues/1957) : **CartoDB editor: "buy more seats" not working in open-source edition**

I'm hiding *upgrade_url*.

Assuming that:
SaaS ==> account_host: ‘cartodb.com’ in app_config.yml

Preview:
screen shot 2015-02-25 at 19 17 08

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1941/))

**Comment by lbosque** [comment]
+1

**Comment by lbosque** [comment]
Like in the other similar PR I would just check if account_host is empty, but not force that its value is strictly 'cartodb.com'

**Comment by viddo** [comment]
Also need to make updates on new dashboard: screen shot 2015-03-04 at 11 11 48

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2094/))

**Comment by viddo** [comment]
Actually, while working on #2542 I think there's some overlap with this issue. If I understand the configuration correctly, `window.upgrade_url` is only available for SaaS so probably makes more sense to just check that rather than adding `account_host` var to pages, right? cc @lbosque

**Comment by Xatpy** [comment]
cc @javisantana

**Comment by Xatpy** [comment]
Closing this PR because it continues in [this 'general' one #2646](https://github.com/CartoDB/cartodb/pull/2646)

**Pull request closed without merging**
