### PR TITLE
Don't trigger changeSchema when schema is not set yet

### PR DESCRIPTION
**Pull request by xavijam**
Related ticket: #12299 .

When a new analysis is added, it was rendered twice because after creating that view, the analysis-form-model was triggering a [`changeSchema`](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-form-models/base-analysis-form-model.js#L126) event where the [`analysis-form-view`](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-form-view.js#L28) was listening it and doing a new render.

It is true that several analyses need to render again when, for example, a fetch has finished (example with [`georeference-analysis-form-model`](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-form-models/georeference-form-model.js#L32)).

The new idea is, don't trigger a `changeSchema` until it is initialized the first time. When it is set for the first time, we will trigger a `createSchema`.

@nobuti @rjimenezda

### CODE REVIEW

**Comment by rjimenezda** [comment]
I've setup a breakpoint to check how many renders of the analysis form view happen and these are the results:

| Analysis  | this branch | production  | Observations |
| ------------- | ------------- | ------------- | ------------- |
| Filter by layer  | 3 renders  | 3 renders  |  -  |
| Georeference  | 2 renders  | 2 renders  |  -  |
| Join Columns  | 3 renders  | 3 renders  |  -  |
| Intersect  | 2 renders  | 2 renders  |  -  |
| Areas of Influence  | 1 render  | 1 render  |  -  |
| Centroid  | 1 render  | 1 render  |  Aggregation checkbox causes render, weighted_by causes 2  |
| Convex Hull | 2 renders  | 2 renders  |  Method causes 2 renders, operation causes 1 |
| Filter by Column  | 2 renders  | 2 renders  |  Column causes 2 renders, some even more (featurecla causes 4!) |
| Filter in Polygons  | 2 renders  | 2 renders  |  -  |
| Connect with lines | 4 renders  | 4 renders  |  Sequential causes 2 on this branch, 1 on prod  |
| Subsampling | 1 render  | 1 render  | - |
| Clustering | 1 render  | 1 render  | - |
| Outliers | 2 renders  | 2 renders  | - |
| Trends | 2 renders  | 2 renders  | - |
| Find Nearest | 2 renders  | 2 renders  | Target causes 2 renders |

I wonder if I've done something wrong because I find it strange that both are exactly the same. I double checked and the code in staging is definitely the one from the branch. In any case, quite a cool table to have right?

**Comment by xavijam** [comment]
No changes? Let's not merge it then :(.

**Comment by xavijam** [comment]
And yes, nice table! 💃 .

**Comment by rjimenezda** [comment]
On production I do have DO enabled, but not on staging, I don't think that makes a difference 🤔 ?

**Pull request closed without merging**
