### PR TITLE
Saves the z-index position of the overlay

### PR DESCRIPTION
**Pull request by javierarce**
This PR fixes a bug that preventing saving the z-index position of the overlays. It also add missing specs to test the feature.

Original ticket: 3554-overlay-order

### CODE REVIEW

**Comment by javierarce** [comment]
@viddo: can you review this, please?

**Comment by viddo** [comment]
Looks legit :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5387/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5388/))

**Pull request merged**
