### PR TITLE
Disables the opacity selection for categories

### LINKED ISSUE #7667: [Fill component] Disable alpha option for categories

### PR DESCRIPTION
**Pull request by javierarce**
Since category ramps are just a list of opaque colors, the color picker shouldn't give the option to change the opacity. This PR does that.

This PR also sets the default opacity to 1 in case it's not defined.

screen shot 2016-06-06 at 13 20 25

Closes #7667

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam 
CR (design): @piensaenpixel

**Comment by xavijam** [comment]
Oh, ok! it is true we don't provide that option in the current editor, not sure if we should disable again in the new one... what do you think @urbanphes ?

**Comment by xavijam** [comment]
BTW, code looks good to me 👌

**Comment by javierarce** [comment]
retest this please

**Pull request merged**
