### PR TITLE
4503 fix failed georeferenced table no geometry

### PR DESCRIPTION
**Pull request by rafatower**
@Kartones or @ethervoid can you please review?

Basically this:
- adds a new log trace for internal geocoders, just in case.
- modifies the query used to copy results so that they are not overwritten if georef_status is not true.

(I fixed the failed tests. I checked all queries in local and some of them in staging so I'll merge & deploy as soon as checks lets me do so)

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5261/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5268/))

**Comment by rafatower** [comment]
retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5297/))

**Comment by ethervoid** [comment]
I've been documenting about this :D, interesting part. LGTM :+1:

**Comment by Kartones** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5313/))

**Pull request merged**
