### PR TITLE
Memoize visualization names taken by user in order to check name candidates

### PR DESCRIPTION
**Pull request by javitonino**
This should improve the situation in #11419 by memoizing temporary results. In map creation, locally, it reduces the time to create a visualization from 2600ms to 60ms, in an account with 300 visualizations (half of that are the data library), 40 of which are unnamed maps.

**Acceptance**
If you have a staging account with many maps, you can take measurements on map creation before and after this patch. Creating several maps named like "Untitled Map XX" (the default) makes the problem more obvious. This also affects visualizations renaming.

- [x] Create map, check that the generated map doesn't conflicts with any others
- [x] Try to rename a map to an existing name -> it should fail
- [x] Try to rename a map to a non-existent name -> it should suceed
- [x] All the previous operations should be quick (a couple of seconds).
- [x] Import a dataset.
- [x] Import the same dataset again.
- [x] Import a .carto
- [x] Import the same .carto again.
- [x] Create a dataset from a query.

### CODE REVIEW

**Comment by javierarce** [comment]
Finished acceptance. In general it seems to work ok (in term of speed, I noticed that creating an empty layer is quicker by a couple of seconds to production)

The only problem I've found is that importing a file (a .carto or a CSV, for example) creates maps with the same name:

screen shot 2017-02-06 at 18 12 03

Is this a deal breaker?

**Comment by juanignaciosl** [comment]
@javierarce how is it different from current behavior?

captura de pantalla 2017-02-07 a las 9 34 02

**Comment by javitonino** [comment]
Yeah, I would consider that a different ticket, maybe we are not checking for duplicate names in all places we should be (it appears we are missing the `.carto` importer). I'd deploy this and open a new ticket, agreed?

**Comment by juanignaciosl** [comment]
My screenshot is a consecutive .csv importing, unrelated to .carto then.

**Comment by javierarce** [comment]
@juanignaciosl yeah, it's like the current behaviour, I mentioned it because the PR talked about renaming and consecutive file upload and wanted to warn you before proceed with the merge.

**Comment by javierarce** [comment]
I open a ticket for the consecutive name issue: https://github.com/CartoDB/cartodb/issues/11472 Feel free to correct me or update the issue if you find is not accurate.

**Pull request merged**
