### PR TITLE
Fixed typo to show title

### LINKED ISSUE #6339: Deep insights map cards are not rendering the title
It is due to we are trying to get the name but api is providing the title.

### PR DESCRIPTION
**Pull request by acanimal**
reviewer @xavijam 

close #6339 

Change title attribute on template from `name` to `title`.

### CODE REVIEW

**Comment by xavijam** [comment]
:+1:

**Comment by acanimal** [comment]
@xavijam take a look again. I have added support for location hash into url.

**Comment by xavijam** [comment]
It can't work because you are not adding/referencing that vendor file in the grunt process. You should add it here:
https://github.com/CartoDB/cartodb/blob/master/lib/build/files/js_files.js#L393

**Comment by xavijam** [comment]
:dancer: :+1:

**Comment by javisantana** [comment]
There is a new library, don't forget to add the license to the licenses excel cc @gfiorav

**Comment by acanimal** [comment]
Done for the leaflet-hash.js library.

**Pull request merged**
