### PR TITLE
Migration adding viz->permissions FK

### PR DESCRIPTION
**Pull request by javitonino**
Part of #7013 

This is the migration to add the FK from visualization to permissions. It still does not drop the `entity_*` columns from permissions (that will come after we are sure it won't cause data loss).

Note that this automatically run the rake task to fix permissions. I think this is good to facilitate upgrades (I'm thinking OSS, on-premise and staging). There is a concern with the `auto_fix` parameter, as it will choose one arbitrary permission when multiple permissions exist for the same visualization. In practice, I have only seen this with a test user and both permissions were identical, so I think it is fine.

There is also a notice in the NEWS file (already merged) recommending to manually run the rake task before migration (without the `auto_fix` parameter).

### CODE REVIEW

**Comment by javitonino** [comment]
retest this, please

**Comment by javitonino** [comment]
The changes to fix the tests for this are already under review on #7059 (tested with and without this migration on top of the changes). I think we can start discussing it. CR please @juanignaciosl

**Comment by juanignaciosl** [comment]
:sparkles:

**Comment by javitonino** [comment]
Retest this, please

**Pull request merged**
