### PR TITLE
Fix logo alignment in small viewports

### PR DESCRIPTION
**Pull request by rubenmoya**
Related to: #13301 

The logo in small viewports wasn't aligned

screen shot 2017-12-28 at 09 01 33

Acceptance:

- Go to a map
- Reduce window size so breakpoints are applied
- The logo should be centered

### CODE REVIEW

**Comment by jesusbotella** [comment]
Changes look good!

I don't know if it is worth to change in this PR but we can remove some CSS styles by adding these styles to `.EditorMenu`

```css
    display: flex;
    flex-direction: column;
    align-items: center;
```

and remove the same styles in `.EditorMenu-logo` and `.EditorMenu-navigation`

**Comment by rubenmoya** [comment]
Great idea! Let me change it

**Comment by jesusbotella** [comment]
I merged master into this branch to resolve conflicts

**Comment by jesusbotella** [comment]
Deploying!

**Pull request merged**
