### PR TITLE
fix header link in account

### PR DESCRIPTION
**Pull request by matallo**
screen shot 2015-07-17 at 17 43 48
screen shot 2015-07-17 at 17 43 57

CR @saleiva

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5105/))

**Comment by matallo** [comment]
retest this, please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5117/))

**Comment by saleiva** [comment]
bump!

**Comment by matallo** [comment]
I take that as a :+1:

**Pull request merged**
