### PR TITLE
More from (user) caching issue in new public map page II

### LINKED ISSUE #3408: More from (user) caching issue in new public map page
branch `3408-public_map_fixes`
- [x] caching and not invalidating vis from "view more vis from..."
- [x] some visualizations are not displaying the datasets used (check saleiva's volcano one)

### PR DESCRIPTION
**Pull request by Kartones**
Closes #3408

### CODE REVIEW

**Comment by Kartones** [comment]
@javisantana CR please :trollface:

**Comment by javisantana** [comment]
:es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3384/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3388/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3391/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3392/))

**Pull request merged**
