### PR TITLE
New public map

### LINKED ISSUE #3120: Implement new public map page
cc @piensaenpixel @saleiva

### PR DESCRIPTION
**Pull request by xavijam**
Feature pull requested finally [here](https://github.com/CartoDB/cartodb/pull/3278).

screen shot 2015-04-15 at 18 44 43
---
screen shot 2015-04-15 at 18 44 54
---
screen shot 2015-04-15 at 18 48 08

- New dashboard style applied.
- Share buttons included.
  - Twitter share button would add owner twitter name if it is present.
- Fullscreen map button is hidden by default (it is already present in the map info).
- Mobile layout ready.
  - If device is a mobile, map will take up almost the device height screen. Only a small space showing the first sentence of the title (if it has more than one line).
- Not possible to edit Disqus styles :(.

Fixes #3120.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3042/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3047/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3048/))

**Comment by saleiva** [comment]
Logo should be shown without text. Only the square.

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
Finally this feature is gonna be managed in https://github.com/CartoDB/cartodb/pull/3278.

**Pull request closed without merging**
