### PR TITLE
[Dashboard] Add trial end date to personal30 account users

### PR DESCRIPTION
**Pull request by csubira**
https://github.com/CartoDB/product/issues/262

Assumptions I made:
- `upgraded_at` does not need to be checked because if the account is upgraded it should not be a `PERSONAL30` type.
_(Let me know if it is otherwise)_

### CODE REVIEW

**Comment by gonzaloriestra** [comment]
:heavy_check_mark: Acceptance OK!

Tested that it shows the right remaining days for `PERSONAL30`, `MAGELLAN` and others (not shown).

**Comment by gonzaloriestra** [comment]
However, I've realized that the `Add payment` button shown is not working. I think we should fix it before deploying this.

@csubira can you try to fix it in this PR or should I create a new issue?

**Comment by csubira** [comment]
No problem, I'll check it and fix it here (as it's part of the same block) Thanks for the heads up @gonzaloriestra!

**Comment by csubira** [comment]
_Add payment_ button fixed. FE part ready to be reviewed!

**Comment by gonzaloriestra** [comment]
:heavy_check_mark: Tested again and the button is working now

**Pull request merged**
