### PR TITLE
A set of functions that can be useful to explore metadata

### PR DESCRIPTION
**Pull request by rafatower**
I just found this useful for peeking into backups and thought about sharing. What do you think?

cc/ @Kartones @juanignaciosl @javisantana

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3777/))

**Comment by juanignaciosl** [comment]
For testing and debugging logic I use Rails console, so I don't see the point of having similar functions in the db, but if this is not intended for production and it's useful to you it's fine.

**Comment by Kartones** [comment]
I see them useful for debugging, Rails logic might fail and sometimes having callbacks is dangerous (e.g. deleting a visualization) so I also go inside the DB and see them nice to have for development, thanks!

**Comment by rafatower** [comment]
My motivation for writing the functions was to debug old metadata dumps and, call me paranoid, but did not want to plug it into rails console.If you find it useful I'll merge it here, otherwise they'll go into a personal public repo

**Comment by Kartones** [comment]
for me go ahead

**Pull request merged**
