### PR TITLE
New public dashboard current user + responsive design

### LINKED ISSUE #2200: Logged in use-cases for new public dashboard
If the user is logged in some interactive functionality should be available on the public pages too.

#### Scope:
- [x] Settings dropdown
  - almost-same as on private dashboard
-  [x] Likes
    - [x] render likes on datasets/maps items ("♥ xx") (also for non-logged-in cases actually)
    - [x] user able to click the "♥ xx" to like map/dataset (only if logged in, otherwise just read-only)
- [x] Responsive/look OK on smaller devices/screens
  - [x] apply visual look as defined in #1787 
  - [x] fix #2103 _In mobile layout, opening attribution "hides" user avatar in new public dashboard_
  - [x] align maps to left instead of center, fill up empty slots with placeholders

#### Proposed solution:
Visually the dropdown should look like:
screen shot 2015-02-12 at 11 33 15
..which is almost the same as on private dashboard so that view should be reusable

probably will need to do some change to the getAuthenticatedUsers (http://:username.cartodb.com/api/v1/get_authenticated_users) API endpoint too (e.g. to return email)

---
edit: Added responsive design to scope since have not been able to merge to master and continued to work in this branch due to the existing changes

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2200 

like

#### User settings
- In the end created new a dropdown view because the existing view and template would have been full of if-else clauses, better to keep them separated and keep the reusable parts to the styles.
- Don't replace signup if there is no logged in user

User settings for a normal user:
screen shot 2015-02-13 at 12 01 50

User settings for a organization user:
screen shot 2015-02-13 at 12 53 54
---

#### Likes:
- Reusing like view as on private dashboard
- Used same approach as for map card previews (i.e. grep for DOM elements using jQuery and create views accordingly, getting additional data from data-attributes), since it's not really motivated to create additional views that just adds overhead for now, minimal bootstrap necessary
- Read-only likes if not logged in (i.e. no hover effect and can not click)

#### Responsive design:

- Changing affected components to be built "mobile first", i.e. CSS styles are based on smallest device screen, and overriden for larger screens as necessary, according to the given visual mockups.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1582/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1583/))

**Comment by viddo** [comment]
@javisantana @xavijam this PR contains the API changes you asked about in the other PR yesterday, have a look and let's have a talk if necessary

**Comment by xavijam** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1588/))

**Comment by viddo** [comment]
@xavijam @saleiva @carlostallon @piensaenpixel please review again, finished "likes" stuff

**Comment by saleiva** [comment]
+1

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1590/))

**Comment by viddo** [comment]
@javierarce since you did the original like you might be the best one to review the changes I guess ;)

**Comment by xavijam** [comment]
Login link once we display a user is logged is useless. Learn link instead of Login? cc @saleiva 

screen shot 2015-02-13 at 17 55 55

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1592/))

**Comment by viddo** [comment]
agree with @xavijam, fixed as proposed in ff8fb7936facc69ff243730a8d4534fa7cefa763

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1594/))

**Comment by saleiva** [comment]
+1

**Comment by viddo** [comment]
bump, any code review feedback before releasing?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1632/))

**Comment by viddo** [comment]
FYI, since have not been able to release today I expanded the scope to include the responsive changes. Finished today and have deployed to staging rui01 so you can test it.

**Comment by xavijam** [comment]
cc @piensaenpixel

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1634/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1635/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1636/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1649/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1651/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1652/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1654/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1661/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1665/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1677/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1678/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1684/))

**Comment by viddo** [comment]
retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1690/))

**Comment by viddo** [comment]
Reviewed styles in person with @piensaenpixel, since all tests finally passed I'll merge & release promptly

**Pull request merged**
