### PR TITLE
Avoid change privacy when a layer is added or removed

### LINKED ISSUE #3057: Visualization 'password protected' loses its privacy if you add/remove a layer
How to reproduce:
1. Create a new visualization.
2. Add a new layer.
3. Change its visualization to **Password protected**
4. Set a password and click on *Save settings*
5. Check the embed map (Share->Embed it; Get a simple URL->Enter password)
6. Go back to the editor. Add (or remove) a new layer
7. Go to the last tag (where the protected visualization is), and reload the page.

What happenend:
- You can't view the visualization (or enter password). **404**
- Visualization has changed its privacy. From protected with password to protected with link.

Expected:
- Visualization continues with **protected password** privacy.

Gif:
bug_password_viz

### PR DESCRIPTION
**Pull request by xavijam**
I had the problem described in the title (and in [issue](https://github.com/CartoDB/cartodb/issues/3057) too) yesterday creating a visualization in production so I've decided to check it today finally.

Seems like we didn't set the new privacy when in master_vis was changed.

REVIEWERS: @javisantana @javierarce 
Fixes #3057

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5563/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5572/))

**Comment by xavijam** [comment]
Could you check guys now? :)

**Comment by javierarce** [comment]
:+1: :dog: :balloon:

**Comment by xavijam** [comment]
@javisantana, any last word?

**Comment by javisantana** [comment]
:es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5579/))

**Pull request merged**
