### PR TITLE
Restore context menu in the edit-feature view

### PR DESCRIPTION
**Pull request by IagoLast**
Related to: https://github.com/CartoDB/support/issues/1233
---

Reverts some changes made in: https://github.com/CartoDB/cartodb/commit/5288d2579e793c4f16be81c76323316c3eb1582f#diff-8c9eba3e0487773d5b1e1d4ff5b8174eL20

### CODE REVIEW

**Comment by matallo** [comment]
acceptance steps? screenshots? come on!

**Comment by IagoLast** [comment]
I think we can merge this already ;)

screen shot 2017-12-29 at 11 11 07

**Comment by matallo** [comment]
leave it at a ded and I'll be delighted to run acceptance

**Comment by matallo** [comment]
like a charm ✨

**Pull request merged**
