### PR TITLE
Fixed breadcrumb icon lock style

### PR DESCRIPTION
**Pull request by xavijam**
cc @viddo

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3204/))

**Comment by viddo** [comment]
Looks OK, but is it necessary to set the padding to 0 explicitly?

**Comment by xavijam** [comment]
You are right :)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3209/))

**Pull request merged**
