### PR TITLE
Fix notification warning positioning issue

### PR DESCRIPTION
**Pull request by alejandraarri**
This PR solves 2 problems with the notification warning.
- There is a positioning issue that provokes banners to stack one above other in the Settings pages.
Screenshot 2019-05-29 at 19 09 17

- In the API Keys page the same message is shown in two different banners.
Screenshot 2019-05-29 at 21 50 44

### Related issue
https://github.com/CartoDB/cartodb/issues/14859

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
cc: @ana-md. That banner should no longer be there, right? Thank you!

**Comment by ana-md** [comment]
It should appear only for the free users that are being migrated today, it appears only for the users scheduled each day (infra takes care of that). The one in staging was only a test we did to make sure everything was working, so I guess that one doesn't need to be there. @gonzalosr can you confirm this please?

**Comment by alejandraarri** [comment]
Yes, but we are mixing things a little bit. Regardless of the message we are showing right now (PG11 migration) we have a warning component that we use to make important announcements to the user. The main problem here is that the same message is shown in two different banners. We are working so that the banner below does not appear when it doesn’t have to.

**Comment by gonzalosr** [comment]
@ana-md yes, the staging one doesn't need to be there anymore

**Comment by alejandraarri** [comment]
But please @gonzalosr, don't remove it because I need it to test all the cases!! 🙏

**Comment by gonzalosr** [comment]
@alejandraarri Thought so! don't worry :)

**Comment by alonsogarciapablo** [comment]
Thank you all! Keep going @alejandraarri!

**Comment by alejandraarri** [comment]
Retest this please

**Comment by alejandraarri** [comment]
Opened a new issue to fix the second error (https://github.com/CartoDB/cartodb/issues/14936) so we can merge this PR and correct the positioning issue as it is important for the new Professional Plan release.

**Comment by alejandraarri** [comment]
Restest this please

**Comment by csubira** [comment]
Acceptance done by:
Login as staging user:

- [ ] Check dashboard home the maintenance warning shows ok

- [ ] Check that Sticky Header (Navbar and maps and dataset tables) are properly displayed when scrolling

- [ ] Maps page (condensed view) and Dataset page: test sticky header of tables and bulk actions when selecting items work properly

- [ ] Profile, account and API Keys page show maintenance banner properly (And correct margin with content below the navbar)

- [ ] Profile/Account page: Display banner (success and error) to see that positioning for both banners is correct

Acceptance 🆗

**Comment by alejandraarri** [comment]
Retest this please

**Pull request merged**
