### PR TITLE
Reviewed twitter import problems

### LINKED ISSUE #3042: Twitter import time irregularities
SCENARIO:
- the user is in the Eastern daylight savings time zone (EDT), which is GMT-4:00
- The current time is 10:30pm EDT on the 6th day of the month / 2:30am GMT on the 7th day of the month
- The user wants to make a table of Tweets from a recent event that spanned from 6:00pm EDT to 10pm EDT, or 10:00pm GMT to 2:00am GMT (the next day)

Because the Twitter import dialog (in the [old?] dashboard) goes off the system time/clock, which is still on 10:30pm EDT on the 6th day, so this is the latest possible time and date that can be selected in the dialog. **However**, times in the dialog are expressed in GMT, and 2am GMT on the 7th day __has already happened__, and thus we should be able to query Tweets from that time, but the dialog will not let us select the 7th day because it is in the "future". We cannot query a few hours of Tweets that already exist.

This bug is only a problem in hours just before midnight, when a user's system clock is in a time zone behind GMT, when trying to query for events spanning two "GMT days".

Workaround:
Reset user's clock to the next day / after midnight, and reload the dashboard/dialog. Then the user can query the hours that they want.

### LINKED ISSUE #3043: Twitter harvester calendar not to true limits of time!
screen shot 2015-04-06 at 11 28 46 pm

See, it is GMT. I am GMT -4. In my time it is 23:30, which means that in GMT it is tomorrow. But the calendar only let's me select up to April 6th, not April 7th which is tomorrow... 

screen shot 2015-04-06 at 11 38 04 pm

### PR DESCRIPTION
**Pull request by xavijam**
- Fixed problem with credits slider (cc @iriberri).
- Added tests for Twitter import (categories and credits views).
- Fixed problem with datepicker UTC offset (check fixed tickets).
- Removed duplicated 'in CartoDB' text in account page.
- Animated progress bar for background importer item finally working.

Fixes #3042
Fixes #3043

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3521/))

**Comment by xavijam** [comment]
@javierarce could you review it please :)?

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3535/))

**Comment by javierarce** [comment]
:+1: :tada:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3539/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3540/))

**Pull request merged**
