### PR TITLE
dataservices configuration example

### PR DESCRIPTION
**Pull request by juanignaciosl**
@rafatower this is currently needed, right?

### CODE REVIEW

**Comment by rafatower** [comment]
I think so, though it is more a frontend thing. E.g:

https://github.com/CartoDB/cartodb/blob/5b547adb755aa075416dfdeb81a6d5d1cfde9124/lib/assets/core/javascripts/cartodb3/data/analyses.js#L323

**Comment by juanignaciosl** [comment]
@xavijam ^

**Comment by juanignaciosl** [comment]
@xavijam pinging you because of rafatower comment. This should be pretty straightforward.

**Comment by xavijam** [comment]
:+1:, update news and go 🚗 .

**Pull request merged**
