### PR TITLE
Geocoding dialog should be enabled in visualization view

### LINKED ISSUE #2541: Georeferenciation is not available in a visualization
This is something to be taken into account if we're moving to give more importance to maps than datasets in the New dashboard.

It's a bit ugly to click on GEO inside a visualization to geocode a dataset and have to go to the table because this cannot be done in a viz.

Don't know if there's any limitation for this, but as well as you can edit the dataset in a visualization, it could be great that you could geocode.

Depending on the results of this issue, I may also open another one about Creating tables from queries applied in a visualization :smile: 

cc @saleiva @xavijam

### PR DESCRIPTION
**Pull request by xavijam**
screen shot 2015-03-09 at 16 28 08

*PROS*
- [x] GEO button in table view enabled.
- [x] No geocoding data dialog will appear when a layer without data or geo info is added.
- [x] Georeference this layer should be a visible option within the editor in a visualization view.

*CONS*
- Each layer added without data or geo data, will make No-geo dialog appear.

*ONE MORE THING*
- [x] Export this layer available in visualization view

cc @saleiva @iriberri @javisantana @javierarce 

Fixes #2541.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2141/))

**Comment by xavijam** [comment]
We had a problem with options_menu dropdown. It wasn't created each time user clicked over 'edit' link. That means models (in short, dataLayer) didn't change and "layer" options was always for the same table, not the active one.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2146/))

**Comment by javierarce** [comment]
Code seems ok :+1:

**Comment by xavijam** [comment]
Last call @javisantana and @saleiva.

**Pull request merged**
