### PR TITLE
qualified_table_name instead of table_id to call CDB_TableMetadataTouch

### LINKED ISSUE #3212: CDB_TableMetadataTouch with qualified table name
table model update_cdb_tablemetadata should call CDB_TableMetadataTouch with a qualified table name instead of oid.

### PR DESCRIPTION
**Pull request by rochoa**
closes #3212

### CODE REVIEW

**Comment by rochoa** [comment]
cc @juanignaciosl @rafatower

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3035/))

**Comment by rafatower** [comment]
:+1:

**Comment by saleiva** [comment]
bump!

**Comment by rochoa** [comment]
I was waiting for @juanignaciosl approval to merge this.

**Comment by juanignaciosl** [comment]
@rafatower is your guy here, nothing to add. If it's tested, LGTM.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3589/))

**Pull request merged**
