### PR TITLE
Headless chrome test-runner

### PR DESCRIPTION
**Pull request by rjimenezda**
This PR integrates a fork of grunt-contrib-jasmine that is able to run tests through headless chrome.

This is the fork: https://github.com/CartoDB/grunt-contrib-jasmine/tree/headless-chrome

This mostly affects `grunt test`, during development it's still better to run `grunt affected_specs` and open the appropriate URL.

Hopefully, travis installs chrome and everything works. Otherwise, there's some extra work.

The speedup is quite significant, Builder tests are about 90 seconds on Chrome, while Phantom usually takes ~250s

Regarding the fork:

- I managed to connect the Chrome events to the already present phantom event handlers, so the output should be identical.
- Error handling is TBD.
- The ChromeReporter.js could measure how much time each spec takes and push a message for those over a threshold (Karma has this), this would be nice to identify slow/problematic tests.
- grunt-contrib-jasmine is very phantom oriented, I just imported the chrome lib & split the code in a few places, there's lots of room for improvement
- As soon as we can use Node 8 (haha) we should change the implementation to puppeteer.

### CODE REVIEW

**Comment by rjimenezda** [comment]
I've added some basic error handling & an option to report the duration of specs above an specified threshold. Interestingly enough, they were gathering this information from Phantom as well, but they were not using it at all, so it's fully phantom compatible.

**Comment by nobuti** [comment]
This is pure love! We need to include chrome in out CI to get rid of that red cross. But those times... ❤️

**Comment by nobuti** [comment]
Timeout 😢

**Comment by rjimenezda** [comment]
We finally found out the issue with the timeout and the Builder tests are running at about ~25s on Travis 🎊 🎉 

The issue was Notifier.js was rendering notifier-view about 6000 times during the test run. Makes sense since it's a singleton and it's being used all around the app, and we have very very good coverage. This was killing the test runner performance, even on Chrome. Tests that are seemingly simple would take more than 20 seconds (causing a timeout) because the browser was likely busy dealing with all that nonsense.

The ideal solution would be mocking the notifier for the testing build, except for the actual Notifier tests. This, however, is not that simple with our current tools. If anyone is able to provide this, we'd be happy to change our current solution.

So, what we did instead was to add an `off` method to Notifier that resets the collection & removes the view, and calling it after test suites that use Notifier are finished. What worried us about this approach was the possibility of that method getting called on production and ruining the UX, so we used the webpack.DefinePlugin to add a global __ENV__ with the execution environment, and wrapped the code around a __ENV__ === 'test' check. That should end up being `if (true)` for the test runner but `if (false)` for development & production, thus being removed by the minification process.

@nobuti also fixed some memory leaks that could snowball in the future all around the specs

So, performance is looking pretty good, we're only missing Chrome on our CI to test more thoroughly.

**Comment by nobuti** [comment]
Related with this, we should change the tooltip plugin we are using, right now is Tipsy, because there is no way to remove a tooltip from an element, so this is causing a memory leak, not only in tests.

**Comment by nobuti** [comment]
@CartoDB/frontend this PR changes the way we use cdb.sql module. This was introducing a memory leak, because the local variable never was deleted from the context stack, so never garbage collected. So, from now on, let's mock it instead, as you can see in the related commit https://github.com/CartoDB/cartodb/pull/12657/commits/2f50cce15b61abbde6d28d9c2568fb977e7bbff9

**Comment by matallo** [comment]
🚀 outstanding work!

**Comment by rjimenezda** [comment]
The biggest plot twist of all time: phantomjs is faster than Chrome 😱 

Although probably more accurate: the phantomjs runner is faster than my Chrome runner

**Comment by matallo** [comment]
we can always try headless firefox 😛 

https://developer.mozilla.org/en-US/Firefox/Headless_mode

**Comment by rjimenezda** [comment]
If it has a decent way to directly setup a callback, I'd be happy to write a runner / reporter

**Comment by rjimenezda** [comment]
We need an upgrade on the deploy infrastructure, blocking until then

**Comment by rjimenezda** [comment]
Upgrading grunt somehow broke the editor build, because of the order things are concatenated now. Maybe the new grunt interprets **/* patterns differently.

**Comment by xavijam** [comment]
\O/

**Comment by rjimenezda** [comment]
Deployed

**Pull request merged**
