### PR TITLE
Dataset rename

### LINKED ISSUE #8641: Renaming a dataset does not edit the table name in the SQL panel
**STR**:

* Go to a table
* Open the SQL panel (not needed, but for checking purposes)
* Rename the table
* The page will load the new name in the table view and in the URL, but the SQL query will not be edited consistently to the new table name

**Expected behaviour**:
SQL query is updated conveniently when the table is renamed.

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #8641.

rename-dataset

cc @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
:+1:

**Comment by nobuti** [comment]
@jvillarf ompremise failing, should I be worried? It's failing in other PR too.

**Comment by jvillarf** [comment]
@buti currently checking...

**Comment by jvillarf** [comment]
@nobuti could you please send me the link of the other links failing? Thanks

**Comment by nobuti** [comment]
AFAIK https://github.com/CartoDB/cartodb.js/pull/1339 and https://github.com/CartoDB/cartodb/pull/8673

**Pull request merged**
