### PR TITLE
4571 legend category fix

### PR DESCRIPTION
**Pull request by javierarce**

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5166/))

**Comment by javierarce** [comment]
cc @javisantana

**Comment by javisantana** [comment]
looks ok, I don't know enough about pecan actually :/

**Comment by javierarce** [comment]
Well, I've tested it in staging. The issue was that I was sending the categories in the ```metadata``` object, and the legend requires a ```categories``` object.

**Comment by javisantana** [comment]
ok :es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5168/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5170/))

**Pull request merged**
