### PR TITLE
Fix incorrect querying of object ids in ArcGIS connector

### LINKED ISSUE #8958: ArcGIS Connector - Data Import Incomplete
## Context
A user is importing a dataset from ArcGIS using the ArcGIS connector. The dataset has 11 records total but only 2 records import. The user is using a MapServer link that looks structured correctly. Is this an issue with the dataset or the ArcGIS connector?

S/B: 9421774

## Details
**REST API Link:**
https://geo.socioambiental.org/arcgis/rest/services/raisg/raisg_desmat_120m/MapServer

**Carto Table**: 
https://team.carto.com/u/chandra/tables/imagen_no_disponible_1

Tested in my team account (chandra).

**Import Log:**
```
2016-07-18 16:26:06 UTC: Running on server que03.useb.cartodb.net with PID: 28406
2016-07-18 16:26:06 UTC: new_importer()
2016-07-18 16:26:06 UTC: Fetching datasource <CartoDB::Datasources::Url::ArcGis @url= @metadata= @ids_total=0 @ids_retrieved=0 current_block_size=0> metadata for item id https://geo.socioambiental.org/arcgis/rest/services/raisg/raisg_desmat_120m/MapServer
2016-07-18 16:26:07 UTC: Downloading file data from datasource
2016-07-18 16:26:07 UTC: Before importer run
2016-07-18 16:26:07 UTC: Starting multi-resources import
2016-07-18 16:26:08 UTC: Starting import for /tmp/imports/20160718-28406-1u0ij3n/imagen_no_disponible.json
2016-07-18 16:26:08 UTC: Filename: /tmp/imports/20160718-28406-1u0ij3n/imagen_no_disponible.json Size (bytes): 2799
true: Importing data from /tmp/imports/20160718-28406-1u0ij3n/imagen_no_disponible.json
true: Streaming import load
true: Detected encoding UTF-8
true: Using database connection with {:adapter=>"postgres", :encoding=>"unicode", :host=>"10.0.128.236", :database=>"cartodb_user_6b304b59-2c86-4d7b-a8a2-dc98a5a35d48_db", :username=>"cartodb_user_9c56e22e-493a-4f27-8b8e-aae6be514a1d", :port=>6432, :direct_port=>5432, :connect_timeout=>2.5}
true: Running in append mode
false: ogr2ogr call:            OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=UTF-8  /usr/bin/ogr2ogr2.1 -f PostgreSQL  PG:"host=10.0.128.236 port=5432 user=cartodb_user_9c56e22e-493a-4f27-8b8e-aae6be514a1d dbname=cartodb_user_6b304b59-2c86-4d7b-a8a2-dc98a5a35d48_db password=5dda3e67309ef1594ca35272e49d7e488ce55ef0cartodb_user_9c56e22e-493a-4f27-8b8e-aae6be514a1d" -t_srs EPSG:4326  -lco DIM=2 -lco PRECISION=NO /tmp/imports/20160718-28406-1u0ij3n/imagen_no_disponible.json  -nln cdb_importer.importer_54ad43d64d0411e6a5180ef24382571b -nlt PROMOTE_TO_MULTI  -doo PRELUDE_STATEMENTS="SET statement_timeout TO '1h'" -doo CLOSING_STATEMENTS='SET statement_timeout TO DEFAULT' -update 
true: ogr2ogr output:          
true: ogr2ogr exit code:       0
true: Georeferencing...
true: Disabling autovacuum for "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b"
true: Creating the_geom from wkb_geometry column
true: replace empty strings by nulls?
true: no string column found, nothing replaced
true: geometrifying
true: casting wkb_geometry to geometry
true: Converting to 2D point
true: geometrified
true: Renaming column wkb_geometry TO the_geom
true: Enabling autovacuum for "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b"
true: Georeferenced
true: Fixing geometry...
true: Disabling autovacuum for "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b"
true: Fixing geometries
true: Running batched query by id in "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b": 
                UPDATE "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b"
                SET the_geom = public.ST_MakeValid("the_geom")
                WHERE ST_IsValid("the_geom") = FALSE
              
true: Using as id 'cartodb_processed_3680069972780403997'
true: Finished batched query by 'cartodb_processed_3680069972780403997' in "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b": query
true: Enabling autovacuum for "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b"
true: Finished importing data from /tmp/imports/20160718-28406-1u0ij3n/imagen_no_disponible.json
2016-07-18 16:26:13 UTC: Errored importing data:
2016-07-18 16:26:13 UTC: CartoDB::Datasources::ResponseError: Missing data: 'fields'
2016-07-18 16:26:13 UTC: ----------------------------------------------------
2016-07-18 16:26:13 UTC: ["/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/datasources/lib/datasources/url/arcgis.rb:252:in `get_subresource_metadata'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/datasources/lib/datasources/url/arcgis.rb:195:in `get_resource_metadata'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:332:in `block (3 levels) in multi_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:328:in `block (2 levels) in multi_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:323:in `block in multi_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:318:in `each'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:318:in `each_with_index'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:318:in `multi_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:99:in `run_import'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:92:in `block in run'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:91:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/app/connectors/importer.rb:43:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/app/models/data_import.rb:714:in `execute_importer'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/app/models/data_import.rb:401:in `dispatch'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/app/models/data_import.rb:178:in `run_import!'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/resque/importer_jobs.rb:9:in `block in perform'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/resque/base_job.rb:21:in `call'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/resque/base_job.rb:21:in `run_action'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/resque/importer_jobs.rb:9:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'", "/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/bin/rake:23:in `load'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/bin/rake:23:in `<main>'"]
2016-07-18 16:26:13 UTC: ----------------------------------------------------
2016-07-18 16:26:13 UTC: Proceeding to register
2016-07-18 16:26:13 UTC: Before renaming from importer_54ad43d64d0411e6a5180ef24382571b to imagen_no_disponible
2016-07-18 16:26:14 UTC: Before moving schema 'imagen_no_disponible_1' from cdb_importer to chandra
2016-07-18 16:26:14 UTC: Before persisting metadata 'imagen_no_disponible_1' data_import_id: 09cc8373-afb4-4870-b283-2b1ca94160ba
2016-07-18 16:26:16 UTC: Table 'imagen_no_disponible_1' registered
2016-07-18 16:26:16 UTC: After importer run
2016-07-18 16:26:16 UTC: synchronization_id: 53a82514-4d04-11e6-a2ea-0e233c30368f
2016-07-18 16:26:16 UTC: importer.success? success
2016-07-18 16:26:16 UTC: After dispatch
2016-07-18 16:26:16 UTC: Import finished
===LOG END===
```

### PR DESCRIPTION
**Pull request by jgoizueta**
Enhance also error reporting: detect invalid layer types
Fixes #8958

### CODE REVIEW

**Comment by jgoizueta** [comment]
Previous behaviour:

* Non vector layers caused an "Missing data: 'fields'" error.

New behaviour:

* For multi-resource (i.e. URLs of a REST service, not of a particular layer) only vector layers are selected and imported. Then if no layers are selected an "Empty layers list" error occurs
* For a single layer import, an "Invalid layer type" occurs if it is not a vector layer.

So, now for a case like #8958 or an URL with vector and non-vector layers, the import is successful  and only vector layers are imported.

Also imports of non supported version 10.01 could fail with "Missing data: supportedQueryFormats". Now it fails with an "Unsupported ARCGIS version error"

**Comment by jgoizueta** [comment]
Please @ethervoid review this

**Comment by julianamori** [comment]
Hey guys,

I´m the user who was trying to upload the dataset from ArcGIS which generated this issue. I´ve been following all the thread, thanks for all the effort in solving it and clarifying the error! 

Now that you have the bug fixed, I´ve tried to upload the same datasets from ArcGIS again and, as I understood from your explanations, the vector layer from the dataset (layer 0 from the REST link) is now successfully uploaded: 
https://infoamazonia.carto.com/dataset/imagen_no_disponible_3 
(we can see all the 11 polygons instead of only 2)

But layer 1 ("Periodo") from the same REST link is a Raster Layer and, now I understang, cannot be successfully uploaded. Anyway - just so you have a feedback - CARTO still shows me a generic error message, where it should show the new behavior you listed above, right?

Error retrieving data from datasource (1011)
There was an error retrieving data from the datasource. Check that the file/data is still present.
Persisting error? Please send us the following code: 
985f640c-e21f-4302-9eb4-9518bad76eea

**Comment by jgoizueta** [comment]
Hi @julianamori: You're right, that error message is misleading and should be changed; I've open a new ticked for that issue: #9108

Thanks for reporting!

**Pull request merged**
