### PR TITLE
Fix URL for liked datasets

### LINKED ISSUE #3650: In the private dashboard, liked datasets not created by you have invalid urls
### STEPS

- Just log in with your CartoDB account.
- Go to any dataset created by any other CartoDB user.
- Yes, you like it and you click over the heart button.
- Go back to your private dashboard and visit liked datasets section.
- Check that the previous liked dataset appears and click over the title.
- It goes to a 404 page :(.

### PR DESCRIPTION
**Pull request by viddo**
Fixes #3650, set dataset URL based on permission privileges.

Please review @xavijam

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3837/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3838/))

**Comment by viddo** [comment]
bump! :)

**Comment by xavijam** [comment]
Good bump! Looks good so far, but I forgot to mention about maps.

**Comment by viddo** [comment]
Aight, fixed in f154dab

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3847/))

**Comment by xavijam** [comment]
yay! thanks :es:

**Pull request merged**
