### PR TITLE
Fix update in multi-user account

### PR DESCRIPTION
**Pull request by Xatpy**
Ref. ticket #2743 : **Update in multi-user account is not being recognized**

Fix in regular expression and tests added.

The problem was when it was being recognised if it was a read or write query.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2371/))

**Comment by Xatpy** [comment]
Retest this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2407/))

**Comment by Xatpy** [comment]
Please, @javisantana , could you check it? Thanks!

**Comment by javisantana** [comment]
good :es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2431/))

**Pull request merged**
