### PR TITLE
Add map previews in the remove table dialog

### PR DESCRIPTION
**Pull request by javierarce**
### Changes

- Adds the vizjson URL [to the template](https://github.com/CartoDB/cartodb/blob/42a2ae35cc0b68c11e3c0a1995e9e6026e97a6a8/lib/assets/javascripts/cartodb/new_dashboard/dialogs/delete_items_view_template.jst.ejs#L19) of the map card items in the delete dialog
- [Uses the protocol of the current location to request the image](https://github.com/CartoDB/cartodb/blob/42a2ae35cc0b68c11e3c0a1995e9e6026e97a6a8/lib/assets/javascripts/cartodb/new_dashboard/mapcard_preview.js) (necessary for development)

screen shot 2015-02-13 at 17 02 54

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1587/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1589/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1591/))

**Comment by javierarce** [comment]
@CartoDB/frontend: can you have a look? I'm unsure about the location of the static map [rendering](https://github.com/CartoDB/cartodb/blob/6ece520d5e107c32259099a0ecc2bf466055df6a/lib/assets/javascripts/cartodb/new_dashboard/dialogs/delete_items_view.js#L182)

**Comment by viddo** [comment]
If we add more functionality it might be motivated to have individual views for the map preview, but they are after all only previews and not full-feature cards so I think where you placed it is fine for now.

Btw, why not use attribute like `data-vizjson-url` to avoid invalid attribute? (value can be accessed through .data method, i.e. `$(this).data("vizjson-url"),`)

**Comment by javierarce** [comment]
Yeah, I agree with you that at some point it will make sense to have proper views.

I'll change that attribute name before merging the PR, thanks!

**Comment by javisantana** [comment]
don't forget to update NEWS

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1605/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1606/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1611/))

**Pull request merged**
