### PR TITLE
Extend layer rebranding task to include basemap category

### LINKED ISSUE #8967: migrate basemap categories from "CartoDB" to "CARTO"
from https://github.com/CartoDB/cartodb/pull/8901 discussion

current user layers are saved with "CartoDB" category in the DB

to take into account for upcoming on-premises release, not assigning a milestone then

/cc @javitonino @juanignaciosl

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #8967

### CODE REVIEW

**Comment by javitonino** [comment]
Please CR @juanignaciosl @matallo

**Comment by matallo** [comment]
LGTM, shall I remove the fallback in the js code now?

**Comment by javitonino** [comment]
Not yet, I'll ping you after this has been merged and executed.

**Comment by matallo** [comment]
BOOM, awesome mate

**Comment by juanignaciosl** [comment]
👍

**Pull request merged**
