### PR TITLE
Ui fixes

### PR DESCRIPTION
**Pull request by piensaenpixel**
@xavijam could you take a look?

- Fixing padding in header and font icons from cartoassets
image

- Remove magnify icon
image

### CODE REVIEW

**Comment by piensaenpixel** [comment]
i dont know why the test are failing :( any idea?

**Comment by xavijam** [comment]
It tries to check that a submit button is present but it is not.

**Comment by piensaenpixel** [comment]
taking a look

**Comment by piensaenpixel** [comment]
Test fixed @xavijam 💃

**Pull request merged**
