### PR TITLE
Round down the quota usage

### LINKED ISSUE #2547: Settings dropdown progress bar is not correct
We are rounding used quota number, it is not correct.

screen shot 2015-02-27 at 18 05 06

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2547 

I'll propose we render the used amount of data with up to 2 decimals if necessary, rounded down to avoid the rounding to be rendered as "10MB" for this kind of edge-case:

screen shot 2015-03-02 at 12 43 23
screen shot 2015-03-02 at 12 44 13

In case the used data has no decimals it renders as before:
screen shot 2015-03-02 at 12 45 00

### CODE REVIEW

**Comment by viddo** [comment]
Please review @xavijam

**Comment by xavijam** [comment]
Good to me :+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2009/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2016/))

**Pull request merged**
