### PR TITLE
revert oneclick bug

### PR DESCRIPTION
**Pull request by matallo**
to be deployed along with _oneclick_

CR @xavijam

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3706/))

**Comment by saleiva** [comment]
bump!

**Comment by xavijam** [comment]
Finally fixed???, so far so good. :+1:

**Comment by xavijam** [comment]
ping!

**Pull request merged**
