### PR TITLE
Show formula widget for cartodb_id.

### LINKED ISSUE #8130: Cartodb_id in DATA tab should be a formula widget that says count
The normal flow would be to add a widget counting a number of features. Widget name should be "Number of" and get COUNT by default as agg method

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #8130.

number-of

I'm deleting the % of null because for cartodb_id I guess it doesn't make sense. Correct me if I'm wrong.

cc @saleiva @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
:+1:

**Comment by saleiva** [comment]
About the name. @javierarce what do you think?
Number of Polygons/points/lines??

**Comment by javierarce** [comment]
Yes. Or `polygon/point/line count`?

**Comment by saleiva** [comment]
+1 to that

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
