### PR TITLE
#954 FE code removal (and BE placeholders)

### LINKED ISSUE #954: remove parent_id from layer model
It's no longer needed,and it is slowing down Layer write operations by searching for non-existing parent/children.

Check also `chldren` as probably isn't used either.

Branches: 
`954-remove_layer_parent_id`
To release after the code/previous one:
`954-remove-db-parent_id-field`
and then frontend part removal (and remaining traces):
`954-FE-layer-parent_id-removal`

### PR DESCRIPTION
**Pull request by Kartones**
Closes #954

### CODE REVIEW

**Comment by Kartones** [comment]
@xavijam CR please (FE)
@juanignaciosl  CR please (BE, although is just removing placeholders)

**Comment by juanignaciosl** [comment]
Not much to say here :+1:

**Comment by xavijam** [comment]
cc @javierarce because he knows more about slides than me.

**Comment by javisantana** [comment]
FE :es:

**Pull request merged**
